import {expect,it,vi} from 'vitest';
import {DocumentOutputViewModel,type DocumentOutputContext,outputFormats} from '../../apps/desktop/src/lib/document-output';
import {EmailDraftViewModel,type EmailContext} from '../../apps/desktop/src/lib/email-draft';
const image='data:image/jpeg;base64,aGVsbG8=';
function output(){let id:string|null='book-1';const context:DocumentOutputContext={snapshot:()=>({bookId:id,title:'Story',language:'en'}),chapter:()=>({title:'Chapter',words:10,kind:'chapter'}),save:vi.fn(async()=>{}),destination:vi.fn(async()=>'/fixture/export'),request:vi.fn(async()=>true),os:{request:vi.fn(async()=>true)},hint:vi.fn(),t:key=>key,generatedCover:vi.fn(async()=>image)};return {context,vm:new DocumentOutputViewModel(context),change:()=>{id='other';}};}
it('whole-book visual formats receive generated art while chapter exports and other formats never render a book cover',async()=>{for(const format of outputFormats){const f=output();await f.vm.export(format);expect(f.context.generatedCover).toHaveBeenCalledTimes(['html','pdf','epub'].includes(format)?1:0);expect(f.context.request).toHaveBeenCalledWith('exportBook',{bookId:'book-1',format,destination:'/fixture/export',language:'en',...(['html','pdf','epub'].includes(format)?{generatedCover:image}:{})});const chapter=output();await chapter.vm.export(format,'chapter-1');expect(chapter.context.generatedCover).not.toHaveBeenCalled();expect(chapter.context.request).toHaveBeenCalledWith('exportChapter',{bookId:'book-1',chapterId:'chapter-1',format,destination:'/fixture/export',language:'en'});}});
it('printing receives one full cover only for the whole manuscript',async()=>{const f=output();await f.vm.print();expect(f.context.os?.request).toHaveBeenCalledWith('printManuscript',{bookId:'book-1',language:'en',generatedCover:image});const chapter=output();await chapter.vm.print('chapter-1');expect(chapter.context.generatedCover).not.toHaveBeenCalled();expect(chapter.context.os?.request).toHaveBeenCalledWith('printChapter',{bookId:'book-1',chapterId:'chapter-1',language:'en'});});
it('changing books while cover rendering awaits never exports or prints a mixed snapshot, and releases busy for retry',async()=>{for(const operation of ['export','print']){const f=output();vi.mocked(f.context.generatedCover!).mockImplementation(async()=>{f.change();return image;});await expect(operation==='export'?f.vm.export('pdf'):f.vm.print()).rejects.toThrow('BOOK_CHANGED');expect(f.context.request).not.toHaveBeenCalled();expect(f.context.os?.request).not.toHaveBeenCalled();vi.mocked(f.context.generatedCover!).mockResolvedValue(image);await f.vm.export('pdf');expect(f.context.request).toHaveBeenCalledOnce();}});
it('canceled picker renders nothing and an optional provider without full-cover capability preserves export behavior',async()=>{const f=output();vi.mocked(f.context.destination).mockResolvedValue(null);await f.vm.export('pdf');expect(f.context.generatedCover).not.toHaveBeenCalled();const plain=output();delete plain.context.generatedCover;await plain.vm.export('pdf');expect(plain.context.request).toHaveBeenCalledWith('exportBook',{bookId:'book-1',format:'pdf',destination:'/fixture/export',language:'en'});});
function email(){let id='book-1';const context:EmailContext={snapshot:()=>({book:{id,title:'Story',words:12},address:'writer@example.com',method:'mail',locale:'en'}),mac:true,os:{request:vi.fn(async()=>true)},prompt:vi.fn(async()=>null),saveSettings:vi.fn(async()=>{}),saveBook:vi.fn(async()=>{}),request:vi.fn(async()=>({fingerprint:'b'.repeat(64)})),publish:vi.fn(),hint:vi.fn(),t:key=>key,generatedCover:vi.fn(async()=>image)};return {context,vm:new EmailDraftViewModel(context),change:()=>{id='other';}};}
it('email receives the exact captured host fingerprint together with its cover to validate the actual PDF snapshot',async()=>{const f=email();await f.vm.draft();expect(f.context.request).toHaveBeenCalledWith('manuscriptFingerprint',{bookId:'book-1'});expect(f.context.generatedCover).toHaveBeenCalledWith('book-1');expect(f.context.os?.request).toHaveBeenCalledWith('emailDraft',expect.objectContaining({bookId:'book-1',generatedCover:image,expectedFingerprint:'b'.repeat(64)}));});
it('a book switch during email cover generation invokes no native draft',async()=>{const f=email();vi.mocked(f.context.generatedCover!).mockImplementation(async()=>{f.change();return image;});await expect(f.vm.draft()).rejects.toThrow('BOOK_CHANGED');expect(f.context.os?.request).not.toHaveBeenCalled();});
