<script lang="ts">
 import { onMount } from 'svelte';import type { AuthoringUI } from './AuthoringViewModel.svelte';
 let { vm }: {vm:AuthoringUI}=$props();let paper:HTMLDivElement;let notebook:HTMLDivElement;
 onMount(()=>{let cleanup:(()=>void)|undefined;void vm.mount(paper,notebook).then(fn=>cleanup=fn);return()=>cleanup?.();});
</script>
<svelte:head><title>NEO · {vm.title}</title></svelte:head>
<main><nav aria-label="Chapters"><small>The manuscript</small><h1>{vm.title}</h1><p>{vm.author}</p>{#each vm.chapters as chapter}<button class:active={vm.current===chapter.id} onclick={()=>vm.navigate(chapter.id)}>{chapter.title}</button>{/each}<button onclick={()=>vm.addChapter()}>Add chapter</button><button onclick={()=>vm.duplicate()}>Duplicate chapter</button><button onclick={()=>vm.reorder()}>Move chapter first</button><button onclick={()=>vm.deleteChapter()}>Delete chapter</button><label>Chapter title<input aria-label="Chapter title" value={vm.chapters.find(c=>c.id===vm.current)?.title||''} onchange={e=>vm.rename(vm.current,e.currentTarget.value)}></label></nav>
<section class="workspace"><div class="tools"><button onclick={()=>vm.undo()} disabled={!vm.canUndo}>Undo</button><button onclick={()=>vm.redo()} disabled={!vm.canRedo}>Redo</button><button onclick={()=>vm.format('bold')}>Bold</button><button onclick={()=>vm.format('italic')}>Italic</button><button onclick={()=>vm.archive()}>Keep as Darling</button><button onclick={()=>vm.move()}>Move paragraph to next chapter</button></div><div class="paper" bind:this={paper}></div></section>
<aside><button onclick={()=>vm.selectPanel('notes')}>Notes</button><button onclick={()=>vm.selectPanel('outline')}>Outline</button><h2>{vm.panel==='notes'?'Notes':'Outline'}</h2><div class="notes-host" bind:this={notebook}></div><h2>Darlings</h2>{#each vm.darlings as darling}<article><p>{darling.text}</p><button onclick={()=>vm.restore(darling.id)}>Restore Darling</button></article>{/each}<h2>Reviews</h2><button onclick={()=>vm.reviewSelection()}>Review selection</button><button onclick={()=>vm.reviewStructure()}>Review structure</button>{#each vm.reviews as row}<article data-kind={row.kind} data-state={row.state}><small>{row.category} · {row.state}</small><p>{row.message}</p>{#each row.resolutions as resolution}<blockquote data-status={resolution.status}>{resolution.status}: {resolution.text}</blockquote>{/each}{#if row.kind==='suggestion'}<p>Suggested: {row.replacement}</p><button disabled={row.state!=='pending'} onclick={()=>vm.accept(row.id)}>Accept</button>{/if}<button disabled={row.state!=='pending'} onclick={()=>vm.reject(row.id)}>Dismiss</button></article>{/each}</aside>
<footer><span>NEO</span><span role="status">{vm.status}</span><span>{vm.words} words</span><button onclick={()=>void vm.save()} disabled={vm.readOnly}>Save</button><button onclick={()=>void vm.reopen()}>Discard changes and reopen</button><button onclick={()=>void vm.requestClose()}>Close book</button></footer></main>
{#if vm.closePrompt}<div class="scrim"><div role="dialog" tabindex="-1" aria-label="Unsaved changes" aria-modal="true"><h2>Keep your changes?</h2><button onclick={()=>void vm.finishClose(false)}>Save and close</button><button onclick={()=>void vm.finishClose(true)}>Discard and close</button><button onclick={()=>vm.cancelClose()}>Keep writing</button></div></div>{/if}
<style>
 :global(body){margin:0;background:#f0eee9;color:#282724;font-family:Georgia,serif}main{display:grid;grid-template-columns:210px minmax(400px,1fr) 310px;min-height:100vh;padding-bottom:48px;box-sizing:border-box}nav,aside{padding:20px;border-right:1px solid #ddd8cf}nav small{text-transform:uppercase;letter-spacing:2px;font:10px system-ui;color:#79766e}nav h1{font-size:24px}nav p{color:#79766e}nav button{display:block;width:100%;text-align:left;margin:7px 0}.active{background:#e3dfd5}label{font:12px system-ui;color:#777;display:block;margin-top:18px}input{width:100%;box-sizing:border-box;margin-top:6px;padding:8px;border:1px solid #d5d0c5;background:#fffef9}.workspace{padding:18px}.tools{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:24px}.paper{max-width:760px;min-height:75vh;padding:60px;margin:auto;background:#fffef9;box-shadow:0 2px 20px #00000008}:global(.ProseMirror){outline:none;font-size:22px;line-height:1.7;white-space:pre-wrap}:global(.ProseMirror p){margin:0 0 22px}:global(.ph-mark){background:#ede5d0}:global(.darling-anchor){display:inline-block;border-left:2px dotted #9a8e6b;height:1em}:global(.poetry){font-style:italic}:global(.scene-break){text-align:center;letter-spacing:4px}:global(.ghost){color:#999}button{border:1px solid #d5d0c5;border-radius:4px;background:#f8f6f0;padding:8px 10px;color:#454139;cursor:pointer;font:12px system-ui}button:disabled{opacity:.4;cursor:default}aside{border-right:0;border-left:1px solid #ddd8cf}aside h2{font-size:20px}.notes-host :global(.ProseMirror){font-size:16px}article{background:#f3ead2;border-left:3px solid #b9a471;padding:12px;margin:16px 0}article[data-kind=note]{background:#dfe8e6;border-color:#87aaa1}article small{font:12px system-ui;color:#696256}blockquote{margin:8px 0;font-size:14px}footer{position:fixed;bottom:0;height:48px;left:0;right:0;background:#f0eee9;border-top:1px solid #ddd8cf;display:flex;align-items:center;gap:16px;padding:0 20px;font:12px system-ui;color:#7d786f}footer>span:first-child{font:20px Georgia;letter-spacing:3px;margin-right:20px}footer [role=status]{flex:1}.scrim{position:fixed;inset:0;background:#0005;display:grid;place-items:center}.scrim>div{padding:28px;background:#fffef9;border-radius:8px}.scrim button{margin-right:8px}
</style>
