import type { RendererFactory } from './renderer-bindings';
import type { EditorPort,ReviewRow,SurfacePort } from './editor-port';
import { CompositionTelemetry } from './telemetry';import type { DocumentStore,AuthoringLifecycle,ChapterRow,Opened,CheckpointValue } from './contracts';
export interface AuthoringUI {
 readonly chapters:ChapterRow[];readonly darlings:{id:string;text:string}[];readonly reviews:ReviewRow[];readonly current:string;readonly panel:string;readonly title:string;readonly author:string;readonly status:string;readonly words:number;readonly revision:number;readonly canUndo:boolean;readonly canRedo:boolean;readonly closePrompt:boolean;readonly readOnly:boolean;
 mount(main:HTMLElement,notes:HTMLElement):Promise<()=>void>;selectPanel(panel:'notes'|'outline'):void;navigate(id:string):void;undo():void;redo():void;format(mark:'bold'|'italic'):void;archive():void;restore(id:string):void;addChapter():void;rename(id:string,title:string):void;duplicate():void;deleteChapter():void;reorder():void;move():void;reviewSelection():void;reviewStructure():void;accept(id:string):void;reject(id:string):void;save():Promise<void>;reopen():Promise<void>;requestClose():Promise<void>;finishClose(discard:boolean):Promise<void>;cancelClose():void;
}
export class AuthoringViewModel implements AuthoringUI {
 chapters=$state.raw<ChapterRow[]>([]);darlings=$state.raw<{id:string;text:string}[]>([]);reviews=$state.raw<ReviewRow[]>([]);current=$state('');panel=$state('notes');title=$state('');author=$state('');status=$state('Opening');words=$state(0);revision=$state(0);canUndo=$state(false);canRedo=$state(false);closePrompt=$state(false);readOnly=$state(false);
 core:EditorPort|null=null;readonly telemetry=new CompositionTelemetry();commits:number[]=[];frames:number[]=[];private started:number|null=null;private dirty=false;private sequence:Promise<void>=Promise.resolve();private versions:Opened['versions']|null=null;private surfaces:SurfacePort|null=null;private mainHost:HTMLElement|null=null;private notesHost:HTMLElement|null=null;private unsubscribe:()=>void=()=>{};private closeUnsubscribe:()=>void=()=>{};private disposed=false;private closing=false;private timer:ReturnType<typeof setTimeout>|null=null;
 constructor(readonly store:DocumentStore,private renderer:RendererFactory,readonly autosave=true,private lifecycle?:AuthoringLifecycle){}
 async mount(main:HTMLElement,notes:HTMLElement){this.mainHost=main;this.notesHost=notes;const opened=await this.store.open();this.versions=opened.versions;this.load(opened);this.status=opened.recovered?'Recovered':'Opened';if(this.lifecycle){this.readOnly=this.lifecycle.readOnly;this.closeUnsubscribe=this.lifecycle.onCloseRequested(()=>void this.requestClose());this.refreshViews();}return()=>this.dispose();}
 private load(opened:Opened){this.unsubscribe();this.surfaces?.destroy();const binding=this.renderer(opened,this.telemetry,()=>this.started=performance.now(),{undo:()=>this.undo(),redo:()=>this.redo(),save:()=>void this.save(),format:m=>this.format(m),archive:()=>this.archive()});this.core=binding.core;this.surfaces=binding.surfaces;this.current=this.core.chapters[0].id;this.project();this.unsubscribe=this.core.subscribe(event=>{
  if(event.kind==='changed'){this.dirty=true;this.status='Unsaved changes';this.lifecycle?.dirty(event.revision);this.schedule();}
  const owner=this.core!.activeSection;if(owner?.role==='chapter'&&owner.id!==this.current){this.current=owner.id;this.render();}else if(owner&&['notes','outline'].includes(owner.role)&&owner.id!==this.panel){this.panel=owner.id;this.render();}else this.refreshViews();this.project();
  if(event.kind==='changed'&&this.started!==null){const start=this.started;this.started=null;this.commits.push(performance.now()-start);requestAnimationFrame(()=>this.frames.push(performance.now()-start));}
 });this.render();this.dirty=false;}
 private project(){const c=this.core;if(!c)return;this.title=c.title;this.author=c.author;this.revision=c.revision;this.words=c.words;this.canUndo=c.canUndo;this.canRedo=c.canRedo;const chapters=c.chapters;if(JSON.stringify(chapters)!==JSON.stringify(this.chapters))this.chapters=chapters;const darlings=c.darlings.map(d=>({id:d.id,text:d.text||d.html.replace(/<[^>]*>/g,'')}));if(JSON.stringify(darlings)!==JSON.stringify(this.darlings))this.darlings=darlings;if(c.reviewRows().length)this.reviews=c.reviewRows();else if(this.reviews.length)this.reviews=[];}
 private render(){if(!this.core||!this.mainHost||!this.notesHost||!this.surfaces)return;if(!this.core.chapters.some(c=>c.id===this.current))this.current=this.core.chapters[0].id;this.surfaces.render(this.mainHost,this.notesHost,this.current,this.panel,!this.readOnly&&!this.closePrompt);}
 private refreshViews(){this.surfaces?.update(this.current,this.panel,!this.readOnly&&!this.closePrompt);}
 private command(op:()=>void){if(this.readOnly||this.closePrompt)return;try{this.telemetry.sync('ui.command',ctx=>{this.core!.setTraceParent(this.telemetry.carrier(ctx));try{op();}finally{this.core!.setTraceParent();}});this.project();this.refreshViews();}catch(e){this.status=e instanceof Error?e.message:'Command failed';}}
 selectPanel(panel:'notes'|'outline'){this.panel=panel;this.render();this.core?.select(panel,1);}
 navigate(id:string){if(!this.core?.chapters.some(c=>c.id===id))return;this.current=id;this.render();this.core.select(id,1);}
 undo(){this.command(()=>{this.core?.undo();});}redo(){this.command(()=>{this.core?.redo();});}
 format(mark:'bold'|'italic'){this.command(()=>{this.core!.format(mark);});this.surfaces?.focus();}
 archive(){this.command(()=>this.core!.archive());}restore(id:string){this.command(()=>this.core!.restore(id));}
 addChapter(){this.command(()=>{const id=this.core!.createChapter('New chapter');this.current=id;this.render();});}
 rename(id:string,title:string){this.command(()=>this.core!.renameChapter(id,title));}
 duplicate(){this.command(()=>{const id=this.core!.duplicateChapter(this.current);this.current=id;this.render();});}
 deleteChapter(){this.command(()=>{this.core!.deleteChapter(this.current);this.current=this.core!.chapters[0].id;this.render();});}
 reorder(){this.command(()=>this.core!.reorderChapter(this.current,0));}
 move(){this.command(()=>{const c=this.core!,next=c.chapters.find(ch=>ch.id!==this.current),p=c.passageRows(this.current)[0];if(next&&p)c.movePassage(p.id,next.id);});}
 reviewSelection(){this.command(()=>{const c=this.core!,ref=c.captureSelection(),input=c.extract([ref.id],'voice');c.receive({reviewId:'fixture-'+input.requestId,requestId:input.requestId,items:[{id:'suggestion-'+input.requestId,kind:'suggestion',category:'voice',references:[ref.id],message:'Try a direct verb.',replacement:'said'}]});});}
 reviewStructure(){this.command(()=>{const c=this.core!,refs=c.passageRows().filter(p=>p.size&&c.chapters.some(ch=>ch.id===p.chapterId)).slice(0,20).map(p=>c.capture(p.id,0,p.size));const input=c.extract(refs.map(r=>r.id),'structure');c.receive({reviewId:'fixture-'+input.requestId,requestId:input.requestId,items:[{id:'note-'+input.requestId,kind:'note',category:'structure',references:refs.map(r=>r.id),message:'Compare these passages.'}]});});}
 accept(id:string){this.command(()=>{const result=this.core!.accept(id);if(!result.ok)throw Error(result.code);});}reject(id:string){this.command(()=>this.core!.reject(id));}
 private schedule(){if(!this.autosave||this.closing)return;if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>{this.timer=null;void this.save();},600);}
 async save(){if(this.timer){clearTimeout(this.timer);this.timer=null;}if(!this.core||!this.versions||this.readOnly)return;const c=this.core;const operation=this.sequence.then(()=>this.telemetry.run('ui.save',async ctx=>{const checkpoint=c.checkpoint(this.telemetry.carrier(ctx)),receipt=await this.store.save(checkpoint,this.versions!,this.telemetry.carrier(ctx));this.versions=receipt.versions;if(!this.disposed&&c===this.core&&receipt.revision===c.revision){this.dirty=false;this.status='Saved';}}));this.sequence=operation.catch(()=>{});try{await operation;}catch(e){this.status=e instanceof Error?e.message:'Save failed';}}
 async reopen(){if(this.timer){clearTimeout(this.timer);this.timer=null;}await this.sequence;if(!this.core)return;const revision=this.core.revision;const opened=await this.store.open();if(revision!==this.core.revision){this.status='Writing changed during reopen';return;}this.versions=opened.versions;this.load(opened);this.status='Reopened';}
 async requestClose(){if(this.closing)return;this.closing=true;if(this.timer){clearTimeout(this.timer);this.timer=null;}await this.sequence;if(this.dirty){this.closePrompt=true;this.refreshViews();}else await this.finishClose(false);}
 async finishClose(discard:boolean){if(!discard&&this.dirty)await this.save();if(!discard&&this.dirty)return;await this.sequence;if(this.lifecycle){const result=await this.lifecycle.finish(discard);if(!result.ok){this.status=result.code;return;}}this.closePrompt=false;this.status='Closed';}
 cancelClose(){this.closing=false;this.closePrompt=false;this.refreshViews();this.schedule();}
 diagnostics(){return{commits:this.commits,frames:this.frames,snapshots:this.core?.snapshots||0,revision:this.revision,words:this.words};}
 private dispose(){this.disposed=true;if(this.timer)clearTimeout(this.timer);this.unsubscribe();this.closeUnsubscribe();this.surfaces?.destroy();void this.telemetry.dispose();}
}
