import { toggleMark } from 'prosemirror-commands';
import type { Context } from '@opentelemetry/api';
import { z } from 'zod';import { Schema,Fragment,Slice,type Node as PMNode } from 'prosemirror-model';import { EditorState,TextSelection,type Transaction } from 'prosemirror-state';import { history,undo,redo,undoDepth,redoDepth,closeHistory } from 'prosemirror-history';
import { importHTML,exportHTML,schema as htmlSchema } from '../parity/src/codec';import { identitySchema,entries,signature,runs,runText } from '../identity-spike/session';import { inspectHTML,baseNode } from '../identity-spike/fidelity';import { Reference,ReviewOutput,type PassageReference,type ReviewItemValue } from '../identity-spike/contracts';
import { SourceBook,Checkpoint,Reviews,Input,type CheckpointValue,type CoreEvent,type ReviewInput } from './contracts';import type { CompositionTelemetry } from './telemetry';
const uuid=()=>crypto.randomUUID();
const nodes=identitySchema.spec.nodes.update('doc',{content:'section+',attrs:{metadata:{default:{}},darlings:{default:[]},accepted:{default:[]},version:{default:null}}}).addToEnd('section',{content:'block+',defining:true,attrs:{id:{default:null},role:{default:'chapter'},title:{default:''},kind:{default:'chapter'}},toDOM:n=>['section',{'data-section':n.attrs.id},0]}).addToEnd('surface',{content:'block+'});
export const bookSchema=new Schema({nodes,marks:identitySchema.spec.marks});
type Part={from:number;to:number};type Location={parts:Part[];deleted:boolean;unresolved:boolean};type Section={node:PMNode;pos:number;index:number};type PassageInfo={id:string;chapterId:string;kind:string;text:string;size:number;pos:number;path:number[];node:PMNode};
const clone=(loc:Location):Location=>({...loc,parts:loc.parts.map(p=>({...p}))});
const words=(s:string)=>s.trim().split(/\s+/).filter(Boolean).length;
const Darling=z.object({id:z.string(),html:z.string(),text:z.string().optional(),chapterId:z.string().optional()}).passthrough();
export class BookCore {
 commandParent:Context|undefined;state:EditorState;revision:number;words=0;snapshots=0;
 private passageDoc:PMNode|null=null;private passageCache:PassageInfo[]=[];private passageById=new Map<string,PassageInfo>();
 private sources=new Map<string,{html:string;initial:Fragment;supported:boolean;title:string;kind:string}>();private originalIds=new Set<string>();private refs=new Map<string,PassageReference>();private locations=new Map<string,Location>();private items=new Map<string,{item:ReviewItemValue;reviewId:string;rejected:boolean}>();private requests=new Map<string,ReviewInput>();
 private cache=new Map<string,Map<string,Location>>();private events:{before:string;after:string}[]=[];private cursor=0;private listeners=new Set<(e:CoreEvent)=>void>();
 constructor(readonly document:Document,raw:unknown,reviewData:unknown|null,notes:string,outline:string,private telemetry?:CompositionTelemetry){
  const book=SourceBook.parse(raw);this.revision=book.revision;const metadata=book.metadata;this.originalIds=new Set(book.chapters.map(c=>c.id));
  const titleMap=z.record(z.string(),z.string()).safeParse(metadata.chapterTitles),kindMap=z.record(z.string(),z.string()).safeParse(metadata.chapterKinds);
  const version=book.formatVersion==='neo-composed/v1'?book.version:uuid();
  const sections=book.chapters.map(ch=>this.makeSection(ch.id,'chapter',ch.html,titleMap.success?titleMap.data[ch.id]||ch.id:ch.id,kindMap.success?kindMap.data[ch.id]||'chapter':'chapter','passages' in ch?ch.passages:undefined));
  sections.push(this.makeSection('notes','notes',notes,''),this.makeSection('outline','outline',outline,''));
  this.state=EditorState.create({doc:bookSchema.nodes.doc.create({metadata,darlings:book.darlings,version,accepted:[]},sections),plugins:[history()]});this.words=this.wordCount();
  if(reviewData){const data=Reviews.parse(reviewData);if(data.bookId!==metadata.id)throw Error('INVALID_REVIEW_BOOK');for(const record of data.references){if(this.refs.has(record.reference.id))throw Error('INVALID_REFERENCE');this.refs.set(record.reference.id,record.reference);let loc:Location={parts:[],deleted:record.deleted,unresolved:record.unresolved||data.version!==version};if(!loc.unresolved&&!loc.deleted){loc.parts=record.segments.map(s=>{const p=this.passage(s.passageId);if(!p||p.chapterId!==s.chapterId||s.to>p.size)throw Error('INVALID_REFERENCE');return{from:p.pos+1+s.from,to:p.pos+1+s.to};});if(!loc.parts.length||loc.parts.some((p,i)=>loc.parts.some((q,j)=>i!==j&&p.from<q.to&&p.to>q.from)))throw Error('INVALID_REFERENCE');}this.locations.set(record.reference.id,loc);}
   const accepted:string[]=[];for(const row of data.items){if(this.items.has(row.item.id)||row.item.references.some(id=>!this.refs.has(id)))throw Error('INVALID_REVIEW');this.items.set(row.item.id,{item:row.item,reviewId:row.reviewId,rejected:row.rejected});if(row.accepted)accepted.push(row.item.id);}this.state=EditorState.create({doc:this.state.doc.type.create({...this.state.doc.attrs,accepted},this.state.doc.content),plugins:[history()]});
  }
  this.remember();
 }
 private makeSection(id:string,role:string,html:string,title:string,kind='chapter',index?:{id:string;path:number[];signature:string}[]){const inspection=inspectHTML(this.document,html);let surface=bookSchema.nodes.surface.create(null,Array.from(inspection.model.content.content,n=>bookSchema.nodeFromJSON(n.toJSON())));let temp=EditorState.create({doc:surface}).tr;const blocks=entries(surface);if(index&&inspection.supported&&index.length!==blocks.length||index&&!inspection.supported&&index.length)throw Error('INVALID_IDENTITY');if(inspection.supported)blocks.forEach((p,i)=>{const saved=index?.[i];if(saved&&(JSON.stringify(saved.path)!==JSON.stringify(p.path)||saved.signature!==signature(p.node)))throw Error('INVALID_IDENTITY');temp.setNodeAttribute(p.pos,'pid',saved?.id||uuid());});surface=temp.doc;this.sources.set(id,{html,initial:surface.content,supported:inspection.supported,title,kind});return bookSchema.nodes.section.create({id,role,title,kind},surface.content);}
 get version():string{return this.state.doc.attrs.version;}
 setTraceParent(carrier?:string){this.commandParent=this.telemetry?.parent(carrier);}
 get activeSection(){const owner=this.owner(this.state.selection.from);return owner?{id:owner.node.attrs.id as string,role:owner.node.attrs.role as string}:null;}
 get title():string{return this.state.doc.attrs.metadata.title;}
 get author():string{return this.state.doc.attrs.metadata.author;}
 get canUndo(){return undoDepth(this.state)>0;}get canRedo(){return redoDepth(this.state)>0;}
 get sections(){const out:Section[]=[];this.state.doc.forEach((node,pos,index)=>out.push({node,pos,index}));return out;}
 section(id:string){const s=this.sections.find(s=>s.node.attrs.id===id);if(!s)throw Error('NOT_FOUND');return s;}
 owner(pos:number){return this.sections.find(s=>pos>=s.pos+1&&pos<=s.pos+s.node.nodeSize-1);}
 get chapters(){return this.sections.filter(s=>s.node.attrs.role==='chapter').map(s=>({id:s.node.attrs.id as string,title:s.node.attrs.title as string,kind:s.node.attrs.kind as string}));}
 get darlings(){return (this.state.doc.attrs.darlings as unknown[]).flatMap(d=>{const parsed=Darling.safeParse(d);return parsed.success?[parsed.data]:[];});}
 supported(id:string){return this.sources.get(id)?.supported??false;}
 passages(sectionId?:string):PassageInfo[]{if(this.passageDoc!==this.state.doc){this.passageDoc=this.state.doc;const sections=this.sections;this.passageCache=entries(this.state.doc).flatMap(e=>{const owner=sections.find(s=>e.pos>=s.pos+1&&e.pos<=s.pos+s.node.nodeSize-1);if(!owner||!this.supported(owner.node.attrs.id))return[];return [{id:e.node.attrs.pid as string,chapterId:owner.node.attrs.id as string,kind:e.node.type.name,text:runText(runs(e.node.content)),size:e.node.content.size,pos:e.pos,path:e.path,node:e.node}];});this.passageById=new Map(this.passageCache.map(p=>[p.id,p]));}return sectionId?this.passageCache.filter(p=>p.chapterId===sectionId):this.passageCache;}
 private passage(id:string){this.passages();return this.passageById.get(id);}

 private wordCount(){return this.passages().filter(p=>this.section(p.chapterId).node.attrs.role==='chapter').reduce((n,p)=>n+words(p.text),0);}
 subscribe(fn:(event:CoreEvent)=>void){this.listeners.add(fn);return()=>this.listeners.delete(fn);}
 private remember(){this.cache.set(this.version,new Map(Array.from(this.locations,([id,loc])=>[id,clone(loc)])));}
 dispatch(tr:Transaction,command='typing',historical=false,parent?:Context){const op=()=>this.apply(tr,command,historical);return this.telemetry?this.telemetry.sync('editor.transaction',op,parent??this.commandParent):op();}
 private apply(tr:Transaction,command:string,historical:boolean){
  if(!tr.docChanged){this.state=this.state.apply(tr);for(const fn of this.listeners)fn({kind:'selection',revision:this.revision,command});return;}
  for(const old of this.sections){if(!this.supported(old.node.attrs.id)){let replacement:PMNode|undefined;tr.doc.forEach(n=>{if(n.attrs.id===old.node.attrs.id)replacement=n;});if(replacement&&!replacement.content.eq(old.node.content))throw Error('UNSUPPORTED_CONTENT');}}
  this.remember();const before=this.state,previous=this.version,depthBefore=undoDepth(before);const firstStep=tr.steps[0]?.toJSON();
  const inline=tr.steps.every(step=>{const d=step.toJSON();return ['addMark','removeMark','docAttr','attr'].includes(d.stepType)||d.stepType==='replace'&&before.doc.resolve(d.from).sameParent(before.doc.resolve(d.to))&&before.doc.resolve(d.from).parent.isTextblock&&(d.slice?.content||[]).every((n:{type:string})=>['text','hard_break','placeholder','darling_anchor'].includes(n.type));});
  if(!historical){if(!inline){const oldPositions=new Map(entries(before.doc).map(e=>[e.node.attrs.pid,tr.mapping.map(e.pos,1)])),all=entries(tr.doc).filter(e=>{let supported=false;tr.doc.forEach((section,pos)=>{if(e.pos>pos&&e.pos<pos+section.nodeSize)supported=this.supported(section.attrs.id);});return supported;}),keep=new Map<string,typeof all[number]>();for(const p of all){const id=p.node.attrs.pid;if(!id)continue;const old=keep.get(id),expected=oldPositions.get(id);if(!old||expected!==undefined&&Math.abs(p.pos-expected)<Math.abs(old.pos-expected))keep.set(id,p);}for(const p of all)if(!p.node.attrs.pid||keep.get(p.node.attrs.pid)!==p)tr.setNodeAttribute(p.pos,'pid',uuid());}tr.setDocAttribute('version',uuid());}
  const relocation=tr.getMeta('relocate') as {start:number;end:number;target:number}|undefined;
  const mapped=new Map<string,Location>();for(const [id,loc]of this.locations){if(loc.deleted||loc.unresolved){mapped.set(id,clone(loc));continue;}const parts=this.segments(loc).map(s=>{const p=this.passage(s.passageId)!;return{from:p.pos+1+s.from,to:p.pos+1+s.to};}).map(p=>relocation&&p.from>=relocation.start+1&&p.to<=relocation.end-1?{from:relocation.target+p.from-relocation.start,to:relocation.target+p.to-relocation.start}:{from:tr.mapping.map(p.from,1),to:tr.mapping.map(p.to,-1)}).filter(p=>p.to>p.from);const merged:Part[]=[];for(const p of parts){const last=merged.at(-1);if(last&&last.to===p.from)last.to=p.to;else merged.push(p);}mapped.set(id,{parts:merged,deleted:!merged.length,unresolved:false});}
  this.state=before.apply(tr);const cached=historical?this.cache.get(this.version):undefined;this.locations=historical?new Map(Array.from(mapped,([id,loc])=>[id,cached?.has(id)?clone(cached.get(id)!):{...loc,unresolved:true}])):mapped;
  this.remember();const depth=undoDepth(this.state);if(historical)this.cursor=depth;else{this.events=this.events.slice(0,this.cursor);if(depth!==depthBefore||!this.events.length)this.events.push({before:previous,after:this.version});else this.events.at(-1)!.after=this.version;while(this.events.length>depth)this.events.shift();this.cursor=this.events.length;}const retained=new Set([this.version,...this.events.flatMap(e=>[e.before,e.after])]);for(const version of this.cache.keys())if(!retained.has(version))this.cache.delete(version);
  if(inline&&firstStep?.stepType==='replace'&&this.owner(tr.mapping.map(firstStep.from,1))?.node.attrs.role==='chapter'){const a=before.doc.resolve(firstStep.from).parent,b=this.state.doc.resolve(tr.mapping.map(firstStep.from,1)).parent;this.words+=words(b.textContent)-words(a.textContent);}else if(!inline)this.words=this.wordCount();
  this.revision++;for(const fn of this.listeners)fn({kind:'changed',revision:this.revision,command});
 }
 undo(){return undo(this.state,tr=>this.dispatch(tr,'undo',true));}redo(){return redo(this.state,tr=>this.dispatch(tr,'redo',true));}
 select(id:string,from:number,to=from){const s=this.section(id);this.dispatch(this.state.tr.setSelection(TextSelection.create(this.state.doc,s.pos+1+from,s.pos+1+to)),'select');}
 insert(text:string){const owner=this.owner(this.state.selection.from);if(!owner||!this.supported(owner.node.attrs.id))throw Error('UNSUPPORTED_CONTENT');this.dispatch(this.state.tr.insertText(text));}
 html(id:string){const s=this.section(id),source=this.sources.get(id)!;if(!source.supported||s.node.content.eq(source.initial))return source.html;const doc=htmlSchema.nodes.doc.create(null,Array.from(s.node.content.content,n=>baseNode(n)));return exportHTML(this.document,doc);}
 createChapter(title:string){const id=uuid(),section=this.makeSection(id,'chapter','<p></p>',title);const last=this.sections.filter(s=>s.node.attrs.role==='chapter').at(-1)!;this.dispatch(closeHistory(this.state.tr).insert(last.pos+last.node.nodeSize,section),'chapter.create');return id;}
 renameChapter(id:string,title:string){const s=this.section(id);this.dispatch(closeHistory(this.state.tr).setNodeAttribute(s.pos,'title',title),'chapter.rename');}
 duplicateChapter(id:string){const source=this.section(id),copy=uuid(),section=this.makeSection(copy,'chapter',this.html(id),source.node.attrs.title+' copy',source.node.attrs.kind);this.dispatch(closeHistory(this.state.tr).insert(source.pos+source.node.nodeSize,section),'chapter.duplicate');return copy;}
 deleteChapter(id:string){const s=this.section(id);if(s.node.attrs.role!=='chapter'||this.chapters.length===1)throw Error('LAST_CHAPTER');this.dispatch(closeHistory(this.state.tr).delete(s.pos,s.pos+s.node.nodeSize),'chapter.delete');}
 reorderChapter(id:string,index:number){const s=this.section(id),chapters=this.sections.filter(s=>s.node.attrs.role==='chapter');if(!Number.isInteger(index)||index<0||index>=chapters.length)throw Error('INVALID_TARGET');if(chapters[index].node.attrs.id===id)return;const tr=closeHistory(this.state.tr).delete(s.pos,s.pos+s.node.nodeSize);let target=0;for(let i=0;i<index;i++)target+=tr.doc.child(i).nodeSize;tr.insert(target,s.node).setMeta('relocate',{start:s.pos,end:s.pos+s.node.nodeSize,target});this.dispatch(tr,'chapter.reorder');}
 movePassage(id:string,targetId:string,index?:number){const p=this.passage(id),source=p&&this.section(p.chapterId),target=this.section(targetId);index??=target.node.childCount;if(!p||p.path.length!==2||!source||source.node.attrs.role!=='chapter'||target.node.attrs.role!=='chapter'||!this.supported(targetId)||!Number.isInteger(index)||index<0||index>target.node.childCount)throw Error('UNSUPPORTED_MOVE');const tr=closeHistory(this.state.tr).delete(p.pos,p.pos+p.node.nodeSize);let at=0;tr.doc.forEach((n,pos)=>{if(n.attrs.id===targetId){at=pos+1;for(let i=0;i<Math.min(index,n.childCount);i++)at+=n.child(i).nodeSize;}});tr.insert(at,p.node).setMeta('relocate',{start:p.pos,end:p.pos+p.node.nodeSize,target:at});this.dispatch(tr,'passage.move');}
 archive(){const {from,to,$from,$to}=this.state.selection;if(from===to||!$from.sameParent($to)||!$from.parent.isTextblock)throw Error('UNSUPPORTED_TARGET');const owner=this.owner(from)!;if(!this.supported(owner.node.attrs.id))throw Error('UNSUPPORTED_CONTENT');const content=this.state.doc.slice(from,to).content,id=uuid();const paragraph=htmlSchema.nodes.paragraph.create(null,Array.from(content.content,n=>baseNode(n)));const html=exportHTML(this.document,htmlSchema.nodes.doc.create(null,paragraph));const record={id,html,text:runText(runs(content)),chapterId:owner.node.attrs.id,chapterLabel:owner.node.attrs.title,date:new Date().toISOString()};const anchor=bookSchema.nodes.darling_anchor.create({did:id});this.dispatch(closeHistory(this.state.tr).replaceWith(from,to,anchor).setDocAttribute('darlings',[...this.state.doc.attrs.darlings,record]),'darling.archive');}
 restore(id:string){const record=this.darlings.find(d=>d.id===id);if(!record)throw Error('NOT_FOUND');let at:number|undefined;this.state.doc.descendants((n,pos)=>{if(n.type.name==='darling_anchor'&&n.attrs.did===id)at=pos;});if(at===undefined)throw Error('MISSING_ANCHOR');const parsed=inspectHTML(this.document,record.html);if(!parsed.supported||parsed.model.childCount!==1||!parsed.model.child(0).isTextblock)throw Error('UNSUPPORTED_TARGET');const content=Fragment.fromArray(Array.from(parsed.model.child(0).content.content,n=>bookSchema.nodeFromJSON(n.toJSON())));this.dispatch(closeHistory(this.state.tr).replace(at,at+1,new Slice(content,0,0)).setDocAttribute('darlings',(this.state.doc.attrs.darlings as unknown[]).filter(d=>!(d&&typeof d==='object'&&'id'in d&&d.id===id))),'darling.restore');}
 format(mark:'bold'|'italic'){toggleMark(bookSchema.marks[mark])(this.state,tr=>this.dispatch(closeHistory(tr),'format'));}
 passageRows(sectionId?:string){return this.passages(sectionId).map(p=>({id:p.id,chapterId:p.chapterId,kind:p.kind,text:p.text,size:p.size}));}
 captureSelection(){const {from,to}=this.state.selection,p=this.passages().find(p=>from>=p.pos+1&&to<=p.pos+1+p.size);if(!p||from===to)throw Error('Select text within a paragraph');return this.capture(p.id,from-p.pos-1,to-p.pos-1);}
 private segments(loc:Location){if(loc.deleted||loc.unresolved)return[];return loc.parts.flatMap(part=>this.passages().filter(p=>part.to>p.pos+1&&part.from<p.pos+1+p.size).map(p=>({chapterId:p.chapterId,passageId:p.id,from:Math.max(0,part.from-p.pos-1),to:Math.min(p.size,part.to-p.pos-1)})));}
 private content(loc:Location){let fragment=Fragment.empty;for(const s of this.segments(loc)){const p=this.passage(s.passageId)!;fragment=fragment.append(p.node.content.cut(s.from,s.to));}return runs(fragment);}
 capture(id:string,from:number,to:number){const p=this.passage(id);if(!p||!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<=from||to>p.size)throw Error('INVALID_REFERENCE');const expected=runs(p.node.content.cut(from,to));const ref=Reference.parse({id:uuid(),chapterId:p.chapterId,passageId:id,from,to,version:this.version,expected,text:runText(expected)});this.refs.set(ref.id,ref);this.locations.set(ref.id,{parts:[{from:p.pos+1+from,to:p.pos+1+to}],deleted:false,unresolved:false});this.remember();return structuredClone(ref);}
 resolve(id:string){const ref=this.refs.get(id),loc=this.locations.get(id);if(!ref||!loc||loc.unresolved)return{status:'unresolved',segments:[],text:''};if(loc.deleted)return{status:'deleted',segments:[],text:''};const content=this.content(loc);return{status:JSON.stringify(content)===JSON.stringify(ref.expected)?'current':'changed',segments:this.segments(loc),text:runText(content)};}
 extract(ids:string[],category:ReviewInput['category']){const input=Input.parse({requestId:uuid(),bookId:this.state.doc.attrs.metadata.id,revision:this.revision,category,extracts:ids.map(id=>{const ref=this.refs.get(id),loc=this.locations.get(id);if(!ref||!loc||this.resolve(id).status!=='current')throw Error('STALE');const segments=this.segments(loc),p=this.passage(segments[0].passageId)!;return{reference:ref,currentSegments:segments,version:this.version,chapterOrder:this.chapters.findIndex(c=>c.id===p.chapterId),passageKind:p.kind,runs:this.content(loc),text:runText(this.content(loc))};})});this.requests.set(input.requestId,input);return structuredClone(input);}
 receive(raw:unknown){const data=ReviewOutput.parse(raw),request=this.requests.get(data.requestId);if(!request)throw Error('UNKNOWN_REQUEST');const allowed=new Set(request.extracts.map(e=>e.reference.id)),ids=new Set<string>();for(const item of data.items){if(ids.has(item.id)||this.items.has(item.id)||item.references.some(id=>!allowed.has(id)))throw Error('INVALID_REVIEW');ids.add(item.id);}for(const item of data.items)this.items.set(item.id,{item,reviewId:data.reviewId,rejected:false});this.revision++;for(const fn of this.listeners)fn({kind:'changed',revision:this.revision,command:'review.attach'});}
 reviewRows(){return structuredClone(Array.from(this.items.values(),row=>({...row.item,state:row.rejected?'rejected':(this.state.doc.attrs.accepted as string[]).includes(row.item.id)?'accepted':'pending',resolutions:row.item.references.map(id=>this.resolve(id))})));}
 accept(id:string){const row=this.items.get(id);if(!row||row.item.kind!=='suggestion')return{ok:false,code:'NOT_FOUND'};if(row.rejected)return{ok:false,code:'REJECTED'};if((this.state.doc.attrs.accepted as string[]).includes(id))return{ok:true};const refid=row.item.references[0],loc=this.locations.get(refid),resolution=this.resolve(refid);if(!loc||resolution.status!=='current')return{ok:false,code:'STALE'};if(resolution.segments.length!==1)return{ok:false,code:'UNSUPPORTED_TARGET'};const {from,to}=loc.parts[0],content=this.state.doc.slice(from,to).content.content;if(content.some(n=>!n.isText||!n.sameMarkup(content[0])))return{ok:false,code:'UNSUPPORTED_TARGET'};const tr=closeHistory(this.state.tr);if(row.item.replacement)tr.replaceWith(from,to,bookSchema.text(row.item.replacement,content[0]?.marks));else tr.delete(from,to);tr.setDocAttribute('accepted',[...this.state.doc.attrs.accepted,id]);this.dispatch(tr,'review.accept');return{ok:true};}
 reject(id:string){const row=this.items.get(id);if(!row)throw Error('NOT_FOUND');if((this.state.doc.attrs.accepted as string[]).includes(id))throw Error('ACCEPTED');if(!row.rejected){row.rejected=true;this.revision++;for(const fn of this.listeners)fn({kind:'changed',revision:this.revision,command:'review.reject'});}}
 checkpoint(carrier?:string):CheckpointValue{this.snapshots++;const op=()=>{const metadata=structuredClone(this.state.doc.attrs.metadata);for(const chapter of this.chapters){const initial=this.sources.get(chapter.id)!;if(!this.originalIds.has(chapter.id)||chapter.title!==initial.title){metadata.chapterTitles={...metadata.chapterTitles,[chapter.id]:chapter.title};}if(!this.originalIds.has(chapter.id)||chapter.kind!==initial.kind){metadata.chapterKinds={...metadata.chapterKinds,[chapter.id]:chapter.kind};}}const book={formatVersion:'neo-composed/v1',revision:this.revision,version:this.version,metadata,darlings:this.state.doc.attrs.darlings,chapters:this.chapters.map(c=>({id:c.id,html:this.html(c.id),version:this.version,passages:this.passages(c.id).map(p=>({id:p.id,path:p.path.slice(1),signature:signature(p.node)}))}))};const reviews={formatVersion:'neo-composed-reviews/v1',bookId:metadata.id,version:this.version,references:Array.from(this.refs.values(),reference=>{const loc=this.locations.get(reference.id)!;return{reference,segments:this.segments(loc),deleted:loc.deleted,unresolved:loc.unresolved};}),items:Array.from(this.items.values(),row=>({...row,accepted:(this.state.doc.attrs.accepted as string[]).includes(row.item.id)}))};return Checkpoint.parse({book,reviews,notes:this.html('notes'),outline:this.html('outline')});};return this.telemetry?this.telemetry.sync('editor.snapshot',op,this.telemetry.parent(carrier)):op();}
}
