import { it,expect } from 'vitest';import { JSDOM } from 'jsdom';import { TextSelection } from 'prosemirror-state';
import { BookCore } from './core';import { deterministicReview } from '../identity-spike/fixture';
const document=new JSDOM('').window.document;
const raw={formatVersion:'neo-lifecycle/v1',revision:0,metadata:{id:'book',title:'Promise',author:'Writer',chapterTitles:{a:'Arrival',b:'Return'}},chapters:[{id:'a',html:'<p>Mara whispered.</p><p>A promise.</p>'},{id:'b',html:'<p>She returned.</p>'}],darlings:[]};
const open=()=>new BookCore(document,raw,null,'<p>Notes <i>here</i>.</p>','<p>Outline.</p>');
it('one native history owns typing, cross-chapter moves, Darling records, chapter metadata and auxiliary prose',()=>{
 const c=open(),initial=c.checkpoint();c.select('a',1,5);c.insert('At dawn, ');expect(c.html('a')).toContain('At dawn');const p=c.passages('a')[1];const ref=c.capture(p.id,0,p.size);c.movePassage(p.id,'b',1);expect(c.resolve(ref.id).status).toBe('current');expect(c.resolve(ref.id).segments[0].chapterId).toBe('b');expect(c.passages('b')[1].id).toBe(p.id);c.undo();expect(c.resolve(ref.id).segments[0].chapterId).toBe('a');c.redo();expect(c.resolve(ref.id).segments[0].chapterId).toBe('b');
 c.select('a',1,5);c.archive();expect(c.darlings).toHaveLength(1);const darling=c.darlings[0];expect(c.html('a')).toContain('darling-anchor');c.restore(darling.id);expect(c.darlings).toHaveLength(0);c.undo();expect(c.darlings).toHaveLength(1);c.undo();expect(c.darlings).toHaveLength(0);
 c.renameChapter('a','New arrival');expect(c.chapters[0].title).toBe('New arrival');c.undo();expect(c.chapters[0].title).toBe('Arrival');c.select('notes',1,1);c.insert('Research ');expect(c.html('notes')).toContain('Research');c.undo();expect(c.html('notes')).toBe(initial.notes);
});
it('chapter create, duplicate, reorder and delete are atomic undo events with preserved originals',()=>{const c=open();const id=c.createChapter('New');c.renameChapter(id,'Revised');c.undo();expect(c.chapters.at(-1)?.title).toBe('New');c.undo();expect(c.chapters).toHaveLength(2);c.redo();const copy=c.duplicateChapter('a');expect(c.html(copy)).toBe(c.html('a'));expect(c.passages(copy).map(p=>p.id)).not.toEqual(c.passages('a').map(p=>p.id));c.reorderChapter(copy,0);expect(c.chapters[0].id).toBe(copy);c.deleteChapter(copy);c.undo();expect(c.chapters[0].id).toBe(copy);});
it('review attachment, acceptance, rejection and references compose with global history and cross-chapter moves',()=>{const c=open(),p=c.passages('a')[0],r=c.capture(p.id,5,14);const input=c.extract([r.id],'voice');c.receive({reviewId:'fixture',requestId:input.requestId,items:[{id:'suggestion',kind:'suggestion',category:'voice',references:[r.id],message:'Direct verb',replacement:'said'}]});c.movePassage(p.id,'b',1);expect(c.accept('suggestion')).toEqual({ok:true});expect(c.html('b')).toContain('Mara said');c.undo();expect(c.resolve(r.id).status).toBe('current');expect(c.reviewRows()[0].state).toBe('pending');c.undo();expect(c.resolve(r.id).segments[0].chapterId).toBe('a');c.redo();c.redo();const saved=c.checkpoint(),re=new BookCore(document,saved.book,saved.reviews,saved.notes,saved.outline);expect(re.html('b')).toContain('Mara said');expect(re.reviewRows()[0].state).toBe('accepted');});
it('unsupported sections remain raw through duplication, reorder, save and native history',()=>{const b=structuredClone(raw);b.chapters[0].html='<p style="color:red">Original</p>';const c=new BookCore(document,b,null,'','');expect(c.supported('a')).toBe(false);expect(()=>c.insert('bad')).toThrow();const copy=c.duplicateChapter('a');expect(c.html(copy)).toBe(b.chapters[0].html);c.deleteChapter('a');c.undo();expect(c.html('a')).toBe(b.chapters[0].html);});

it('a fresh checkpoint retains imported metadata, rich source, Darlings and auxiliary bytes',()=>{const source=structuredClone(raw);source.metadata=Object.assign(source.metadata,{custom:{colour:'ochre'}});source.darlings=[{id:'existing',html:'<p><i>Kept</i></p>',text:'Kept',extra:'retained'}] as never;const c=new BookCore(document,source,null,'<p data-note="yes">Notes</p>','<p>Plot &amp; motive.</p>'),saved=c.checkpoint();expect(saved.book.metadata).toEqual(source.metadata);expect(saved.book.darlings).toEqual(source.darlings);expect(saved.book.chapters.map(ch=>ch.html)).toEqual(source.chapters.map(ch=>ch.html));expect(saved.notes).toBe('<p data-note="yes">Notes</p>');expect(saved.outline).toBe('<p>Plot &amp; motive.</p>');});
