import { test,expect,_electron,type ElectronApplication,type Page } from '@playwright/test';import { mkdtemp,writeFile,readFile,chmod,rm,mkdir,readdir } from 'node:fs/promises';import { join,resolve } from 'node:path';import { tmpdir,homedir } from 'node:os';import { execFileSync } from 'node:child_process';import { legacyFixture } from '../lifecycle-spike/fixture';import { Manuscript,Reviews } from './contracts';
const packageRoot=resolve(import.meta.dirname,'..');
async function start(root:string){const receipt=JSON.parse(await readFile(join(packageRoot,'node_modules/.neo-parity-hosts/electron/receipt.json'),'utf8'));execFileSync('codesign',['--verify','--deep','--strict',join(packageRoot,'node_modules/.neo-parity-hosts/electron/NEO Parity.app')]);return _electron.launch({executablePath:receipt.executable,args:[join(packageRoot,'composition-spike/launch.cjs')],env:{...process.env,NEO_COMPOSITION_ROOT:root},timeout:15000});}
async function caret(p:Page,offset:number,label='Manuscript'){await p.getByRole('textbox',{name:label,exact:true}).evaluate((el,offset)=>{(el as HTMLElement).focus();const text=el.querySelector('p')!.firstChild!,range=document.createRange();range.setStart(text,offset);range.collapse(true);const selection=getSelection()!;selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'));},offset);await p.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));}
async function dumps(){try{return(await readdir(join(homedir(),'Library/Logs/DiagnosticReports'))).filter(f=>/^(Electron|NEO).*\.ips$/.test(f));}catch{return[];}}
test('signed hidden composed host: actual IPC, durable review/prose checkpoint, global undo, process restart and failed save-on-close',async()=>{
 const before=await dumps(),root=await mkdtemp(join(tmpdir(),'neo-composition-native-'));let app:ElectronApplication|undefined;try{
  await writeFile(join(root,'.composition-fixture'),'neo-composition-v1');await legacyFixture(join(root,'source'));app=await start(root);let p=await app.firstWindow();const errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));await expect(p.getByRole('status')).toHaveText('Opened');expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().every(w=>!w.isVisible()))).toBe(true);expect(await p.evaluate(()=>typeof (window as unknown as {require?:unknown}).require)).toBe('undefined');await p.getByRole('button',{name:'The arrival',exact:true}).click();await caret(p,0);await p.keyboard.type('Acknowledged ');await expect(p.getByRole('textbox',{name:'Manuscript',exact:true})).toContainText('Acknowledged');
  await caret(p,0,'Book notes');await p.keyboard.type('Observation ');await p.getByRole('button',{name:'Undo',exact:true}).click();await expect(p.getByRole('textbox',{name:'Book notes',exact:true})).not.toContainText('Observation');await p.getByRole('button',{name:'Redo',exact:true}).click();await expect(p.getByRole('textbox',{name:'Book notes',exact:true})).toContainText('Observation');
  await p.getByRole('button',{name:'Review structure',exact:true}).click();await p.getByRole('button',{name:'Save',exact:true}).click();await expect(p.getByRole('status')).toHaveText('Saved');const committed=Manuscript.parse(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8'))),reviews=Reviews.parse(JSON.parse(await readFile(join(root,'book/reviews.json'),'utf8')));expect(committed.chapters.find(c=>c.id==='arrival')!.html).toContain('Acknowledged');expect(reviews.version).toBe(committed.version);expect(await readFile(join(root,'book/notes.html'),'utf8')).toContain('Observation');
  const traces=await p.evaluate(async()=>({renderer:await window.compositionSpike.telemetry.report(),host:await window.compositionHost!.request({method:'diagnostics'})}));expect(traces.host.ok).toBe(true);if(!traces.host.ok)throw Error('No diagnostics');const host=traces.host.value as {name:string;traceId:string;spanId:string;parentSpanId?:string}[],ui=traces.renderer.find(s=>s.name==='ui.save')!;const ipc=host.find(s=>s.name==='ipc.save'&&s.traceId===ui.traceId&&s.parentSpanId===ui.spanId)!;expect(ipc).toBeTruthy();expect(host.some(s=>s.name==='storage.checkpoint'&&s.traceId===ui.traceId&&s.parentSpanId===ipc.spanId)).toBe(true);expect(traces.renderer.some(s=>s.name==='editor.transaction'&&s.parentSpanId&&traces.renderer.some(p=>p.spanId===s.parentSpanId&&['ui.input','ui.command'].includes(p.name)))).toBe(true);expect(JSON.stringify(traces)).not.toContain('Acknowledged');expect(JSON.stringify(traces)).not.toContain(root);
  await mkdir('/tmp/neo-composition-spike',{recursive:true});await writeFile('/tmp/neo-composition-spike/ipc-traces.json',JSON.stringify(traces,null,2));
  app.process().kill('SIGKILL');await new Promise<void>(resolve=>app!.process().once('exit',()=>resolve()));app=await start(root);p=await app.firstWindow();p.on('pageerror',e=>errors.push(e.message));await expect(p.getByRole('status')).toHaveText('Opened');await p.getByRole('button',{name:'The arrival',exact:true}).click();await expect(p.getByRole('textbox',{name:'Manuscript',exact:true})).toContainText('Acknowledged');await expect(p.getByRole('textbox',{name:'Book notes',exact:true})).toContainText('Observation');await expect(p.locator('article[data-kind=note] blockquote[data-status=current]')).toHaveCount(reviews.references.length);
  await caret(p,0);await p.keyboard.type('Retain ');await chmod(join(root,'book'),0o500);await p.getByRole('button',{name:'Close book'}).click();await expect(p.getByRole('dialog')).toBeVisible();await p.getByRole('button',{name:'Save and close'}).click();await expect(p.getByRole('status')).toHaveText('DISK_ERROR');await expect(p.getByRole('dialog')).toBeVisible();await chmod(join(root,'book'),0o700);const exiting=app.process();await p.getByRole('button',{name:'Save and close'}).click();await expect.poll(()=>exiting.exitCode).not.toBeNull();await app.close().catch(()=>{});app=undefined;expect(Manuscript.parse(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8'))).chapters.find(c=>c.id==='arrival')!.html).toContain('Retain');expect(errors).toEqual([]);expect((await dumps()).filter(f=>!before.includes(f))).toEqual([]);
 }finally{await chmod(join(root,'book'),0o700).catch(()=>{});if(app)await app.close().catch(()=>app!.process().kill('SIGKILL'));await rm(root,{recursive:true,force:true});}
});
