import { EditorState,TextSelection } from 'prosemirror-state';import { Mapping,StepMap } from 'prosemirror-transform';import { EditorView } from 'prosemirror-view';import { keymap } from 'prosemirror-keymap';import { baseKeymap,toggleMark } from 'prosemirror-commands';import { closeHistory } from 'prosemirror-history';import { context,trace } from '@opentelemetry/api';
import { BookCore,bookSchema } from './core';import type { SurfacePort,SurfaceActions } from './editor-port';import type { CompositionTelemetry } from './telemetry';
export class ProseMirrorSurfaces implements SurfacePort {
 private mainView:EditorView|null=null;private auxView:EditorView|null=null;private enabled=true;
 constructor(private core:BookCore,private actions:SurfaceActions,private telemetry:CompositionTelemetry,private input:()=>void){}
 private localState(id:string){const c=this.core,s=c.section(id),doc=bookSchema.nodes.surface.create(null,s.node.content);const selection=c.state.selection,base=s.pos+1;const from=Math.max(1,Math.min(doc.content.size-1,selection.from-base)),to=Math.max(1,Math.min(doc.content.size-1,selection.to-base));return EditorState.create({doc,selection:TextSelection.create(doc,from,to),storedMarks:c.state.storedMarks,plugins:[keymap(baseKeymap)]});}
 private createView(host:HTMLElement,id:()=>string){return new EditorView(host,{state:this.localState(id()),editable:()=>this.enabled&&this.core.supported(id()),attributes:{role:'textbox','aria-label':id()==='notes'?'Book notes':id()==='outline'?'Book outline':'Manuscript',spellcheck:'true'},handleDOMEvents:{beforeinput:()=>{this.input();return false;}},handleKeyDown:(_view,e)=>{if(e.isComposing||e.keyCode===229)return false;const mod=e.metaKey||e.ctrlKey;if(mod&&e.key.toLowerCase()==='z'){e.shiftKey?this.actions.redo():this.actions.undo();return true;}if(mod&&e.key.toLowerCase()==='y'){this.actions.redo();return true;}if(mod&&e.key.toLowerCase()==='s'){this.actions.save();return true;}if(mod&&['b','i'].includes(e.key.toLowerCase())){this.actions.format(e.key.toLowerCase()==='b'?'bold':'italic');return true;}if(mod&&e.shiftKey&&e.key.toLowerCase()==='d'){this.actions.archive();return true;}return false;},dispatchTransaction:local=>{
  const c=this.core,base=c.section(id()).pos+1,mapping=new Mapping([StepMap.offset(base)]),tr=c.state.tr;for(const step of local.steps){const mapped=step.map(mapping);if(!mapped)throw Error('INVALID_SURFACE_STEP');tr.step(mapped);}tr.setSelection(local.selection.map(tr.doc,mapping));if(local.storedMarksSet)tr.setStoredMarks(local.storedMarks);if(tr.docChanged)this.telemetry.sync('ui.input',ctx=>c.dispatch(tr,'typing',false,ctx));else c.dispatch(tr,'selection');
 }});}

 render(main:HTMLElement,aux:HTMLElement,current:string,panel:string,enabled:boolean){this.destroy();this.enabled=enabled;this.mainView=this.createView(main,()=>current);this.auxView=this.createView(aux,()=>panel);}
 update(current:string,panel:string,enabled:boolean){this.enabled=enabled;this.mainView?.updateState(this.localState(current));this.auxView?.updateState(this.localState(panel));this.mainView?.setProps({editable:()=>enabled&&this.core.supported(current)});this.auxView?.setProps({editable:()=>enabled&&this.core.supported(panel)});}
 focus(){this.mainView?.focus();}destroy(){this.mainView?.destroy();this.auxView?.destroy();this.mainView=null;this.auxView=null;}
}
