import { writable } from 'svelte/store';
import { english } from '@leafloom/language-contracts';
import { createLibrary } from '@leafloom/library';
import { fontChoices } from './font-choices';
import type { AppState } from './application-types';

export function createApplicationState() {
  return writable<AppState>({
    nativeMenus: false,
    publicationPage: null,
    loading: true,
    hostRecovery: null,
    emailSettings: null,
    coverArt: null,
    fontPicker: null,
    goals: null,
    librarySettings: null,
    information: null,
    update: null,
    language: english,
    onboardingFonts: fontChoices('macos'),
    library: createLibrary(),
    books: [],
    covers: {},
    book: null,
    view: 'library',
    panel: 'manuscript',
    manuscriptMode: 'prose',
    screenplayScenes: [],
    chapters: [],
    protectedChapterIds: [],
    outlineRows: [],
    outlineCards: [],
    looseOutlineCards: [],
    walkingOutlineNote: null,
    contentsRows: [],
    darlings: [],
    stickies: [],
    words: 0,
    wordMode: 'book',
    wordLabel: '0 words',
    positionLabel: '',
    currentChapter: null,
    revision: 0,
    dirty: false,
    readOnly: false,
    externalChange: null,
    navOpen: false,
    sideOpen: false,
    stickyAutoOpened: false,
    canUndo: false,
    canRedo: false,
    hint: '',
    modal: null,
    menu: null,
    searchOpen: false,
    search: '',
    searchedQuery: '',
    matches: [],
    matchIndex: 0,
    todayWords: 0,
    sprint: null,
    spellOn: false,
    zoom: 1,
    navPinned: false,
    sidePinned: false,
  });
}
