import type { AppState, AppActions } from './application-types';
export function overlayPresentation(app: AppState) {
  return {
    coverArt: app.coverArt,
    emailSettings: app.emailSettings,
    fontPicker: app.fontPicker,
    goals: app.goals,
    hint: app.hint,
    hostRecovery: app.hostRecovery,
    information: app.information,
    language: app.language,
    librarySettings: app.librarySettings,
    menu: app.menu,
    modal: app.modal,
    publicationPage: app.publicationPage,
    update: app.update,
  };
}
export function overlayActions(actions: AppActions) {
  return {
    answer: actions.answer,
    backupLibrary: actions.backupLibrary,
    bindPublicationPage: actions.bindPublicationPage,
    bodyFontStyle: actions.bodyFontStyle,
    chooseCover: actions.chooseCover,
    chooseEmailMethod: actions.chooseEmailMethod,
    chooseFont: actions.chooseFont,
    chooseLibraryFolder: actions.chooseLibraryFolder,
    closeCoverArt: actions.closeCoverArt,
    closeEmailSettings: actions.closeEmailSettings,
    closeFontPicker: actions.closeFontPicker,
    closeGoals: actions.closeGoals,
    closeInformation: actions.closeInformation,
    closeLibrarySettings: actions.closeLibrarySettings,
    closePublicationPage: actions.closePublicationPage,
    dismissHint: actions.dismissHint,
    dismissMenu: actions.dismissMenu,
    editCoverSettings: actions.editCoverSettings,
    editGoal: actions.editGoal,
    editPublicationTitle: actions.editPublicationTitle,
    enterPublicationTitle: actions.enterPublicationTitle,
    execute: actions.execute,
    fontPickerEnter: actions.fontPickerEnter,
    goalsSprint: actions.goalsSprint,
    leaveFontList: actions.leaveFontList,
    modalValue: actions.modalValue,
    pastePublicationTitle: actions.pastePublicationTitle,
    previewFont: actions.previewFont,
    publicationRedo: actions.publicationRedo,
    publicationUndo: actions.publicationUndo,
    recoverHost: actions.recoverHost,
    restartForUpdate: actions.restartForUpdate,
    revealLibrary: actions.revealLibrary,
    saveCoverSettings: actions.saveCoverSettings,
    searchFonts: actions.searchFonts,
  };
}
