import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import path from 'node:path';
import JSZip from 'jszip';
import {JSDOM} from 'jsdom';
export const sha256=bytes=>createHash('sha256').update(bytes).digest('hex');
export const formatCases=[['NEO-258-A','txt','Plain Text (.txt)'],['NEO-259-A','md','Markdown (.md)'],['NEO-260-A','html','Web Page (.html)'],['NEO-261-A','docx','Word (.docx)'],['NEO-262-A','epub','EPUB (.epub)'],['NEO-263-A','pdf','PDF (.pdf)']];
export const basicFixture={chapters:['<p>Alpha <b>bold</b> <i>italic</i> café 東京.</p><p class="scene-break">***</p><p class="poetry"><i>Verse line.</i></p><p class="ghost">SECRET_GHOST</p><p>End<span class="ph-mark" data-sid="fixture-note" contenteditable="false">⚑</span>.</p>','<p>Second chapter.</p>'],metadata:{title:'An Output & Beyond',author:'Élodie Writer',chapterTitles:{'ch-1':'Opening','ch-2':'Closing'}},stickies:[{id:'fixture-note',chapterId:'ch-1',text:'Private note excluded from export.'}],library:{fonts:{body:'Georgia',dropcap:'none'}}};
export const editionFixture={chapters:['<p>Copyright fixture rights.</p>','<p>For our readers.</p>','<p>Words above a storm.</p><p>— Quoted Writer</p>','<p><br></p>','<p>Movement One</p><p>Movement opening.</p>','<p style="text-align:center">Centered opening.</p><p style="text-align:right">Right edge words.</p><p class="poetry"><i>Verse indented line.</i></p><p>Ordinary last line.</p>','<p>Closing body.</p>','<p>Author biography.</p>'],metadata:{title:'A Book & Beyond',subtitle:'Collected scenes',author:'Guest Export Writer',chapterKinds:{'ch-1':'copyright','ch-2':'dedication','ch-3':'epigraph','ch-4':'contents','ch-5':'part','ch-8':'about'},chapterTitles:{'ch-5':'Movement One','ch-6':'Opening','ch-7':'Closing'}},library:{fonts:{body:'Georgia',dropcap:'literary'}}};
const dom=(text,xml=false)=>new JSDOM(text,xml?{contentType:'text/xml'}:{}).window.document;
const compact=text=>text.normalize('NFKC').replace(/\s/g,'').toLowerCase();
export async function readPDF(bytes){const module=await import('pdfjs-dist/legacy/build/pdf.mjs');const task=module.getDocument({data:new Uint8Array(bytes),useSystemFonts:true});const pdf=await task.promise;const pages=await Promise.all(Array.from({length:pdf.numPages},(_,i)=>pdf.getPage(i+1)));const items=await Promise.all(pages.map(async page=>(await page.getTextContent()).items.filter(item=>'str'in item)));return{pdf,pages,items,text:items.map(page=>page.map(item=>item.str).join(' ')).join('\n'),close:()=>task.destroy()};}
export async function inspectExport(format,bytes){assert.ok(bytes.length>30,'Actual nonempty export file');let text=bytes.toString('utf8'),details={};
 if(format==='html'){const document=dom(text);assert.equal(document.querySelectorAll('script').length,0,'Standalone HTML excludes scripts');details={title:document.title};text=document.body.textContent;}
 if(format==='docx'){const zip=await JSZip.loadAsync(bytes),xml=await zip.file('word/document.xml')?.async('string');assert.ok(xml,'Real DOCX document.xml');assert.ok(zip.file('word/styles.xml'),'Real DOCX styles');const document=dom(xml,true);text=[...document.getElementsByTagName('w:t')].map(el=>el.textContent).join(' ');assert.match(xml,/<w:b(?:\s|\/|>)/);assert.match(xml,/<w:i(?:\s|\/|>)/);details={entries:Object.keys(zip.files)};}
 if(format==='epub'){const zip=await JSZip.loadAsync(bytes);assert.equal(await zip.file('mimetype')?.async('string'),'application/epub+zip');assert.equal(bytes.readUInt16LE(8),0,'EPUB mimetype uncompressed');assert.equal(bytes.subarray(30,38).toString(),'mimetype','EPUB mimetype first');const opfName=Object.keys(zip.files).find(name=>name.endsWith('.opf'));assert.ok(opfName,'Real OPF');const doc=dom(await zip.file(opfName).async('string'),true),base=path.posix.dirname(opfName);const manifest=[...doc.getElementsByTagName('item')].map(el=>({id:el.getAttribute('id'),href:el.getAttribute('href'),properties:el.getAttribute('properties')}));const spine=[...doc.getElementsByTagName('itemref')].map(el=>el.getAttribute('idref'));for(const id of spine){const item=manifest.find(item=>item.id===id);assert.ok(item,'Spine manifest entry '+id);assert.ok(zip.file(path.posix.join(base,item.href)),'Spine file '+item.href);}const nav=manifest.find(item=>item.properties?.split(/\s/).includes('nav'));assert.ok(nav,'EPUB3 navigation');const navigation=dom(await zip.file(path.posix.join(base,nav.href)).async('string'),true);for(const link of navigation.getElementsByTagName('a')){const href=link.getAttribute('href');if(!href||/^[a-z]+:/i.test(href))continue;assert.ok(zip.file(path.posix.normalize(path.posix.join(base,href.split('#')[0]))),'Navigation target '+href);}const xhtml=Object.keys(zip.files).filter(name=>name.endsWith('.xhtml'));text=(await Promise.all(xhtml.map(async name=>dom(await zip.file(name).async('string'),true).documentElement.textContent))).join('\n');details={entries:Object.keys(zip.files),spine};}
 if(format==='pdf'){assert.equal(bytes.subarray(0,5).toString(),'%PDF-');const parsed=await readPDF(bytes);try{assert.ok(parsed.pdf.numPages>=2,'Title and body PDF pages');assert.ok((await parsed.pdf.getOutline())?.length,'Actual PDF bookmarks');text=parsed.text;details={pages:parsed.pdf.numPages,outline:await parsed.pdf.getOutline()};}finally{await parsed.close();}}
 const content=compact(text);for(const phrase of ['Edited Alpha','bold','italic','café','東京','Verse line.','Second chapter.','Opening','Closing'])assert.ok(content.includes(compact(phrase)),'Actual '+format+' text '+phrase);for(const excluded of ['SECRET_GHOST','Private note excluded','⚑','data-sid'])assert.ok(!text.includes(excluded),'Export excludes '+excluded);if(format==='md'){assert.match(text,/\*\*bold\*\*/);assert.match(text,/\*italic\*/);}return{format,sha256:sha256(bytes),bytes:bytes.length,details};
}
export async function inspectEdition(format,bytes){const required=['Copyright fixture rights.','For our readers.','Movement opening.','Centered opening.','Closing body.','Author biography.'];let ordered;
 if(format==='html'){const document=dom(bytes.toString('utf8'));assert.equal(document.title,'A Book & Beyond');assert.equal(document.querySelectorAll('script').length,0);for(const link of document.querySelectorAll('a[href^="#"]'))assert.ok(document.getElementById(link.getAttribute('href').slice(1)),'Actual HTML TOC destination');const paragraphs=[...document.querySelectorAll('p')];assert.equal(paragraphs.find(p=>p.textContent==='Centered opening.')?.style.textAlign,'center');assert.equal(paragraphs.find(p=>p.textContent==='Right edge words.')?.style.textAlign,'right');assert.equal(document.querySelector('p.poetry')?.textContent,'Verse indented line.');assert.match(bytes.toString('utf8'),/first-letter/);ordered=document.body.textContent;}
 if(format==='docx'){const zip=await JSZip.loadAsync(bytes),xml=await zip.file('word/document.xml').async('string'),document=dom(xml,true);const paragraphs=[...document.getElementsByTagName('w:p')];const paragraph=text=>paragraphs.find(p=>p.textContent.includes(text));assert.equal(paragraph('Centered opening.').getElementsByTagName('w:jc')[0]?.getAttribute('w:val'),'center');assert.equal(paragraph('Right edge words.').getElementsByTagName('w:jc')[0]?.getAttribute('w:val'),'right');const verse=paragraph('Verse indented line.'),indent=verse.getElementsByTagName('w:ind')[0];assert.ok(Number(indent?.getAttribute('w:left'))>0&&Number(indent?.getAttribute('w:right'))>0,'Poetry left/right indentation');assert.ok(verse.getElementsByTagName('w:i').length,'Poetry italic');assert.ok(paragraphs.some(p=>p.getElementsByTagName('w:pageBreakBefore').length),'Actual chapter page boundaries');assert.match(await zip.file('word/styles.xml').async('string'),/outlineLvl/);ordered=document.documentElement.textContent;}
 if(format==='epub'){const zip=await JSZip.loadAsync(bytes),opfName=Object.keys(zip.files).find(name=>name.endsWith('.opf')),doc=dom(await zip.file(opfName).async('string'),true),base=path.posix.dirname(opfName),manifest=[...doc.getElementsByTagName('item')],spine=[...doc.getElementsByTagName('itemref')];ordered=(await Promise.all(spine.map(async entry=>{const item=manifest.find(item=>item.getAttribute('id')===entry.getAttribute('idref'));assert.ok(item);const name=path.posix.join(base,item.getAttribute('href'));assert.ok(zip.file(name));return dom(await zip.file(name).async('string'),true).documentElement.textContent;}))).join('\n');const css=await zip.file(path.posix.join(base,'style.css')).async('string');assert.match(css,/\.poetry/);assert.match(css,/font-family:\s*serif/);const nav=manifest.find(item=>item.getAttribute('properties')?.split(/\s/).includes('nav'));assert.ok(nav);const links=dom(await zip.file(path.posix.join(base,nav.getAttribute('href'))).async('string'),true).getElementsByTagName('a');assert.ok(links.length>=3);for(const link of links)assert.ok(zip.file(path.posix.join(base,link.getAttribute('href').split('#')[0])),'EPUB actual navigation file');}
 let last=-1;for(const phrase of required){const index=ordered.indexOf(phrase);assert.ok(index>last,'Ordered '+format+' section '+phrase);last=index;}return{format,sha256:sha256(bytes),bytes:bytes.length,orderedSections:required};
}
export async function importFiles(){const styles='<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:styleId="Emphasis"><w:rPr><w:i/></w:rPr></w:style><w:style w:styleId="Inherited"><w:basedOn w:val="Emphasis"/></w:style></w:styles>';const zip=new JSZip();zip.file('word/styles.xml',styles);zip.file('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t>Styled story</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>Opening</w:t></w:r></w:p><w:p><w:r><w:rPr><w:rStyle w:val="Inherited"/></w:rPr><w:t>café </w:t></w:r><w:r><w:rPr><w:rStyle w:val="Inherited"/><w:i w:val="0"/><w:b/></w:rPr><w:t>bold</w:t></w:r><w:r><w:t> plain.</w:t></w:r></w:p></w:body></w:document>');return[{name:'Markdown.md',bytes:Buffer.from('# Opening\n\nAlpha **bold** café.\n\n***\n\n*Verse*.\n\n# Closing\n\nOmega.'),title:'Markdown',paragraphs:[['Alpha bold café.','***','Verse.'],['Omega.']]},{name:'Numbers.txt',bytes:Buffer.from('I\n\nAlpha.\n\nII\n\nPart of me wanted to run.\n\nIII\n\nOmega.'),title:'Numbers',paragraphs:[['Alpha.'],['Part of me wanted to run.'],['Omega.']]},{name:'Styles.docx',bytes:await zip.generateAsync({type:'nodebuffer'}),title:'Styled story',paragraphs:[['café bold plain.']]}];}

/** Inspect one actual exported story: every format must exclude its neighboring chapter. */
export async function inspectChapterExport(format,bytes){
 assert.ok(bytes.length>30);let text=bytes.toString('utf8');
 if(format==='html')text=dom(text).body.textContent;
 if(format==='docx'){const zip=await JSZip.loadAsync(bytes);text=[...dom(await zip.file('word/document.xml').async('string'),true).getElementsByTagName('w:t')].map(el=>el.textContent).join(' ');}
 if(format==='epub'){const zip=await JSZip.loadAsync(bytes);text=(await Promise.all(Object.keys(zip.files).filter(name=>/\.xhtml$/.test(name)).map(async name=>dom(await zip.file(name).async('string'),true).documentElement.textContent))).join('\n');}
 if(format==='pdf'){const pdf=await readPDF(bytes);try{text=pdf.text;}finally{await pdf.close();}}
 assert.ok(compact(text).includes(compact('Only Second chapter.')),'Current second story included');
 for(const omitted of ['Alpha','bold','italic','Verse line.','SECRET_GHOST','Private note','Opening'])assert.ok(!compact(text).includes(compact(omitted)),'Neighbor/annotation excluded: '+omitted);
 for(const heading of ['An Output & Beyond','Élodie Writer','Closing'])assert.ok(compact(text).includes(compact(heading)),'Chapter title-page/heading retained: '+heading);
 return{format,bytes:bytes.length,sha256:sha256(bytes),scope:'ch-2',excludedNeighbor:'ch-1'};
}
