<script lang="ts">
 import { onMount } from 'svelte';
 import { WorkbenchViewModel } from './WorkbenchViewModel.svelte';
 import type { EngineId } from './contracts';
 const vm=new WorkbenchViewModel(); let editorHost:HTMLDivElement;
 const choices:[EngineId,string][]=[['neo','NEO browser'],['prosemirror','ProseMirror'],['lexical','Lexical']];
 onMount(()=>{vm.mount(editorHost);window.spike=vm;return()=>{delete window.spike;vm.dispose();};});
</script>
<svelte:head><title>NEO · {choices.find(c=>c[0]===vm.engine)?.[1]}</title></svelte:head>
<div class:dark={vm.dark} class="workbench">
 <header><button class="brand" onclick={()=>vm.shelf=!vm.shelf}>NEO</button><span class="experiment">EDITOR OPTIONS · SPIKE</span><nav aria-label="Editor options">{#each choices as [id,label]}<button class:active={vm.engine===id} aria-pressed={vm.engine===id} onclick={()=>vm.switchEngine(id)}>{label}</button>{/each}</nav><button class="quiet" aria-label="Toggle dark mode" onclick={()=>vm.dark=!vm.dark}>{vm.dark?'☀':'☾'}</button><button class="quiet" aria-label="Toggle inspector" onclick={()=>vm.inspector=!vm.inspector}>☷</button></header>
 <div class="workspace" class:inspector-open={vm.inspector}>
  <aside class="chapters"><div class="side-title">THE MANUSCRIPT</div><h1>{vm.document.title}</h1><div class="author">{vm.document.author}</div><div class="chapter-list">{#each vm.document.chapters as chapter,i}<button class:current={vm.selection?.chapterId===chapter.id} onclick={()=>vm.focusChapter(chapter.id)}><span class="chapter-number">{i+1}</span><span>{chapter.title||'Untitled chapter'}</span></button>{/each}</div><div class="side-foot">{vm.words} words<br><span>Paragraph → scene → chapter</span></div></aside>
  <main><div class="paper-toolbar"><span>{vm.document.title}</span><div><button aria-label="Bold" onmousedown={e=>e.preventDefault()} onclick={()=>vm.format('bold')}><b>B</b></button><button aria-label="Italic" onmousedown={e=>e.preventDefault()} onclick={()=>vm.format('italic')}><i>I</i></button><button aria-label="Undo" disabled={!vm.canUndo} onclick={()=>vm.undo()}>↶</button><button aria-label="Redo" disabled={!vm.canRedo} onclick={()=>vm.redo()}>↷</button></div></div><div class="paper-scroll">{#if vm.shelf}<div class="bookshelf"><button class="book-cover" onclick={()=>vm.shelf=false}><span>THE<br>LIGHT<br>KEEPER</span><small>A. WRITER</small></button><p>Your manuscript, on the shelf.</p></div>{/if}<article class="paper" class:concealed={vm.shelf}><div bind:this={editorHost} class="editor-host" data-engine={vm.engine}></div><div class="endmark">❦</div></article></div><footer><span>{vm.words} words · revision {vm.document.revision}</span><span>{vm.message||((vm.saved===vm.document.revision)?'Saved':'Writing locally')}</span><span>{window.spikeHost?'Disk files':'Browser storage'}</span></footer></main>
  {#if vm.inspector}<aside class="inspector"><div class="side-title">WRITING COMPANION</div><section><h2>Darlings</h2><p>Keep a passage. Bring it back when it belongs.</p><button class="action" onmousedown={e=>e.preventDefault()} onclick={()=>vm.archive()}>Keep selected passage</button>{#each vm.document.darlings as darling}<div class="darling"><blockquote>{darling.runs.map(r=>r.text).join('')}</blockquote><button onclick={()=>vm.restore(darling.id)}>Restore passage</button></div>{/each}</section><section><h2>A second pair of eyes</h2><p>Select a passage, then request a revision. You can keep writing while it works.</p><small class="fixture-label">Deterministic agent · protocol experiment</small><button class="action" onmousedown={e=>e.preventDefault()} disabled={vm.reviewing} onclick={()=>vm.review()}>{vm.reviewing?'Reading your passage…':'Suggest a revision'}</button>{#if vm.reviewing}<button onclick={()=>vm.cancelReview()}>Cancel review</button>{/if}{#if vm.proposal}<div class="proposal"><small>Source revision {vm.proposal.sourceRevision}</small><del>{vm.proposal.expected}</del><ins>{vm.proposal.replacement.map(r=>r.text).join('')}</ins><p>{vm.proposal.explanation}</p><button class="action" onclick={()=>vm.accept()}>Apply revision</button><button onclick={()=>vm.dismiss()}>Dismiss</button></div>{/if}</section><section class="lab-controls"><h2>Experiment controls</h2><div class="buttons"><button onclick={()=>vm.save()}>Save</button><button onclick={()=>vm.reopen()}>Reopen</button><button onclick={()=>vm.reset()}>Reset fixture</button></div><details><summary>Application events ({vm.events.length})</summary><ol>{#each vm.events.slice().reverse() as event}<li>{event.type}{'revision' in event?' · '+event.revision:''}</li>{/each}</ol></details></section></aside>{/if}
 </div>
</div>
