import {test,expect}from'@playwright/test';
import {readFile}from'node:fs/promises';import path from'node:path';
import{openEditingFixture,selectText,assertTexts,caretState,menu,clipboard,type Engine,type Fixture}from'./editing-helpers';
const engine:Engine=process.env.NEO_EDITING_EDGE_ENGINE==='prosemirror'?'prosemirror':'original';
type Context=Awaited<ReturnType<typeof openEditingFixture>>;
function scenario(id:string,title:string,fixture:Fixture,run:(c:Context)=>Promise<void>){test(`[${id}] ${engine}: ${title}`,async()=>{const c=await openEditingFixture(engine,fixture);try{await run(c);}finally{await c.close();}});}
const json=async(c:Context,name:string)=>JSON.parse(await readFile(path.join(c.bookdir,name+'.json'),'utf8'));
for(const text of ['日本語','中文','écriture','Русский'])scenario('NEO-067-A',`Chromium native IME commits ${text} once and undoes as one run`,{chapters:['<p>Alpha.</p>']},async(c)=>{await selectText(c.page,0,0,6);const ime=await c.page.context().newCDPSession(c.page);await ime.send('Input.imeSetComposition',{text:text.slice(0,1),selectionStart:1,selectionEnd:1});await ime.send('Input.imeSetComposition',{text,selectionStart:text.length,selectionEnd:text.length});await ime.send('Input.insertText',{text});await ime.detach();await assertTexts(c.page,[['Alpha.'+text]]);expect(await caretState(c.page)).toMatchObject({offset:6+text.length});await c.page.keyboard.press('Meta+z');await assertTexts(c.page,[['Alpha.']]);await menu(c.app,['Edit','Redo']);await assertTexts(c.page,[['Alpha.'+text]]);});
scenario('NEO-067-A','Chromium native IME cancel restores original prose',{chapters:['<p>Alpha.</p>']},async(c)=>{await selectText(c.page,0,0,6);const ime=await c.page.context().newCDPSession(c.page);await ime.send('Input.imeSetComposition',{text:'日本',selectionStart:2,selectionEnd:2});await ime.send('Input.imeSetComposition',{text:'',selectionStart:0,selectionEnd:0});await ime.detach();await assertTexts(c.page,[['Alpha.']]);});
scenario('NEO-096-A','Undo chapter deletion resurrects full files, kinds, notes and annotation references',{chapters:['<p>Front.</p>','<p class="poetry"><i>Verse.</i></p><p>Beta <span class="ph-mark" data-sid="sticky-one" contenteditable="false">⚑</span> end.</p><p class="ghost" data-sec-id="sec-one">Ghost beat</p>'],kinds:{'ch-1':'dedication'},metadata:{chapterTitles:{'ch-2':'Second title'},chapterNotes:{'ch-2':'Second note'},sectionNotes:{'ch-2':[{id:'sec-one',text:'Ghost beat'}]}},stickies:[{id:'sticky-one',chapterId:'ch-2',text:'Original note',resolved:false}],darlings:[{id:'saved',chapterId:'ch-2',text:'Saved prose',html:'<b>Saved prose</b>',date:'2026-10-02T10:00:00Z',chapterLabel:'Second'}]},async(c)=>{await selectText(c.page,0,0,0);await c.page.keyboard.press('F6');await c.page.locator('#nav-pin').focus();await c.page.keyboard.press('Enter');await c.page.locator('.nav-item[data-id="ch-2"] .n-row').click({button:'right'});await c.page.locator('.pop-menu button').filter({hasText:/^Delete$/}).click();await expect(c.page.locator('.chapter-body')).toHaveCount(1);await c.page.locator('.tab[data-tab="darlings"]').click();await c.page.keyboard.press('Meta+z');await expect(c.page.locator('.chapter-body')).toHaveCount(2);const meta=await json(c,'book');expect(meta.chapterOrder).toEqual(['ch-1','ch-2']);expect(meta.chapterKinds).toEqual({'ch-1':'dedication'});expect(meta.chapterTitles).toEqual({'ch-2':'Second title'});expect(meta.chapterNotes).toEqual({'ch-2':'Second note'});expect(meta.sectionNotes).toEqual({'ch-2':[{id:'sec-one',text:'Ghost beat'}]});expect(await json(c,'stickies')).toEqual([{id:'sticky-one',chapterId:'ch-2',text:'Original note',resolved:false}]);expect((await json(c,'darlings')).map((d:{id:string})=>d.id)).toEqual(['saved']);const html=await readFile(path.join(c.bookdir,'chapters','ch-2.html'),'utf8');expect(html).toContain('class="poetry"');expect(html).toContain('data-sid="sticky-one"');expect(html).toContain('data-sec-id="sec-one"');expect(html).not.toContain('Original note');});
scenario('NEO-098-A','eleven structural deletions retain only ten undo snapshots',{darlings:Array.from({length:11},(_,i)=>({id:'saved-'+i,chapterId:'ch-1',text:'Saved '+i,html:'<p>Saved '+i+'</p>',date:'2026-10-02T10:00:00Z',chapterLabel:'Chapter 1'}))},async(c)=>{await c.page.locator('.tab[data-tab="darlings"]').click();for(let i=0;i<11;i++){await c.page.locator('.d-del').first().click();await expect(c.page.locator('.darling')).toHaveCount(10-i);}for(let i=0;i<10;i++){await c.page.keyboard.press('Meta+z');await expect(c.page.locator('.darling')).toHaveCount(i+1);}expect((await json(c,'darlings')).map((d:{id:string})=>d.id)).toEqual(Array.from({length:10},(_,i)=>'saved-'+(i+1)));await c.page.keyboard.press('Meta+z');await expect(c.page.locator('.darling')).toHaveCount(10);});
scenario('NEO-097-A','native Redo after structural Undo cannot replay stale scene HTML',{chapters:['<p>Alpha.</p>']},async(c)=>{await selectText(c.page,0,0,6);await c.page.keyboard.press('Enter');await c.page.keyboard.press('Enter');await assertTexts(c.page,[['Alpha.','***','']]);await c.page.keyboard.press('Meta+z');await assertTexts(c.page,[['Alpha.']]);await menu(c.app,['Edit','Redo']);await assertTexts(c.page,[['Alpha.']]);await expect(c.page.locator('.chapter-body .scene-break')).toHaveCount(0);});
for(const key of ['ArrowLeft','ArrowRight','Backspace'])scenario('NEO-071-A',`${key} resets repeated Enter escalation`,{chapters:['<p>Alpha beta.</p>']},async(c)=>{await selectText(c.page,0,0,5);await c.page.keyboard.press('Enter');await c.page.keyboard.press(key);await c.page.keyboard.press('Enter');await expect(c.page.locator('.chapter-body .scene-break')).toHaveCount(0);await expect(c.page.locator('.chapter-body')).toHaveCount(1);});
scenario('NEO-071-A','pointer down resets repeated Enter escalation',{chapters:['<p>Alpha beta.</p>']},async(c)=>{await selectText(c.page,0,0,5);await c.page.keyboard.press('Enter');await c.page.locator('.chapter-body p').last().click();await c.page.keyboard.press('Enter');await expect(c.page.locator('.chapter-body .scene-break')).toHaveCount(0);});
for(const key of ['Enter','X'])scenario('NEO-091-A',`${key} reveals long manuscript caret with bottom breathing room`,{chapters:[Array.from({length:100},(_,i)=>`<p>Paragraph ${i} has some prose to read.</p>`).join('')]},async(c)=>{await selectText(c.page,0,99,36);await c.page.keyboard.press(key);await expect.poll(()=>c.page.evaluate(()=>{const r=window.getSelection()!.getRangeAt(0).cloneRange();r.collapse(false);let box=r.getBoundingClientRect();if(!box.height)box=((r.endContainer.nodeType===Node.ELEMENT_NODE?r.endContainer:r.endContainer.parentElement) as Element).getBoundingClientRect();const scroll=document.querySelector('#paper-scroll')!;return{top:box.top-scroll.getBoundingClientRect().top,bottom:scroll.getBoundingClientRect().bottom-box.bottom,scrolled:(scroll as HTMLElement).scrollTop>0};})).toMatchObject({scrolled:true});const position=await c.page.evaluate(()=>{const r=window.getSelection()!.getRangeAt(0).cloneRange();r.collapse(false);let box=r.getBoundingClientRect();if(!box.height)box=((r.endContainer.nodeType===Node.ELEMENT_NODE?r.endContainer:r.endContainer.parentElement) as Element).getBoundingClientRect();const scroll=document.querySelector('#paper-scroll')!;return{top:box.top-scroll.getBoundingClientRect().top,bottom:scroll.getBoundingClientRect().bottom-box.bottom};});expect(position.top).toBeGreaterThanOrEqual(0);expect(position.bottom).toBeGreaterThanOrEqual(35);});
scenario('NEO-091-A','bold and italic keyboard formatting retain manuscript scroll',{chapters:[Array.from({length:100},(_,i)=>`<p>Paragraph ${i} has some prose to read.</p>`).join('')]},async(c)=>{await selectText(c.page,0,60,0,12);await c.page.locator('#paper-scroll').evaluate(el=>{el.scrollTop=1200;});const before=await c.page.locator('#paper-scroll').evaluate(el=>el.scrollTop);await c.page.keyboard.press('Meta+b');await c.page.waitForTimeout(60);expect(await c.page.locator('#paper-scroll').evaluate(el=>el.scrollTop)).toBe(before);await c.page.keyboard.press('Meta+i');await c.page.waitForTimeout(60);expect(await c.page.locator('#paper-scroll').evaluate(el=>el.scrollTop)).toBe(before);await expect(c.page.locator('.chapter-body p').nth(60).locator('b,strong')).toHaveText('Paragraph 60');await expect(c.page.locator('.chapter-body p').nth(60).locator('i,em')).toHaveText('Paragraph 60');});
for(const[language,wanted]of[['es','—Hola'],['pt-BR','— Hola'],['ru','— Hola']]as const)scenario('NEO-121-A',`${language} native styled paste keeps dash and emphasis across style boundaries`,{chapters:['<p><br></p>'],library:{spellLanguage:language}},async(c)=>{await selectText(c.page,0,0,0);await clipboard(c.app,'- Hola','<p><b>- </b><i>Hola</i></p>');await menu(c.app,['Edit','Paste']);await assertTexts(c.page,[[wanted]]);await expect(c.page.locator('.chapter-body').locator('b,strong')).toHaveText(language==='es'?'—':'— ');await expect(c.page.locator('.chapter-body').locator('i,em')).toHaveText('Hola');});
for(const boundary of ['title Enter','help Escape'] as const)scenario('NEO-067-B',`${boundary} stopPropagation keeps subsequent native composition observable and persistent`,{chapters:['<p>Alpha.</p>','<p>Second.</p>'],metadata:{chapterTitles:{'ch-1':'Original title'}}},async(c)=>{
 if(boundary==='title Enter'){await c.page.locator('.ch-title').first().fill('Composition boundary');await c.page.locator('.ch-title').first().press('Enter');await expect(c.page.locator('.ch-title').first()).not.toBeFocused();}
 else{await menu(c.app,['View','Keyboard Shortcuts…']);await expect(c.page.locator('.modal-backdrop:not([hidden])')).toBeVisible();await c.page.keyboard.press('Escape');await expect(c.page.locator('.modal-backdrop:not([hidden])')).toHaveCount(0);}
 await c.page.locator('.chapter-body').first().click();await selectText(c.page,0,0,6);
 const ime=await c.page.context().newCDPSession(c.page);try{await ime.send('Input.imeSetComposition',{text:'日',selectionStart:1,selectionEnd:1});await ime.send('Input.imeSetComposition',{text:'日本語',selectionStart:3,selectionEnd:3});await ime.send('Input.insertText',{text:'日本語'});}finally{await ime.detach();}
 await assertTexts(c.page,[['Alpha.日本語'],['Second.']]);expect(await caretState(c.page)).toMatchObject({offset:9});await menu(c.app,['Edit','Undo']);await assertTexts(c.page,[['Alpha.'],['Second.']]);await menu(c.app,['Edit','Redo']);await assertTexts(c.page,[['Alpha.日本語'],['Second.']]);await c.page.locator('#back-to-shelf').click();expect(await readFile(path.join(c.bookdir,'chapters','ch-1.html'),'utf8')).toContain('Alpha.日本語');await c.page.locator('.book').first().click();await assertTexts(c.page,[['Alpha.日本語'],['Second.']]);
});
scenario('NEO-098-B','native typing history retains sixteen distinct paragraph runs beyond structural ten-entry cap',{chapters:[Array.from({length:16},(_,i)=>`<p>Paragraph ${i}.</p>`).join('')]},async(c)=>{
 for(let i=0;i<16;i++){await selectText(c.page,0,i,0);await c.page.keyboard.type(String.fromCharCode(65+i));}
 await assertTexts(c.page,[Array.from({length:16},(_,i)=>String.fromCharCode(65+i)+`Paragraph ${i}.`)]);
 for(let remaining=15;remaining>=0;remaining--){await menu(c.app,['Edit','Undo']);await assertTexts(c.page,[Array.from({length:16},(_,i)=>(i<remaining?String.fromCharCode(65+i):'')+`Paragraph ${i}.`)]);}
 for(let restored=1;restored<=16;restored++){await menu(c.app,['Edit','Redo']);await assertTexts(c.page,[Array.from({length:16},(_,i)=>(i<restored?String.fromCharCode(65+i):'')+`Paragraph ${i}.`)]);}
 await c.page.locator('#back-to-shelf').click();await c.page.locator('.book').first().click();await assertTexts(c.page,[Array.from({length:16},(_,i)=>String.fromCharCode(65+i)+`Paragraph ${i}.`)]);
});
scenario('NEO-067-C','trusted native keyCode229 apostrophe bypasses smart typography before real committed input',{chapters:['<p>Alpha.</p>']},async(c)=>{
 await selectText(c.page,0,0,6);await c.page.evaluate(()=>{(window as any).__neoCompositionEvents=[];document.addEventListener('keydown',e=>(window as any).__neoCompositionEvents.push({trusted:e.isTrusted,key:e.key,keyCode:e.keyCode,isComposing:e.isComposing}),true);});
 const driver=await c.page.context().newCDPSession(c.page);try{await driver.send('Input.dispatchKeyEvent',{type:'keyDown',key:"'",code:'Quote',windowsVirtualKeyCode:229,nativeVirtualKeyCode:229,text:"'",unmodifiedText:"'"});await driver.send('Input.dispatchKeyEvent',{type:'keyUp',key:"'",code:'Quote',windowsVirtualKeyCode:229,nativeVirtualKeyCode:229});}finally{await driver.detach();}
 const seen=await c.page.evaluate(()=>(window as any).__neoCompositionEvents);expect(seen).toEqual(expect.arrayContaining([expect.objectContaining({trusted:true,key:"'",keyCode:229})]));await assertTexts(c.page,[["Alpha.'"]]);await menu(c.app,['Edit','Undo']);await assertTexts(c.page,[['Alpha.']]);await menu(c.app,['Edit','Redo']);await assertTexts(c.page,[["Alpha.'"]]);
});
scenario('NEO-067-D','trusted active-composition Enter reports isComposing and avoids chapter split',{chapters:['<p>Alpha.</p><p><br></p>']},async(c)=>{
 await selectText(c.page,0,1,0);await c.page.evaluate(()=>{(window as any).__neoCompositionEvents=[];document.addEventListener('keydown',e=>(window as any).__neoCompositionEvents.push({trusted:e.isTrusted,key:e.key,keyCode:e.keyCode,isComposing:e.isComposing}),true);});const driver=await c.page.context().newCDPSession(c.page);
 try{await driver.send('Input.imeSetComposition',{text:'日',selectionStart:1,selectionEnd:1});await driver.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});await driver.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});await driver.send('Input.insertText',{text:'日本'});}finally{await driver.detach();}
 expect(await c.page.evaluate(()=>(window as any).__neoCompositionEvents)).toEqual(expect.arrayContaining([expect.objectContaining({trusted:true,key:'Enter',isComposing:true})]));await expect(c.page.locator('.chapter-body')).toHaveCount(1);await expect(c.page.locator('.chapter-body')).toContainText('Alpha.');await expect(c.page.locator('.chapter-body')).toContainText('日本');await c.page.locator('#back-to-shelf').click();const saved=await readFile(path.join(c.bookdir,'chapters','ch-1.html'),'utf8');expect(saved).toContain('日本');expect(saved).toContain('Alpha.');
});
