import {test,expect,type Page,type Locator} from '@playwright/test';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {openEditingFixture,menu,selectText,caretState,assertTexts,type Engine} from './editing-helpers';
import {createReferenceDirectory,launchReference,removeReferenceDirectory} from '../reference/harness';
import {libraryPath,option} from './library-helpers';
import {bound,shelfMetas,chapterPath} from './books-helpers';
const dialog=(page:Page)=>page.locator('.modal-backdrop:not([hidden]) [role="dialog"]');
async function named(page:Page,name:string|RegExp){const box=dialog(page);await expect(box).toBeVisible();await expect(box).toHaveAttribute('aria-modal','true');await expect(box).toHaveAccessibleName(name);return box;}
async function adjacent(page:Page,first:Locator,second:Locator){await first.focus();await page.keyboard.press('Tab');await expect(second).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(first).toBeFocused();}
async function anchor(page:Page){await page.locator('#zoom-level').focus();await page.keyboard.press('Tab');await page.locator('#zoom-level').focus();await expect(page.locator('#zoom-level')).toBeFocused();}
async function library(directory:string){return JSON.parse(await readFile(path.join(libraryPath(directory),'library.json'),'utf8'));}
const ids='[NEO-217-C][NEO-283-C]';
for(const engine of (['original','prosemirror']as Engine[]).filter(e=>!process.env.NEO_MODAL_FAMILIES_ENGINE||process.env.NEO_MODAL_FAMILIES_ENGINE===e))test.describe(engine,()=>{
 test(`${ids} first-run named dialog keeps unanswered onboarding and ordinary input Tab order`,async({},info)=>{
  const directory=await createReferenceDirectory(),app=await launchReference(directory,engine==='original'?undefined:engine);try{const page=await app.firstWindow();await named(page,'Welcome to NEO');
   // Static hidden dialog autofocus is scheduled before async library load;
   // record actual initial focus rather than invent a mandatory trap/autofocus.
   info.annotations.push({type:'source-initial-focus',description:await page.evaluate(()=>document.activeElement?.id||document.activeElement?.tagName||'none')});
   await adjacent(page,page.locator('#fr-name'),page.locator('#fr-pen'));await page.locator('#fr-name').fill('Modal Writer');await page.keyboard.press('Escape');await expect(page.locator('#firstrun')).toBeVisible();await page.keyboard.press('Enter');await expect(page.locator('#fr-step1')).toBeVisible();
   await page.locator('.fr-choice[data-style="pantser"]').focus();await page.keyboard.press('Enter');await expect(page.locator('#fr-step2')).toBeVisible();await page.locator('#fr-done').focus();await page.keyboard.press('Enter');await expect(page.locator('#firstrun')).toBeHidden();expect((await library(directory)).authorName).toBe('Modal Writer');
  }finally{await app.close();await removeReferenceDirectory(directory);}
 });
 test(`${ids} cover settings focus key traverse buttons and Escape cancels unsaved changes`,async()=>{
  const c=await openEditingFixture(engine);try{await anchor(c.page);const before=(await library(c.directory)).coverArt;await menu(c.app,['File','Cover Art…']);const box=await named(c.page,'Cover art');await expect(box.locator('#ca-key')).toBeFocused();await adjacent(c.page,box.locator('.m-cancel'),box.locator('.m-ok'));await box.locator('.m-ok').focus();await c.page.keyboard.press('Tab');expect(await box.evaluate(el=>el.contains(document.activeElement))).toBe(false);await c.page.keyboard.press('Shift+Tab');await expect(box.locator('.m-ok')).toBeFocused();await box.locator('#ca-auto').uncheck();await box.locator('#ca-key').focus();await c.page.keyboard.press('Enter');await expect(box).toBeVisible();await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);await expect(c.page.locator('#zoom-level')).toBeFocused();expect((await library(c.directory)).coverArt).toEqual(before);await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);}finally{await c.close();}
 });
 test(`${ids} book progress backdrop focus Tab goals Escape saves and keyboard sprint starts`,async()=>{
  const c=await openEditingFixture(engine);try{await anchor(c.page);await menu(c.app,['File','Goals…']);let box=await named(c.page,'Editing fixture — progress');await expect(c.page.locator('.modal-backdrop:visible')).toBeFocused();await c.page.keyboard.press('Tab');await expect(box.locator('#st-daily')).toBeFocused();await adjacent(c.page,box.locator('#st-daily'),box.locator('#st-book'));await box.locator('#st-daily').fill('321');await box.locator('#st-book').fill('654');await c.page.keyboard.press('Enter');await expect(box).toBeVisible();await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);expect((await library(c.directory)).dailyGoal).toBe(321);await expect.poll(async()=>JSON.parse(await readFile(path.join(c.bookdir,'book.json'),'utf8')).wordGoal).toBe(654);await expect(c.page.locator('#zoom-level')).toBeFocused();
   await menu(c.app,['File','Goals…']);box=await named(c.page,'Editing fixture — progress');await box.locator('#st-sprint').fill('50');await adjacent(c.page,box.locator('#st-sprint'),box.locator('#st-sprint-btn'));await box.locator('#st-sprint-btn').focus();await c.page.keyboard.press('Enter');await expect(box).toHaveCount(0);await expect(c.page.locator('#hint')).toContainText('Sprint started');await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);
  }finally{await c.close();}
 });
 test(`${ids} shelf Goals dialog has no book fields and Done Enter saves keyboard edits`,async()=>{
  const c=await openEditingFixture(engine);try{await c.page.locator('#back-to-shelf').click();await menu(c.app,['File','Goals…']);const box=await named(c.page,'Goals');await expect(c.page.locator('.modal-backdrop:visible')).toBeFocused();await expect(box.locator('#st-book, #st-sprint')).toHaveCount(0);await adjacent(c.page,box.locator('#st-daily'),box.locator('#st-dayends'));await box.locator('#st-daily').fill('123');await box.locator('.m-ok').focus();await c.page.keyboard.press('Enter');await expect(box).toHaveCount(0);expect((await library(c.directory)).dailyGoal).toBe(123);await c.page.locator('.book').first().click();await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);}finally{await c.close();}
 });
 test(`${ids} installed font dialog focuses search traverses filtered face and Escape cancels Enter selects`,async()=>{
  const c=await openEditingFixture(engine);try{
   // Permission seam admits the genuine installed-font API, no fabricated font list.
   await c.app.evaluate(({BrowserWindow})=>{const session=BrowserWindow.getAllWindows()[0].webContents.session;session.setPermissionCheckHandler((_wc,p)=>p==='local-fonts');session.setPermissionRequestHandler((_wc,p,callback)=>callback(p==='local-fonts'));});
   await anchor(c.page);await menu(c.app,['Format','Body Font','Other Font…']);let box=await named(c.page,'Other font');await expect(box.locator('input')).toBeFocused();await box.locator('input').fill('Georgia');await expect(box.locator('.font-list button')).toHaveCount(1);const returnId=await box.evaluate(el=>(el.closest('.modal-backdrop') as HTMLElement & {_returnFocus?:HTMLElement})._returnFocus?.id||'BODY');await adjacent(c.page,box.locator('input'),box.locator('.font-list button'));await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);expect(await c.page.evaluate(()=>(window as unknown as {neo:{fullscreenEscape:()=>Promise<boolean>}}).neo.fullscreenEscape())).toBe(false);if(engine==='original'){await expect(c.page.locator('#bookshelf-view')).toBeVisible();await c.page.locator('#bookshelf-view .book').first().click();await expect(c.page.locator('#editor-view')).toBeVisible();await anchor(c.page);}else{await expect(c.page.locator('#editor-view')).toBeVisible();await expect.poll(()=>c.page.evaluate(()=>document.activeElement?.id||document.activeElement?.tagName)).toBe(returnId);}expect((await library(c.directory)).fonts.body).toBe('Georgia');
   await menu(c.app,['Format','Body Font','Other Font…']);box=await named(c.page,'Other font');await box.locator('input').fill('Georgia');await c.page.keyboard.press('Enter');await expect(box).toHaveCount(0);expect((await library(c.directory)).fonts.body).toBe('Georgia');await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);
  }finally{await c.close();}
 });
 test('[NEO-217-E][NEO-283-E] font search Escape completes genuine fullscreen IPC without leaving the manuscript',async({},info)=>{
  const c=await openEditingFixture(engine);try{
   await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({ipcLog:true,ipcDelays:{'fullscreen:escape':{after:80}}}));
   await c.app.evaluate(({BrowserWindow})=>{const session=BrowserWindow.getAllWindows()[0].webContents.session;session.setPermissionCheckHandler((_wc,p)=>p==='local-fonts');session.setPermissionRequestHandler((_wc,p,callback)=>callback(p==='local-fonts'));});
   await anchor(c.page);await menu(c.app,['Format','Body Font','Other Font…']);const box=await named(c.page,'Other font');await expect(box.locator('input')).toBeFocused();await box.locator('input').fill('Georgia');await expect(box.locator('.font-list button')).toHaveCount(1);
   const returnId=await box.evaluate(el=>(el.closest('.modal-backdrop') as HTMLElement & {_returnFocus?:HTMLElement})._returnFocus?.id||'BODY');
   await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);
   // A later genuine request waits for the earlier same-channel Escape reply;
   // synchronous dialog removal/focus restoration cannot masquerade as completion.
   expect(await c.page.evaluate(()=>(window as unknown as {neo:{fullscreenEscape:()=>Promise<boolean>}}).neo.fullscreenEscape())).toBe(false);
   const effects=JSON.parse(await readFile(path.join(c.directory,'intercepted-effects.json'),'utf8')) as Array<{type:string,payload:{channel?:string,result?:unknown}}>;
   const completions=effects.filter(effect=>effect.type==='ipc-complete'&&effect.payload.channel==='fullscreen:escape');
   expect(completions).toHaveLength(engine==='original'?2:1);for(const completion of completions)expect(completion.payload.result).toBe(false);
   await info.attach('font-escape-genuine-ipc',{body:JSON.stringify(completions,null,2),contentType:'application/json'});
   if(engine==='original'){await expect(c.page.locator('#bookshelf-view')).toBeVisible();await expect(c.page.locator('#editor-view')).toBeHidden();await c.page.locator('#bookshelf-view .book').first().click();await expect(c.page.locator('#editor-view')).toBeVisible();}
   else{await expect(c.page.locator('#editor-view')).toBeVisible();await expect(c.page.locator('#bookshelf-view')).toBeHidden();await expect.poll(()=>c.page.evaluate(()=>document.activeElement?.id||document.activeElement?.tagName)).toBe(returnId);}
   expect((await library(c.directory)).fonts.body).toBe('Georgia');await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);
  }finally{await c.close();}
 });
 test(`${ids} email input owns Enter and mandatory method dialog keeps Escape until keyboard choice`,async()=>{
  const c=await openEditingFixture(engine);try{await anchor(c.page);await menu(c.app,['File','Email Settings…']);let box=await named(c.page,'Email drafts to');await expect(box.locator('input')).toBeFocused();await adjacent(c.page,box.locator('input'),box.locator('.m-cancel'));await box.locator('input').fill('dialog@example.invalid');await c.page.keyboard.press('Enter');box=await named(c.page,'How should NEO email your drafts?');await expect(box.locator('[data-m="gmail"]')).toBeFocused();await adjacent(c.page,box.locator('[data-m="gmail"]'),box.locator('[data-m="mail"]'));await c.page.keyboard.press('Escape');await expect(box).toBeVisible();await expect(box.locator('.m-cancel, .m-ok')).toHaveCount(0);await c.page.keyboard.press('Enter');await expect(box).toHaveCount(0);expect((await library(c.directory)).emailAddress).toBe('dialog@example.invalid');expect((await library(c.directory)).emailMethod).toBe('gmail');await expect(c.page.locator('#zoom-level')).toBeFocused();await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);}finally{await c.close();}
 });
 test(`${ids} help traps its two Tab controls restores actual caret and About returns keyboard focus`,async()=>{
  const c=await openEditingFixture(engine);try{await selectText(c.page,0,0,5);const caret=await caretState(c.page);await menu(c.app,['View','Keyboard Shortcuts…']);let box=await named(c.page,'Keyboard shortcuts');await expect(box.locator('.shortcuts-content')).toBeFocused();await c.page.keyboard.press('Shift+Tab');await expect(box.locator('.m-ok')).toBeFocused();await c.page.keyboard.press('Tab');await expect(box.locator('.shortcuts-content')).toBeFocused();await c.page.keyboard.press('Tab');await expect(box.locator('.m-ok')).toBeFocused();await c.page.keyboard.press('Enter');await expect(box).toHaveCount(0);await expect(c.page.locator('.chapter-body').first()).toBeFocused();expect(await caretState(c.page)).toEqual(caret);
   await anchor(c.page);await menu(c.app,['Help','About NEO']);box=await named(c.page,'NEO');await expect(box.locator('.m-ok')).toBeFocused();await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);await expect(c.page.locator('#zoom-level')).toBeFocused();await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);
  }finally{await c.close();}
 });
 test(`${ids} title and content page sheets expose names focus fields and save through Enter or Escape`,async()=>{
  const c=await openEditingFixture(engine);try{await c.page.locator('#back-to-shelf').click();await bound(c.page,c.directory);await c.page.locator('.bound-cover').click();let box=await named(c.page,'Title Page');await expect(box.locator('.tp-t')).toBeFocused();await adjacent(c.page,box.locator('.tp-t'),box.locator('.tp-s'));await box.locator('.tp-t').fill('Modal Collection');await c.page.keyboard.press('Enter');await expect(box.locator('.tp-s')).toBeFocused();await box.locator('.tp-s').fill('Subtitle retained');await c.page.keyboard.press('Enter');await expect(box.locator('.tp-a')).toBeFocused();await c.page.keyboard.press('Enter');await expect(box).toHaveCount(0);await expect(c.page.locator('.shelf-label')).toHaveText('Modal Collection');
   await c.page.locator('.ghost-page[aria-label="Dedication"]').click();box=await named(c.page,'Dedication');await expect(box.locator('.ps-body')).toBeFocused();await box.locator('.ps-body').fill('For keyboard writers');await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);const dedication=(await shelfMetas(c.directory)).find(m=>m.kind==='dedication')!;expect(await readFile(chapterPath(c.directory,dedication.id,dedication.chapterOrder[0]),'utf8')).toContain('For keyboard writers');await c.page.locator('.kind-dedication').click();box=await named(c.page,'Dedication');await expect(box.locator('.ps-body')).toHaveText('For keyboard writers');await box.locator('.ps-done').focus();await c.page.keyboard.press('Enter');await expect(box).toHaveCount(0);
  }finally{await c.close();}
 });
 test(`${ids} author shelf anthology and book goal reuse named choice and input dialogs without altering cancelled data`,async()=>{
  const c=await openEditingFixture(engine);try{await c.page.locator('#back-to-shelf').click();await c.page.keyboard.press('Tab');await c.page.locator('#author-chip').focus();await c.page.keyboard.press('Enter');let box=await named(c.page,'Writing as Parity Writer');await expect(box.locator('.fr-choice').first()).toBeFocused();await adjacent(c.page,box.locator('.fr-choice').first(),box.locator('.fr-choice').nth(1));await box.locator('.fr-choice').first().focus();await c.page.keyboard.press('Enter');box=await named(c.page,'Author name');await expect(box.locator('input')).toBeFocused();await box.locator('input').fill('Cancelled rename');await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);expect((await library(c.directory)).authors[0].name).toBe('Parity Writer');await expect(c.page.locator('#author-chip')).toBeFocused();
   await c.page.locator('.shelf-label').first().click({button:'right'});box=await named(c.page,'Shelf “Editing”');await expect(box.locator('.fr-choice').first()).toBeFocused();await box.locator('.fr-choice').nth(1).focus();await c.page.keyboard.press('Enter');box=await named(c.page,'Anthology title');await expect(box.locator('input')).toBeFocused();await c.page.keyboard.press('Enter');box=await named(c.page,'Export the anthology as…');await expect(box.locator('.fr-choice').first()).toBeFocused();await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);expect((await library(c.directory)).shelves[0].name).toBe('Editing');
   await c.page.locator('.book').first().click({button:'right'});box=await named(c.page,'“Editing fixture”');await option(c.page,'Set word goal');box=await named(c.page,'Word count goal for “Editing fixture”');await expect(box.locator('input')).toBeFocused();await box.locator('input').fill('999');await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);expect(JSON.parse(await readFile(path.join(c.bookdir,'book.json'),'utf8')).wordGoal).toBeUndefined();await c.page.locator('.book').first().click();await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);
  }finally{await c.close();}
 });
 test(`${ids} release update dialog owns backdrop focus Later Tab and Escape returns without changing manuscript`,async()=>{
  const c=await openEditingFixture(engine);try{await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({httpResponses:[{match:'api.github.com',body:{tag_name:'v999.9.9',html_url:'https://github.com/hughhowey/neo/releases/tag/v999.9.9'}}]}));await anchor(c.page);await menu(c.app,['Help','Check for Update…']);const box=await named(c.page,'NEO 999.9.9 is available');await expect(c.page.locator('.modal-backdrop:visible')).toBeFocused();await c.page.keyboard.press('Tab');await expect(box.locator('.m-cancel')).toBeFocused();await adjacent(c.page,box.locator('.m-cancel'),box.locator('.m-ok'));await c.page.keyboard.press('Escape');await expect(box).toHaveCount(0);await expect(c.page.locator('#zoom-level')).toBeFocused();await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);}finally{await c.close();}
 });
 test('[NEO-217-D][NEO-283-D] update notice owns OK Enter and labels legacy unnamed explicit-role dialog',async()=>{
  const c=await openEditingFixture(engine);try{await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({httpResponses:[{match:'api.github.com',body:{tag_name:'v0.0.0'}}]}));await anchor(c.page);await menu(c.app,['Help','Check for Update…']);const box=dialog(c.page);await expect(box).toBeVisible();await expect(box).toHaveAttribute('aria-modal','true');await expect(box.locator('h2')).toHaveText('NEO is up to date');await expect(box).toHaveAccessibleName(engine==='original'?'':'NEO is up to date');await expect(box.locator('.m-ok')).toBeFocused();await c.page.keyboard.press('Enter');await expect(box).toHaveCount(0);await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);}finally{await c.close();}
 });
});
