import {test,expect,type Page} from '@playwright/test';
import {openEditingFixture,selectText,caretState,assertTexts,menu,type Engine} from './editing-helpers';
const engine:Engine=process.env.NEO_NATIVE_ACCESSIBILITY_ENGINE==='prosemirror'?'prosemirror':'original';
const visibleDialog=(page:Page)=>page.locator('.modal-backdrop:not([hidden]) [role="dialog"]');
function scenario(ids:string,title:string,run:(c:Awaited<ReturnType<typeof openEditingFixture>>)=>Promise<void>){test(`${ids} ${engine}: ${title}`,async()=>{const c=await openEditingFixture(engine,{chapters:['<p>Alpha beta.</p>','<p>Second chapter.</p>','<p>Third chapter.</p>']});try{await run(c);}finally{await c.close();}});}
scenario('[NEO-278-B]','author covers counters and zoom expose real keyboard activation',async({page})=>{
 await page.locator('#back-to-shelf').click();
 const author=page.locator('#author-chip');await expect(author).toHaveAttribute('role','button');await expect(author).toHaveAttribute('tabindex','0');await page.keyboard.press('Tab');await author.focus();await page.keyboard.press('Enter');await expect(visibleDialog(page)).toBeVisible();await expect.poll(()=>visibleDialog(page).evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.keyboard.press('Escape');await expect(visibleDialog(page)).toHaveCount(0);await expect(author).toBeFocused();
 const cover=page.locator('#bookshelf-view .book').first();await expect(cover).toHaveAttribute('role','button');await expect(cover).toHaveAttribute('tabindex','0');await cover.focus();await page.keyboard.press('Space');await expect(page.locator('.chapter-body').first()).toBeVisible();
 const counter=page.locator('#word-counter');await counter.focus();const before=await counter.textContent();await page.keyboard.press('Enter');expect(await counter.textContent()).not.toBe(before);await expect(counter).toBeFocused();await page.keyboard.press('Space');expect(await counter.textContent()).toBe(before);
 await page.locator('#zoom-level').focus();await page.keyboard.press('Enter');await expect(page.locator('#zoom-level')).toHaveText('100%');await assertTexts(page,[['Alpha beta.'],['Second chapter.'],['Third chapter.']]);
});
scenario('[NEO-279-B]','reverse F6 and CtrlTab cycle four source regions and shelf two regions',async({page})=>{
 await selectText(page,0,0,5);const saved=await caretState(page);
 await page.keyboard.press('Shift+F6');await expect(page.locator('.tab.active')).toBeFocused();
 await page.keyboard.press('Control+Shift+Tab');await expect(page.locator('#side-pin')).toBeFocused();
 await page.keyboard.press('Control+Shift+Tab');await expect(page.locator('.n-row').first()).toBeFocused();
 await page.keyboard.press('Control+Shift+Tab');await expect(page.locator('.chapter-body').first()).toBeFocused();expect(await caretState(page)).toEqual(saved);
 await page.locator('#back-to-shelf').click();await page.locator('#bookshelf-view .book').first().focus();await page.keyboard.press('Control+Shift+Tab');await expect(page.locator('#author-chip')).toBeFocused();await page.keyboard.press('Shift+F6');await expect(page.locator('#bookshelf-view .book').first()).toBeFocused();
});
scenario('[NEO-282-B]','chapter arrows clamp focus and Enter activates while pointer context owns menu keys',async({page})=>{
 await selectText(page,0,0,0);await page.keyboard.press('F6');await page.locator('#nav-pin').focus();await page.keyboard.press('Enter');const rows=page.locator('.n-row');await rows.first().focus();await expect(rows.first()).toBeFocused();await page.keyboard.press('ArrowUp');await expect(rows.first()).toBeFocused();await page.keyboard.press('ArrowDown');await expect(rows.nth(1)).toBeFocused();await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');await expect(rows.last()).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('.chapter-body').nth(2)).toBeFocused();expect(await page.evaluate(()=>{const s=getSelection()!,r=s.getRangeAt(0),e=r.startContainer.nodeType===Node.ELEMENT_NODE?r.startContainer as Element:r.startContainer.parentElement!;return{chapter:Array.from(document.querySelectorAll('.chapter-body')).indexOf(e.closest('.chapter-body')!),collapsed:s.isCollapsed};})).toEqual({chapter:2,collapsed:true});
 await rows.nth(1).click({button:'right'});await expect(page.locator('.pop-menu')).toBeVisible();await page.keyboard.press('ArrowDown');expect(await page.locator('.pop-menu').evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.keyboard.press('Escape');await expect(page.locator('.pop-menu')).toHaveCount(0);await assertTexts(page,[['Alpha beta.'],['Second chapter.'],['Third chapter.']]);
});
scenario('[NEO-283-B][NEO-217-B]','ask-input and choice modal own labels initial focus Enter Escape and return focus',async({page})=>{
 await page.locator('#back-to-shelf').click();const cover=page.locator('.book').first();await cover.focus();await cover.click({button:'right'});let dialog=visibleDialog(page);await expect(dialog).toHaveAttribute('aria-modal','true');const name=await dialog.getAttribute('aria-labelledby');expect(name).toBeTruthy();await expect(page.locator('#'+name)).toBeVisible();expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);
 await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);
 await page.locator('#author-chip').focus();await page.keyboard.press('Enter');await visibleDialog(page).getByRole('button',{name:'Add a pen name…'}).click();dialog=visibleDialog(page);const input=dialog.locator('input');await expect(input).toBeFocused();await input.fill('Keyboard-created story');await page.keyboard.press('Tab');expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);await input.focus();await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(page.locator('.book')).toHaveCount(1);
});
scenario('[NEO-284-B]','pointer textfield interaction stays editable while modal mouse focus remains owned',async({page,app})=>{
 await menu(app,['File','Goals…']);const dialog=visibleDialog(page);await expect(dialog).toBeVisible();const input=dialog.locator('input').first();await input.click();await expect(input).toBeFocused();await input.fill('17');await page.keyboard.press('ArrowLeft');await expect(input).toBeFocused();expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);await dialog.locator('.m-ok').click();await expect(dialog).toHaveCount(0);await assertTexts(page,[['Alpha beta.'],['Second chapter.'],['Third chapter.']]);
});
scenario('[NEO-199-B]','quiet shelf grip and chrome become visible on hover or keyboard focus',async({page})=>{
 await page.locator('#back-to-shelf').click();await page.mouse.move(1,1);const grip=page.locator('.shelf-grip').first();await expect.poll(()=>grip.evaluate(el=>parseFloat(getComputedStyle(el).opacity))).toBe(0);await page.locator('.shelf-label').first().hover();await expect.poll(()=>grip.evaluate(el=>parseFloat(getComputedStyle(el).opacity))).toBe(1);
 await page.mouse.move(1,1);await page.keyboard.press('Tab');await page.locator('.shelf-label').first().focus();await expect.poll(()=>grip.evaluate(el=>parseFloat(getComputedStyle(el).opacity))).toBeCloseTo(.6,1);await page.locator('.book').first().focus();expect(await page.locator('.book').first().evaluate(el=>getComputedStyle(el).outlineStyle)).not.toBe('none');
});
scenario('[NEO-285-B]','minimum native window with enlarged interface and page keeps keyboard controls usable',async({page,app})=>{
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(800,600));await menu(app,['View','Interface Size','300%']);await page.mouse.move(400,300);await page.keyboard.down('Control');await page.mouse.wheel(0,-800);await page.keyboard.up('Control');await expect(page.locator('#zoom-level')).toHaveText('300%');
 await selectText(page,0,0,0);await page.keyboard.press('F6');await expect(page.locator('.n-row').first()).toBeFocused();await page.keyboard.press('F6');await expect(page.locator('#side-pin')).toBeFocused();await page.keyboard.press('F6');await expect(page.locator('.tab.active')).toBeFocused();
 await menu(app,['View','Keyboard Shortcuts…']);await expect(visibleDialog(page)).toBeVisible();await expect.poll(()=>visibleDialog(page).evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.keyboard.press('Escape');await expect(visibleDialog(page)).toHaveCount(0);await menu(app,['View','Interface Size','Normal']);await assertTexts(page,[['Alpha beta.'],['Second chapter.'],['Third chapter.']]);
});
