import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {compile} from 'svelte/compiler';
import {Shelf} from '../../packages/library/src/index';
import {boundShelfLayout,romanPart,coverInsertionIndex,type ShelfBook} from '../../apps/desktop/src/lib/library-shelf';
const book=(id:string,kind?:string):ShelfBook=>({id,title:id,author:'Writer',...(kind?{kind}:{})});
const shelf=(ids:string[],bound=true)=>Shelf.parse({id:'s',name:'Collection',authorId:'a',bookIds:ids,binding:{bound}});
describe('source-defined bound shelf layout',()=>{
 it('retains three author stories with seven ghost pages and one Part seam before each story',()=>{const books=[book('cover','cover'),book('a'),book('b'),book('c')],tiles=boundShelfLayout(shelf(books.map(b=>b.id)),books);expect(tiles.filter(t=>t.type==='ghost').map(t=>t.kind)).toEqual(['copyright','dedication','epigraph','prologue','epilogue','acknowledgments','about']);expect(tiles.filter(t=>t.type==='seam').map(t=>t.beforeId)).toEqual(['a','b','c']);expect(tiles.filter(t=>t.type==='book'||t.type==='cover').map(t=>t.book.id)).toEqual(['cover','a','b','c']);expect(tiles[0]).toMatchObject({type:'cover',label:'Collection'});});
 it('keeps authored Part/body positions, suppresses adjacent duplicate Part insertion and labels Roman Parts',()=>{const books=[book('cover','cover'),book('p1','part'),book('a'),book('p2','part'),book('b'),book('c')],tiles=boundShelfLayout(shelf(books.map(b=>b.id)),books);expect(tiles.filter(t=>t.type==='page').map(t=>[t.book.id,t.label])).toEqual([['p1','Part I'],['p2','Part II']]);expect(tiles.filter(t=>t.type==='seam').map(t=>t.beforeId)).toEqual(['c']);expect(tiles.filter(t=>t.type==='page'||t.type==='book').map(t=>t.book.id)).toEqual(['p1','a','p2','b','c']);});
 it('renders retained front/back pages in source print order without offering their ghost duplicates',()=>{const books=[book('cover','cover'),book('epigraph','epigraph'),book('dedication','dedication'),book('a'),book('about','about'),book('epilogue','epilogue')],tiles=boundShelfLayout(shelf(books.map(b=>b.id)),books);expect(tiles.filter(t=>t.type==='page').map(t=>t.book.id)).toEqual(['dedication','epigraph','epilogue','about']);expect(tiles.filter(t=>t.type==='ghost').map(t=>t.kind)).toEqual(['copyright','prologue','acknowledgments']);});
 it('avoids a duplicate standalone prologue/epilogue offer when a single story already owns that chapter role',()=>{const books=[book('cover','cover'),{...book('a'),chapterOrder:['intro','last'],chapterKinds:{intro:'prologue',last:'epilogue'}}];expect(boundShelfLayout(shelf(['cover','a']),books).filter(t=>t.type==='ghost').map(t=>t.kind)).toEqual(['copyright','dedication','epigraph','acknowledgments','about']);});
 it('unbound presentation retains all present stories and omits missing file IDs without page affordances',()=>{const books=[book('a'),book('b')],tiles=boundShelfLayout(shelf(['b','absent','a'],false),books);expect(tiles).toEqual([{type:'book',book:books[1],label:'b'},{type:'book',book:books[0],label:'a'},{type:'new'}]);});
 it('touch presentation keeps actual page order and removes hover-only ghosts/seams',()=>{const books=[book('cover','cover'),book('a')],tiles=boundShelfLayout(shelf(['cover','a']),books,false);expect(tiles.map(t=>t.type)).toEqual(['cover','book','new']);expect(romanPart(14)).toBe('XIV');});
 it('compiles the presentation independently with typed callbacks and no provider imports',()=>{const source=readFileSync(new URL('../../apps/desktop/src/LibraryShelf.svelte',import.meta.url),'utf8'),result=compile(source,{generate:'server',filename:'LibraryShelf.svelte'});expect(result.warnings).toEqual([]);expect(source).not.toMatch(/fetch\(|@tauri|desktop-host|filesystem-documents/);});
});

it('native cover insertion selects before midpoint, after neighbours and wrapped rows using source geometry',()=>{const rectangles=[{top:20,bottom:170,left:10,width:100},{top:20,bottom:170,left:130,width:100},{top:190,bottom:340,left:10,width:100}];expect(coverInsertionIndex(rectangles,25,70)).toBe(0);expect(coverInsertionIndex(rectangles,180,70)).toBe(2);expect(coverInsertionIndex(rectangles,500,180)).toBe(2);expect(coverInsertionIndex(rectangles,200,250)).toBe(3);expect(coverInsertionIndex([],0,0)).toBe(0);});
