import { test, expect, type Page } from '@playwright/test';
async function caret(page:Page,offset:number){await page.getByRole('textbox',{name:'Manuscript'}).evaluate((el,offset)=>{(el as HTMLElement).focus();const text=el.querySelector('p')!.firstChild!;const range=document.createRange();range.setStart(text,offset);range.collapse(true);const selection=getSelection()!;selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'));},offset);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));}
async function selectVerb(page:Page){await caret(page,5);for(let i=0;i<9;i++)await page.keyboard.press('Shift+ArrowRight');await expect.poll(()=>page.evaluate(()=>getSelection()?.toString())).toBe('whispered');}
test('real Svelte/PM selection → review → accept → undo/redo → JSON reopen',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await selectVerb(page);await page.getByRole('button',{name:'Review selection',exact:true}).click();const row=page.locator('article[data-kind=suggestion]');await expect(row).toContainText('whispered');await row.getByRole('button',{name:'Accept',exact:true}).click();await expect(page.getByRole('textbox')).toContainText('Mara said softly.');await expect(row).toHaveAttribute('data-state','accepted');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('textbox')).toContainText('Mara whispered softly.');await expect(row).toHaveAttribute('data-state','pending');await expect(row.locator('.reference')).toHaveAttribute('data-status','current');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(row).toHaveAttribute('data-state','accepted');await page.getByRole('button',{name:'Save and reopen fixture'}).click();await expect(page.getByRole('textbox')).toContainText('Mara said softly.');await expect(row).toHaveAttribute('data-state','accepted');expect(errors).toEqual([]);
});
test('changed source blocks acceptance, undo makes suggestion applicable again, dismiss does not edit',async({page})=>{await page.goto('/');await selectVerb(page);await page.getByRole('button',{name:'Review selection',exact:true}).click();await caret(page,6);await page.keyboard.type('X');const row=page.locator('article[data-kind=suggestion]');await expect(row.locator('.reference')).toHaveAttribute('data-status','changed');await row.getByRole('button',{name:'Accept',exact:true}).click();await expect(page.getByRole('status')).toContainText('stale');await expect(page.getByRole('textbox')).toContainText('wXhispered');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(row.locator('.reference')).toHaveAttribute('data-status','current');await row.getByRole('button',{name:'Dismiss',exact:true}).click();await expect(row).toHaveAttribute('data-state','rejected');await expect(page.getByRole('textbox')).toContainText('whispered');});
test('structure note spans chapters and follows split, merge and movement',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Review structure',exact:true}).click();const note=page.locator('article[data-kind=note]');await expect(note.locator('.reference')).toHaveCount(3);await caret(page,5);await page.keyboard.press('Enter');await expect(note.locator('.reference').first()).toContainText('2 passage(s)');await expect(note.locator('.reference').first()).toHaveAttribute('data-status','current');await page.keyboard.press('Backspace');await expect(note.locator('.reference').first()).toContainText('1 passage(s)');await page.getByRole('button',{name:'Move first paragraph'}).click();await expect(page.getByRole('textbox').locator('p').first()).toContainText('She kept');await expect(note.locator('.reference').first()).toContainText('Mara whispered softly.');await page.getByRole('button',{name:'return',exact:true}).click();await expect(page.getByRole('textbox')).toContainText('Mara returned');await page.getByRole('button',{name:'Save and reopen fixture'}).click();await expect(note.locator('.reference')).toHaveCount(3);await expect(note.locator('.reference').first()).toHaveAttribute('data-status','current');await page.screenshot({path:'/tmp/neo-identity-spike/reviews.png',fullPage:true});});
test('unsupported formatting is preserved and editing/review commands are disabled',async({page})=>{await page.goto('/?unsupported');await expect(page.getByRole('status')).toContainText('Unsupported content preserved');await expect(page.getByRole('textbox')).toHaveAttribute('contenteditable','false');await expect(page.getByRole('button',{name:'Review selection'})).toBeDisabled();await page.getByRole('button',{name:'Save and reopen fixture'}).click();await expect(page.getByRole('textbox')).toHaveAttribute('contenteditable','false');await expect(page.getByRole('textbox')).toContainText('Keep my original colour.');});
