import { describe, it, expect } from 'vitest';
import { JSDOM } from 'jsdom';
import { TextSelection } from 'prosemirror-state';
import { splitBlock, joinBackward } from 'prosemirror-commands';
import { closeHistory } from 'prosemirror-history';
import { IdentitySession } from './session';
import { runConformance } from './conformance';
import { deterministicReview } from './fixture';
import { IdentityBook, ReviewFile } from './contracts';
const document = new JSDOM('').window.document;
const book=(html='<p>Mara whispered softly.</p><p>She kept her promise.</p>')=>({formatVersion:'neo-lifecycle/v1' as const,revision:0,metadata:{id:'book-one',title:'The promise',author:'Writer'},chapters:[{id:'arrival',html}],darlings:[]});
const open=(html?:string)=>new IdentitySession(document,book(html));
runConformance({describe,it,expect},()=>open());
describe('real ProseMirror identity and review integration',()=>{
 it('splits, joins, moves, and restores exact identities and references through native undo/redo',()=>{
  const s=open(), e=s.editor('arrival');const initial=s.passages();const ref=s.capture('arrival',initial[0].id,0,22);const ids=initial.map(p=>p.id);
  e.dispatch(closeHistory(e.state.tr).setSelection(TextSelection.create(e.state.doc,6)));splitBlock(e.state,tr=>e.dispatch(tr));
  expect(s.passages()).toHaveLength(3);expect(s.passages()[0].id).toBe(ids[0]);expect(s.passages()[1].id).not.toBe(ids[0]);expect(s.resolve(ref.id).segments).toHaveLength(2);
  const splitIds=s.passages().map(p=>p.id);expect(e.undo()).toBe(true);expect(s.passages().map(p=>p.id)).toEqual(ids);expect(s.resolve(ref.id).status).toBe('current');expect(e.redo()).toBe(true);expect(s.passages().map(p=>p.id)).toEqual(splitIds);
  e.dispatch(closeHistory(e.state.tr).setSelection(TextSelection.create(e.state.doc,e.state.doc.child(0).nodeSize+1)));joinBackward(e.state,tr=>e.dispatch(tr));expect(s.passages()).toHaveLength(2);expect(s.resolve(ref.id).status).toBe('current');
  e.undo();expect(s.passages().map(p=>p.id)).toEqual(splitIds);e.redo();
  s.move('arrival',ids[0],1);expect(s.passages().map(p=>p.id)).toEqual([ids[1],ids[0]]);expect(s.resolve(ref.id).status).toBe('current');e.undo();expect(s.passages().map(p=>p.id)).toEqual(ids);e.redo();expect(s.resolve(ref.id).status).toBe('current');
 });
 it('follows repeated text using identity and transactions, never a global quote search',()=>{
  const s=open('<p>same same same</p><p>same same same</p>');const e=s.editor('arrival');const p=s.passages();const ref=s.capture('arrival',p[0].id,5,9);
  e.dispatch(closeHistory(e.state.tr).insertText('prefix ',1));const r=s.resolve(ref.id);expect(r.status).toBe('current');expect(r.segments[0]).toMatchObject({passageId:p[0].id,from:12,to:16});s.move('arrival',p[0].id,1);expect(s.resolve(ref.id).segments[0].passageId).toBe(p[0].id);
 });
 it('rejects stale or deleted suggestions, restores references with undo, and guards rich formatting',()=>{
  const s=open(),p=s.passages()[0],input=s.extract([s.capture('arrival',p.id,5,14).id],'voice');s.receive(deterministicReview(input));const item=s.reviews()[0],e=s.editor('arrival');
  e.dispatch(closeHistory(e.state.tr).insertText('shouted',6,15));expect(s.resolve(input.extracts[0].reference.id).status).toBe('changed');expect(s.accept(item.id)).toEqual({ok:false,code:'STALE'});expect(e.state.doc.textContent).toContain('shouted');e.undo();expect(s.resolve(input.extracts[0].reference.id).status).toBe('current');
  expect(s.accept(item.id).ok).toBe(true);expect(e.state.doc.textContent).toContain('said');e.undo();expect(s.resolve(input.extracts[0].reference.id).status).toBe('current');expect(s.reviews()[0].state).toBe('pending');e.redo();expect(s.reviews()[0].state).toBe('accepted');
  const r=s.capture('arrival',s.passages()[1].id,0,20);e.dispatch(closeHistory(e.state.tr).delete(e.state.doc.child(0).nodeSize,e.state.doc.content.size));expect(s.resolve(r.id).status).toBe('deleted');e.undo();expect(s.resolve(r.id).status).toBe('current');
 });
 it('persists identities and reviews, rejects mismatched versions, validates source instead of guessing',()=>{
  const s=open();const refs=s.passages().map(p=>s.capture(p.chapterId,p.id,0,p.size));s.receive(deterministicReview(s.extract(refs.map(r=>r.id),'structure')));const saved=s.checkpoint();const re=new IdentitySession(document,JSON.parse(JSON.stringify(saved.book)),JSON.parse(JSON.stringify(saved.reviews)));expect(re.passages().map(p=>p.id)).toEqual(s.passages().map(p=>p.id));expect(re.resolve(refs[0].id).status).toBe('current');expect(re.reviews()[1].references).toHaveLength(2);
  const mismatched=structuredClone(saved.book);mismatched.chapters[0].version=crypto.randomUUID();const other=new IdentitySession(document,mismatched,saved.reviews);expect(other.resolve(refs[0].id).status).toBe('unresolved');expect(other.accept(other.reviews()[0].id)).toEqual({ok:false,code:'STALE'});
  const bad=structuredClone(saved.book);bad.chapters[0].html='<p>Different</p>';expect(()=>new IdentitySession(document,bad)).toThrow('INVALID_IDENTITY');expect(()=>IdentityBook.parse({...saved.book,extra:'bad'})).toThrow();expect(()=>ReviewFile.parse({...saved.reviews,bookId:'',extra:1})).toThrow();
 });
 it('does not overwrite atoms or lose formatting when accepting plain text suggestions',()=>{
  const s=open('<p>Mara <b><i>whispered</i></b>.<span class="ph-mark" data-sid="x">⚑</span><span class="darling-anchor" data-did="d"></span></p>');const p=s.passages()[0],ref=s.capture('arrival',p.id,5,14);s.receive(deterministicReview(s.extract([ref.id],'voice')));expect(s.accept(s.reviews()[0].id).ok).toBe(true);const html=s.checkpoint().book.chapters[0].html;expect(html).toContain('<b><i>said</i></b>');expect(html).toContain('data-sid="x"');expect(html).toContain('data-did="d"');
 });
});
describe('reference and review boundary cases',()=>{
 it('copy creates a new identity while the original retains its identity',()=>{const s=open(),e=s.editor('arrival'),p=s.passages()[0],ref=s.capture('arrival',p.id,0,p.size);e.dispatch(closeHistory(e.state.tr).insert(0,e.state.doc.child(0)));expect(s.passages()[1].id).toBe(p.id);expect(s.passages()[0].id).not.toBe(p.id);expect(s.resolve(ref.id).segments[0].passageId).toBe(p.id);e.undo();expect(s.passages()[0].id).toBe(p.id);});
 it('split-spanning suggestion remains located but cannot implicitly join paragraphs',()=>{const s=open(),p=s.passages()[0],ref=s.capture('arrival',p.id,0,p.size),e=s.editor('arrival');s.receive(deterministicReview(s.extract([ref.id],'voice')));e.dispatch(closeHistory(e.state.tr).setSelection(TextSelection.create(e.state.doc,6)));splitBlock(e.state,tr=>e.dispatch(tr));expect(s.resolve(ref.id).status).toBe('current');expect(s.accept(s.reviews()[0].id)).toEqual({ok:false,code:'UNSUPPORTED_TARGET'});});
 it('marks changed inside a target invalidate it, and native undo restores applicability',()=>{const s=open(),p=s.passages()[0],r=s.capture('arrival',p.id,5,14),e=s.editor('arrival');s.receive(deterministicReview(s.extract([r.id],'voice')));e.dispatch(closeHistory(e.state.tr).addMark(6,15,e.state.schema.marks.italic.create()));expect(s.resolve(r.id).status).toBe('changed');expect(s.accept(s.reviews()[0].id).ok).toBe(false);e.undo();expect(s.resolve(r.id).status).toBe('current');});
 it('rejects targets mixing marks or containing atoms without flattening their content',()=>{const s=open('<p>A <b>bold</b> word<span class="ph-mark" data-sid="x">⚑</span></p>');const p=s.passages()[0];for(const [from,to]of [[0,p.size],[0,11]]){const r=s.capture('arrival',p.id,from,to);s.receive(deterministicReview(s.extract([r.id],'voice')));expect(s.accept(s.reviews().at(-2)!.id)).toEqual({ok:false,code:'UNSUPPORTED_TARGET'});}expect(s.checkpoint().book.chapters[0].html).toContain('<b>bold</b>');});
 it('validates whole review replies atomically and enforces the requested extract scope',()=>{const s=open(),p=s.passages()[0],r=s.capture('arrival',p.id,0,p.size),input=s.extract([r.id],'voice');const reply=deterministicReview(input);expect(()=>s.receive({...reply,items:[reply.items[0],{...reply.items[1],references:['outside-request']}]})).toThrow('INVALID_REVIEW');expect(s.reviews()).toEqual([]);expect(()=>s.receive({...reply,requestId:'unknown'})).toThrow('UNKNOWN_REQUEST');expect(()=>s.receive({...reply,extra:'sdk'})).toThrow();s.receive(reply);expect(()=>s.receive(reply)).toThrow('INVALID_REVIEW');});
 it('public snapshots cannot mutate registered references or reviews',()=>{const s=open(),p=s.passages()[0],r=s.capture('arrival',p.id,0,p.size),input=s.extract([r.id],'voice');s.receive(deterministicReview(input));r.expected=[];input.extracts[0].reference.expected=[];s.reviews()[0].references[0]='bad';expect(s.resolve(r.id).status).toBe('current');expect(s.accept(s.reviews()[0].id).ok).toBe(true);});
 it('notes span chapters and remain independent of manuscript content',()=>{const b=book();b.chapters.push({id:'return',html:'<p>Mara returned.</p>'});const s=new IdentitySession(document,b),before=s.checkpoint().book;const refs=s.passages().filter(p=>p.chapterId==='arrival'&&p.id===s.passages()[0].id||p.chapterId==='return').map(p=>s.capture(p.chapterId,p.id,0,p.size));const input=s.extract(refs.map(r=>r.id),'character');s.receive(deterministicReview(input));expect(input.extracts.map(e=>e.chapterOrder)).toEqual([0,1]);expect(s.reviews()[1].references).toHaveLength(2);expect(s.checkpoint().book).toEqual(before);});
 it('reopening with missing review sidecar retains passage identities; wrong-book sidecars are rejected',()=>{const s=open(),saved=s.checkpoint();const re=new IdentitySession(document,saved.book);expect(re.passages().map(p=>p.id)).toEqual(s.passages().map(p=>p.id));expect(re.reviews()).toEqual([]);expect(()=>new IdentitySession(document,saved.book,{...saved.reviews,bookId:'other'})).toThrow('INVALID_REVIEW_BOOK');});
});
describe('fragmented reference lineage',()=>{
 it('keeps both halves when one fragment moves away, including save/reopen and native undo',()=>{const s=open(),p=s.passages()[0],r=s.capture('arrival',p.id,0,p.size),e=s.editor('arrival');e.dispatch(closeHistory(e.state.tr).setSelection(TextSelection.create(e.state.doc,6)));splitBlock(e.state,tr=>e.dispatch(tr));s.move('arrival',p.id,2);expect(s.resolve(r.id).status).toBe('current');expect(s.resolve(r.id).segments).toHaveLength(2);const saved=s.checkpoint();const re=new IdentitySession(document,saved.book,saved.reviews);expect(re.resolve(r.id)).toEqual(s.resolve(r.id));e.undo();expect(s.resolve(r.id).status).toBe('current');e.redo();expect(s.resolve(r.id).status).toBe('current');});
});
describe('reference retention follows native history events',()=>{
 it('coalesces typing snapshots while restoring exact references at undo/redo boundaries',()=>{const s=open(),e=s.editor('arrival'),p=s.passages()[0],r=s.capture('arrival',p.id,5,14);for(let i=0;i<1000;i++)e.dispatch(e.state.tr.insertText('x',1));expect(e.retainedSnapshots).toBeLessThanOrEqual(3);expect(s.resolve(r.id).status).toBe('current');expect(s.resolve(r.id).segments[0].from).toBe(1005);e.undo();expect(s.resolve(r.id).segments[0].from).toBe(5);e.redo();expect(s.resolve(r.id).segments[0].from).toBe(1005);});
 it('branching after undo drops obsolete redo reference snapshots',()=>{const s=open(),e=s.editor('arrival'),p=s.passages()[0],r=s.capture('arrival',p.id,5,14);e.dispatch(closeHistory(e.state.tr).insertText('one ',1));e.dispatch(closeHistory(e.state.tr).insertText('two ',1));e.undo();e.dispatch(closeHistory(e.state.tr).insertText('new ',1));expect(e.redo()).toBe(false);expect(s.resolve(r.id).status).toBe('current');expect(s.resolve(r.id).segments[0].from).toBe(13);});
});
describe('persisted contract failures and history retention',()=>{
 it('rejects malformed indexes and reference coordinates instead of guessing',()=>{const s=open(),p=s.passages()[0];s.capture('arrival',p.id,0,p.size);const saved=s.checkpoint();const duplicate=structuredClone(saved.book);duplicate.chapters[0].passages[1].id=duplicate.chapters[0].passages[0].id;expect(()=>new IdentitySession(document,duplicate)).toThrow();const badPath=structuredClone(saved.book);badPath.chapters[0].passages[0].path=[99];expect(()=>new IdentitySession(document,badPath)).toThrow('INVALID_IDENTITY');const badRange=structuredClone(saved.reviews);badRange.references[0].location.segments[0].to=999;expect(()=>new IdentitySession(document,saved.book,badRange)).toThrow('INVALID_REFERENCE');});
 it('references created after an edit become unresolved before their creation and restore on redo',()=>{const s=open(),e=s.editor('arrival');e.dispatch(closeHistory(e.state.tr).insertText('Before, ',1));const p=s.passages()[0],r=s.capture('arrival',p.id,13,22);e.undo();expect(s.resolve(r.id).status).toBe('unresolved');e.redo();expect(s.resolve(r.id).status).toBe('current');});
 it('native history rollover bounds retained snapshots and keeps surviving events usable',()=>{const s=open(),e=s.editor('arrival'),p=s.passages()[0],r=s.capture('arrival',p.id,5,14);for(let i=0;i<250;i++)e.dispatch(closeHistory(e.state.tr).insertText('x',1));expect(e.retainedSnapshots).toBeLessThanOrEqual(242);expect(s.resolve(r.id).status).toBe('current');for(let i=0;i<30;i++)e.undo();expect(s.resolve(r.id).status).toBe('current');for(let i=0;i<30;i++)e.redo();expect(s.resolve(r.id).status).toBe('current');});
});
describe('merge identity and semantic edit guards',()=>{
 it('a reference to the merged-away paragraph follows its content into the survivor and back',()=>{const s=open(),e=s.editor('arrival'),p=s.passages(),r=s.capture('arrival',p[1].id,0,p[1].size);e.dispatch(closeHistory(e.state.tr).setSelection(TextSelection.create(e.state.doc,e.state.doc.child(0).nodeSize+1)));joinBackward(e.state,tr=>e.dispatch(tr));expect(s.passages()).toHaveLength(1);expect(s.resolve(r.id).status).toBe('current');expect(s.resolve(r.id).segments[0].passageId).toBe(p[0].id);e.undo();expect(s.passages()[1].id).toBe(p[1].id);expect(s.resolve(r.id).status).toBe('current');e.redo();expect(s.resolve(r.id).status).toBe('current');});
 it('suggestion acceptance does not overwrite unrelated edits elsewhere in the same passage',()=>{const s=open(),e=s.editor('arrival'),p=s.passages()[0],r=s.capture('arrival',p.id,5,14);s.receive(deterministicReview(s.extract([r.id],'voice')));e.dispatch(closeHistory(e.state.tr).insertText('At dawn, ',1));expect(s.accept(s.reviews()[0].id).ok).toBe(true);expect(e.state.doc.child(0).textContent).toBe('At dawn, Mara said softly.');});
});
