<script lang="ts">
 import { onMount } from 'svelte';import { LifecycleViewModel,type LifecycleUI } from './LifecycleViewModel.svelte';
 const focusDialog=(element:HTMLElement)=>element.focus();
 const model=new LifecycleViewModel(window.lifecycleHost);const vm:LifecycleUI=model;let paper:HTMLDivElement,notes:HTMLDivElement;
 onMount(()=>{vm.mount(paper,notes);window.lifecycleSpike=model;return()=>vm.dispose();});
</script>
<svelte:head><title>NEO · {vm.title}</title></svelte:head>
<div class="workbench"><div class="workspace inspector-open"><aside class="chapters"><div class="side-title">THE MANUSCRIPT</div><h1>{vm.title}</h1><div class="author">{vm.author}</div><nav class="chapter-list" aria-label="Chapters">{#each vm.chapters as chapter (chapter.id)}<button class:current={vm.currentChapter===chapter.id} onclick={()=>vm.chapter(chapter.id)}>{chapter.title}</button>{/each}</nav></aside>
<main><div class="paper-toolbar"><span>{vm.title}</span><div><button aria-label="Bold" onmousedown={e=>e.preventDefault()} onclick={()=>vm.format('bold')}>B</button><button aria-label="Italic" onmousedown={e=>e.preventDefault()} onclick={()=>vm.format('italic')}>I</button><button aria-label="Undo" onmousedown={e=>e.preventDefault()} onclick={()=>vm.undo()}>↶</button><button aria-label="Redo" onmousedown={e=>e.preventDefault()} onclick={()=>vm.redo()}>↷</button></div></div><div class="paper-scroll"><article class="paper"><section class="chapter"><h2 class="chapter-title">{vm.chapters.find(c=>c.id===vm.currentChapter)?.title}</h2><div bind:this={paper} class="editor-host chapter-body"></div></section></article></div></main><aside class="inspector"><h2>Notes</h2><div bind:this={notes} class="notes-host"></div></aside></div>
<footer><span class="brand">NEO</span><span role="status">{vm.status}</span><div><button onclick={()=>vm.save()} disabled={vm.readOnly}>Save</button><button onclick={()=>vm.reload()} disabled={vm.readOnly}>Discard changes and reload</button><button onclick={()=>vm.newWindow()}>New window</button><button onclick={()=>vm.requestClose()}>Close book</button></div></footer></div>
{#if vm.closePrompt}<div class="close-scrim"><div use:focusDialog role="dialog" aria-modal="true" tabindex="-1" aria-label="Unsaved changes"><h2>Keep your changes?</h2><p>This book has changes waiting to be saved.</p><button onclick={()=>vm.chooseClose('save')}>Save and close</button><button onclick={()=>vm.chooseClose('discard')}>Discard and close</button><button onclick={()=>vm.chooseClose('cancel')}>Keep writing</button></div></div>{/if}
