import { it,expect } from 'vitest';import { mkdtemp,readFile,writeFile,readdir,rm } from 'node:fs/promises';import { tmpdir } from 'node:os';import { join } from 'node:path';import { JSDOM } from 'jsdom';
import { legacyFixture } from './fixture';import { importNeo,exportNeo } from './legacy';import { importHTML,exportHTML } from '../parity/src/codec';
it('real NEO folder contract round-trips metadata, chapters, anchors, rich notes, Darlings and assets',async()=>{const root=await mkdtemp(join(tmpdir(),'neo-lifecycle-import-'));try{const source=join(root,'source'),target=join(root,'target'),exported=join(root,'exported');const fixture=await legacyFixture(source);const book=await importNeo(source,target);expect(book.chapters.map(c=>c.id)).toEqual(fixture.metadata.chapterOrder);await exportNeo(target,exported);
 expect(JSON.parse(await readFile(join(exported,'book.json'),'utf8'))).toEqual(fixture.metadata);expect(JSON.parse(await readFile(join(exported,'darlings.json'),'utf8'))).toEqual(fixture.darlings);
 for(const name of ['notes.html','outline.html','stickies.json','cover.png'])expect(await readFile(join(exported,name))).toEqual(await readFile(join(source,name)));
 const document=new JSDOM('').window.document;for(const [id,html]of Object.entries(fixture.chapters)){expect(await readFile(join(exported,'chapters',id+'.html'),'utf8')).toBe(html);const model=importHTML(document,html);expect(importHTML(document,exportHTML(document,model)).eq(model)).toBe(true);}
 expect((await readdir(target)).includes('chapters')).toBe(false);expect(JSON.parse(await readFile(join(source,'book.json'),'utf8'))).toEqual(fixture.metadata);
 }finally{await rm(root,{recursive:true,force:true});}});
it('missing, orphan or unsafe chapter references fail migration without silent loss',async()=>{const root=await mkdtemp(join(tmpdir(),'neo-lifecycle-invalid-'));try{const source=join(root,'source');const fixture=await legacyFixture(source);await writeFile(join(source,'chapters','orphan.html'),'<p>Do not lose me</p>');await expect(importNeo(source,join(root,'target'))).rejects.toThrow('INVALID');await writeFile(join(source,'book.json'),JSON.stringify({...fixture.metadata,chapterOrder:['../outside']}));await expect(importNeo(source,join(root,'target'))).rejects.toThrow();}finally{await rm(root,{recursive:true,force:true});}});
it('preserves plain filenames accepted by NEO, including punctuation and auxiliary backup files',async()=>{const root=await mkdtemp(join(tmpdir(),'neo-lifecycle-names-'));try{const source=join(root,'source'),target=join(root,'target'),out=join(root,'out');const data=await legacyFixture(source);const id='arrival (α)#1';await writeFile(join(source,'chapters',id+'.html'),data.chapters.arrival);await rm(join(source,'chapters','arrival.html'));await writeFile(join(source,'book.json'),JSON.stringify({...data.metadata,chapterOrder:data.metadata.chapterOrder.map(c=>c==='arrival'?id:c)}));for(const name of ['.DS_Store','review.bak','reference (one).bin'])await writeFile(join(source,name),'Retain file bytes');await importNeo(source,target);await exportNeo(target,out);expect(await readFile(join(out,'chapters',id+'.html'),'utf8')).toBe(data.chapters.arrival);for(const name of ['.DS_Store','review.bak','reference (one).bin'])expect(await readFile(join(out,name),'utf8')).toBe('Retain file bytes');}finally{await rm(root,{recursive:true,force:true});}});
