import { EditorState, type Transaction } from 'prosemirror-state';import { EditorView } from 'prosemirror-view';import { history,undo,redo } from 'prosemirror-history';import { keymap } from 'prosemirror-keymap';import { baseKeymap,toggleMark } from 'prosemirror-commands';
import { importHTML,exportHTML,schema } from '../parity/src/codec';
import { Book,unwrap,LifecycleError,type LifecyclePort,type OpenResult,type OpenBook,type DocumentName,type BookDocument,type SavedReceipt } from './contracts';import { LifecycleTelemetry } from './telemetry';
export interface LifecycleUI {
 readonly title:string;readonly author:string;readonly chapters:readonly {id:string;title:string}[];readonly currentChapter:string;readonly status:string;readonly readOnly:boolean;readonly closePrompt:boolean;
 mount(paper:HTMLElement,notes:HTMLElement):void;chapter(id:string):void;format(mark:'bold'|'italic'):void;undo():void;redo():void;save():Promise<void>;reload():Promise<void>;requestClose():void;chooseClose(choice:'save'|'discard'|'cancel'):Promise<void>;newWindow():void;dispose():void;
}
type Editor={state:EditorState;changed:boolean;source:string;unsupported:boolean};
const messages={SAVE_UNCERTAIN:'The save could not be confirmed. Retry, or reload to inspect the saved version.',BUSY:'This book is already open for editing.',EXTERNAL_CHANGE:'The files changed outside this window. Your edits are still here.',CORRUPT:'Neither saved version could be recovered.',DISK_ERROR:'Could not save to disk. Your edits are still here.',INVALID:'The document request is invalid.',UNAUTHORIZED:'This window does not own the book.',UNSAVED:'Save your changes before closing.'};
export class LifecycleViewModel implements LifecycleUI {
 title=$state('Opening book');author=$state('');chapters=$state.raw<{id:string;title:string}[]>([]);currentChapter=$state('');status=$state('Opening');readOnly=$state(true);closePrompt=$state(false);
 readonly telemetry=new LifecycleTelemetry();private book:BookDocument|null=null;private lease:string|null=null;private versions!:Record<DocumentName,string>;private revisions:Record<DocumentName,number>={manuscript:0,notes:0,outline:0};private dirty=new Set<DocumentName>();
 private editors=new Map<string,Editor>();private paper:HTMLElement|null=null;private notes:HTMLElement|null=null;private mainView:EditorView|null=null;private noteView:EditorView|null=null;private queue:Promise<void>=Promise.resolve();private pending=0;private closing=false;private timer:ReturnType<typeof setTimeout>|null=null;private disposed=false;private off:()=>void;
 constructor(private port:LifecyclePort){this.off=port.onCloseRequested(()=>void this.prepareClose());}
 mount(paper:HTMLElement,notes:HTMLElement){this.paper=paper;this.notes=notes;void this.open();}
 private failure(error:unknown){this.status=error instanceof LifecycleError?messages[error.code]: 'Could not complete the document operation.';}
 private async open(){try{const opened=await this.telemetry.run('ui.open',async ctx=>unwrap(await this.port.request<OpenResult>({method:'open'},this.telemetry.carrier(ctx))));this.lease=opened.lease;this.readOnly=opened.readOnly;this.apply(opened);this.status=opened.readOnly?'This book is open elsewhere. Reading only.':opened.recovered?'Recovered the previous saved version.':'Opened';}catch(error){this.failure(error);}}
 private apply(opened:OpenBook){this.book=Book.parse(opened.book);this.title=this.book.metadata.title;this.author=this.book.metadata.author;this.versions={...opened.versions};this.revisions={manuscript:this.book.revision,notes:0,outline:0};this.dirty.clear();this.editors.clear();const titles=this.book.metadata.chapterTitles;this.chapters=this.book.chapters.map(c=>({id:c.id,title:titles&&typeof titles==='object'&&!Array.isArray(titles)&&typeof titles[c.id]==='string'?titles[c.id] as string:c.id}));
  for(const c of this.book.chapters)this.createEditor('chapter:'+c.id,c.html);this.createEditor('notes',opened.notes);this.createEditor('outline',opened.outline);this.currentChapter=this.book.chapters[0]?.id??'';this.render();}
 private createEditor(id:string,html:string){if(!this.paper)return;const detached=this.paper.ownerDocument.createElement('div');detached.innerHTML=html;const allowed=new Set(['P','DIV','H1','H2','H3','H4','H5','H6','BLOCKQUOTE','UL','OL','LI','PRE','HR','BR','B','STRONG','I','EM','U','S','DEL','STRIKE','CODE','A','SPAN']);let unsupported=false;
  detached.querySelectorAll('*').forEach(node=>{if(!allowed.has(node.tagName))unsupported=true;const style=(node as HTMLElement).style;for(const property of style)if(!['text-align','font-weight','font-style','text-decoration'].includes(property))unsupported=true;});
  this.editors.set(id,{state:EditorState.create({doc:importHTML(this.paper.ownerDocument,html),plugins:[history(),keymap({'Mod-z':undo,'Mod-Shift-z':redo,'Mod-y':redo,'Mod-b':toggleMark(schema.marks.bold),'Mod-i':toggleMark(schema.marks.italic)}),keymap(baseKeymap)]}),source:html,changed:false,unsupported});
 }
 private render(){this.mainView?.destroy();this.noteView?.destroy();this.mainView=null;this.noteView=null;if(!this.paper||!this.notes)return;const make=(host:HTMLElement,id:string)=>{const editor=this.editors.get(id);if(!editor)return null;return new EditorView(host,{state:editor.state,editable:()=>!this.readOnly&&!editor.unsupported&&!this.closePrompt,attributes:{role:'textbox','aria-label':id==='notes'?'Book notes':'Manuscript',spellcheck:'true'},dispatchTransaction:tr=>this.dispatch(id,tr)});};this.mainView=make(this.paper,'chapter:'+this.currentChapter);this.noteView=make(this.notes,'notes');if(this.editors.get('chapter:'+this.currentChapter)?.unsupported)this.status='This section has formatting the spike cannot edit. Its source is preserved.';}
 private dispatch(id:string,tr:Transaction){const editor=this.editors.get(id)!;editor.state=editor.state.apply(tr);(id==='notes'?this.noteView:this.mainView)?.updateState(editor.state);if(!tr.docChanged)return;editor.changed=true;const name:DocumentName=id.startsWith('chapter:')?'manuscript':id as DocumentName;this.revisions[name]++;this.dirty.add(name);this.status='Unsaved changes';void this.port.request({method:'dirty',name,revision:this.revisions[name]});if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>{this.timer=null;void this.save();},600);}
 chapter(id:string){if(!this.chapters.some(c=>c.id===id))return;this.currentChapter=id;this.render();}
 format(mark:'bold'|'italic'){if(!this.mainView||this.readOnly)return;toggleMark(schema.marks[mark])(this.mainView.state,tr=>this.mainView!.dispatch(tr));this.mainView.focus();}
 undo(){if(this.mainView&&!this.readOnly)undo(this.mainView.state,tr=>this.mainView!.dispatch(tr));}redo(){if(this.mainView&&!this.readOnly)redo(this.mainView.state,tr=>this.mainView!.dispatch(tr));}
 private html(id:string){const editor=this.editors.get(id)!;return editor.changed?exportHTML(this.paper!.ownerDocument,editor.state.doc):editor.source;}
 snapshot(){if(!this.book)throw new LifecycleError('INVALID');return Book.parse({...this.book,revision:this.revisions.manuscript,chapters:this.book.chapters.map(c=>({id:c.id,html:this.html('chapter:'+c.id)}))});}
 async save(){if(this.timer){clearTimeout(this.timer);this.timer=null;}if(!this.book||!this.lease||!this.dirty.size)return;const lease=this.lease,captured=[...this.dirty].map(name=>({name,revision:this.revisions[name],content:name==='manuscript'?this.snapshot():this.html(name)}));this.pending++;
 const operation=this.queue.then(()=>this.telemetry.run('ui.save',async ctx=>{for(const document of captured){const receipt=unwrap(await this.port.request<SavedReceipt>({method:'save',lease,...document,expected:this.versions[document.name]},this.telemetry.carrier(ctx)));this.versions[document.name]=receipt.etag;if(this.revisions[document.name]===receipt.revision)this.dirty.delete(document.name);}if(!this.disposed)this.status=this.dirty.size?'Unsaved changes':'Saved';}));this.queue=operation.catch(()=>{});
 try{await operation;}catch(error){this.failure(error);}finally{this.pending--;}
 }
 async reload(){if(!this.lease)return;if(this.timer){clearTimeout(this.timer);this.timer=null;}const revision={...this.revisions};await this.queue;try{const opened=await this.telemetry.run('ui.reload',async ctx=>unwrap(await this.port.request<OpenBook>({method:'reload',lease:this.lease!},this.telemetry.carrier(ctx))));if(Object.keys(revision).some(key=>revision[key as DocumentName]!==this.revisions[key as DocumentName])){this.status='You kept writing while the files were read.';return;}this.apply(opened);this.status=opened.recovered?'Recovered the previous saved version.':'Reloaded';}catch(error){this.failure(error);}}
 requestClose(){void this.port.request({method:'close'});}newWindow(){void this.port.request({method:'new-window'});}
 private refreshEditable(){this.mainView?.setProps({editable:()=>!this.readOnly&&!this.editors.get('chapter:'+this.currentChapter)?.unsupported&&!this.closePrompt});this.noteView?.setProps({editable:()=>!this.readOnly&&!this.editors.get('notes')?.unsupported&&!this.closePrompt});}
 private async prepareClose(){if(this.closing)return;this.closing=true;if(this.timer){clearTimeout(this.timer);this.timer=null;}await this.queue;if(this.dirty.size){this.closePrompt=true;this.refreshEditable();return;}await this.chooseClose('discard');}
 async chooseClose(choice:'save'|'discard'|'cancel'){if(choice==='cancel'){this.closePrompt=false;this.closing=false;this.refreshEditable();if(this.dirty.size)this.timer=setTimeout(()=>{this.timer=null;void this.save();},600);return;}if(choice==='save'){await this.save();await this.queue;if(this.dirty.size)return;}else{if(this.timer){clearTimeout(this.timer);this.timer=null;}await this.queue;}
  try{unwrap(await this.port.request({method:'finish-close',discard:choice==='discard'}));}catch(error){this.failure(error);}}
 dispose(){this.disposed=true;if(this.timer)clearTimeout(this.timer);this.off();this.mainView?.destroy();this.noteView?.destroy();void this.telemetry.dispose();}
}
