import { test,expect,_electron,type ElectronApplication,type Page } from '@playwright/test';import { mkdtemp,writeFile,readFile,chmod,rm,mkdir,readdir } from 'node:fs/promises';import { join,resolve } from 'node:path';import { tmpdir,homedir } from 'node:os';import { execFileSync } from 'node:child_process';
import { legacyFixture } from './fixture';import { Book } from './contracts';
const packageRoot=resolve(import.meta.dirname,'..');let crashStop=false;test.beforeEach(()=>test.skip(crashStop,'Native crash stop')); 
async function start(root:string){await readFile(join(packageRoot,'lifecycle-dist/host/main.js'));const receipt=JSON.parse(await readFile(join(packageRoot,'node_modules/.neo-parity-hosts/electron/receipt.json'),'utf8'));execFileSync('codesign',['--verify','--deep','--strict',join(packageRoot,'node_modules/.neo-parity-hosts/electron/NEO Parity.app')]);const application=await _electron.launch({executablePath:receipt.executable,args:[join(packageRoot,'lifecycle-spike/launch.cjs')],env:{...process.env,NEO_LIFECYCLE_ROOT:root},timeout:20000});application.process().on('exit',(_code,signal)=>{if(signal&&signal!=='SIGKILL')crashStop=true;});return application;}
async function fixture(){const root=await mkdtemp(join(tmpdir(),'neo-lifecycle-native-'));await writeFile(join(root,'.lifecycle-fixture'),'neo-lifecycle-v1');await legacyFixture(join(root,'source'));return root;}
async function page(app:ElectronApplication){const p=await app.firstWindow();const errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await expect(p.getByRole('status')).toHaveText(/Opened|Recovered/);await expect(p).toHaveTitle('NEO · The Light Keeper');return{p,errors};}
async function write(p:Page,text:string){const editor=p.getByRole('textbox',{name:'Manuscript',exact:true});await editor.evaluate(element=>{(element as HTMLElement).focus();const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT),first=walker.nextNode()!;const range=document.createRange();range.setStart(first,0);range.collapse(true);const selection=getSelection()!;selection.removeAllRanges();selection.addRange(range);});await p.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));await p.keyboard.type(text);await expect(editor).toContainText(text.trim());await expect(p.getByRole('status')).toHaveText('Unsaved changes');}
async function dumps(){try{return(await readdir(join(homedir(),'Library/Logs/DiagnosticReports'))).filter(f=>/^(Electron|NEO).*\.ips$/.test(f));}catch{return[];}}
test('signed hidden host: import, typed IPC, durable receipt, reader window, crash and reopen',async()=>{
 const root=await fixture(),before=await dumps();let app:ElectronApplication|undefined;
 try{app=await start(root);const initial=await page(app);let p=initial.p;const errors=initial.errors;expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().every(w=>!w.isVisible()))).toBe(true);expect(await p.evaluate(()=>typeof (window as unknown as {require?:unknown}).require)).toBe('undefined');
 await p.getByRole('button',{name:'The arrival',exact:true}).click();await expect(p.locator('.paper .ph-mark')).toHaveCount(1);await expect(p.locator('.paper .darling-anchor')).toHaveCount(1);await expect(p.locator('.notes-host ul')).toHaveCount(1);
 await write(p,'Acknowledged ');await p.getByRole('button',{name:'Save',exact:true}).click();await expect(p.getByRole('status')).toHaveText('Saved');await p.getByRole('textbox',{name:'Book notes'}).click();await p.keyboard.press('ControlOrMeta+Home');await p.keyboard.type('Observation ');await p.getByRole('button',{name:'Save',exact:true}).click();await expect(p.getByRole('status')).toHaveText('Saved');expect(await readFile(join(root,'book/notes.html'),'utf8')).toContain('Observation');const committed=Book.parse(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8')));expect(committed.chapters.find(c=>c.id==='arrival')?.html).toContain('Acknowledged ');expect(committed.darlings).toHaveLength(1);
 const invalid=await p.evaluate(()=>window.lifecycleHost.request({method:'save',lease:'00000000-0000-4000-8000-000000000000',name:'notes',expected:'0'.repeat(64),revision:1,content:'Unauthorized'}));expect(invalid).toEqual({ok:false,code:'UNAUTHORIZED'});
 const traces=await p.evaluate(async()=>({renderer:await window.lifecycleSpike.telemetry.report(),main:(await window.lifecycleHost.request({method:'diagnostics'}))}));expect(traces.main.ok).toBe(true);if(!traces.main.ok)throw Error('Trace report failed');const main=traces.main.value as {name:string;traceId:string;parentSpanId?:string;attributes:unknown}[];
 const ui=traces.renderer.find(s=>s.name==='ui.save')!;expect(main.some(s=>s.name==='ipc.save'&&s.traceId===ui.traceId&&s.parentSpanId===ui.spanId)).toBe(true);expect(main.some(s=>s.name==='storage.save'&&s.traceId===ui.traceId&&s.parentSpanId)).toBe(true);expect(JSON.stringify(traces)).not.toContain('Acknowledged');expect(JSON.stringify(traces)).not.toContain(root);await writeFile(join(root,'trace-proof.json'),JSON.stringify(traces,null,2));
 const windowEvent=app.waitForEvent('window');await p.getByRole('button',{name:'New window'}).click();const reader=await windowEvent;await expect(reader.getByRole('status')).toContainText('Reading only');await expect(reader.getByRole('button',{name:'Save',exact:true})).toBeDisabled();expect(await reader.getByRole('textbox',{name:'Manuscript',exact:true}).getAttribute('contenteditable')).toBe('false');await reader.getByRole('button',{name:'Close book'}).click();
 await expect.poll(()=>app!.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length)).toBe(1);const rendererWindow=app.waitForEvent('window');const rendererPid=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getOSProcessId());process.kill(rendererPid,'SIGKILL');p=await rendererWindow;await expect(p.getByRole('status')).toHaveText('Opened');await p.getByRole('button',{name:'The arrival',exact:true}).click();await expect(p.locator('.paper')).toContainText('Acknowledged');await expect(p.locator('.notes-host')).toContainText('Observation');
 await write(p,'Unacknowledged ');app.process().kill('SIGKILL');await new Promise<void>(resolve=>app!.process().once('exit',()=>resolve()));app=await start(root);const reopened=await page(app);await reopened.p.getByRole('button',{name:'The arrival',exact:true}).click();await expect(reopened.p.locator('.paper')).toContainText('Acknowledged');await expect(reopened.p.locator('.paper')).not.toContainText('Unacknowledged');await expect(reopened.p.locator('.notes-host')).toContainText('Observation');expect(Book.parse(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8')))).toEqual(committed);
 await write(reopened.p,'Keep local ');const external={...committed,revision:100,metadata:{...committed.metadata,title:'External revision'}};await writeFile(join(root,'book/manuscript.json'),JSON.stringify(external));await reopened.p.getByRole('button',{name:'Save',exact:true}).click();await expect(reopened.p.getByRole('status')).toContainText('changed outside this window');await expect(reopened.p.locator('.paper')).toContainText('Keep local');expect(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8'))).toEqual(external);await reopened.p.getByRole('button',{name:'Discard changes and reload'}).click();await expect(reopened.p.getByRole('status')).toHaveText('Reloaded');await expect(reopened.p).toHaveTitle('NEO · External revision');await expect(reopened.p.locator('.paper')).not.toContainText('Keep local');
 await mkdir('/tmp/neo-lifecycle-spike',{recursive:true});await reopened.p.getByRole('button',{name:'The arrival',exact:true}).click();await reopened.p.screenshot({path:'/tmp/neo-lifecycle-spike/reopened.png'});await writeFile('/tmp/neo-lifecycle-spike/ipc-traces.json',JSON.stringify(traces,null,2));expect(errors).toEqual([]);expect(reopened.errors).toEqual([]);
 await reopened.p.getByRole('button',{name:'Close book'}).click();await app.process().exitCode;await app.close().catch(()=>{});app=undefined;expect((await dumps()).filter(f=>!before.includes(f))).toEqual([]);
 }finally{if(app)await app.close().catch(()=>app!.process().kill('SIGKILL'));await rm(root,{recursive:true,force:true});}
});
test('unsaved exit: cancel, failed save keeps window open, retry saves and closes; explicit discard preserves disk',async()=>{
 const root=await fixture();let app:ElectronApplication|undefined;try{app=await start(root);const{p,errors}=await page(app);await write(p,'Retain ');await p.getByRole('button',{name:'Close book'}).click();await expect(p.getByRole('dialog',{name:'Unsaved changes'})).toBeVisible();await p.waitForTimeout(750);expect(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8')).revision).toBe(0);await p.getByRole('button',{name:'Keep writing'}).click();await expect(p.getByRole('dialog')).toHaveCount(0);
 await chmod(join(root,'book'),0o500);await p.getByRole('button',{name:'Close book'}).click();await p.getByRole('button',{name:'Save and close'}).click();await expect(p.getByRole('status')).toContainText('Could not save to disk');await expect(p.getByRole('dialog')).toBeVisible();expect((await app.windows()).length).toBe(1);await chmod(join(root,'book'),0o700);await p.getByRole('button',{name:'Save and close'}).click();await app.close().catch(()=>{});app=undefined;const saved=Book.parse(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8')));expect(saved.chapters[0].html).toContain('Retain');expect(errors).toEqual([]);
 app=await start(root);const fresh=await page(app);await write(fresh.p,'Discarded ');await fresh.p.getByRole('button',{name:'Close book'}).click();await expect(fresh.p.getByRole('dialog')).toBeVisible();await fresh.p.waitForTimeout(750);expect(Book.parse(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8')))).toEqual(saved);await fresh.p.getByRole('button',{name:'Discard and close'}).click();await app.close().catch(()=>{});app=undefined;expect(Book.parse(JSON.parse(await readFile(join(root,'book/manuscript.json'),'utf8')))).toEqual(saved);
 }finally{await chmod(join(root,'book'),0o700).catch(()=>{});if(app)await app.close().catch(()=>app!.process().kill('SIGKILL'));await rm(root,{recursive:true,force:true});}
});
