import { test, expect, type Page, type ElectronApplication } from '@playwright/test';
import { readFile, writeFile, access, realpath, cp, readdir, rm } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import path from 'node:path';
import JSZip from 'jszip';
import { spawnReference, createReferenceDirectory, launchReference, removeReferenceDirectory } from '../reference/harness';
import { onboard, book, shelf, authorMenu, readLibrary, libraryPath, option, nativeMenu, input } from './library-helpers';
import { fixture, meta, metaPath, chapterPath, png, host, bound, bind, shelfOption, shelfMetas, addPage, closeSheet, navigation, chapterChoice, pickImage, paste, exportFile, configurePaint } from './books-helpers';
import { caret, spot, external, refresh, events } from './persistence-helpers';
declare const NeoCovers:{plan(meta:{id:string;title:string;author:string;coverSeed:string}):{template:string}};
const require=createRequire(import.meta.url);

// Parse the exported artifact itself; this helper never invokes an app exporter or editor command.
async function pdfText(file:string) {
 const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');
 const task=getDocument({data:new Uint8Array(await readFile(file)),useSystemFonts:true});const pdf=await task.promise;
 try {const pages:string[]=[];for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n);const c=await p.getTextContent();pages.push(c.items.map(i=>'str'in i?i.str:'').join(' '));}return pages.join(' ');} finally {await task.destroy();}
}
async function orderedText(page:Page,file:string) {
 if(file.endsWith('.pdf'))return pdfText(file);
 const zip=await JSZip.loadAsync(await readFile(file));
 if(file.endsWith('.docx'))return(await zip.file('word/document.xml')!.async('string')).replace(/<[^>]+>/g,' ');
 const opf=await zip.file('OEBPS/content.opf')!.async('string');
 const paths=await page.evaluate(opf=>{const d=new DOMParser().parseFromString(opf,'application/xml');return[...d.querySelectorAll('spine itemref')].map(ref=>d.querySelector(`manifest item[id="${ref.getAttribute('idref')}"]`)!.getAttribute('href')!);},opf);
 const texts=await Promise.all(paths.map(p=>zip.file('OEBPS/'+p)!.async('string')));return texts.join(' ').replace(/<[^>]+>/g,' ');
}
for(const engine of (['original','prosemirror']as const).filter(e=>!process.env.NEO_ACCEPTANCE_GAP_ENGINE||process.env.NEO_ACCEPTANCE_GAP_ENGINE===e))test.describe(engine,()=>{
 let directory:string,app:ElectronApplication,page:Page;
 async function restart(){await app.close();app=await launchReference(directory,engine==='original'?undefined:engine);page=await app.firstWindow();await expect(page.locator('#bookshelf-view')).toBeVisible();}
 test.beforeEach(async()=>{directory=await realpath(await createReferenceDirectory());app=await launchReference(directory,engine==='original'?undefined:engine);page=await app.firstWindow();});
 test.afterEach(async()=>{await app?.close();await removeReferenceDirectory(directory);});

 test('[NEO-001-B] [NEO-002-B] real attribution and stored onboarding pen persist then explicitly added pen identity authors separately',async()=>{
  await onboard(page,{name:'Real Writer',pen:'Pen Writer'});await expect(page.locator('#author-chip')).toHaveText('Real Writer');
  const real=await book(page,'Real attribution');expect((await meta(directory,real.bookId)).author).toBe('Real Writer');
  expect((await readLibrary(directory)).penNames).toEqual(['Pen Writer']);expect((await readLibrary(directory)).authors.map(a=>a.name)).toEqual(['Real Writer']);await authorMenu(page,'Add a pen name');await input(page,'Pen Writer');
  await expect(page.locator('#author-chip')).toHaveText('Pen Writer');const pen=await book(page,'Pen attribution');expect((await meta(directory,pen.bookId)).author).toBe('Pen Writer');
  await expect(page.locator(`[data-book-id="${real.bookId}"]`)).toHaveCount(0);await restart();await expect(page.locator('#firstrun')).toBeHidden();await expect(page.locator('#author-chip')).toHaveText('Pen Writer');await expect(page.locator(`[data-book-id="${pen.bookId}"]`)).toBeVisible();
  await authorMenu(page,'Write as Real Writer');await expect(page.locator(`[data-book-id="${real.bookId}"]`)).toBeVisible();
 });
 test('[NEO-004-B] chosen dropcap previews visibly hover another face and leave restores choice before persistence',async()=>{
  await page.locator('#fr-name').fill('Font Writer');await page.locator('.fr-choice[data-style="pantser"]').click();
  const family=()=>page.locator('#fr-sample-text').evaluate(el=>getComputedStyle(el,'::first-letter').fontFamily);
  const cap=page.locator('#fr-dropcaps .fr-font').filter({hasText:'Fantasy'});
  const fantasyFamily=await cap.locator('.fr-cap').evaluate(el=>getComputedStyle(el).fontFamily);await cap.click();await page.mouse.move(1,1);
  await expect.poll(family).toBe(fantasyFamily);
  const scifi=page.locator('#fr-dropcaps .fr-font').filter({hasText:'Sci-Fi'}),scifiFamily=await scifi.locator('.fr-cap').evaluate(el=>getComputedStyle(el).fontFamily);
  expect(scifiFamily).not.toBe(fantasyFamily);await scifi.hover();await expect.poll(family).toBe(scifiFamily);
  await page.mouse.move(1,1);await expect.poll(family).toBe(fantasyFamily);await page.locator('#fr-done').click();expect((await readLibrary(directory)).fonts.dropcap).toBe('fantasy');await restart();
  // loadLibrary renders the shelf before its completion handler applies saved fonts.
  await expect(page.locator('#author-chip')).toHaveText('Font Writer');
  await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--dropcap-font').trim())).toBe(fantasyFamily);
 });
 test('[NEO-022-B] keyboard activation of add shelf focuses its editable label and commits named shelf',async()=>{
  await onboard(page);await page.locator('#add-shelf-btn').focus();await page.keyboard.press('Enter');const label=page.locator('.shelf-label').last();await expect(label).toBeFocused();await label.fill('Keyboard shelf');await label.press('Enter');expect((await readLibrary(directory)).shelves.at(-1)?.name).toBe('Keyboard shelf');await restart();await expect(page.locator('.shelf-label').last()).toHaveText('Keyboard shelf');
 });
 test('[NEO-027-B] removing custom image reveals retained completed painting and removes only custom file',async()=>{
  await onboard(page);const made=await book(page,'Layered cover');await pickImage(page,directory,made.bookId);const m=await meta(directory,made.bookId);const original=m.coverImage!;m.coverArt={status:'done',file:'art-fixture.png'};await writeFile(path.join(libraryPath(directory),m.id,'art-fixture.png'),png);await writeFile(metaPath(directory,m.id),JSON.stringify(m));await page.reload();await page.locator(`[data-book-id="${m.id}"]`).click({button:'right'});await option(page,'Remove cover art');await expect.poll(async()=>(await meta(directory,m.id)).coverImage).toBeNull();await expect(access(path.join(libraryPath(directory),m.id,original))).rejects.toMatchObject({code:'ENOENT'});expect(await readFile(path.join(libraryPath(directory),m.id,'art-fixture.png'))).toEqual(png);await page.locator('.b-refresh').click();await expect(page.locator('.fr-choice strong').filter({hasText:'Show NEO’s painting'})).toHaveCount(0);await expect(page.locator('.fr-choice strong').filter({hasText:'Show the abstract'})).toHaveCount(1);await page.keyboard.press('Escape');
 });
 test('[NEO-031-B] cancelling valid changed cover settings restores saved models quality and automatic preference',async()=>{
  await onboard(page);await nativeMenu(app,'Cover Art');await page.locator('#ca-auto').uncheck();await page.locator('.m-ok').click();await expect(page.locator('#ca-auto')).toHaveCount(0);const before=JSON.parse(await readFile(path.join(libraryPath(directory),'library.json'),'utf8')).coverArt;await nativeMenu(app,'Cover Art');await page.locator('.st-advanced summary').click();await page.locator('#ca-tmodel').fill('unsaved-brief');await page.locator('#ca-imodel').fill('unsaved-image');await page.locator('#ca-quality').selectOption('low');await page.locator('#ca-auto').check();await page.locator('.m-cancel').click();expect(JSON.parse(await readFile(path.join(libraryPath(directory),'library.json'),'utf8')).coverArt).toEqual(before);await nativeMenu(app,'Cover Art');await expect(page.locator('#ca-auto')).not.toBeChecked();await expect(page.locator('#ca-tmodel')).not.toHaveValue('unsaved-brief');await expect(page.locator('#ca-imodel')).not.toHaveValue('unsaved-image');
 });
 test('[NEO-036-B] unbind and rebind restores parked Part before its story and back page last with original words',async()=>{
  await onboard(page);const ids=await bound(page,directory);await page.locator('.part-seam').nth(1).click();await page.locator('.ps-body').fill('Second movement');await closeSheet(page);await addPage(page,'About the Author','A retained biography');const before=await shelfMetas(directory);const part=before.find(m=>m.kind==='part')!,about=before.find(m=>m.kind==='about')!;await shelfOption(page,'Unbind');expect((await shelfMetas(directory)).map(m=>m.id)).toEqual(ids);await restart();await bind(page);const after=(await shelfMetas(directory)).map(m=>m.id);expect(after.indexOf(part.id)+1).toBe(after.indexOf(ids[1]));expect(after.at(-1)).toBe(about.id);await page.locator(`[data-book-id="${part.id}"]`).click();await expect(page.locator('.ps-body')).toHaveText('Second movement');await closeSheet(page);await page.locator(`[data-book-id="${about.id}"]`).click();await expect(page.locator('.ps-body')).toHaveText('A retained biography');
 });
 test('[NEO-037-B] bound title subtitle and author edited in sheet all reopen after Escape and restart',async()=>{
  await onboard(page);await bound(page,directory);await page.locator('.bound-cover').click();await page.locator('.tp-t').fill('Bound collection');await page.locator('.tp-s').fill('All the stories');await page.locator('.tp-a').fill('Collection Writer');await page.keyboard.press('Escape');await restart();await page.locator('.bound-cover').click();await expect(page.locator('.tp-t')).toHaveText('Bound collection');await expect(page.locator('.tp-s')).toHaveText('All the stories');await expect(page.locator('.tp-a')).toHaveText('Collection Writer');
 });
 test('[NEO-041-C] copyright dedication Part and back sheets retain their kind typography formatted prose and Escape commit',async()=>{
  await onboard(page);await bound(page,directory);
  for(const [kind,label]of [['copyright','Copyright'],['dedication','Dedication'],['part','Part'],['acknowledgments','Acknowledgments'],['about','About the Author']]){
   if(kind==='part')await page.locator('.part-seam').first().click();else await page.locator(`.ghost-page[aria-label="${label}"]`).click();
   await paste(page,'.ps-body','Heading words\nSecond words','<p><b>Heading words</b></p><p><i>Second words</i></p>');
   const styles=await page.locator('.ps-body').evaluate(el=>{const ps=el.querySelectorAll('p');return{size:getComputedStyle(el).fontSize,style:getComputedStyle(el).fontStyle,firstSize:getComputedStyle(ps[0]).fontSize,firstStyle:getComputedStyle(ps[0]).fontStyle,indent:getComputedStyle(ps[1]).textIndent,italic:getComputedStyle(el.querySelector('i,em')!).fontStyle};});
   if(kind==='copyright'){expect(styles.size).toBe('10.5px');expect(styles.italic).toBe('italic');}
   if(kind==='dedication'){expect(styles.size).toBe('17px');expect(styles.style).toBe('italic');}
   if(kind==='part'){expect(styles.size).toBe('14px');expect(styles.firstSize).toBe('24px');expect(styles.firstStyle).toBe('normal');}
   if(kind==='about'||kind==='acknowledgments'){expect(parseFloat(styles.indent)).toBeGreaterThan(0);expect(styles.italic).toBe('italic');}
   await page.keyboard.press('Escape');const m=(await shelfMetas(directory)).find(m=>m.kind===kind)!;const saved=await readFile(chapterPath(directory,m.id,m.chapterOrder[0]),'utf8');expect(saved).toMatch(/<(b|strong)>Heading words/);expect(saved).toMatch(/<(i|em)>Second words/);expect(saved).not.toMatch(/data-attr|<h[1-6]/);await page.locator(`[data-book-id="${m.id}"]`).click();await expect(page.locator('.ps-body')).toContainText('Second words');await expect(page.locator('.ps-body b,.ps-body strong')).toHaveText('Heading words');await closeSheet(page);
  }
 });
 test('[NEO-045-B] [NEO-046-B] bound and anthology menus expose three formats whose real artifacts retain shelf and chapter order',async()=>{
  await onboard(page);await bound(page,directory);
  for(const mode of ['bound','anthology']){
   if(mode==='anthology')await shelfOption(page,'Unbind');
   for(const format of ['epub','docx','pdf']as const){const file=await exportFile(page,directory,app,format,async()=>{
    await shelfOption(page,mode==='bound'?'Export the book':'Export shelf as anthology');if(mode==='anthology'){await expect(page.locator('.modal-backdrop:not([hidden]) input')).toHaveCount(1);await input(page,'Ordered anthology');}
    await expect(page.locator('.modal-backdrop:not([hidden]) .fr-choice strong')).toHaveText(['EPUB','Word (.docx)','PDF']);await option(page,format==='epub'?'EPUB':format==='docx'?'Word (.docx)':'PDF');
   },mode+'-'+format);const text=(await orderedText(page,file)).replace(/\s/g,'');const values=[1,2,3].flatMap(n=>['Unique opening for story '+n+'.','Unique ending for story '+n+'.']);const positions=values.map(v=>text.indexOf(v.replace(/\s/g,'')));expect(positions.every(n=>n>=0)).toBe(true);expect(positions).toEqual([...positions].sort((a,b)=>a-b));}
  }
 });
 test('[NEO-047-B] subtitle reopens and clearing title produces Untitled on real shelf cover and restart',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'one',html:'<p>Words.</p>'}]);await page.locator('#tp-subtitle').fill('Retained subtitle');await page.locator('#back-to-shelf').click();await page.locator(`[data-book-id="${id}"]`).click();await expect(page.locator('#tp-subtitle')).toHaveText('Retained subtitle');await page.locator('#tp-title').fill('');await page.locator('#back-to-shelf').click();expect((await meta(directory,id)).title).toBe('Untitled');await expect(page.locator(`[data-book-id="${id}"]`)).toHaveAttribute('aria-label',/^Untitled,/);await restart();await page.locator(`[data-book-id="${id}"]`).click();await expect(page.locator('#tp-subtitle')).toHaveText('Retained subtitle');
 });
 test('[NEO-049-B] title and subtitle Enter focus existing story past front matter without creating duplicate chapter',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'front',kind:'dedication',html:'<p>For everyone.</p>'},{id:'story',html:'<p>Existing words.</p>'},{id:'back',kind:'about',html:'<p>Biography.</p>'}]);
  for(const selector of ['#tp-title','#tp-subtitle']){await page.locator(selector).focus();await page.keyboard.press('Enter');await expect(page.locator('[data-id="story"] .chapter-body')).toBeFocused();await expect(page.locator('.chapter')).toHaveCount(3);expect((await meta(directory,id)).chapterOrder).toEqual(['front','story','back']);}
 });
 test('[NEO-051-B] chapter heading Enter blurs empty title restores default and Shift Enter poetry accepts words before existing prose',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'one',html:'<p>Original prose.</p>'},{id:'other',html:'<p>Other prose.</p>'}]);const title=page.locator('[data-id="one"] .ch-title');await title.fill('New title');await title.press('Enter');await expect(title).not.toBeFocused();await title.fill('');await page.locator('[data-id="one"] .chapter-body').click();await expect(page.locator('[data-id="one"] .chapter-head')).not.toHaveClass(/has-title/);await expect(page.locator('[data-id="one"] .ch-num')).toHaveText('Chapter 1');await title.click();await page.keyboard.press('Shift+Enter');await page.keyboard.type('Poetry opening');await expect(page.locator('[data-id="one"] .chapter-body p').first()).toHaveClass(/poetry/);await expect(page.locator('[data-id="one"] .chapter-body p').first()).toContainText('Poetry opening');await expect(page.locator('[data-id="one"] .chapter-body p').last()).toHaveText('Original prose.');await page.locator('#back-to-shelf').click();expect(await readFile(chapterPath(directory,id,'one'),'utf8')).toContain('Poetry opening');
 });
 test('[NEO-053-B] deleting Part renumbers remaining Roman heading and Undo restores numbering and all prose',async()=>{
  await onboard(page);await fixture(page,directory,[{id:'p1',kind:'part',html:'<p>Movement one.</p>'},{id:'one',html:'<p>First story.</p>'},{id:'p2',kind:'part',html:'<p>Movement two.</p>'},{id:'two',html:'<p>Second story.</p>'}]);await navigation(page);await chapterChoice(page,'p1','Delete');await expect(page.locator('.ch-num')).toHaveText(['Chapter 1','Part I','Chapter 2']);await expect(page.locator('[data-id="p2"] .chapter-body')).toHaveText('Movement two.');await page.keyboard.press('Meta+z');await expect(page.locator('.ch-num')).toHaveText(['Part I','Chapter 1','Part II','Chapter 2']);await expect(page.locator('[data-id="p1"] .chapter-body')).toHaveText('Movement one.');
 });
 test('[NEO-056-B] generated contents Part link focuses actual Part body and tracks current navigation row',async()=>{
  await onboard(page);await fixture(page,directory,[{id:'contents',kind:'contents'},{id:'movement',kind:'part',html:'<p>The first movement.</p>'},{id:'one',html:'<p>Story prose.</p>'}]);await navigation(page);await page.locator('.toc-list li').filter({hasText:'Part I'}).click();await expect(page.locator('[data-id="movement"] .chapter-body')).toBeFocused();await expect(page.locator('.nav-item[data-id="movement"]')).toHaveClass(/current/);
 });
 test('[NEO-062-B] nav note blur writes metadata and immediately appears on matching Outline line',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'one',html:'<p>Body words.</p>'}]);await navigation(page);await page.locator('.nav-note[contenteditable="true"]').fill('Blurred chapter note');await page.locator('.chapter-body').click();await expect.poll(async()=>(await meta(directory,id)).chapterNotes?.one).toBe('Blurred chapter note');await page.locator('.tab[data-tab="outline"]').click();await expect(page.locator('.ol-line[data-ch-id="one"] .ol-text')).toContainText('Blurred chapter note');
 });
 test('[NEO-063-C] heading and Outline context menus delete real chapter archive formatted prose and Undo restores exact order',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'one',html:'<p><b>Archived bold words.</b></p>'},{id:'two',html:'<p>Remaining words.</p>'}]);
  for(const entry of ['heading','outline']){if(entry==='outline'){await page.locator('.tab[data-tab="outline"]').click();await page.locator('.ol-line[data-ch-id="one"]').click({button:'right'});}else await page.locator('[data-id="one"] .chapter-head').click({button:'right'});await page.locator('.pop-menu button').filter({hasText:/^Delete$/}).click();await expect(page.locator('.chapter')).toHaveCount(1);const darlings=JSON.parse(await readFile(path.join(libraryPath(directory),id,'darlings.json'),'utf8'));expect(darlings.some((d:{html:string})=>/<(b|strong)>Archived bold words/.test(d.html))).toBe(true);await page.keyboard.press('Meta+z');await expect(page.locator('.chapter')).toHaveCount(2);expect((await meta(directory,id)).chapterOrder).toEqual(['one','two']);await expect(page.locator('[data-id="one"] .chapter-body b,[data-id="one"] .chapter-body strong')).toHaveText('Archived bold words.');}
 });
 test('[NEO-065-B] chapter PDF artifact contains selected custom heading and prose while excluding book front matter and other story',async()=>{
  await onboard(page);await fixture(page,directory,[{id:'front',kind:'dedication',html:'<p>Excluded dedication unique.</p>'},{id:'one',title:'Selected heading',html:'<p>Selected PDF unique prose.</p>'},{id:'two',html:'<p>Excluded other story unique.</p>'}]);await navigation(page);const file=await exportFile(page,directory,app,'pdf',async()=>{await chapterChoice(page,'one','Export Chapter…');await option(page,'PDF');});const text=(await pdfText(file)).replace(/\s/g,'');expect(text).toContain('SelectedPDFuniqueprose.');expect(text.toLowerCase()).toContain('selectedheading');expect(text).not.toContain('Excludeddedicationunique.');expect(text).not.toContain('Excludedotherstoryunique.');
 });
 test('[NEO-231-C] chapter words typed immediately before host close flush to original file and reopen after restart',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'one',html:'<p>Original beginning.</p>'}]);await caret(page,'one',0,19);await page.keyboard.type(' Immediate close tail');await restart();expect(await readFile(chapterPath(directory,id,'one'),'utf8')).toContain('Immediate close tail');await page.locator(`[data-book-id="${id}"]`).click();await expect(page.locator('.chapter-body')).toContainText('Immediate close tail');
 });
 test('[NEO-237-B] external text refresh preserves nonzero scroll and distant caret and emits one adoption toast',async()=>{
  await onboard(page);const paragraphs=Array.from({length:100},(_,n)=>`<p>Paragraph ${n} has enough ordinary prose to establish a long manuscript page.</p>`);const id=await fixture(page,directory,[{id:'one',html:paragraphs.join('')}]);await caret(page,'one',65,4);await page.locator('#paper-scroll').evaluate(el=>{el.scrollTop=1500;});const before=await spot(page);const scroll=await page.locator('#paper-scroll').evaluate(el=>el.scrollTop);expect(scroll).toBeGreaterThan(100);
  await page.evaluate(()=>{(window as unknown as {adoptionMessages:string[]}).adoptionMessages=[];const el=document.querySelector('#hint')!;new MutationObserver(()=>{if(el.textContent?.includes('Updated from your other device'))(window as unknown as {adoptionMessages:string[]}).adoptionMessages.push(el.textContent);}).observe(el,{childList:true,characterData:true,subtree:true});});
  paragraphs[3]='<p>External paragraph changed without altering the remaining long manuscript.</p>';await external(directory,id,'one',paragraphs.join(''));await refresh(page);await expect(page.locator('.chapter-body')).toContainText('External paragraph changed');expect(await spot(page)).toEqual(before);expect(await page.locator('#paper-scroll').evaluate(el=>el.scrollTop)).toBe(scroll);await refresh(page);await page.waitForTimeout(500);expect(await page.evaluate(()=>(window as unknown as {adoptionMessages:string[]}).adoptionMessages.length)).toBe(1);
 });
 test('[NEO-009-B] dragging book into populated second shelf inserts before target and persists unique placement',async()=>{
  await onboard(page);const first=await book(page,'First book'),moving=await book(page,'Moving book');await shelf(page,'Second shelf');const anchor=await book(page,'Anchor book',1);await page.locator(`[data-book-id="${moving.bookId}"]`).dragTo(page.locator(`[data-book-id="${anchor.bookId}"]`),{targetPosition:{x:2,y:20}});await expect.poll(async()=>(await readLibrary(directory)).shelves.map(s=>s.bookIds)).toEqual([[first.bookId],[moving.bookId,anchor.bookId]]);await restart();await expect(page.locator('.shelf').last().locator('.book')).toHaveCount(2);expect((await readLibrary(directory)).shelves.flatMap(s=>s.bookIds).filter(id=>id===moving.bookId)).toHaveLength(1);
 });
 test('[NEO-019-B] Reshelve sorts removed stories by modification date while excluding parked bound pages',async()=>{
  await onboard(page);const ids=await bound(page,directory);await addPage(page,'Dedication','Parked dedication words');const dedication=(await shelfMetas(directory)).find(m=>m.kind==='dedication')!;await shelfOption(page,'Unbind');
  for(const [index,id]of ids.slice(0,2).entries()){await page.locator(`[data-book-id="${id}"]`).click({button:'right'});await option(page,'Remove from bookshelf');const m=await meta(directory,id);m.modified=index===0?'2020-01-01T00:00:00Z':'2030-01-01T00:00:00Z';await writeFile(metaPath(directory,id),JSON.stringify(m));}
  await nativeMenu(app,'Reshelve a Book');await expect(page.locator('.modal-backdrop:not([hidden]) .fr-choice strong')).toHaveText(['Story 2','Story 1']);await option(page,'Story 1');expect((await readLibrary(directory)).shelves[0].bookIds).toContain(ids[0]);expect((await readLibrary(directory)).shelves[0].bookIds).not.toContain(dedication.id);expect(await readFile(chapterPath(directory,dedication.id,dedication.chapterOrder[0]),'utf8')).toContain('Parked dedication words');
 });
 test('[NEO-043-B] page tile exposes Open and Remove only and inserting a second Part retains first page and both positions',async()=>{
  await onboard(page);const ids=await bound(page,directory);await page.locator('.part-seam').first().click();await page.locator('.ps-body').fill('First movement words');await closeSheet(page);const first=(await shelfMetas(directory)).find(m=>m.kind==='part')!;
  const tile=page.locator(`[data-book-id="${first.id}"]`);expect(await tile.evaluate(el=>(el as HTMLElement).draggable)).toBe(false);await tile.click({button:'right'});await expect(page.locator('.modal-backdrop:not([hidden]) .fr-choice strong')).toHaveText(['Open','Remove page']);await page.locator('.modal-backdrop:not([hidden]) .m-cancel').click();await page.locator('.part-seam').last().click();await page.locator('.ps-body').fill('Second movement words');await closeSheet(page);const all=await shelfMetas(directory),parts=all.filter(m=>m.kind==='part');expect(parts).toHaveLength(2);expect(all.findIndex(m=>m.id===first.id)+1).toBe(all.findIndex(m=>m.id===ids[0]));expect(all.findIndex(m=>m.id===parts[1].id)+1).toBe(all.findIndex(m=>m.id===ids[2]));expect(await readFile(chapterPath(directory,first.id,first.chapterOrder[0]),'utf8')).toContain('First movement words');await expect(page.locator('.kind-part .pt-label')).toHaveText(['Part I','Part II']);
 });
 test('[NEO-054-B] explicit modern Prologue and Epilogue roles persist in arbitrary positions without legacy first last migration',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'first',kind:'epilogue',html:'<p>Modern epilogue first.</p>'},{id:'middle',kind:'prologue',html:'<p>Modern prologue middle.</p>'},{id:'last',html:'<p>Ordinary last chapter.</p>'}]);await expect(page.locator('.ch-num')).toHaveText(['Epilogue','Prologue','Chapter 1']);await page.locator('#back-to-shelf').click();await restart();await page.locator(`[data-book-id="${id}"]`).click();await expect(page.locator('.chapter[data-id="first"]')).toHaveClass(/kind-epilogue/);await expect(page.locator('.chapter[data-id="middle"]')).toHaveClass(/kind-prologue/);expect((await meta(directory,id)).chapterKinds).toEqual({first:'epilogue',middle:'prologue'});
 });
 test('[NEO-240-B] external metadata refresh adopts title author tab names Outline note and both side datasets',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'one',html:'<p>Retained manuscript words.</p>'}]);await page.waitForTimeout(1000);await page.locator('.tab[data-tab="outline"]').click();const m=await meta(directory,id);Object.assign(m,{title:'External title',subtitle:'External subtitle',author:'External author',chapterNotes:{one:'Remote chapter note'},tabNames:{notes:'Research desk',outline:'Story map'}});await writeFile(metaPath(directory,id),JSON.stringify(m));await writeFile(path.join(libraryPath(directory),id,'stickies.json'),JSON.stringify([{id:'remote-sticky',chapterId:'one',text:'External sticky',resolved:false}]));await writeFile(path.join(libraryPath(directory),id,'darlings.json'),JSON.stringify([{id:'remote-darling',chapterId:'one',html:'<p><i>External saved passage.</i></p>',text:'External saved passage.',date:'2026-01-01T00:00:00Z'}]));await refresh(page);await expect(page.locator('#tp-title')).toHaveText('External title');await expect(page.locator('#tp-subtitle')).toHaveText('External subtitle');await expect(page.locator('#tp-author')).toHaveText('External author');await expect(page.locator('.tab[data-tab="notes"]')).toHaveText('Research desk');await expect(page.locator('.tab[data-tab="outline"]')).toHaveText('Story map');await expect(page.locator('.ol-line[data-ch-id="one"] .ol-text')).toContainText('Remote chapter note');await expect(page.locator('.sticky textarea')).toHaveValue('External sticky');await page.locator('.tab[data-tab="darlings"]').click();await expect(page.locator('.darling i,.darling em')).toHaveText('External saved passage.');expect(await readFile(chapterPath(directory,id,'one'),'utf8')).toContain('Retained manuscript words');
 });
 test('[NEO-245-B] external shelf catalog rename preserves nonzero library scroll and stable shelf identity',async()=>{
  await onboard(page);for(let n=0;n<10;n++)await shelf(page,'Shelf '+n);await page.locator('#bookshelf-view').evaluate(el=>{el.scrollTop=700;});const scroll=await page.locator('#bookshelf-view').evaluate(el=>el.scrollTop);expect(scroll).toBeGreaterThan(100);const lib=await readLibrary(directory),id=lib.shelves.at(-1)!.id;lib.shelves.at(-1)!.name='External renamed shelf';await writeFile(path.join(libraryPath(directory),'library.json'),JSON.stringify(lib));await refresh(page);await expect(page.locator('.shelf-label').last()).toHaveText('External renamed shelf');expect(await page.locator('#bookshelf-view').evaluate(el=>el.scrollTop)).toBe(scroll);expect((await readLibrary(directory)).shelves.at(-1)!.id).toBe(id);
 });
 test('[NEO-020-B] selecting populated private library adopts its existing author shelf book and chapter without first run',async()=>{
  await onboard(page);const made=await book(page,'Original source book'),destination=path.join(directory,'Populated Library');await cp(libraryPath(directory),destination,{recursive:true});const bookMetaPath=path.join(destination,made.bookId,'book.json');const incoming=JSON.parse(await readFile(bookMetaPath,'utf8'));incoming.title='Existing incoming book';incoming.author='Incoming Author';await writeFile(bookMetaPath,JSON.stringify(incoming));await writeFile(path.join(destination,made.bookId,'chapters',made.chapterId+'.html'),'<p>Existing incoming chapter words.</p>');
  const libraryFile=path.join(destination,'library.json'),lib=JSON.parse(await readFile(libraryFile,'utf8'));lib.authors[0].name='Incoming Author';lib.shelves[0].name='Incoming shelf';await writeFile(libraryFile,JSON.stringify(lib));await host(directory,{messageResponses:[0],openPaths:[destination]});const closed=app.waitForEvent('close');await nativeMenu(app,'Library Folder');await closed;app=await launchReference(directory,engine==='original'?undefined:engine);page=await app.firstWindow();await expect(page.locator('#firstrun')).toBeHidden();await expect(page.locator('#author-chip')).toHaveText('Incoming Author');await expect(page.locator('.shelf-label')).toHaveText('Incoming shelf');await page.locator(`[data-book-id="${made.bookId}"]`).click();await expect(page.locator('#tp-title')).toHaveText('Existing incoming book');await expect(page.locator('.chapter-body')).toHaveText('Existing incoming chapter words.');expect((await meta(directory,made.bookId)).title).toBe('Original source book');
 });
 test('[NEO-052-B] entry kind conversion updates actual chapter headings and visible typography for every original role',async()=>{
  await onboard(page);await fixture(page,directory,[{id:'convert'},{id:'other',html:'<p>Other words.</p>'}]);await navigation(page);
  for(const [kind,label,heading]of [['contents','Contents','Contents'],['prologue','Prologue','Prologue'],['part','Part','Part I'],['chapter','Chapter','Chapter 1'],['unnumbered','Unnumbered Chapter','Untitled'],['epilogue','Epilogue','Epilogue'],['acknowledgments','Acknowledgments','Acknowledgments'],['about','About the Author','About the Author'],['dedication','Dedication','Dedication'],['epigraph','Epigraph','Epigraph'],['copyright','Copyright','Copyright']]){
   await chapterChoice(page,'convert',label);await expect(page.locator('[data-id="convert"] .ch-num')).toHaveText(heading);const body=page.locator('[data-id="convert"] .chapter-body');if(kind==='contents'){await expect(body).toBeHidden();continue;}await expect(body).toBeVisible();const style=await body.evaluate(el=>({align:getComputedStyle(el).textAlign,size:parseFloat(getComputedStyle(el).fontSize),italic:getComputedStyle(el).fontStyle}));if(kind==='dedication'||kind==='epigraph'||kind==='part')expect(style.align).toBe('center');if(kind==='part')expect(style.italic).toBe('italic');if(kind==='copyright'){expect(style.size).toBeLessThan(15);await expect(body).toContainText('All rights reserved.');}if(kind==='unnumbered')await expect(page.locator('[data-id="convert"] .ch-num')).toBeHidden();
  }
 });
 test('[NEO-303-B] German Italian Dutch Polish Romanian and Greek connectors shrink within complete Unicode stack cover titles',async()=>{
  await onboard(page);const made=await book(page,'Connector cover');
  for(const [title,connector]of [['Nacht und Sterne','und'],['Mare della Notte','della'],['Nacht van Sterren','van'],['Noc ze Gwiazdami','ze'],['Noapte fără Stele','fără'],['Νύχτα από Αστέρια','από'],['Nuit où Étoiles','où']]){
   const m=await meta(directory,made.bookId);m.title=title;m.coverSeed=await page.evaluate(m=>{for(let n=0;n<100;n++){const coverSeed='connector-proof-'+n;if(NeoCovers.plan({id:m.id,title:m.title,author:m.author,coverSeed}).template==='stack')return coverSeed;}throw Error('No stack seed');},{id:m.id,title:m.title,author:m.author});await writeFile(metaPath(directory,m.id),JSON.stringify(m));await page.reload();const tile=page.locator(`[data-book-id="${m.id}"]`);await expect(tile).toHaveClass(/cv-stack/);expect((await tile.locator('.b-title').innerText()).replace(/\s/g,'').toLowerCase()).toBe(title.replace(/\s/g,'').toLowerCase());expect((await tile.locator('.b-small').innerText()).toLowerCase()).toBe(connector.toLowerCase());const small=parseFloat(await tile.locator('.b-small').evaluate(el=>getComputedStyle(el).fontSize));const large=await tile.locator('.b-line:not(.b-small)').evaluateAll(els=>Math.max(...els.map(el=>parseFloat(getComputedStyle(el).fontSize))));expect(small).toBeLessThan(large);await expect(tile.locator('.b-author')).toHaveText('Library Writer');
  }
 });
 test('[NEO-032-B] saved provider key never enters actual book JSON HTML or side files and secret encoding follows native safeStorage availability',async()=>{
  await onboard(page);const made=await book(page,'Secret isolation');const key='sk-private-fixture-book-proof-00000000000';await configurePaint(page,app,key,false);const walk=async(root:string):Promise<string[]>=>{const entries=await readdir(root,{withFileTypes:true});return(await Promise.all(entries.map(e=>e.isDirectory()?walk(path.join(root,e.name)):Promise.resolve([path.join(root,e.name)])))).flat();};const files=(await walk(libraryPath(directory))).filter(f=>/\.(json|html)$/.test(f));expect(files.some(f=>f.endsWith(made.bookId+'/book.json'))).toBe(true);for(const file of files)expect(await readFile(file,'utf8')).not.toContain(key);const encrypted=await app.evaluate(({safeStorage})=>safeStorage.isEncryptionAvailable());const secrets=JSON.parse(await readFile(path.join(directory,'userData','secrets.json'),'utf8'));expect(secrets.openai.enc).toBe(encrypted);if(encrypted)expect(secrets.openai.value).not.toBe(key);else expect(secrets.openai.value).toBe(key);await nativeMenu(app,'Cover Art');await page.locator('#ca-key').fill('remove');await page.locator('.m-ok').click();expect(JSON.parse(await readFile(path.join(directory,'userData','secrets.json'),'utf8')).openai).toBeUndefined();
 });
 test('[NEO-235-B] second isolated process restores and focuses original minimized window without spawning another editor',async()=>{
  await onboard(page);await fixture(page,directory,[{id:'one',html:'<p>Single instance words.</p>'}]);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].minimize());const child=spawnReference(directory,engine==='prosemirror'?engine:undefined);const code=await new Promise<number|null>((resolve,reject)=>{const timer=setTimeout(()=>{child.kill();reject(Error('Second process remained alive'));},10_000);child.once('exit',code=>{clearTimeout(timer);resolve(code);});child.once('error',reject);});expect(code).toBe(0);await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFocused())).toBe(true);expect(app.windows()).toHaveLength(1);await expect(page.locator('.chapter-body')).toContainText('Single instance words.');
 });
 test('[NEO-290-B] exported PDF includes real seeded cover image resources and excludes the one pixel generated painting',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'one',html:'<p>Cover export manuscript.</p>'}],{coverMode:'painted',coverArt:{status:'done',file:'art-private.png'}});await writeFile(path.join(libraryPath(directory),id,'art-private.png'),png);const file=await exportFile(page,directory,app,'pdf',()=>nativeMenu(app,'PDF (.pdf)'));const raw=(await readFile(file)).toString('latin1');const images=[...raw.matchAll(/\/Subtype\s*\/Image\b[\s\S]*?\/Width\s+(\d+)[\s\S]*?\/Height\s+(\d+)/g)].map(m=>({width:Number(m[1]),height:Number(m[2])}));expect(images.length).toBeGreaterThan(0);expect(images.every(image=>image.width>1&&image.height>1)).toBe(true);expect((await pdfText(file)).replace(/\s/g,'')).toContain('Coverexportmanuscript.');expect(await readFile(path.join(libraryPath(directory),id,'art-private.png'))).toEqual(png);
 });
 test('[NEO-024-B] keyboard selection of New cover in real cover menu persists seed and retained title author',async()=>{
  await onboard(page);const made=await book(page,'Keyboard cover');const seed=(await meta(directory,made.bookId)).coverSeed;await page.locator(`[data-book-id="${made.bookId}"]`).click({button:'right'});const choice=page.locator('.modal-backdrop:not([hidden]) .fr-choice').filter({has:page.locator('strong',{hasText:'New cover'})});await choice.focus();await page.keyboard.press('Enter');await expect.poll(async()=>(await meta(directory,made.bookId)).coverSeed).not.toBe(seed);await expect(page.locator('.b-author')).toHaveText('Library Writer');await restart();await expect(page.locator('.book')).toHaveAttribute('aria-label',/^Keyboard cover,/);
 });
 test('[NEO-233-B] controlled host UTC day creates one real backup then next day captures new manuscript in another ZIP',async()=>{
  await onboard(page);const id=await fixture(page,directory,[{id:'one',html:'<p>First day manuscript.</p>'}]);await page.locator('#back-to-shelf').click();await app.close();const backups=path.join(libraryPath(directory),'Backups');await rm(backups,{recursive:true,force:true});await host(directory,{clockNowIso:'2099-04-03T23:59:00.000Z'});app=await launchReference(directory,engine==='original'?undefined:engine);page=await app.firstWindow();const first=path.join(backups,'neo-backup-2099-04-03.zip');await expect.poll(()=>readFile(first).then(()=>true).catch(()=>false)).toBe(true);const bytes=await readFile(first);expect(await(await JSZip.loadAsync(bytes)).file(id+'/chapters/one.html')!.async('string')).toContain('First day manuscript.');await external(directory,id,'one','<p>Second day manuscript.</p>');await restart();expect(await readFile(first)).toEqual(bytes);await host(directory,{clockNowIso:'2099-04-04T00:01:00.000Z'});await restart();const second=path.join(backups,'neo-backup-2099-04-04.zip');await expect.poll(()=>readFile(second).then(()=>true).catch(()=>false)).toBe(true);expect(await(await JSZip.loadAsync(await readFile(second))).file(id+'/chapters/one.html')!.async('string')).toContain('Second day manuscript.');expect((await readdir(backups)).sort()).toEqual(['neo-backup-2099-04-03.zip','neo-backup-2099-04-04.zip']);expect(await readFile(first)).toEqual(bytes);
 });
 test('[NEO-243-B] delayed real external side-file reply cannot leak first books stickies or Darlings into newly opened book',async()=>{
  await onboard(page);const first=await fixture(page,directory,[{id:'one',html:'<p>First book retained words.</p>'}]);await page.locator('#back-to-shelf').click();const second=await book(page,'Second safe book');await writeFile(path.join(libraryPath(directory),second.bookId,'stickies.json'),JSON.stringify([{id:'own',chapterId:second.chapterId,text:'Second own sticky',resolved:false}]));await writeFile(path.join(libraryPath(directory),second.bookId,'darlings.json'),JSON.stringify([{id:'own-d',chapterId:second.chapterId,html:'<p>Second own saved passage.</p>',text:'Second own saved passage.',date:'2026-01-01T00:00:00Z'}]));await page.locator(`[data-book-id="${first}"]`).click();await page.waitForTimeout(1000);const m=await meta(directory,first);m.subtitle='Externally restructured first book';await writeFile(metaPath(directory,first),JSON.stringify(m));await writeFile(path.join(libraryPath(directory),first,'stickies.json'),JSON.stringify([{id:'foreign',chapterId:'one',text:'First foreign sticky',resolved:false}]));await writeFile(path.join(libraryPath(directory),first,'darlings.json'),JSON.stringify([{id:'foreign-d',chapterId:'one',html:'<p>First foreign saved passage.</p>',text:'First foreign saved passage.',date:'2026-01-01T00:00:00Z'}]));await host(directory,{ipcLog:true,ipcDelays:{'json:read':{after:900}}});await refresh(page);await expect.poll(async()=>(await events(directory)).filter(e=>e.kind==='ipc-start'&&e.channel==='json:read'&&e.args?.[0]===first&&e.args?.[1]==='stickies').length).toBeGreaterThan(0);await page.locator('#back-to-shelf').click();await page.locator(`[data-book-id="${second.bookId}"]`).click();await expect(page.locator('#tp-title')).toHaveText('Second safe book');await expect(page.locator('.sticky textarea')).toHaveValue('Second own sticky');await page.waitForTimeout(1200);await expect(page.locator('.sticky textarea')).toHaveValue('Second own sticky');await page.locator('.tab[data-tab="darlings"]').click();await expect(page.locator('.darling')).toContainText('Second own saved passage.');await expect(page.locator('.darling')).not.toContainText('First foreign saved passage.');expect(JSON.parse(await readFile(path.join(libraryPath(directory),second.bookId,'stickies.json'),'utf8'))[0].id).toBe('own');
 });
});
