import {test,expect}from '@playwright/test';import{readFile,writeFile,readdir,mkdir}from 'node:fs/promises';import path from 'node:path';import JSZip from 'jszip';import{openEditingFixture,selectText,menu,assertTexts}from './editing-helpers';import{nativeMenu,libraryPath}from './library-helpers';
const exports=[['NEO-258-A','txt','Plain Text (.txt)'],['NEO-259-A','md','Markdown (.md)'],['NEO-260-A','html','Web Page (.html)'],['NEO-261-A','docx','Word (.docx)'],['NEO-262-A','epub','EPUB (.epub)'],['NEO-263-A','pdf','PDF (.pdf)']]as const;
for(const engine of ['original','prosemirror']as const)test.describe(engine,()=>{
 for(const[id,format,label]of exports)test(`[${id}] [NEO-131-A] real ${format} export preserves edited Unicode prose and excludes annotations`,async()=>{
  const c=await openEditingFixture(engine,{chapters:['<p>Alpha <b>bold</b> <i>italic</i> café.</p><p class="scene-break">***</p><p class="poetry"><i>Verse line.</i></p><p class="ghost">SECRET_GHOST</p><p>End<span class="ph-mark" data-sid="one" contenteditable="false">⚑</span>.</p>','<p>Second chapter.</p>'],metadata:{chapterTitles:{'ch-1':'Opening','ch-2':'Closing'}}});
  try{await selectText(c.page,0,0,0);await c.page.keyboard.type('Edited ');await expect(c.page.locator('.chapter-body').first()).toContainText('Edited Alpha');
   const output=path.join(c.directory,`manuscript.${format}`);await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({savePath:output}));await nativeMenu(c.app,label);await expect.poll(async()=>{try{return(await readFile(output)).length;}catch{return 0;}}).toBeGreaterThan(30);
   const bytes=await readFile(output);let content=bytes.toString('utf8');
   if(format==='docx'){const zip=await JSZip.loadAsync(bytes);content=await zip.file('word/document.xml')!.async('string');expect(content).toContain('<w:b');expect(content).toContain('<w:i');expect(zip.file('word/styles.xml')).not.toBeNull();expect(await zip.file('word/styles.xml')!.async('string')).toContain('w:pageBreakBefore');}
   if(format==='epub'){const zip=await JSZip.loadAsync(bytes);expect(await zip.file('mimetype')!.async('string')).toBe('application/epub+zip');expect(bytes.readUInt16LE(8)).toBe(0);expect(bytes.subarray(30,38).toString()).toBe('mimetype');const names=Object.keys(zip.files);expect(names.some(x=>x.endsWith('.opf'))).toBe(true);expect(names.some(x=>x.endsWith('nav.xhtml'))).toBe(true);content=(await Promise.all(names.filter(x=>/\.xhtml$/.test(x)).map(x=>zip.file(x)!.async('string')))).join('\n');expect(content).toContain('poetry');expect(content).toMatch(/<(?:b|strong)>bold<\/(?:b|strong)>/);expect(content).toMatch(/<(?:i|em)>italic<\/(?:i|em)>/);}
   if(format==='pdf'){expect(bytes.subarray(0,5).toString()).toBe('%PDF-');const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const task=getDocument({data:new Uint8Array(bytes),useSystemFonts:true});const pdf=await task.promise;expect(pdf.numPages).toBeGreaterThan(1);content=(await Promise.all(Array.from({length:pdf.numPages},async(_,i)=>{const page=await pdf.getPage(i+1);return(await page.getTextContent()).items.map(x=>'str'in x?x.str:'').join(' ');}))).join('\n');expect(await pdf.getOutline()).not.toBeNull();await task.destroy();}
   for(const text of ['Edited Alpha','bold','italic','café','Verse line.','Second chapter.','Opening','Closing'])expect(format==='pdf'?content.toLowerCase().replace(/\s/g,''):content.toLowerCase()).toContain(format==='pdf'?text.toLowerCase().replace(/\s/g,''):text.toLowerCase());
   expect(content).not.toContain('SECRET_GHOST');expect(content).not.toContain('⚑');expect(content).not.toContain('data-sid');if(format==='md'){expect(content).toContain('**bold**');expect(content).toContain('*italic*');}if(format==='html'){expect(content).toContain('font-family');expect(content).toContain('poetry');expect(content).toContain('<b>bold</b>');}
   await assertTexts(c.page,[['Edited Alpha bold italic café.','***','Verse line.','SECRET_GHOST','End⚑.'],['Second chapter.']]);
  }finally{await c.close();}
 });
 test('[NEO-265-A] save cancellation and write failure preserve manuscript and report failure',async()=>{const c=await openEditingFixture(engine);try{await nativeMenu(c.app,'Plain Text (.txt)');expect(await readdir(c.directory)).not.toContain('manuscript.txt');await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({savePath:path.join(c.directory,'missing','manuscript.txt')}));await nativeMenu(c.app,'Plain Text (.txt)');await expect(c.page.locator('#hint')).toContainText('Couldn’t export');expect(await readFile(path.join(libraryPath(c.directory),'neo-errors.log'),'utf8')).toContain('Could not write');await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);}finally{await c.close();}});
 const imports:{ids:string[];name:string;text:string;titles:string[];paras:string[][];bold?:boolean;italic?:boolean;title?:string;author?:string;roles?:boolean}[]=[
  {ids:['NEO-248-A','NEO-250-A'],name:'Markdown.md',text:'# Opening\n\nAlpha **bold** café.\n\n***\n\n*Verse*.\n\n# Closing\n\nOmega.',titles:['Opening','Closing'],paras:[['Alpha bold café.','***','Verse.'],['Omega.']],bold:true,italic:true},
  {ids:['NEO-251-A'],name:'Numbers.txt',text:'I\n\nAlpha.\n\nII\n\nPart of me wanted to run.\n\nIII\n\nOmega.',titles:[],paras:[['Alpha.'],['Part of me wanted to run.'],['Omega.']]},
  {ids:['NEO-252-A'],name:'Refinement.md',text:'Chapter 1\n\n# Opening\n\nAlpha.\n\nChapter 2\n\n# Closing\n\nOmega.',titles:['Opening','Closing'],paras:[['Alpha.'],['Omega.']]},
  {ids:['NEO-253-A'],name:'Markers.txt',text:'Opening sentence.\n\n* * *\n\nSecond sentence.\n\n⁂\n\nThird sentence.\n\n—\n\nLast sentence.',titles:[],paras:[['Opening sentence.','***','Second sentence.','***','Third sentence.','***','Last sentence.']]},
  {ids:['NEO-255-A'],name:'Café.txt',text:'Café\n\npar Élodie Martin\n\nFirst sentence.\n\nVon Anfang an.',titles:[],paras:[['First sentence.','Von Anfang an.']],title:'Café',author:'Élodie Martin'},
  {ids:['NEO-256-A'],name:'Roles.txt',text:'Prologue\n\nBefore.\n\nChapter 1\n\nDuring.\n\nEpilogue\n\nAfter.',titles:[],paras:[['Before.'],['During.'],['After.']],roles:true},
 ];
 for(const fixture of imports)test(`${fixture.ids.map(id=>`[${id}]`).join(' ')} native import ${fixture.name} parses real file and persists chapters`,async()=>{const c=await openEditingFixture(engine);try{await c.page.locator('#back-to-shelf').click();const input=path.join(c.directory,fixture.name);await writeFile(input,fixture.text);await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({openPaths:[input]}));await c.page.locator('#import-btn').click();await expect(c.page.locator('.book')).toHaveCount(2);const tile=c.page.locator('.book').last(),bookid=(await tile.getAttribute('data-book-id'))!;const meta=JSON.parse(await readFile(path.join(libraryPath(c.directory),bookid,'book.json'),'utf8'));if(fixture.title)expect(meta.title).toBe(fixture.title);if(fixture.author)expect(meta.author).toBe(fixture.author);for(const title of fixture.titles)expect(Object.values(meta.chapterTitles)).toContain(title);if(fixture.roles){expect(meta.prologue).toBe(meta.chapterOrder[0]);expect(meta.epilogue).toBe(meta.chapterOrder.at(-1));}await tile.click();await assertTexts(c.page,fixture.paras);if(fixture.bold)await expect(c.page.locator('.chapter-body b')).toHaveText('bold');if(fixture.italic)await expect(c.page.locator('.chapter-body i')).toHaveText('Verse');expect(await readFile(input,'utf8')).toBe(fixture.text);}finally{await c.close();}});
 test('[NEO-257-A] malformed DOCX cannot prevent another selected manuscript import',async()=>{const c=await openEditingFixture(engine);try{await c.page.locator('#back-to-shelf').click();const bad=path.join(c.directory,'Broken.docx'),good=path.join(c.directory,'Good.txt');await writeFile(bad,'not a zip');await writeFile(good,'Good prose survives.');await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({openPaths:[bad,good]}));await c.page.locator('#import-btn').click();await expect(c.page.locator('.book')).toHaveCount(2);expect(await readFile(bad,'utf8')).toBe('not a zip');expect(await readFile(path.join(libraryPath(c.directory),'neo-errors.log'),'utf8')).toContain('import');await c.page.locator('.book').last().click();await assertTexts(c.page,[['Good prose survives.']]);}finally{await c.close();}});
 test('[NEO-249-A] DOCX inherited style and explicit cancellation survive real import',async()=>{
  const c=await openEditingFixture(engine);try{
   const zip=new JSZip();zip.file('word/styles.xml','<w:styles><w:style w:styleId="Emphasis"><w:rPr><w:i/></w:rPr></w:style><w:style w:styleId="Inherited"><w:basedOn w:val="Emphasis"/></w:style></w:styles>');
   zip.file('word/document.xml','<w:document><w:body><w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t>Styled story</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>Opening</w:t></w:r></w:p><w:p><w:r><w:rPr><w:rStyle w:val="Inherited"/></w:rPr><w:t>café </w:t></w:r><w:r><w:rPr><w:rStyle w:val="Inherited"/><w:i w:val="0"/><w:b/></w:rPr><w:t>bold</w:t></w:r><w:r><w:t> plain.</w:t></w:r></w:p></w:body></w:document>');
   const file=path.join(c.directory,'Styles.docx');await writeFile(file,await zip.generateAsync({type:'nodebuffer'}));await c.page.locator('#back-to-shelf').click();await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({openPaths:[file]}));await c.page.locator('#import-btn').click();await expect(c.page.locator('.book')).toHaveCount(2);await c.page.locator('.book').last().click();await assertTexts(c.page,[['café bold plain.']]);await expect(c.page.locator('.chapter-body i')).toHaveText('café ');await expect(c.page.locator('.chapter-body b')).toHaveText('bold');await expect(c.page.locator('#tp-title')).toHaveText('Styled story');
  }finally{await c.close();}
 });
 test('[NEO-254-A] excessive DOCX page breaks collapse to one intact chapter',async()=>{
  const c=await openEditingFixture(engine);try{const zip=new JSZip();zip.file('word/document.xml','<w:document><w:body>'+Array.from({length:9},(_,i)=>`<w:p><w:pPr><w:pageBreakBefore/></w:pPr><w:r><w:t>Sentence ${i} remains.</w:t></w:r></w:p>`).join('')+'</w:body></w:document>');const file=path.join(c.directory,'Confetti.docx');await writeFile(file,await zip.generateAsync({type:'nodebuffer'}));await c.page.locator('#back-to-shelf').click();await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({openPaths:[file]}));await c.page.locator('#import-btn').click();await expect(c.page.locator('.book')).toHaveCount(2);await c.page.locator('.book').last().click();await assertTexts(c.page,[Array.from({length:9},(_,i)=>`Sentence ${i} remains.`)]);}finally{await c.close();}
 });
 test('[NEO-264-A] native custom chapter title preference changes actual export headings',async()=>{const c=await openEditingFixture(engine,{chapters:['<p>Alpha.</p>','<p>Beta.</p>'],metadata:{chapterTitles:{'ch-1':'Opening'}}});try{await c.app.evaluate(({Menu,BrowserWindow})=>{const file=Menu.getApplicationMenu()!.items.find(x=>x.label==='File')!,exp=file.submenu!.items.find(x=>x.label==='Export')!,item=exp.submenu!.items.find(x=>x.id==='export-custom-chapter-titles')!;item.click(item,BrowserWindow.getAllWindows()[0],{}as any);});const output=path.join(c.directory,'titles.md');await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({savePath:output}));await nativeMenu(c.app,'Markdown (.md)');await expect.poll(async()=>{try{return await readFile(output,'utf8');}catch{return '';}}).toContain('Opening');expect(await readFile(output,'utf8')).not.toContain('Chapter 1');expect(JSON.parse(await readFile(path.join(libraryPath(c.directory),'library.json'),'utf8')).exportCustomChapterTitles).toBe(true);}finally{await c.close();}});
 test('[NEO-266-A] HTML embeds bundled Jost and EPUB uses reader serif fallback',async()=>{const c=await openEditingFixture(engine,{library:{fonts:{body:'Jost',dropcap:'none'}}});try{for(const[format,label]of[['html','Web Page (.html)'],['epub','EPUB (.epub)']]){const output=path.join(c.directory,`font.${format}`);await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({savePath:output}));await nativeMenu(c.app,label);await expect.poll(async()=>{try{return(await readFile(output)).length;}catch{return 0;}}).toBeGreaterThan(30);if(format==='html'){const html=await readFile(output,'utf8');expect(html).toContain('Jost');expect(html).toMatch(/data:font\/[^;]+;base64,/);}else{const zip=await JSZip.loadAsync(await readFile(output));const fonts=Object.keys(zip.files).filter(name=>/\.(?:woff2?|ttf|otf)$/.test(name));expect(fonts).toEqual([]);expect(await zip.file('OEBPS/style.css')!.async('string')).toContain('font-family: serif');}}}finally{await c.close();}});
 test('[NEO-267-A] email settings dialog persists address and chosen method',async()=>{const c=await openEditingFixture(engine);try{await nativeMenu(c.app,'Email Settings');await c.page.locator('.modal-backdrop:not([hidden]) input').fill('writer@example.invalid');await c.page.locator('.modal-backdrop:not([hidden]) .m-ok').click();await c.page.locator('.fr-choice[data-m="gmail"]').click();await expect(c.page.locator('#hint')).toContainText('Email settings saved');const library=JSON.parse(await readFile(path.join(libraryPath(c.directory),'library.json'),'utf8'));expect(library.emailAddress).toBe('writer@example.invalid');expect(library.emailMethod).toBe('gmail');}finally{await c.close();}});
 test('[NEO-268-A] real Gmail snapshot contains provenance hash and reveals actual PDF',async()=>{const c=await openEditingFixture(engine,{library:{emailAddress:'writer@example.invalid',emailMethod:'gmail'}});try{await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({allowEmailDraft:true}));await nativeMenu(c.app,'Email Draft to Myself');await expect(c.page.locator('#hint')).toContainText('Gmail compose opened',{timeout:20000});const effects=JSON.parse(await readFile(path.join(c.directory,'intercepted-effects.json'),'utf8'));const url=new URL(effects.find((e:{type:string})=>e.type==='external-url').payload);expect(url.hostname).toBe('mail.google.com');expect(url.searchParams.get('to')).toBe('writer@example.invalid');const {createHash}=await import('node:crypto');expect(url.searchParams.get('body')).toContain(createHash('sha256').update('Editing fixture\nAlpha beta.Gamma delta.').digest('hex'));const file=effects.find((e:{type:string})=>e.type==='reveal-file').payload;expect(file.startsWith(path.join(libraryPath(c.directory),'Exports')+path.sep)).toBe(true);expect((await readFile(file)).subarray(0,5).toString()).toBe('%PDF-');await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);}finally{await c.close();}});
 test('[NEO-269-A] cancelled email configuration and unavailable Mail preserve draft',async()=>{const c=await openEditingFixture(engine);try{await nativeMenu(c.app,'Email Draft to Myself');await c.page.locator('.modal-backdrop:not([hidden]) .m-cancel').click();expect(await readdir(libraryPath(c.directory))).not.toContain('Exports');await nativeMenu(c.app,'Email Settings');await c.page.locator('.modal-backdrop:not([hidden]) input').fill('writer@example.invalid');await c.page.locator('.modal-backdrop:not([hidden]) .m-ok').click();await c.page.locator('.fr-choice[data-m="mail"]').click();await writeFile(path.join(c.directory,'.neo-parity-host.json'),JSON.stringify({allowEmailDraft:true,mailError:true}));await nativeMenu(c.app,'Email Draft to Myself');await expect(c.page.locator('#hint')).toContainText('Mail unavailable',{timeout:20000});const effects=JSON.parse(await readFile(path.join(c.directory,'intercepted-effects.json'),'utf8'));expect(effects.some((e:{type:string})=>e.type==='mail-draft-script')).toBe(true);const file=effects.find((e:{type:string})=>e.type==='reveal-file').payload;expect((await readFile(file)).subarray(0,5).toString()).toBe('%PDF-');await assertTexts(c.page,[['Alpha beta.','Gamma delta.']]);}finally{await c.close();}});

});
