import {test,expect} from '../candidate/author-fixture';
import {writing} from '../candidate/editing-helpers';
import {persistedBook} from '../candidate/storage-probe';
test('Source characterization: native poetry Backspace merge saves NBSP and style wrappers but normalizes visible spaces on reopen',async({page})=>{
 const d=await writing(page);await d.type('Alpha beta.');await d.select(0,0,5);await d.key('Shift+Enter');await d.key('Backspace');await d.key('Backspace');await d.expectParagraphs([['Alpha\u00a0beta.']]);const title=await page.locator('#tp-title').textContent();await d.reopen();await d.expectParagraphs([['Alpha beta.']]);const saved=await persistedBook(page,title!);expect(saved.chapters[0].html).toContain('&nbsp;beta.');expect(saved.chapters[0].html).toContain('white-space: normal');await test.info().attach('source-durable-merge',{body:JSON.stringify({visible:await d.paragraphs(),html:saved.chapters[0].html}),contentType:'application/json'});
});
test('Source characterization: empty poetry structural Undo restores the class and native Redo does not replay conversion',async({page})=>{
 const d=await writing(page);await d.key('Shift+Enter');await d.key('Enter');await expect(page.locator('.chapter-body p.poetry')).toHaveCount(0);await d.undo();await expect(page.locator('.chapter-body p.poetry')).toHaveCount(1);await d.redo();await expect(page.locator('.chapter-body p.poetry')).toHaveCount(1);await d.expectParagraphs([['']]);
});

test('Source characterization: tab rename refreshes the auxiliary heading only on a later tab switch and Escape cancellation returns to shelf',async({page})=>{
 const d=await writing(page);await d.type('Retained author words.');const notes=page.locator('.tab[data-tab="notes"]');await notes.dblclick();const dialog=page.getByRole('dialog');await dialog.locator('input').fill('Research journal');await dialog.locator('input').press('Enter');await expect(dialog).toBeHidden();await expect(notes).toHaveText('Research journal');await expect(page.locator('#aux-title')).toHaveText('Notes');await page.locator('.tab[data-tab="manuscript"]').click();await notes.click();await expect(page.locator('#aux-title')).toHaveText('Research journal');await notes.dblclick();await page.getByRole('dialog').locator('input').fill('Uncommitted');await page.getByRole('dialog').locator('input').press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('#bookshelf-view')).toBeVisible();await d.selectBook('Parity '+test.info().testId);await expect(notes).toHaveText('Research journal');await d.expectParagraphs([['Retained author words.']]);
});
test('Source characterization: Replace All structural Undo belongs to a focused button and native Redo does not replay its snapshot',async({page})=>{
 const d=await writing(page);await d.type('Alpha alpha.');await d.key('Enter');await d.key('Enter');await d.key('Enter');await d.type('ALPHA tail.');const {clickReferenceMenu}=await import('./harness');await clickReferenceMenu(page,['Edit','Find & Replace']);await page.locator('#search-input').fill('alpha');await expect(page.locator('#search-count')).toHaveText('3 found');await page.locator('#replace-input').fill('Omega');await page.locator('#replace-all').click();await d.expectParagraphs([['Omega Omega.'],['Omega tail.']]);await page.locator('#replace-all').focus();await d.undo();await d.expectParagraphs([['Alpha alpha.'],['ALPHA tail.']]);await d.redo();await d.expectParagraphs([['Alpha alpha.'],['ALPHA tail.']]);
});
