import {test,expect} from '../candidate/author-fixture';
import {existingBook,type BookFixture} from '../candidate/book-fixture';
import {privateStorageRoot,persistedBook,persistedLibrary} from '../candidate/storage-probe';
import {clickReferenceMenu} from './harness';
import {readFile,writeFile,readdir,mkdir,copyFile} from 'node:fs/promises';
import path from 'node:path';
import {formatCases,basicFixture,editionFixture,inspectExport,inspectEdition,inspectChapterExport,readPDF,importFiles,sha256} from '../shared/document-io.mjs';
import type {Page} from '@playwright/test';
function fixtureRoot(page:Page){return path.resolve(privateStorageRoot(page),'../..');}
async function seeded(page:Page,fixture:BookFixture){const title=typeof fixture.metadata?.title==='string'?fixture.metadata.title:undefined;const metadata={...fixture.metadata};delete metadata.title;const c=await existingBook(page,{...fixture,metadata});if(title)await c.driver.title(title);return {...c,title:title??c.title};}
async function picker(page:Page,value:Record<string,unknown>){await writeFile(path.join(fixtureRoot(page),'.neo-parity-host.json'),JSON.stringify(value));}
async function saved(page:Page,name:string){const output=path.join(fixtureRoot(page),name);await expect.poll(()=>readFile(output).then(bytes=>bytes.length,()=>0),{timeout:30000}).toBeGreaterThan(30);const bytes=await readFile(output);await test.info().attach(name,{body:bytes,contentType:name.endsWith('.pdf')?'application/pdf':'application/octet-stream'});return bytes;}
for(const [id,format,label] of formatCases)test(`[${id}][NEO-131-A] Leafloom: actual ${format} author export preserves current rich Unicode prose and excludes notes ghosts and flags`,async({page})=>{
 const c=await seeded(page,basicFixture);await c.driver.select(0,0,0);await c.driver.type('Edited ');const before=await c.driver.paragraphs();await picker(page,{savePath:path.join(fixtureRoot(page),'author-export.'+format)});await clickReferenceMenu(page,['File','Export',label]);const bytes=await saved(page,'author-export.'+format);const evidence=await inspectExport(format,bytes);await test.info().attach('parsed-artifact',{body:JSON.stringify(evidence,null,2),contentType:'application/json'});await c.driver.expectParagraphs(before);await c.driver.shelf();const persisted=await persistedBook(page,c.title,c.id);expect(persisted.chapters[0].html).toContain('Edited Alpha');expect(persisted.stickies).toHaveLength(1);expect(persisted.chapters[0].html).toContain('café 東京.');
});
for(const [id,format,label] of [['NEO-260-B','html','Web Page (.html)'],['NEO-261-B','docx','Word (.docx)'],['NEO-262-B','epub','EPUB (.epub)']] as const)test(`[${id}] Leafloom: actual ${format} whole edition retains front body back order navigation and paragraph presentation`,async({page})=>{
 const c=await seeded(page,editionFixture);const before=await c.driver.paragraphs();await picker(page,{savePath:path.join(fixtureRoot(page),'edition.'+format)});await clickReferenceMenu(page,['File','Export',label]);const evidence=await inspectEdition(format,await saved(page,'edition.'+format));await test.info().attach('edition-structure',{body:JSON.stringify(evidence,null,2),contentType:'application/json'});await c.driver.expectParagraphs(before);await c.driver.shelf();const persisted=await persistedBook(page,c.title,c.id);expect(persisted.metadata.chapterKinds['ch-8']).toBe('about');expect(persisted.chapters[5].html).toContain('Verse indented line.');
});
test('[NEO-265-A] Leafloom: actual export picker cancellation writes no artifact and a real unwritable destination preserves manuscript',async({page})=>{
 const c=await existingBook(page),before=await c.driver.paragraphs(),root=fixtureRoot(page),files=await readdir(root);await picker(page,{});await clickReferenceMenu(page,['File','Export','Plain Text (.txt)']);await expect.poll(async()=>{const effects=JSON.parse(await readFile(path.join(root,'intercepted-effects.json'),'utf8'));return effects.some((entry:{type:string})=>entry.type==='native-save');}).toBe(true);expect((await readdir(root)).filter(name=>!files.includes(name)&&name!=='.neo-parity-host.json')).not.toContain('cancelled.txt');await picker(page,{savePath:path.join(root,'unavailable-parent','export.txt')});await clickReferenceMenu(page,['File','Export','Plain Text (.txt)']);await expect(page.locator('#hint')).toContainText('Couldn’t export');await c.driver.expectParagraphs(before);await c.driver.shelf();expect((await persistedBook(page,c.title,c.id)).chapters[0].html).toContain('Alpha beta.');
});
test('[NEO-248-A][NEO-250-A][NEO-251-A][NEO-249-B] Leafloom: actual multi-file import parses Markdown numeral chapters and inherited DOCX styles without changing source bytes',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();const files=await importFiles(),input=path.join(fixtureRoot(page),'Inputs');await mkdir(input);const paths=[];for(const file of files){const filename=path.join(input,file.name);await writeFile(filename,file.bytes);paths.push(filename);}await picker(page,{openPaths:[]});await page.locator('#import-btn').click();await expect(page.locator('.book:not(.new-book)')).toHaveCount(1);await picker(page,{openPaths:paths});await page.locator('#import-btn').click();await expect(page.locator('.book:not(.new-book)')).toHaveCount(4);const library=await persistedLibrary(page);expect(library.shelves[0].bookIds).toHaveLength(4);for(let index=0;index<files.length;index++){const file=files[index];await c.driver.selectBook(file.title);await c.driver.expectParagraphs(file.paragraphs);if(file.name==='Markdown.md'){await expect(page.locator('.chapter-body b,.chapter-body strong')).toHaveText('bold');await expect(page.locator('.chapter-body i,.chapter-body em')).toHaveText('Verse');}if(file.name==='Styles.docx'){await expect(page.locator('.chapter-body i,.chapter-body em')).toHaveText('café ');await expect(page.locator('.chapter-body b,.chapter-body strong')).toHaveText('bold');}expect(sha256(await readFile(paths[index]))).toBe(sha256(file.bytes));await c.driver.shelf();}await page.reload();await expect(page.locator('.book:not(.new-book)')).toHaveCount(4);
});
test('[NEO-257-A] Leafloom: malformed first DOCX does not prevent the later selected manuscript and preserves every input byte',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();const root=fixtureRoot(page),bad=path.join(root,'Broken.docx'),good=path.join(root,'Survivor.txt');await writeFile(bad,'not a zip');await writeFile(good,'Good café prose survives.');await picker(page,{openPaths:[bad,good]});await page.locator('#import-btn').click();await expect(page.locator('.book:not(.new-book)')).toHaveCount(2);await c.driver.selectBook('Survivor');await c.driver.expectParagraphs([['Good café prose survives.']]);expect(await readFile(bad,'utf8')).toBe('not a zip');expect(await readFile(good,'utf8')).toBe('Good café prose survives.');await c.driver.shelf();await page.reload();await expect(page.locator('.book:not(.new-book)')).toHaveCount(2);
});

for(const [id,format] of formatCases)test(`[${id}][NEO-065-A] Leafloom: actual ${format} chapter export includes only the chosen story and preserves both chapters`,async({page})=>{
 const c=await seeded(page,basicFixture);await c.driver.select(1,0,0);await c.driver.type('Only ');const before=await c.driver.paragraphs();
 if(await page.locator('#nav-pin').getAttribute('aria-pressed')!=='true'){await page.locator('#nav-hotzone').hover();await page.locator('#nav-pin').click();}
 await picker(page,{savePath:path.join(fixtureRoot(page),'one-chapter.'+format)});await page.locator('.nav-item').nth(1).locator('.n-row').click({button:'right'});await page.getByRole('menuitem',{name:'Export Chapter…',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:({txt:'Text',md:'Markdown',html:'HTML',pdf:'PDF',docx:'Word',epub:'EPUB'}[format])+` (.${format})`,exact:true}).click();
 const evidence=await inspectChapterExport(format,await saved(page,'one-chapter.'+format));await test.info().attach('chapter-scope',{body:JSON.stringify(evidence),contentType:'application/json'});await c.driver.expectParagraphs(before);await c.driver.shelf();const book=await persistedBook(page,c.title,c.id);expect(book.chapters[0].html).toContain('Alpha');expect(book.chapters[1].html).toContain('Only Second chapter.');
});
test('[NEO-121-A] Leafloom: Spanish dialogue conversion is applied by actual file import while quotes ellipsis and originals stay literal',async({page})=>{
 const c=await existingBook(page,{library:{spellLanguage:'es'}});await c.driver.shelf();const filename=path.join(fixtureRoot(page),'Dialogue.txt'),input='-Hola - dijo -.\n\n"Literal" ... -- prose.';await writeFile(filename,input);await picker(page,{openPaths:[filename]});await page.locator('#import-btn').click();await expect(page.locator('.book:not(.new-book)')).toHaveCount(2);await c.driver.selectBook('Dialogue');await c.driver.expectParagraphs([['—Hola — dijo —.','"Literal" ... -- prose.']]);expect(await readFile(filename,'utf8')).toBe(input);await c.driver.shelf();await page.reload();await c.driver.selectBook('Dialogue');await c.driver.expectParagraphs([['—Hola — dijo —.','"Literal" ... -- prose.']]);
});

test('[NEO-263-B] Leafloom: actual original literary dropcap PDF retains searchable opening prose and records native glyph geometry',async({page})=>{
 const prose='Opening bold rich words walk beside the river. The manuscript has enough prose to fill several lines beneath the two-line initial. Every word remains intact when copied or searched in the actual exported PDF.';
 const c=await seeded(page,{chapters:['<p>Opening <strong>bold rich words</strong> walk beside the river. The manuscript has enough prose to fill several lines beneath the two-line initial. Every word remains intact when copied or searched in the actual exported PDF.</p>','<p>Next chapter.</p>'],metadata:{title:'Dropcap Fixture',author:'Test'},library:{fonts:{body:'Georgia',dropcap:'literary'},language:'en'}});
 const output=path.join(fixtureRoot(page),'dropcap-source.pdf');await picker(page,{savePath:output});await clickReferenceMenu(page,['File','Export','PDF (.pdf)']);const bytes=await saved(page,'dropcap-source.pdf'),pdf=await readPDF(bytes);
 try{expect(pdf.text.replace(/\s/g,'')).toContain(prose.replace(/\s/g,''));const evidence={sha256:sha256(bytes),pages:pdf.pdf.numPages,pageSizes:pdf.pages.map(page=>page.view),items:pdf.items,fonts:{body:'Georgia',dropcap:'literary'},metadata:{title:c.title,author:'Test'},oracle:'actual original searchable copy and observed glyph geometry; no candidate geometry threshold inferred'};await test.info().attach('source-pdf-geometry',{body:JSON.stringify(evidence,null,2),contentType:'application/json'});const root=path.resolve('.leafloom/evidence');await mkdir(root,{recursive:true});const name='original-dropcap-'+Date.now();await copyFile(output,path.join(root,name+'.pdf'));await writeFile(path.join(root,name+'.json'),JSON.stringify(evidence,null,2));}finally{await pdf.close();}
});
