import {test,expect} from '../candidate/author-fixture';
import {existingBook} from '../candidate/book-fixture';
import {persistedBook,persistedLibrary} from '../candidate/storage-probe';
import {clickReferenceMenu} from './harness';
import type {Page} from '@playwright/test';
const dictionaries=[['en-US','English (US)','hello'],['en-GB','English (UK)','colour'],['en-CA','English (Canada)','colour'],['en-AU','English (Australia)','colour'],['fr','Français','bonjour'],['es','Español','hola'],['de','Deutsch','Haus'],['nl','Nederlands','huis'],['pl','Polski','dom'],['pt-BR','Português (Brasil)','não'],['ro','Română','școală'],['ru','Русский','текст'],['el','Ελληνικά','κόσμος']] as const;
async function flags(page:Page){return page.evaluate(()=>{const css=CSS as unknown as {highlights:Map<string,Set<Range>>};return [...(css.highlights.get('neo-spell')??[])].map(range=>range.toString());});}
const pass=(page:Page)=>clickReferenceMenu(page,['Edit','Spellcheck Pass']);
test('[NEO-169-A] Pinned NEO: spelling begins off and deliberate native menu pass highlights then clears actual ranges',async({page})=>{const c=await existingBook(page,{chapters:['<p>tekst qzxvplmno</p>']});await c.driver.select(0,0,0);expect(await flags(page)).toEqual([]);await pass(page);await expect.poll(()=>flags(page)).toEqual(['tekst','qzxvplmno']);await pass(page);await expect.poll(()=>flags(page)).toEqual([]);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('tekst qzxvplmno');});
for(const [code,label,word] of dictionaries)test(`[NEO-178-A] Pinned NEO: ${code} real dictionary accepts ${word} and flags nonsense with durable selection`,async({page})=>{const c=await existingBook(page,{chapters:[`<p>${word} qzxvplmno</p>`]});await c.driver.select(0,0,0);await clickReferenceMenu(page,['Edit','Spellcheck Language',label]);await expect.poll(async()=>(await persistedLibrary(page)).spellLanguage).toBe(code);await pass(page);await expect.poll(()=>flags(page)).toEqual(['qzxvplmno']);expect((await persistedBook(page,c.title)).chapters[0].html).toContain(word);});
test('[NEO-177-A] Pinned NEO: learning a real flagged word survives dictionary changes and reload through the global custom list',async({page})=>{const c=await existingBook(page,{chapters:['<p>qzxvplmno</p>']});await c.driver.select(0,0,0);await pass(page);await expect.poll(()=>flags(page)).toEqual(['qzxvplmno']);const point=await page.evaluate(()=>{const css=CSS as unknown as {highlights:Map<string,Set<Range>>};const range=[...(css.highlights.get('neo-spell')??[])][0];if(!range)throw Error('Missing actual spelling range');const box=range.getBoundingClientRect();return {x:box.x+box.width/2,y:box.y+box.height/2};});await page.mouse.click(point.x,point.y,{button:'right'});await expect(page.locator('.spell-menu')).toBeVisible();await page.locator('.spell-menu').getByRole('button',{name:'Add “qzxvplmno” to dictionary',exact:true}).click();await expect.poll(()=>flags(page)).toEqual([]);await expect.poll(async()=>(await persistedLibrary(page)).customWords).toEqual(['qzxvplmno']);await clickReferenceMenu(page,['Edit','Spellcheck Language','Français']);await expect.poll(async()=>(await persistedLibrary(page)).spellLanguage).toBe('fr');await expect.poll(()=>flags(page)).toEqual([]);await c.driver.shelf();await page.reload();await c.driver.selectBook(c.title);await c.driver.select(0,0,0);await pass(page);await expect.poll(()=>flags(page)).toEqual([]);expect((await persistedLibrary(page)).customWords).toEqual(['qzxvplmno']);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('qzxvplmno');});
