import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,access} from 'node:fs/promises';
import path from 'node:path';
import JSZip from 'jszip';
import {JSDOM} from 'jsdom';
import {readPDF,sha256} from '../shared/document-io.mjs';
const xml=text=>new JSDOM(text,{contentType:'text/xml'}).window.document;
const compact=text=>text.normalize('NFKC').replace(/\s+/g,'');
export async function inspectCollection(format,bytes,{title,passages}){
 let text;
 if(format==='pdf'){const pdf=await readPDF(bytes);try{text=pdf.text;}finally{await pdf.close();}}
 else{const zip=await JSZip.loadAsync(bytes);if(format==='docx')text=[...xml(await zip.file('word/document.xml').async('string')).getElementsByTagName('w:t')].map(el=>el.textContent).join(' ');
 else{const name=Object.keys(zip.files).find(name=>name.endsWith('.opf'));assert.ok(name);const doc=xml(await zip.file(name).async('string')),base=path.posix.dirname(name);assert.equal(doc.getElementsByTagName('dc:title')[0]?.textContent,title,'Exact actual EPUB title');const manifest=[...doc.getElementsByTagName('item')];text=(await Promise.all([...doc.getElementsByTagName('itemref')].map(async ref=>{const item=manifest.find(item=>item.getAttribute('id')===ref.getAttribute('idref'));assert.ok(item);const file=path.posix.join(base,item.getAttribute('href'));assert.ok(zip.file(file));return xml(await zip.file(file).async('string')).documentElement.textContent;}))).join('\n');}}
 const content=compact(text);assert.ok(content.includes(compact(title)),'Actual chosen collection title');let last=-1;for(const passage of passages){const at=content.indexOf(compact(passage));assert.ok(at>last,'Actual constituent order '+passage);last=at;}
 return{format,sha256:sha256(bytes),bytes:bytes.length,title,orderedPassages:passages};
}
export async function runCollectionUI({script,click,type,clear,until,fixture}){
 const artifacts=path.resolve('.leafloom/evidence/native-collection-'+Date.now());await mkdir(artifacts,{recursive:true});const evidence=[];
 const library=async()=>JSON.parse(await readFile(path.join(fixture,'library.json'),'utf8'));
 const enter=selector=>script('const el=document.querySelector(arguments[0]);if(!el)throw Error("Missing actual Enter target");el.focus();el.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",code:"Enter",keyCode:13,which:13,bubbles:true,cancelable:true}));el.dispatchEvent(new KeyboardEvent("keyup",{key:"Enter",code:"Enter",keyCode:13,which:13,bubbles:true}));return true;',[selector]);
 const saved=async id=>JSON.parse(await readFile(path.join(fixture,id,'manuscript.json'),'utf8'));
 const textClick=async(selector,label)=>{const n=await script('return Array.from(document.querySelectorAll(arguments[0])).findIndex(el=>(el.querySelector("strong")?.textContent??el.textContent).trim()===arguments[1]);',[selector,label]);assert.ok(n>=0,'Actual control '+label);await click(`${selector}:nth-of-type(${n+1})`);};
 const context=async selector=>{await script('const el=document.querySelector(arguments[0]);if(!el)throw Error("Missing context target");el.dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true,clientX:200,clientY:200}));return true;',[selector]);await until(()=>script('return !!document.querySelector(".pop-menu");'),'real author context menu');};
 const shelfCount=await script('return document.querySelectorAll(".shelf").length;');await click('#add-shelf-btn');await until(()=>script('const shelves=Array.from(document.querySelectorAll(".shelf"));return shelves.length===arguments[0]+1&&shelves.at(-1).querySelector(".shelf-label")===document.activeElement;',[shelfCount]),'actual newly created shelf focused');
 // Locate by actual shelf identity rather than template title typography.
 const shelfId=await script('return Array.from(document.querySelectorAll(".shelf")).at(-1).getAttribute("data-shelf-id");');assert.ok(shelfId);const shelfSelector=`.shelf[data-shelf-id="${shelfId}"]`;
 await clear(shelfSelector+' .shelf-label');await type(shelfSelector+' .shelf-label','Collection shelf');await enter(shelfSelector+' .shelf-label');await until(async()=>(await library()).shelves.find(s=>s.id===shelfId)?.name==='Collection shelf','durable collection shelf title');
 const passages=['First opening.','First ending.','Second opening.','Second ending.'],ids=[];
 for(let i=0;i<2;i++){await click(shelfSelector+' .new-book');await until(()=>script('return !!document.querySelector("#tp-title");'),'new book title');await clear('#tp-title');await type('#tp-title',i?'Second constituent':'First constituent');await enter('#tp-title');await until(()=>script('return !!document.querySelector(".chapter-body .ProseMirror");'),'new story body');await type('.chapter-body .ProseMirror',passages[i*2]);await enter('.chapter-body .ProseMirror');await type('.chapter-body .ProseMirror',passages[i*2+1]);await click('#back-to-shelf');await until(()=>script('return !!document.querySelector("#bookshelf-view")&&!document.querySelector("#editor-view");'),'closed shelf');await until(async()=>{const shelf=(await library()).shelves.find(s=>s.id===shelfId);return shelf?.bookIds?.length===i+1;},'durable shelf membership');const id=(await library()).shelves.find(s=>s.id===shelfId).bookIds[i];ids.push(id);await until(()=>access(path.join(fixture,id,'.writer.lock')).then(()=>false,()=>true),'durable close');assert.ok((await saved(id)).chapters.map(c=>c.html).join('').includes(passages[i*2+1]));}
 const before=await Promise.all(ids.map(saved));
 for(const bound of [false,true]){if(bound){await context(shelfSelector+' .shelf-label');await textClick('.pop-menu button','Bind shelf');await until(async()=>Boolean((await library()).shelves.find(s=>s.id===shelfId)?.binding?.bound),'actual bound collection');}
 for(const [format,label] of [['epub','EPUB'],['docx','Word (.docx)'],['pdf','PDF']]){const title=bound?'Collection shelf':'Collected é東京';await context(shelfSelector+(bound?' .bound-cover':' .shelf-label'));await textClick('.pop-menu button',bound?'Export the book…':'Export shelf as anthology…');if(!bound){await clear('.modal input');await type('.modal input',title);await textClick('.modal button','Save');}await until(()=>script('return document.querySelectorAll(".modal .fr-choice").length===3;'),'three actual publication formats');const output=path.join(fixture,(bound?'bound':'anthology')+'.'+format);await writeFile(path.join(fixture,'.leafloom-dialogs.json'),JSON.stringify({selectExportFile:[output]}));await textClick('.modal .fr-choice',label);await until(()=>readFile(output).then(b=>b.length>30,()=>false),'real collection file');const artifact=await inspectCollection(format,await readFile(output),{title,passages});await copyFile(output,path.join(artifacts,path.basename(output)));for(let i=0;i<ids.length;i++){const after=await saved(ids[i]);assert.equal(after.metadata.title,before[i].metadata.title);assert.deepEqual(after.chapters,before[i].chapters);}
 const id=bound?'NEO-045-A':'NEO-046-A';evidence.push({id,title:`[${id}] Leafloom: actual ${format} ${bound?'bound collection':'anthology'} retains chosen title and constituent order`,driverActions:['Create two actual authored books in one shelf',bound?'Bind the shelf and choose Export the book':'Choose anthology and enter Unicode title','Choose actual '+label+' and private native destination'],assertions:['Parsed file contains exact collection title','Both constituent paragraphs retain shelf order','Original author titles and rich chapters unchanged'],artifact,artifactFile:path.basename(output),qualification:'hidden WebView contextmenu/Enter event delivery and actual text input with debug private picker; physical native keys/pointer/picker unproved'});}}
 return{driver:'tauri-native-hidden',artifacts,evidence};
}
