import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';

/** Actual hidden WebView author actions; only the loopback provider and fixture key store are controlled. */
export async function runCoverArtUI({script,request,click,type,clear,until,fixture,bookId,session,offlineProvider}){
 const evidence=[];
 const disk=async()=>JSON.parse(await readFile(join(fixture,bookId,'manuscript.json'),'utf8'));
 const library=async()=>JSON.parse(await readFile(join(fixture,'library.json'),'utf8'));
 const dialog='[role="dialog"][aria-label="Cover art"]';
 const textClick=async(selector,text)=>{const index=await script('return Array.from(document.querySelectorAll(arguments[0])).findIndex(el=>(el.querySelector("strong")?.textContent??el.textContent).trim()===arguments[1]);',[selector,text]);assert.ok(index>=0,'Actual author control: '+text);await click(`${selector}:nth-of-type(${index+1})`);};
 const settings=async()=>{await click('#view-menu');await textClick('.pop-menu button','Cover Art…');await until(()=>script('return document.querySelector(arguments[0])&&document.activeElement?.id==="ca-key"',[dialog]),'cover settings focused');};
 const save=async()=>{await click(dialog+' .m-ok');await until(()=>script('return !document.querySelector(arguments[0])',[dialog]),'settings closed');};
 await click(`.book[data-book-id="${bookId}"]`);await until(()=>script('return !!document.querySelector("#editor-view")'),'existing native book');
 const before=await library();await settings();await type('#ca-key','not-a-key');await click(dialog+' .m-ok');await until(()=>script('return !!document.querySelector(arguments[0]+" [role=alert]")',[dialog]),'invalid key alert');assert.ok(await script('return !!document.querySelector(arguments[0])',[dialog]));await click(dialog+' .m-cancel');assert.deepEqual((await library()).coverArt,before.coverArt);assert.equal(offlineProvider.posts,0);evidence.push({id:'NEO-031-A',action:'invalid key then Cancel',assertions:['dialog retained with alert','actual library settings unchanged','no provider request']});
 await settings();await type('#ca-key','fixture-only-never-a-real-key');if(await script('return document.querySelector("#ca-auto").checked'))await click('#ca-auto');await click(dialog+' summary');await clear('#ca-tmodel');await type('#ca-tmodel','gpt-5-mini');await clear('#ca-imodel');await type('#ca-imodel','gpt-image-1-mini');await script('const select=document.querySelector("#ca-quality");select.value="high";select.dispatchEvent(new Event("change",{bubbles:true}));return select.value;');assert.equal(await script('return document.querySelector("#ca-quality").value'),'high');await save();await until(async()=>{const row=await library();return row.coverArt?.auto===false&&row.coverArt?.quality==='high';},'actual cover settings durability');
 await settings();assert.equal(await script('return document.querySelector("#ca-key").value'),'');assert.match(await script('return document.querySelector("#ca-note").textContent'),/saved/);await save();evidence.push({id:'NEO-031-A',action:'fixture key plus models/quality then blank-key save',assertions:['actual settings durable','key input blank on reopen','configured status remains'],credentialQualification:'debug marked-fixture memory store; native encryption is not proved',selectQualification:'hidden WebView select uses real DOM value/change event; physical native dropdown is not proved'});
 await settings();await type('#ca-key','remove');await save();await settings();await until(()=>script('return document.querySelector("#ca-note").textContent.includes("Get a key")'),'fixture key removed');await type('#ca-key','fixture-only-never-a-real-key');await save();
 await type('.chapter-body .ProseMirror',' '+Array.from({length:1000},(_,i)=>'river'+i).join(' '));await click('#back-to-shelf');await until(async()=>Number((await disk()).metadata.wordCount)>=1000,'real typed words durable');assert.equal(offlineProvider.posts,0,'automatic painting disabled');
 const tile=`.book[data-book-id="${bookId}"]`;await script('const tile=document.querySelector(arguments[0]),r=tile.getBoundingClientRect();tile.dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true,button:2,clientX:r.x+10,clientY:r.y+10}));',[tile]);await until(()=>script('return !!document.querySelector(".pop-menu")'),'actual cover context handler');await textClick('.pop-menu button','New cover');await until(()=>script('return !!document.querySelector(".option-list")'),'cover choice dialog');await textClick('.option-list button','Paint a cover from the text');await until(()=>offlineProvider.imageStarted,'loopback image request');const pending=await disk();assert.equal(pending.metadata.coverArt.status,'pending');
 await click(tile);await until(()=>script('return !!document.querySelector(".chapter-body .ProseMirror")'),'author continues during painting');await type('.chapter-body .ProseMirror',' Author continues.');await click('#back-to-shelf');await until(async()=>JSON.stringify((await disk()).chapters).includes('Author continues.'),'concurrent writing durable');offlineProvider.releaseImage();await until(async()=>(await disk()).metadata.coverArt?.status==='done','painting completion durable');const done=await disk(),file=done.metadata.coverArt.file;assert.equal(done.metadata.coverMode,'painted');const image=await readFile(join(fixture,bookId,file));assert.equal(createHash('sha256').update(image).digest('hex'),offlineProvider.imageSha256);assert.equal(offlineProvider.posts,2);await until(()=>script('return getComputedStyle(document.querySelector(arguments[0])).backgroundImage.startsWith("url(")',[tile]),'painted shelf image');const decoded=await request('/session/'+session+'/execute/async',{script:'const done=arguments[arguments.length-1],url=getComputedStyle(document.querySelector(arguments[0])).backgroundImage.slice(4,-1).replace(/^"|"$/g,""),image=new Image();image.onload=()=>done({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>done({error:true});image.src=url;',args:[tile]});assert.ok(decoded.width>0&&decoded.height>0,'Actual shelf background decodes');assert.ok(JSON.stringify(done.chapters).includes('Author continues.'));assert.ok(!JSON.stringify(done).includes('fixture-only-never-a-real-key'));evidence.push({id:'NEO-030-A',action:'actual shelf cover choice starts job while author writes',assertions:['real pending and done metadata','author prose durably retained','exact loopback image bytes','one brief and one image request','no key in manuscript']});
 return {driver:'tauri-native-hidden',provider:'controlled loopback HTTP',contextMenuQualification:'hidden WebView uses bubbling contextmenu event; physical secondary-pointer/native popup unproved',credentialStore:'marked debug fixture memory',nativeEncryptionProved:false,evidence,imageSha256:offlineProvider.imageSha256};
}
