import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,readdir,access} from 'node:fs/promises';
import path from 'node:path';
import {runCoverIOEdges} from './io-cover-edge.mjs';
import {runChapterEditionIO} from './chapter-edition-io.mjs';
import {inspectPDFLayout} from '../shared/pdf-layout.mjs';
import {Book} from '../../../packages/documents/document-contracts/src/index.ts';
import {basicFixture,editionFixture,formatCases,inspectExport,inspectEdition,inspectChapterExport,importFiles,sha256} from '../shared/document-io.mjs';

/** Copy actual closed-book files; manifests bind every companion to retained bytes. */
export async function retainBookSnapshot({fixture,artifacts,label,bookId}){
 assert.ok(!path.isAbsolute(label)&&!label.split(/[\\/]/).includes('..'),'Safe snapshot label');
 assert.ok(typeof bookId==='string'&&bookId.length>0&&!['.','..'].includes(bookId)&&!bookId.includes('/')&&!bookId.includes('\\'),'Safe book identity');
 const relative='snapshots/'+label,target=path.join(artifacts,relative);await mkdir(target,{recursive:true});const files={};
 for(const name of ['manuscript.json','reviews.json','notes.html','outline.html']){const bytes=await readFile(path.join(fixture,bookId,name));await writeFile(path.join(target,name),bytes);files[name]={sha256:sha256(bytes),bytes:bytes.length};}
 const manifest={bookId,files},bytes=Buffer.from(JSON.stringify(manifest,null,2));await writeFile(path.join(target,'manifest.json'),bytes);return{path:relative,...manifest,manifestSha256:sha256(bytes)};
}

/** Picker selections are private debug fixtures; every converter is reached through actual author UI. */
export async function runDocumentIOUI({script,request,click,type,clear,until,fixture,bookId,session,artifactOnly=false}){
 const evidence=[],folder=path.join(fixture,bookId),artifacts=path.resolve('.leafloom/evidence/native-document-io-'+Date.now());await mkdir(artifacts,{recursive:true});
 const manuscript=async()=>JSON.parse(await readFile(path.join(folder,'manuscript.json'),'utf8'));
 const library=async()=>JSON.parse(await readFile(path.join(fixture,'library.json'),'utf8'));
 const captureSnapshot=(label,id=bookId)=>retainBookSnapshot({fixture,artifacts,label,bookId:id});
 const captureInput=async(filename,label)=>{const bytes=await readFile(filename),relative='inputs/'+label;await mkdir(path.dirname(path.join(artifacts,relative)),{recursive:true});await writeFile(path.join(artifacts,relative),bytes);return{path:relative,sha256:sha256(bytes),bytes:bytes.length};};

 // Cover line wrapping and uppercase templates affect presentation, not authored metadata.
 const importedId=title=>script('return Array.from(document.querySelectorAll(".book:not(.new-book)")).find(el=>Array.from(el.querySelectorAll(".b-title .b-line")).map(line=>line.textContent).join(" ").replace(/\\s+/g," ").trim().toLocaleLowerCase()===arguments[0].toLocaleLowerCase())?.getAttribute("data-book-id");',[title]);
 const assertImportedTitle=async(id,title)=>{assert.ok(id,'Actual imported title '+title);const saved=JSON.parse(await readFile(path.join(fixture,id,'manuscript.json'),'utf8'));assert.equal(saved.metadata.title,title,'Exact durable imported author title');};

 const reload=async()=>{const origin=await script('return performance.timeOrigin;');await script('location.reload();return true;');await until(()=>script('return performance.timeOrigin!==arguments[0]&&!!document.querySelector("#bookshelf-view")&&!!document.querySelector(arguments[1]);',[origin,`.book[data-book-id="${bookId}"]`]),'new document library and seeded tile');};
 const picker=async(value)=>writeFile(path.join(fixture,'.leafloom-dialogs.json'),JSON.stringify(value));
 const textClick=async(selector,text)=>{const index=await script('return Array.from(document.querySelectorAll(arguments[0])).findIndex(el=>(el.querySelector("strong")?.textContent??el.textContent).trim()===arguments[1]);',[selector,text]);assert.ok(index>=0,'Actual author control '+text);await click(`${selector}:nth-of-type(${index+1})`);};
 const paragraphs=()=>script('return Array.from(document.querySelectorAll(".chapter-body")).map(root=>Array.from(root.querySelectorAll("p")).map(p=>p.textContent));');
 const shelf=async()=>{if(await script('return !!document.querySelector("#back-to-shelf")'))await click('#back-to-shelf');await until(()=>script('return !!document.querySelector("#bookshelf-view")&&!document.querySelector("#editor-view")'),'closed library view');await until(()=>access(path.join(folder,'.writer.lock')).then(()=>false,()=>true),'actual writer lease closed');};
 const open=async(id=bookId)=>{await until(()=>script('return !!document.querySelector(arguments[0]);',[`.book[data-book-id="${id}"]`]),'actual target book tile ready');await click(`.book[data-book-id="${id}"]`);await until(()=>script('return !!document.querySelector(".chapter-body .ProseMirror")'),'native manuscript mounted');};
 const seed=async(value)=>{await shelf();const current=await manuscript();await writeFile(path.join(folder,'manuscript.json'),JSON.stringify(Book.parse({formatVersion:'neo-lifecycle/v1',revision:current.revision,metadata:{...current.metadata,...value.metadata,stickies:value.stickies??[]},chapters:value.chapters.map((html,index)=>({id:'ch-'+(index+1),html})),darlings:[]})));await writeFile(path.join(folder,'notes.html'),value.notes??'');await writeFile(path.join(folder,'outline.html'),value.outline??'');const prefs=await library();await writeFile(path.join(fixture,'library.json'),JSON.stringify({...prefs,...value.library}));await reload();await open();};
 const exportFile=async(format,name)=>{const file=path.join(fixture,name+'.'+format);await picker({selectExportFile:[file]});await click('#export-menu');await textClick('.pop-menu button','Export '+format.toUpperCase());await until(()=>readFile(file).then(bytes=>bytes.length>30,()=>false),'actual '+format+' export receipt');const bytes=await readFile(file);await copyFile(file,path.join(artifacts,name+'.'+format));return bytes;};
 await seed(basicFixture);await script('const view=document.querySelector(".chapter-body .ProseMirror"),p=view.querySelector("p"),node=p.firstChild;view.focus({preventScroll:true});const range=document.createRange();range.setStart(node,0);range.collapse(true);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);return true;');await type('.chapter-body .ProseMirror','Edited ');await until(()=>script('return document.querySelector(".chapter-body p")?.textContent.startsWith("Edited Alpha")'),'actual newly typed prefix');const before=await paragraphs();
 for(const [id,format] of formatCases){const bytes=await exportFile(format,'author-export'),artifact=await inspectExport(format,bytes);assert.deepEqual(await paragraphs(),before,'Export never mutates live draft');const disk=await manuscript();assert.ok(disk.chapters[0].html.includes('Edited Alpha'),'Latest real UI edit included in durable snapshot');assert.ok(disk.chapters[0].html.includes('café 東京.'),'Rich author prose remains in document');assert.equal(disk.metadata.stickies.length,1,'Sticky retained');evidence.push({id,title:`[${id}][NEO-131-A] Leafloom: actual ${format} author export preserves current rich Unicode prose and excludes notes ghosts and flags`,driverActions:['Open existing native book','Type Edited at real manuscript caret','Choose Export '+format.toUpperCase(),'Supply private fixture destination through native picker provider'],assertions:['Parsed output contains current Unicode rich prose and chapter headings','Ghost/flag/note text absent from artifact','Live author document and sticky retained'],artifact});}
 await script('const view=document.querySelectorAll(".chapter-body .ProseMirror")[1],node=view.querySelector("p").firstChild;view.focus({preventScroll:true});const range=document.createRange();range.setStart(node,0);range.collapse(true);getSelection().removeAllRanges();getSelection().addRange(range);return true;');await type('.chapter-body[data-chid="ch-2"] .ProseMirror','Only ').catch(async()=>{throw new Error('Actual second chapter editable UI target unavailable');});
 await until(()=>script('return Array.from(document.querySelectorAll(".chapter-body"))[1]?.textContent.startsWith("Only Second");'),'second chapter author input');
 const scopedBefore=await paragraphs();for(const [id,format] of formatCases){const output=path.join(fixture,'one-chapter.'+format);await picker({selectExportFile:[output]});await script('const row=document.querySelectorAll(".nav-item .n-row")[1];if(!row)throw Error("Actual chapter navigation missing");row.dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true,clientX:200,clientY:200}));return true;');await until(()=>script('return !!document.querySelector(".pop-menu")'),'actual chapter menu');await textClick('.pop-menu button','Export Chapter…');await textClick('.modal button',({txt:'Text',md:'Markdown',html:'HTML',pdf:'PDF',docx:'Word',epub:'EPUB'}[format])+` (.${format})`);await until(()=>readFile(output).then(bytes=>bytes.length>30,()=>false),'real chapter output');const bytes=await readFile(output),artifact=await inspectChapterExport(format,bytes);await copyFile(output,path.join(artifacts,'one-chapter.'+format));assert.deepEqual(await paragraphs(),scopedBefore);evidence.push({id,supplementalIds:['NEO-065-A'],title:`[${id}][NEO-065-A] Leafloom: actual ${format} chapter export includes only the chosen story and preserves both chapters`,driverActions:['Type Only in actual second story','Dispatch contextmenu on real navigation row in hidden WebView','Choose Export Chapter and actual format button','Provide isolated native picker destination'],assertions:['Only selected story and source heading/title page exported','First story and annotations excluded','Both live chapter texts preserved'],artifact,qualification:'hidden WebView contextmenu delivery; physical secondary pointer unproved'});}
 await seed(editionFixture);const editionBefore=await paragraphs();for(const [id,format] of [['NEO-260-B','html'],['NEO-261-B','docx'],['NEO-262-B','epub']]){const artifact=await inspectEdition(format,await exportFile(format,'edition'));assert.deepEqual(await paragraphs(),editionBefore);evidence.push({id,title:`[${id}] Leafloom: actual ${format} whole edition retains front body back order navigation and paragraph presentation`,driverActions:['Open initial edition fixture','Choose Export '+format.toUpperCase(),'Supply actual native scoped output destination'],assertions:['Parsed artifact retains front/body/back order','TOC destinations or chapter styles are real','Paragraph alignment and poetry remain in actual resources'],artifact});}
 const pdfLayout=await inspectPDFLayout(await exportFile('pdf','edition-layout'));assert.deepEqual(await paragraphs(),editionBefore);await writeFile(path.join(artifacts,'edition-layout.json'),JSON.stringify(pdfLayout,null,2));evidence.push({id:'NEO-263-B',title:'[NEO-263-B] Leafloom: real edition PDF bookmarks TOC destinations footers and poetry geometry agree with actual pages',driverActions:['Open actual edition','Choose PDF export and scoped native destination','Parse actual PDF objects and glyph coordinates'],assertions:['Bookmark body text and Contents page/link destinations agree','Title footer suppressed and body physical page numbers match','Poetry italic glyphs and indentation plus right paragraph alignment retained'],artifact:pdfLayout});
 evidence.push(...await runChapterEditionIO({script,click,type,until,seed,exportFile,textClick,shelf,open,manuscript,paragraphs,captureSnapshot,fixture,bookId}));
 await seed(editionFixture);evidence.push(...await runCoverIOEdges({script,click,until,fixture,bookId,artifacts,shelf,open,picker,textClick,exportFile,paragraphs,manuscript,captureSnapshot}));
 await picker({selectExportFile:[null]});const cancelBefore=await paragraphs(),filesBefore=await readdir(fixture);await click('#export-menu');await textClick('.pop-menu button','Export TXT');await until(()=>readFile(path.join(fixture,'.leafloom-dialogs.json'),'utf8').then(text=>JSON.parse(text).selectExportFile.length===0),'actual cancel selection consumed');assert.deepEqual(await paragraphs(),cancelBefore);assert.deepEqual((await readdir(fixture)).filter(name=>!filesBefore.includes(name)),[],'Cancel writes no new output');evidence.push({id:'NEO-265-A',title:'[NEO-265-A] Leafloom: actual export picker cancellation writes no artifact and a real unwritable destination preserves manuscript',driverActions:['Choose Export TXT','Cancel at isolated native picker boundary'],assertions:['No file created','Visible draft unchanged'],qualification:'Debug-only marked-fixture picker cancellation reaches the real export action; physical OS picker panels remain unproved. Actual denied-write error presentation and destination preservation are independently checked by the separate NEO-265-A denied export write case in this same callback run.'});
 if(artifactOnly)return{driver:'tauri-native-hidden',checkpoint:'export-artifacts-only',pickerQualification:'debug-only marked-fixture responses; real grants/converters/files, physical native picker panels unproved',artifacts,evidence,unexecutedClauses:['multi-file import and styles','malformed-first/later-valid isolation','Spanish import-only dialogue']};
 await shelf();const imports=await importFiles(),input=path.join(fixture,'Inputs');await mkdir(input);const paths=[];for(const file of imports){const filename=path.join(input,file.name);await writeFile(filename,file.bytes);paths.push(filename);}const count=await script('return document.querySelectorAll(".book:not(.new-book)").length;');await picker({selectImportFiles:[[]]});await click('#import-btn');await until(()=>readFile(path.join(fixture,'.leafloom-dialogs.json'),'utf8').then(text=>JSON.parse(text).selectImportFiles.length===0),'actual import cancellation consumed');assert.equal(await script('return document.querySelectorAll(".book:not(.new-book)").length;'),count);await picker({selectImportFiles:[paths]});await click('#import-btn');await until(()=>script('return document.querySelectorAll(".book:not(.new-book)").length;').then(value=>value===count+3),'three actual imported books');
 const importedSnapshots=[];for(let index=0;index<imports.length;index++){const file=imports[index],id=await importedId(file.title);assert.ok(id,'Actual imported title '+file.title);await open(id);await assertImportedTitle(id,file.title);assert.deepEqual(await paragraphs(),file.paragraphs);if(file.name==='Markdown.md'){assert.equal(await script('return document.querySelector(".chapter-body b,.chapter-body strong")?.textContent;'),'bold');assert.equal(await script('return document.querySelector(".chapter-body i,.chapter-body em")?.textContent;'),'Verse');}if(file.name==='Styles.docx'){assert.equal(await script('return document.querySelector(".chapter-body i,.chapter-body em")?.textContent;'),'café ');assert.equal(await script('return document.querySelector(".chapter-body b,.chapter-body strong")?.textContent;'),'bold');}assert.equal(sha256(await readFile(paths[index])),sha256(file.bytes));await shelf();importedSnapshots.push({title:file.title,bookId:id,input:await captureInput(paths[index],file.name),snapshot:await captureSnapshot('imports/'+id,id)});}evidence.push({id:'NEO-248-A',supplementalIds:['NEO-250-A','NEO-251-A','NEO-249-B'],title:'[NEO-248-A][NEO-250-A][NEO-251-A][NEO-249-B] Leafloom: actual multi-file import parses Markdown numeral chapters and inherited DOCX styles without changing source bytes',driverActions:['Cancel actual import picker','Select actual Markdown/TXT/DOCX fixture paths','Open each resulting real book','Close and inspect unchanged inputs'],assertions:['Cancel creates no book','Three results appear in library','Source chapter/scene/emphasis/style semantics retained','Original bytes unchanged'],durableArtifacts:importedSnapshots});
 const bad=path.join(input,'Broken.docx'),good=path.join(input,'Survivor.txt');await writeFile(bad,'not a zip');await writeFile(good,'Good café prose survives.');const countBefore=await script('return document.querySelectorAll(".book:not(.new-book)").length;');await picker({selectImportFiles:[[bad,good]]});await click('#import-btn');await until(()=>script('return document.querySelectorAll(".book:not(.new-book)").length;').then(value=>value===countBefore+1),'bad first file isolates later good import');const survivor=await importedId('Survivor');assert.ok(survivor);await open(survivor);await assertImportedTitle(survivor,'Survivor');assert.deepEqual(await paragraphs(),[['Good café prose survives.']]);assert.equal(await readFile(bad,'utf8'),'not a zip');assert.equal(await readFile(good,'utf8'),'Good café prose survives.');await shelf();evidence.push({id:'NEO-257-A',title:'[NEO-257-A] Leafloom: malformed first DOCX does not prevent the later selected manuscript and preserves every input byte',driverActions:['Select malformed DOCX then valid TXT in same actual picker delivery','Open resulting survivor'],assertions:['Later valid file imports despite earlier failure','Survivor author prose exact','Both original inputs byte-identical'],durableArtifacts:{inputs:[await captureInput(bad,'Broken.docx'),await captureInput(good,'Survivor.txt')],snapshot:await captureSnapshot('malformed-survivor',survivor)}});
 const preferences=await library();await writeFile(path.join(fixture,'library.json'),JSON.stringify({...preferences,spellLanguage:'es'}));await reload();const dialogue=path.join(input,'Dialogue.txt'),dialogueInput='-Hola - dijo -.\n\n"Literal" ... -- prose.';await writeFile(dialogue,dialogueInput);await picker({selectImportFiles:[[dialogue]]});await click('#import-btn');await until(()=>importedId('Dialogue'),'actual Spanish file import');const dialogueId=await importedId('Dialogue');assert.ok(dialogueId);await open(dialogueId);await assertImportedTitle(dialogueId,'Dialogue');assert.deepEqual(await paragraphs(),[['—Hola — dijo —.','"Literal" ... -- prose.']]);assert.equal(await readFile(dialogue,'utf8'),dialogueInput);await shelf();evidence.push({id:'NEO-121-A',title:'[NEO-121-A] Leafloom: Spanish dialogue conversion is applied by actual file import while quotes ellipsis and originals stay literal',driverActions:['Persist private initial Spanish writing preference and reload','Select real text through isolated native picker','Open actual imported book'],assertions:['Dialogue dashes converted with source spaces preserved','Quotes/ellipsis/double hyphens stay literal','Input bytes unchanged'],durableArtifacts:{input:await captureInput(dialogue,'Dialogue.txt'),snapshot:await captureSnapshot('spanish-dialogue',dialogueId)}});
 return{driver:'tauri-native-hidden',pickerQualification:'debug-only marked-fixture responses; real grants/converters/files, physical native picker panels unproved',artifacts,evidence};
}
