import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook,persistedLibrary} from './storage-probe';
import type {Page} from '@playwright/test';
const reference=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference';
async function bound(page:Page){const c=await existingBook(page);await c.driver.shelf();await page.locator('.shelf-label').first().click({button:'right'});if(reference)await page.locator('.fr-choice').filter({hasText:'Bind into one book'}).click();else await page.getByRole('menuitem',{name:'Bind shelf',exact:true}).click();await expect(page.locator('.shelf')).toHaveClass(/bound/);return c;}
async function ghost(page:Page,label:string){await page.locator('.shelf').hover();await page.locator('.ghost-page').filter({has:page.locator('.pt-label').filter({hasText:new RegExp('^'+label+'$')})}).click();}
test('[NEO-037-A] Leafloom: title sheet pasted whitespace becomes one native undoable line and blank fields retain source fallbacks',async({page})=>{
 await bound(page);await page.locator('.bound-cover').click();await page.locator('.tp-t').evaluate(el=>{const data=new DataTransfer();data.setData('text/plain','Collected\n\t stories');el.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:data}));});await expect(page.locator('.tp-t')).toHaveText('Collected stories');await page.keyboard.press(process.platform==='darwin'?'Meta+z':'Control+z');await expect(page.locator('.tp-t')).toHaveText('Fixture books');await page.locator('.tp-t').fill('');await page.locator('.tp-s').fill('');await page.locator('.tp-a').fill('');await page.locator('.ps-done').click();await page.reload();await page.locator('.bound-cover').click();await expect(page.locator('.tp-t')).toHaveText('Fixture books');await expect(page.locator('.tp-s')).toHaveText('');await expect(page.locator('.tp-a')).toHaveText('Fixture Writer');await page.locator('.ps-done').click();const id=(await persistedLibrary(page)).shelves[0].bookIds[0],saved=await persistedBook(page,'Fixture books',id);expect(saved.metadata.author).toBe('Fixture Writer');expect(saved.metadata.subtitle??'').toBe('');
});
test('[NEO-038-A] Leafloom: bound Copyright starts with owner and rights paragraphs and retains edited rich text after reload',async({page})=>{
 await bound(page);await ghost(page,'Copyright');await expect(page.locator('.ps-body')).toContainText('Copyright © 2026 Fixture Writer');await expect(page.locator('.ps-body')).toContainText('All rights reserved.');await expect(page.locator('.ps-body')).toBeFocused();await page.keyboard.type(' Additional rights.');await page.locator('.ps-done').click();await page.reload();await page.locator('.page-tile.kind-copyright').click();await expect(page.locator('.ps-body')).toContainText('Additional rights.');await page.keyboard.press('Escape');const s=await persistedBook(page,'Copyright — Fixture books');expect(s.metadata.kind).toBe('copyright');expect(s.chapters[0].html).toContain('Additional rights.');expect(s.chapters[0].html).toContain('All rights reserved.');
});
for(const [kind,label,id] of [['prologue','Prologue','NEO-038-A'],['epilogue','Epilogue','NEO-039-A']] as const)test(`[${id}] Leafloom: bound ${kind} opens full manuscript at its first empty caret and persists author writing`,async({page})=>{
 const c=await bound(page);await ghost(page,label);await expect(page.locator('#editor-view')).toBeVisible();await expect(page.locator('.page-sheet')).toHaveCount(0);await expect(page.locator('.chapter-body').first()).toBeVisible();expect(await c.driver.caret()).toMatchObject({chapter:0,paragraph:0,offset:0,collapsed:true});await page.keyboard.type('First '+kind+' words.');await c.driver.shelf();await page.reload();const tile=page.locator('.page-tile.kind-'+kind);await tile.click();await expect(page.locator('.chapter-body').first()).toHaveText('First '+kind+' words.');await c.driver.shelf();const s=await persistedBook(page,label);expect(s.metadata.kind).toBe(kind);expect(s.metadata.subtitle).toBe('Fixture books');expect(s.chapters[0].html).toContain('First '+kind+' words.');const ids=(await persistedLibrary(page)).shelves[0].bookIds;expect(ids.indexOf(s.metadata.id)).toBe(kind==='prologue'?1:2);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('Alpha beta.');
});
test('[NEO-040-A] Leafloom: multiple Part seams preserve Roman order and suppress an adjacent duplicate Part affordance',async({page})=>{
 const c=await bound(page);await c.driver.newBook();await c.driver.title('Second part story');await c.driver.type('Second story.');await c.driver.shelf();await page.locator('.shelf').hover();await expect(page.locator('.part-seam')).toHaveCount(2);await page.locator('.part-seam').first().click();await expect(page.locator('.ps-label')).toHaveText('Part I');await page.locator('.ps-done').click();await page.locator('.shelf').hover();await expect(page.locator('.part-seam')).toHaveCount(1);await page.locator('.part-seam').click();await expect(page.locator('.ps-label')).toHaveText('Part II');await page.locator('.ps-done').click();await page.locator('.shelf').hover();await expect(page.locator('.part-seam')).toHaveCount(0);const ids=(await persistedLibrary(page)).shelves[0].bookIds;expect(ids).toHaveLength(5);expect(ids[2]).toBe(c.id);await page.reload();await expect(page.locator('.page-tile.kind-part')).toHaveText(['Part I','Part II']);expect((await persistedLibrary(page)).shelves[0].bookIds).toEqual(ids);
});
