import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook,persistedLibrary} from './storage-probe';
import type {Page} from '@playwright/test';
const reference=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference';
async function collection(page:Page){const c=await existingBook(page);await c.driver.shelf();await page.locator('.shelf-label').first().click({button:'right'});if(reference)await page.locator('.fr-choice').filter({hasText:'Bind into one book'}).click();else await page.getByRole('menuitem',{name:'Bind shelf',exact:true}).click();await expect(page.locator('.shelf')).toHaveClass(/bound/);return c;}
async function ghost(page:Page,label:string){await page.locator('.shelf').hover();await page.locator('.ghost-page').filter({has:page.locator('.pt-label').filter({hasText:new RegExp('^'+label+'$')})}).click();}
async function finish(page:Page){await page.locator('.ps-done').click();await expect(page.locator('.page-sheet')).toBeHidden();}
for(const [kind,label,id] of [['dedication','Dedication','NEO-038-B'],['epigraph','Epigraph','NEO-038-A'],['acknowledgments','Acknowledgments','NEO-039-A'],['about','About the Author','NEO-039-B']] as const)test(`[${id}] Leafloom: bound ${kind} ghost becomes a stationary page sheet and retains authored text after reload`,async({page})=>{
 const c=await collection(page);await ghost(page,label);await expect(page.locator('.page-sheet')).toBeVisible();await expect(page.locator('.ps-body')).toBeFocused();await expect(page.locator('.ps-body')).toHaveText('');await page.keyboard.type('Stored '+kind+' words.');await finish(page);const tile=page.locator('.page-tile.kind-'+kind);const pageId=await tile.getAttribute('data-book-id');if(!pageId)throw Error('Missing current publication page identity');await expect(tile).toHaveText(label);expect(await tile.getAttribute('draggable')).toBe('false');await page.reload();await tile.click();await expect(page.locator('.ps-body')).toHaveText('Stored '+kind+' words.');await page.keyboard.press('Escape');await expect(page.locator('.page-sheet')).toBeHidden();const saved=await persistedBook(page,label+' — Fixture books',pageId);expect(saved.metadata.kind).toBe(kind);expect(saved.chapters[0].html).toContain('Stored '+kind+' words.');expect(saved.chapters[0].html).not.toMatch(/data-attr|ProseMirror/);const library=await persistedLibrary(page);expect(library.shelves[0].bookIds.indexOf(saved.metadata.id)).toBe(kind==='dedication'||kind==='epigraph'?1:2);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('Alpha beta.');
});
test('[NEO-040-B] Leafloom: a Part seam creates a Roman-labelled stationary sheet whose optional title survives emptying and reload',async({page})=>{
 await collection(page);await page.locator('.shelf').hover();await page.locator('.part-seam').first().click();await expect(page.locator('.ps-label')).toHaveText('Part I');await expect(page.locator('.ps-body')).toBeFocused();await page.keyboard.type('Movement title.');await finish(page);const tile=page.locator('.page-tile.kind-part');const partId=await tile.getAttribute('data-book-id');if(!partId)throw Error('Missing current Part identity');await page.reload();await expect(tile).toHaveText('Part I');await tile.click();await expect(page.locator('.ps-body')).toHaveText('Movement title.');await page.locator('.ps-body').fill('');await finish(page);await page.reload();await expect(tile).toHaveText('Part I');await tile.click();await expect(page.locator('.ps-body')).toHaveText('');await finish(page);expect((await persistedBook(page,'Part — Fixture books',partId)).chapters[0].html).not.toContain('Movement title.');
});
test('[NEO-037-B] Leafloom: bound title sheet advances title subtitle and author focus and persists all fields after reload',async({page})=>{
 await collection(page);await page.locator('.bound-cover').click();await expect(page.locator('.tp-t')).toBeFocused();await page.locator('.tp-t').fill('Collected stories');await page.keyboard.press('Enter');await expect(page.locator('.tp-s')).toBeFocused();await page.keyboard.type('A subtitle');await page.keyboard.press('Enter');await expect(page.locator('.tp-a')).toBeFocused();await page.locator('.tp-a').fill('Collection Writer');await page.keyboard.press('Escape');await expect(page.locator('.page-sheet')).toBeHidden();await expect.poll(async()=>(await persistedLibrary(page)).shelves[0].name).toBe('Collected stories');await page.reload();await page.locator('.bound-cover').click();await expect(page.locator('.tp-t')).toHaveText('Collected stories');await expect(page.locator('.tp-s')).toHaveText('A subtitle');await expect(page.locator('.tp-a')).toHaveText('Collection Writer');await finish(page);const coverId=(await persistedLibrary(page)).shelves[0].bookIds[0];const cover=await persistedBook(page,'Collected stories',coverId);expect(cover.metadata.subtitle).toBe('A subtitle');expect(cover.metadata.author).toBe('Collection Writer');
});
