import {expect,type Page} from '@playwright/test';
/** Author operations over the real production UI. Fixture preparation is separate. */
export class BrowserAuthorDriver{
 readonly implementation=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'?'neo-pinned-original':'leafloom-production';readonly runtime=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'?'electron-reference':'browser';
 private bookTitle='';
 constructor(readonly page:Page){}
 async open(){if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')return;await this.page.goto(process.env.LEAFLOOM_CANDIDATE_URL??'http://localhost:5190');}
 async onboard(name='Parity Writer',pen='',style='pantser'){await expect(this.page.locator('#firstrun')).toBeVisible();await this.page.locator('#fr-name').fill(name);if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'||pen)await this.page.locator('#fr-pen').fill(pen);await this.page.locator(`[data-style="${style}"]`).click();await this.page.locator('#fr-done').click();await expect(this.page.locator('#firstrun')).toBeHidden();}
 async newBook(){await this.page.locator('.new-book').first().click();await expect(this.page.locator('#editor-view')).toBeVisible();}
 async selectBook(title:string){this.bookTitle=title;await this.page.getByRole('button',{name:new RegExp(title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i')}).and(this.page.locator('.book:not(.new-book)')).first().click();await expect(this.page.locator('#editor-view')).toBeVisible();}
 async title(value:string){this.bookTitle=value;await this.page.locator('#tp-title').fill(value);await this.page.locator('#tp-title').press('Enter');await expect(this.page.locator('.chapter-body').first()).toBeVisible();}
 async type(value:string){await this.page.keyboard.type(value);}
 async key(value:string){await this.page.keyboard.press(value);}
 async select(chapter:number,paragraph:number,from:number,to=from,toParagraph=paragraph){await expect(this.page.locator('.chapter-body').nth(chapter)).toBeVisible();await expect(this.page.locator('.chapter-body').nth(chapter).locator('p').nth(paragraph)).toBeAttached();await this.page.evaluate(({chapter,paragraph,from,to,toParagraph})=>{const root=document.querySelectorAll<HTMLElement>('.chapter-body')[chapter];(root.querySelector<HTMLElement>('[contenteditable="true"]')??root).focus();const p=root.querySelectorAll('p')[paragraph];const points=(p:Element,offset:number)=>{const walker=document.createTreeWalker(p,NodeFilter.SHOW_TEXT);let last:Node|null=null;for(let n=walker.nextNode();n;n=walker.nextNode()){last=n;if(offset<=(n.textContent?.length??0))return{node:n,offset};offset-=n.textContent?.length??0;}return{node:last??p,offset:last?(last.textContent?.length??0):0};};const a=points(p,from),b=points(root.querySelectorAll('p')[toParagraph],to),range=document.createRange();range.setStart(a.node,a.offset);range.setEnd(b.node,b.offset);const selection=getSelection()!;selection.removeAllRanges();selection.addRange(range);},{chapter,paragraph,from,to,toParagraph});}
 async caret(){return this.page.evaluate(()=>{const selection=getSelection();if(!selection?.anchorNode)return null;const element=selection.anchorNode.nodeType===Node.ELEMENT_NODE?selection.anchorNode as Element:selection.anchorNode.parentElement;const body=element?.closest('.chapter-body'),paragraph=element?.closest('p');if(!body)return null;if(!paragraph){const editor=body.querySelector('[contenteditable="true"]')??body;if(selection.anchorNode!==editor||![0,editor.childNodes.length].includes(selection.anchorOffset))return null;const paragraphs=[...body.querySelectorAll('p')],end=selection.anchorOffset===editor.childNodes.length,target=end?paragraphs.at(-1):paragraphs[0];if(!target)return null;return{chapter:[...document.querySelectorAll('.chapter-body')].indexOf(body),paragraph:paragraphs.indexOf(target),offset:end?(target.textContent?.length??0):0,collapsed:selection.isCollapsed};}const prefix=document.createRange();prefix.selectNodeContents(paragraph);prefix.setEnd(selection.anchorNode,selection.anchorOffset);return {chapter:[...document.querySelectorAll('.chapter-body')].indexOf(body),paragraph:[...body.querySelectorAll('p')].indexOf(paragraph),offset:prefix.toString().length,collapsed:selection.isCollapsed};});}
 async paragraphs(){return this.page.locator('.chapter-body').evaluateAll(roots=>roots.map(root=>[...root.querySelectorAll('p')].map(p=>p.textContent??'')));}
 async expectParagraphs(expected:string[][]){await expect.poll(()=>this.paragraphs()).toEqual(expected);}
 async undo(){await this.key(process.platform==='darwin'?'Meta+z':'Control+z');}
 async redo(){await this.key(process.platform==='darwin'?'Meta+Shift+z':'Control+Shift+z');}
 async shelf(){await this.page.locator('#back-to-shelf').click();await expect(this.page.locator('#bookshelf-view')).toBeVisible();}
 async reopen(){await this.shelf();await this.page.getByRole('button',{name:new RegExp(this.bookTitle.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i')}).and(this.page.locator('.book:not(.new-book)')).first().click();await expect(this.page.locator('.chapter-body').first()).toBeVisible();}
 async restart(){await this.page.reload();await expect(this.page.locator('#bookshelf-view')).toBeVisible();await this.page.getByRole('button',{name:new RegExp(this.bookTitle.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i')}).and(this.page.locator('.book:not(.new-book)')).first().click();await expect(this.page.locator('.chapter-body').first()).toBeVisible();}
}
