import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook} from './storage-probe';
/** Trusted Chromium input delivery, not a claim of hardware keyboard/OS IME qualification. */
for(const text of ['日本語','中文','écriture','Русский'])test(`[NEO-067-A] Leafloom: trusted Chromium composition commits ${text} once with author Undo Redo and disk reopen`,async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>']});await c.driver.select(0,0,6);await page.evaluate(()=>{const events:unknown[]=[];(window as unknown as {nativeCompositionEvents:unknown[]}).nativeCompositionEvents=events;for(const name of ['compositionstart','compositionupdate','compositionend','beforeinput','input'])document.addEventListener(name,event=>{const e=event as InputEvent;events.push({type:event.type,trusted:event.isTrusted,data:e.data,inputType:e.inputType,composing:e.isComposing,text:(event.target as HTMLElement)?.textContent});},true);});const ime=await page.context().newCDPSession(page);try{await ime.send('Input.imeSetComposition',{text:text.slice(0,1),selectionStart:1,selectionEnd:1});await ime.send('Input.imeSetComposition',{text,selectionStart:text.length,selectionEnd:text.length});await ime.send('Input.insertText',{text});}finally{await ime.detach();}await test.info().attach('native-composition-event-trace',{body:JSON.stringify(await page.evaluate(()=>(window as unknown as {nativeCompositionEvents:unknown[]}).nativeCompositionEvents),null,2),contentType:'application/json'});await c.driver.expectParagraphs([['Alpha.'+text]]);expect(await c.driver.caret()).toMatchObject({offset:6+text.length,collapsed:true});await c.driver.undo();await c.driver.expectParagraphs([['Alpha.']]);await c.driver.redo();await c.driver.expectParagraphs([['Alpha.'+text]]);await c.driver.reopen();await c.driver.expectParagraphs([['Alpha.'+text]]);expect((await persistedBook(page,c.title)).chapters[0].html.replace(/<[^>]+>/g,'')).toBe('Alpha.'+text);
});
test('[NEO-067-A] Leafloom: native composition cancellation retains the original prose and persisted content',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>']});await c.driver.select(0,0,6);const ime=await page.context().newCDPSession(page);try{await ime.send('Input.imeSetComposition',{text:'日本',selectionStart:2,selectionEnd:2});await ime.send('Input.imeSetComposition',{text:'',selectionStart:0,selectionEnd:0});}finally{await ime.detach();}await c.driver.expectParagraphs([['Alpha.']]);await c.driver.reopen();await c.driver.expectParagraphs([['Alpha.']]);
});
test('[NEO-067-D] Leafloom: trusted active-composition Enter reports isComposing and cannot split the author chapter',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p><p><br></p>']});await c.driver.select(0,1,0);await page.evaluate(()=>{const seen:unknown[]=[];(window as unknown as {compositionKeys:unknown[]}).compositionKeys=seen;document.addEventListener('keydown',event=>{if(event.key==='Enter')seen.push({trusted:event.isTrusted,composing:event.isComposing,keyCode:event.keyCode});},true);});const ime=await page.context().newCDPSession(page);try{await ime.send('Input.imeSetComposition',{text:'日',selectionStart:1,selectionEnd:1});await ime.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});await ime.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});await ime.send('Input.insertText',{text:'日本'});}finally{await ime.detach();}expect(await page.evaluate(()=>(window as unknown as {compositionKeys:unknown[]}).compositionKeys)).toEqual([{trusted:true,composing:true,keyCode:13}]);await c.driver.expectParagraphs([['Alpha.','日本']]);await c.driver.reopen();await c.driver.expectParagraphs([['Alpha.','日本']]);
});
test('[NEO-067-C] Leafloom: trusted keyCode229 Quote preserves literal apostrophe with native history and disk',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>']});await c.driver.select(0,0,6);await page.evaluate(()=>{const seen:unknown[]=[];(window as unknown as {compositionKeys:unknown[]}).compositionKeys=seen;document.addEventListener('keydown',event=>seen.push({trusted:event.isTrusted,key:event.key,keyCode:event.keyCode}),true);});const ime=await page.context().newCDPSession(page);try{await ime.send('Input.dispatchKeyEvent',{type:'keyDown',key:"'",code:'Quote',windowsVirtualKeyCode:229,nativeVirtualKeyCode:229,text:"'",unmodifiedText:"'"});await ime.send('Input.dispatchKeyEvent',{type:'keyUp',key:"'",code:'Quote',windowsVirtualKeyCode:229,nativeVirtualKeyCode:229});}finally{await ime.detach();}expect(await page.evaluate(()=>(window as unknown as {compositionKeys:unknown[]}).compositionKeys)).toEqual(expect.arrayContaining([{trusted:true,key:"'",keyCode:229}]));await c.driver.expectParagraphs([["Alpha.'"]]);await c.driver.undo();await c.driver.expectParagraphs([['Alpha.']]);await c.driver.redo();await c.driver.expectParagraphs([["Alpha.'"]]);await c.driver.reopen();await c.driver.expectParagraphs([["Alpha.'"]]);
});

test('[NEO-067-B] Leafloom: heading Enter then mouse-focused native composition retains one commit and author history',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>','<p>Beta.</p>']});
 await page.locator('.ch-title').first().click();await page.keyboard.press('Enter');
 await page.locator('.chapter-body p').first().click();await page.keyboard.press('End');
 expect(await c.driver.caret()).toMatchObject({chapter:0,paragraph:0,offset:6,collapsed:true});
 const ime=await page.context().newCDPSession(page);try{
  await ime.send('Input.imeSetComposition',{text:'日',selectionStart:1,selectionEnd:1});
  await ime.send('Input.imeSetComposition',{text:'日本語',selectionStart:3,selectionEnd:3});
  await ime.send('Input.insertText',{text:'日本語'});
 }finally{await ime.detach();}
 await c.driver.expectParagraphs([['Alpha.日本語'],['Beta.']]);expect(await c.driver.caret()).toMatchObject({offset:9,collapsed:true});
 await c.driver.undo();await c.driver.expectParagraphs([['Alpha.'],['Beta.']]);await c.driver.redo();await c.driver.expectParagraphs([['Alpha.日本語'],['Beta.']]);
 await c.driver.reopen();await c.driver.expectParagraphs([['Alpha.日本語'],['Beta.']]);expect((await persistedBook(page,c.title)).chapters[0].html.replace(/<[^>]+>/g,'')).toBe('Alpha.日本語');
});
