import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook} from './storage-probe';
test('[NEO-184-A] Leafloom: book counter includes every story kind while excluding pages, scenes, ghosts and markers',async({page})=>{
 const kinds=['copyright','dedication','epigraph','contents','prologue','part','chapter','unnumbered','epilogue','acknowledgments','about'];const chapterKinds=Object.fromEntries(kinds.map((kind,i)=>['ch-'+(i+1),kind]));const c=await existingBook(page,{chapters:kinds.map((_,i)=>`<p>One two.</p><p class="scene">***</p><p class="ghost" data-sec-id="ghost-${i}">Not real story words</p><p><span class="ph-mark" data-sid="sticky-${i}" contenteditable="false">⚑</span></p>`),metadata:{chapterKinds},stickies:kinds.map((_,i)=>({id:'sticky-'+i,chapterId:'ch-'+(i+1),text:'Marker note',resolved:false}))});await expect(page.locator('#word-counter')).toHaveText('8 words');await c.driver.select(6,0,8);await c.driver.type(' three.');await expect(page.locator('#word-counter')).toHaveText('9 words');await c.driver.shelf();expect((await persistedBook(page,c.title)).metadata.wordCount).toBe(9);
});
test('[NEO-184-A] Leafloom: Thai word boundaries follow actual browser Intl Segmenter and persist the same count',async({page})=>{
 const text='ภาษาไทยเป็นภาษาที่สวยงาม',n=await page.evaluate(text=>[...new Intl.Segmenter('th',{granularity:'word'}).segment(text)].filter(s=>s.isWordLike).length,text);expect(n).toBeGreaterThan(1);const c=await existingBook(page,{chapters:[`<p>${text}</p>`]});await expect(page.locator('#word-counter')).toHaveText(n+' words');await c.driver.shelf();expect((await persistedBook(page,c.title)).metadata.wordCount).toBe(n);
});
test('[NEO-185-A] Leafloom: counter clicks cycle book and current story with special name and numbered locator',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>One two three.</p>','<p>Four five.</p>','<p>Six seven.</p>'],metadata:{chapterKinds:{'ch-2':'prologue'},chapterTitles:{'ch-2':'Prelude'}}});await c.driver.select(0,0,0);await expect(page.locator('#word-counter')).toHaveText('7 words');await page.locator('#word-counter').click();await expect(page.locator('#word-counter')).toHaveText('ch. 1: 3 words');await expect(page.locator('#pos-counter')).toHaveText('chapter 1 of 2');await c.driver.select(1,0,0);await expect(page.locator('#word-counter')).toHaveText('Prologue: 2 words');await expect(page.locator('#pos-counter')).toHaveText('Prologue');await page.locator('#word-counter').click();await expect(page.locator('#word-counter')).toHaveText('7 words');
});
test('[NEO-186-A] Leafloom: styled prose selection reports words and collapse restores the author count mode',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>One <i>two three</i> four.</p>','<p>Five six.</p>']});await c.driver.select(0,0,4,13);await expect(page.locator('#word-counter')).toHaveText('2 selected');await c.driver.select(0,0,13);await expect(page.locator('#word-counter')).toHaveText('6 words');await page.locator('#word-counter').click();await expect(page.locator('#word-counter')).toHaveText('ch. 1: 4 words');await c.driver.select(0,0,0,18);await expect(page.locator('#word-counter')).toHaveText('4 selected');await c.driver.select(0,0,18);await expect(page.locator('#word-counter')).toHaveText('ch. 1: 4 words');
});
test('[NEO-187-A] Leafloom: real wheel scroll changes current chapter locator without moving the author caret',async({page})=>{
 const c=await existingBook(page,{chapters:[Array.from({length:30},(_,i)=>`<p>First chapter line ${i}.</p>`).join(''),Array.from({length:30},(_,i)=>`<p>Second chapter line ${i}.</p>`).join('')]});await c.driver.select(0,0,0);await expect(page.locator('#pos-counter')).toHaveText('chapter 1 of 2');const caret=await c.driver.caret();await page.locator('#paper-scroll').hover();await page.mouse.wheel(0,1800);await expect(page.locator('#pos-counter')).toHaveText('chapter 2 of 2');const nav=page.locator('.nav-item.current');await expect(nav).toHaveAttribute(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'?'data-id':'data-chid','ch-2');expect(await c.driver.caret()).toEqual(caret);
});
