import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook} from './storage-probe';
const book=(page:import('@playwright/test').Page,id:string)=>page.locator(`.book[data-book-id="${id}"]`);
async function art(page:import('@playwright/test').Page,id:string){return book(page,id).evaluate(el=>getComputedStyle(el).backgroundImage);}
test('[NEO-023-A] Leafloom: saved seeded artwork and real title-author overlay retain the same pixels after reload',async({page})=>{
 const c=await existingBook(page,{metadata:{coverSeed:'leafloom-ui-cover-seed'}});await c.driver.shelf();const tile=book(page,c.id);await expect.poll(async()=>(await tile.locator('.b-line').allTextContents()).join(' ').toUpperCase()).toBe(c.title.toUpperCase());await expect(tile.locator('.b-author')).toHaveText('Fixture Writer');await expect.poll(()=>art(page,c.id)).toContain('data:image/png');const before=await art(page,c.id);expect(await tile.locator('.b-title').evaluate(el=>el instanceof HTMLElement && el.innerText.length>0)).toBe(true);await page.reload();await expect(tile).toBeVisible();await expect.poll(()=>art(page,c.id)).toBe(before);expect((await persistedBook(page,c.title)).metadata.coverSeed).toBe('leafloom-ui-cover-seed');
});
test('[NEO-024-B] Leafloom: pointer-opened cover menu native Enter creates fresh art while title-author and seed persist after restart',async({page})=>{
 const c=await existingBook(page,{metadata:{coverSeed:'leafloom-old-ui-seed'}});await c.driver.shelf();await expect.poll(()=>art(page,c.id)).toContain('data:image/png');const old=await art(page,c.id);await book(page,c.id).click({button:'right'});const action=page.getByRole(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'?'button':'menuitem',{name:'New cover',exact:true});await action.focus();await action.press('Enter');await expect.poll(async()=>(await persistedBook(page,c.title)).metadata.coverSeed).not.toBe('leafloom-old-ui-seed');await expect.poll(()=>art(page,c.id)).not.toBe(old);const changed=await art(page,c.id),seed=(await persistedBook(page,c.title)).metadata.coverSeed;await expect.poll(async()=>(await book(page,c.id).locator('.b-line').allTextContents()).join(' ').toUpperCase()).toBe(c.title.toUpperCase());await expect(book(page,c.id).locator('.b-author')).toHaveText('Fixture Writer');await page.reload();await expect.poll(()=>art(page,c.id)).toBe(changed);expect((await persistedBook(page,c.title)).metadata.coverSeed).toBe(seed);await c.driver.selectBook(c.title);await c.driver.expectParagraphs([['Alpha beta.','Gamma delta.']]);
});
