import {test,expect} from './author-fixture';
import type {Page} from '@playwright/test';
import {existingBook} from './book-fixture';
import {persistedBook} from './storage-probe';
import {clickReferenceMenu} from '../reference/harness';
const original=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference';
const mod=process.platform==='darwin'?'Meta':'Control';
const tab=(page:Page,name:string)=>page.locator(`.tab[data-tab="${name}"]`).click();
async function dropSelected(page:Page){
 // Scoped in-app DragEvent/DataTransfer, never the global OS clipboard. Physical drag delivery is separately unproved.
 await page.evaluate(()=>{const selection=getSelection()!,range=selection.getRangeAt(0),holder=document.createElement('div');holder.append(range.cloneContents());const data=new DataTransfer();data.setData('text/plain',selection.toString());data.setData('text/html',holder.innerHTML);const element=range.startContainer.nodeType===Node.ELEMENT_NODE?range.startContainer as Element:range.startContainer.parentElement!;element.dispatchEvent(new DragEvent('dragstart',{bubbles:true,cancelable:true,dataTransfer:data}));const target=document.querySelector('.tab[data-tab="darlings"]')!;target.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:data}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));element.dispatchEvent(new DragEvent('dragend',{bubbles:true,dataTransfer:data}));});
}
const companion={notes:'<p><b>Research stays.</b></p>',metadata:{chapterNotes:{'ch-1':'Opening plan'},sectionNotes:{'ch-1':[{id:'beat',text:'Planned scene'}]}}};
async function restore(page:Page,index=0){await tab(page,'darlings');await page.locator('.darling').nth(index).getByRole('button',{name:'Restore',exact:true}).click();}
function legacyDarling(owner='ch-1',html='<p><b>Kept.</b></p><p><i>Again.</i></p>'){return{id:'kept',html,text:'Kept.\nAgain.',chapterId:owner,chapterLabel:'Chapter 1',date:Date.UTC(2026,9,1),anchorPrefix:'Alpha ',anchorSuffix:'Gamma.'};}
for(const blank of [false,true])test(`[NEO-132-A] Leafloom: in-app drag ${blank?'ignores blank selection':'cuts rich selected prose with date chapter and durable companions'}`,async({page})=>{
 const c=await existingBook(page,{...companion,chapters:[blank?'<p>Alpha   Omega.</p>':'<p>Alpha <i>beta</i> Gamma.</p>']});await c.driver.select(0,0,6,blank?8:10);await dropSelected(page);await tab(page,'darlings');await expect(page.locator('.darling')).toHaveCount(blank?0:1);await c.driver.shelf();const saved=await persistedBook(page,c.title,c.id);expect(saved.notes).toContain('Research stays.');expect(saved.metadata.chapterNotes['ch-1']).toBe('Opening plan');expect(saved.metadata.sectionNotes['ch-1']).toEqual([{id:'beat',text:'Planned scene'}]);if(blank){expect(saved.chapters[0].html).toContain('Alpha   Omega.');expect(saved.darlings).toEqual([]);}else{expect(saved.chapters[0].html).not.toContain('beta');expect(saved.darlings[0]).toMatchObject({text:'beta',chapterId:'ch-1',chapterLabel:'Chapter 1'});expect(saved.darlings[0].html).toMatch(/<(?:i|em)>beta<\/(?:i|em)>/);expect(Number.isFinite(new Date(saved.darlings[0].date).getTime())).toBe(true);}
});
test('[NEO-134-A] Leafloom: multi-paragraph Darling drag retains rich blocks and removes the empty source shell with meaningful caret',async({page})=>{
 const c=await existingBook(page,{...companion,chapters:['<p>Before.</p><p><b>Kept.</b></p><p><i>Again.</i></p><p>After.</p>']});await c.driver.select(0,1,0,6,2);await dropSelected(page);await c.driver.expectParagraphs(original?[['Before.','','After.']]:[['Before.','After.']]);if(original)test.info().annotations.push({type:'source-characterization',description:'Original removes starting empty paragraph shell but retains an empty terminal selected paragraph; Leafloom removes both empty selection shells while preserving Before/After and complete rich archive.'});expect(await c.driver.caret()).toMatchObject({chapter:0,paragraph:0,offset:7});await tab(page,'darlings');await expect(page.locator('.darling b,.darling strong')).toHaveText('Kept.');await expect(page.locator('.darling i,.darling em')).toHaveText('Again.');await c.driver.reopen();const saved=await persistedBook(page,c.title,c.id);expect(saved.darlings[0].html).toContain('Kept.');expect(saved.darlings[0].html).toContain('Again.');expect(saved.notes).toContain('Research stays.');
});
test('[NEO-135-A] Leafloom: reopened Darling uses sixty-character text context after real author edits before and after its old spot',async({page})=>{
 const prefix='0123456789'.repeat(8),suffix='abcdefghij'.repeat(8);const c=await existingBook(page,{...companion,chapters:[`<p>${prefix}<i>KEEP</i>${suffix}</p>`]});await c.driver.select(0,0,prefix.length,prefix.length+4);await c.driver.key(mod+'+Shift+d');await c.driver.reopen();let saved=await persistedBook(page,c.title,c.id);expect(saved.darlings[0].anchorPrefix).toBe(prefix.slice(-60));expect(saved.darlings[0].anchorSuffix).toBe(suffix.slice(0,60));await c.driver.select(0,0,0);await c.driver.type('Before ');await c.driver.select(0,0,7+prefix.length+suffix.length);await c.driver.type(' After');await restore(page);await c.driver.expectParagraphs([[`Before ${prefix}KEEP${suffix} After`]]);await c.driver.reopen();saved=await persistedBook(page,c.title,c.id);expect(saved.darlings).toEqual([]);expect(saved.chapters[0].html).toMatch(/<(?:i|em)>KEEP<\/(?:i|em)>/);expect(saved.notes).toContain('Research stays.');
});
test('[NEO-137-A] Leafloom: legacy block Darling restores rich paragraphs after its context host without losing surrounding prose',async({page})=>{
 const c=await existingBook(page,{...companion,chapters:['<p>Alpha Gamma.</p><p>After.</p>'],darlings:[legacyDarling()]});await restore(page);await c.driver.expectParagraphs([['Alpha Gamma.','Kept.','Again.','After.']]);await c.driver.reopen();const saved=await persistedBook(page,c.title,c.id);expect(saved.darlings).toEqual([]);expect(saved.chapters[0].html).toMatch(/<(?:b|strong)>Kept\.<\/(?:b|strong)>/);expect(saved.chapters[0].html).toMatch(/<(?:i|em)>Again\.<\/(?:i|em)>/);expect(saved.notes).toContain('Research stays.');
});
for(const missing of [false,true])test(`[NEO-138-A] Leafloom: missing Darling context restores at ${missing?'last chapter when owner is gone':'owning chapter end'} with notice and durable removal`,async({page})=>{
 const c=await existingBook(page,{...companion,chapters:['<p>Changed.</p>','<p>Later.</p>'],darlings:[legacyDarling(missing?'gone':'ch-1')]});await restore(page);await c.driver.expectParagraphs(missing?[['Changed.'],['Later.','Kept.','Again.']]:[['Changed.','Kept.','Again.'],['Later.']]);await expect(page.locator('#hint,#toast')).toContainText('Original spot is gone');await c.driver.reopen();const saved=await persistedBook(page,c.title,c.id);expect(saved.darlings).toEqual([]);expect(saved.chapters[missing?1:0].html).toContain('Kept.');expect(saved.notes).toContain('Research stays.');
});
test('[NEO-139-A] Leafloom: Delete forever acts immediately and outside-editor Undo restores the Darling and persisted companions',async({page})=>{
 const c=await existingBook(page,{...companion,darlings:[legacyDarling()]});await tab(page,'darlings');await page.locator('.darling').getByRole('button',{name:original?'Delete forever':'Delete',exact:true}).click();await expect(page.locator('.darling')).toHaveCount(0);await expect(page.locator('.modal-backdrop:visible')).toHaveCount(0);await expect.poll(async()=>(await persistedBook(page,c.title,c.id)).darlings.length).toBe(0);await c.driver.undo();await expect(page.locator('.darling')).toHaveCount(1);await c.driver.shelf();const saved=await persistedBook(page,c.title,c.id);expect(saved.darlings[0].id).toBe('kept');expect(saved.notes).toContain('Research stays.');await c.driver.selectBook(c.title);await tab(page,'darlings');await expect(page.locator('.darling b,.darling strong')).toHaveText('Kept.');
});
test('[NEO-143-A] Leafloom: newest cut precedes older rich Darling with chapter date controls and displayed-text Find',async({page})=>{
 const c=await existingBook(page,{...companion,chapters:['<p>Alpha <i>beta</i> Gamma.</p>'],darlings:[legacyDarling()]});await c.driver.select(0,0,6,10);await c.driver.key(mod+'+Shift+d');await tab(page,'darlings');await expect(page.locator('.darling')).toHaveCount(2);await expect(page.locator('.darling').first().locator('i,em')).toHaveText('beta');await expect(page.locator('.darling').first()).toContainText('Chapter 1');await expect(page.locator('.darling').first().getByRole('button',{name:'Restore',exact:true})).toBeVisible();if(original)await clickReferenceMenu(page,['Edit','Find & Replace']);else await page.keyboard.press(mod+'+f');await page.locator('#search-input').fill('beta');await expect(page.locator('#search-count')).toHaveText('1 found');await page.locator('#search-input').press('Escape');await c.driver.shelf();const saved=await persistedBook(page,c.title,c.id);expect(saved.darlings.map((d:{id:string})=>d.id)).toEqual([saved.darlings[0].id,'kept']);expect(saved.darlings[0].chapterLabel).toBe('Chapter 1');expect(Number.isFinite(new Date(saved.darlings[0].date).getTime())).toBe(true);
});
async function removeSection(page:Page,id:string){await page.locator(`.ol-section[data-sec-id="${id}"]`).click({button:'right'});if(original)await page.locator('.fr-choice').filter({hasText:'Delete section'}).click();else await page.getByRole('menuitem',{name:'Delete section',exact:true}).click();}
test('[NEO-147-A] Leafloom: repeating Outline labels keep stable IDs and exact metadata order through edits and reopen',async({page})=>{
 const sections=Array.from({length:28},(_,i)=>({id:'sec-'+i,text:'beat '+i})),c=await existingBook(page,{chapters:['<p>Alpha.</p>'],metadata:{sectionNotes:{'ch-1':sections}}});await tab(page,'outline');await expect(page.locator('.ol-section .ol-num')).toHaveText(sections.map((_,i)=>String.fromCharCode(65+i%26)));await page.locator('.ol-section[data-sec-id="sec-26"] .ol-text').fill('Revised repeated A');await c.driver.reopen();await tab(page,'outline');expect(await page.locator('.ol-section').evaluateAll(rows=>rows.map(r=>r.getAttribute('data-sec-id')))).toEqual(sections.map(s=>s.id));const saved=await persistedBook(page,c.title,c.id);expect(saved.metadata.sectionNotes['ch-1']).toEqual(sections.map((s,i)=>i===26?{...s,text:'Revised repeated A'}:s));
});
test('[NEO-149-A] Leafloom: last Outline ArrowDown clamps at line end and ArrowUp moves to previous line end',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>'],metadata:{chapterNotes:{'ch-1':'Owner'},sectionNotes:{'ch-1':[{id:'a',text:'First'},{id:'b',text:'Last beat'}]}}});await tab(page,'outline');const last=page.locator('.ol-section[data-sec-id="b"] .ol-text');await last.click();await last.press('End');await last.press('ArrowDown');await expect(last).toBeFocused();expect(await page.evaluate(()=>{const s=getSelection()!,r=document.createRange();r.selectNodeContents(document.activeElement!);r.setEnd(s.anchorNode!,s.anchorOffset);return r.toString().length;})).toBe(9);await last.press('ArrowUp');await expect(page.locator('.ol-section[data-sec-id="a"] .ol-text')).toBeFocused();expect(await page.evaluate(()=>{const s=getSelection()!,r=document.createRange();r.selectNodeContents(document.activeElement!);r.setEnd(s.anchorNode!,s.anchorOffset);return r.toString().length;})).toBe(5);await c.driver.reopen();await c.driver.expectParagraphs([['Alpha.','***','First','***','Last beat']]);
});
test('[NEO-151-A] Leafloom: Outline outdent reconciles ghosts and moves section text into a new chapter note durably',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>'],metadata:{sectionNotes:{'ch-1':[{id:'a',text:'First beat'},{id:'b',text:'Second beat'}]}}});await tab(page,'outline');await page.locator('.ol-section[data-sec-id="a"] .ol-text').click();await page.locator('.ol-chapter .ol-text').click();await tab(page,'manuscript');await expect(page.locator('p.ghost')).toHaveText(['First beat','Second beat']);await tab(page,'outline');await page.locator('.ol-section[data-sec-id="a"] .ol-text').press('Shift+Tab');await expect(page.locator('.ol-chapter .ol-text')).toHaveText(['','First beat']);await tab(page,'manuscript');await expect(page.locator('p.ghost')).toHaveText('Second beat');await expect(page.locator('p[data-sec-id="a"]')).toHaveCount(0);await c.driver.reopen();const saved=await persistedBook(page,c.title,c.id);expect(saved.metadata.chapterNotes[saved.chapters[1].id]).toBe('First beat');expect(saved.metadata.sectionNotes['ch-1']).toEqual([{id:'b',text:'Second beat'}]);
});
test('[NEO-153-A] Leafloom: Outline chapter context delete archives rich prose as a Darling and Undo restores chapter companions',async({page})=>{
 const c=await existingBook(page,{...companion,chapters:['<p><b>Alpha.</b></p><p><i>Beta.</i></p>','<p>Later.</p>']});await tab(page,'outline');await page.locator('.ol-section[data-sec-id="beat"] .ol-text').click();await page.locator('.ol-chapter .ol-text').first().click();await tab(page,'manuscript');await c.driver.expectParagraphs([['Alpha.','Beta.','***','Planned scene'],['Later.']]);await tab(page,'outline');await page.locator('.ol-chapter').first().click({button:'right'});if(original)await page.locator('.pop-menu button').filter({hasText:/^Delete$/}).click();else await page.getByRole('menuitem',{name:'Delete chapter',exact:true}).click();await tab(page,'darlings');await expect(page.locator('.darling')).toHaveCount(1);await expect(page.locator('.darling b,.darling strong')).toHaveText('Alpha.');await expect(page.locator('.darling i,.darling em')).toHaveText('Beta.');await c.driver.undo();await tab(page,'manuscript');await c.driver.expectParagraphs([['Alpha.','Beta.','***','Planned scene'],['Later.']]);await c.driver.reopen();const saved=await persistedBook(page,c.title,c.id);expect(saved.darlings).toEqual([]);expect(saved.metadata.chapterNotes['ch-1']).toBe('Opening plan');expect(saved.metadata.sectionNotes['ch-1']).toEqual([{id:'beat',text:'Planned scene'}]);expect(saved.notes).toContain('Research stays.');
});
test('[NEO-156-A] Leafloom: ghost rename and section removal preserve authored paragraph while untouched ghosts mirror remaining order',async({page})=>{
 const c=await existingBook(page,{chapters:['<p data-sec-id="a"><b>Written stays.</b></p>'],metadata:{sectionNotes:{'ch-1':[{id:'a',text:'Written plan'},{id:'b',text:'Second beat'},{id:'c',text:'Third beat'}]}}});await tab(page,'outline');await page.locator('.ol-section[data-sec-id="b"] .ol-text').fill('Revised second');await page.locator('.ol-section[data-sec-id="c"] .ol-text').click();await tab(page,'manuscript');await expect(page.locator('p.ghost')).toHaveText(['Revised second','Third beat']);await tab(page,'outline');await removeSection(page,'a');await removeSection(page,'b');await tab(page,'manuscript');await expect(page.locator('p[data-sec-id="a"]')).toHaveText('Written stays.');await expect(page.locator('p.ghost')).toHaveText('Third beat');await expect(page.locator('p[data-sec-id="b"]')).toHaveCount(0);await c.driver.reopen();const saved=await persistedBook(page,c.title,c.id);expect(saved.metadata.sectionNotes['ch-1']).toEqual([{id:'c',text:'Third beat'}]);expect(saved.chapters[0].html).toMatch(/<(?:b|strong)>Written stays\.<\/(?:b|strong)>/);
});

test('[NEO-138-A] Leafloom: missing owner in an empty manuscript creates a restorable chapter without losing rich archive',async({page})=>{
 const c=await existingBook(page,{chapters:[],darlings:[legacyDarling('gone')],notes:companion.notes});await restore(page);await c.driver.expectParagraphs(original?[['','Kept.','Again.']]:[['Kept.','Again.']]);if(original)test.info().annotations.push({type:'source-characterization',description:'Original newChapter fallback keeps its initial empty paragraph before restored blocks; candidate replaces that unused shell.'});await expect(page.locator('#hint,#toast')).toContainText('Original spot is gone');await c.driver.reopen();const saved=await persistedBook(page,c.title,c.id);expect(saved.darlings).toEqual([]);expect(saved.chapters).toHaveLength(1);expect(saved.chapters[0].html).toMatch(/<(?:b|strong)>Kept\.<\/(?:b|strong)>/);expect(saved.notes).toContain('Research stays.');
});
test('[NEO-156-A] Leafloom: outdent then indent moves a planned section to outline end and ghosts follow relative order without moving written prose',async({page})=>{
 const c=await existingBook(page,{chapters:['<p data-sec-id="a"><b>Written stays.</b></p>'],metadata:{sectionNotes:{'ch-1':[{id:'a',text:'Written plan'},{id:'b',text:'Second beat'},{id:'c',text:'Third beat'}]}}});await tab(page,'outline');await page.locator('.ol-section[data-sec-id="b"] .ol-text').click();await page.locator('.ol-chapter .ol-text').first().click();await page.locator('.ol-section[data-sec-id="b"] .ol-text').press('Shift+Tab');const newChapter=page.locator('.ol-chapter .ol-text').nth(1);await expect(newChapter).toHaveText('Second beat');await newChapter.press('Tab');await expect(page.locator('.ol-section .ol-text')).toHaveText(['Written plan','Third beat','Second beat']);await tab(page,'manuscript');await expect(page.locator('p.ghost')).toHaveText(['Third beat','Second beat']);await expect(page.locator('p[data-sec-id="a"]')).toHaveText('Written stays.');await c.driver.reopen();const saved=await persistedBook(page,c.title,c.id);expect(saved.chapters).toHaveLength(1);expect(saved.metadata.sectionNotes['ch-1'].map((s:{text:string})=>s.text)).toEqual(['Written plan','Third beat','Second beat']);expect(saved.metadata.sectionNotes['ch-1'].map((s:{id:string})=>s.id).slice(0,2)).toEqual(['a','c']);expect(saved.chapters[0].html).toMatch(/<(?:b|strong)>Written stays\.<\/(?:b|strong)>/);
});
