import {test,expect} from './author-fixture';
import {writing,markedStory} from './editing-helpers';
import {existingBook} from './book-fixture';
import {persistedBook} from './storage-probe';
const mod=process.platform==='darwin'?'Meta':'Control';
const tab=async(d:Awaited<ReturnType<typeof writing>>,name:string)=>{await d.page.locator(`.tab[data-tab="${name}"]`).click();};
test('[NEO-133-A] Leafloom: Darling keyboard cut preserves styled content and metadata on disk',async({page})=>{
 const d=await writing(page);await markedStory(d);await d.select(0,0,6,10);await d.key(mod+'+Shift+d');await d.expectParagraphs([['Alpha .','Gamma.']]);await tab(d,'darlings');await expect(page.locator('.darling')).toHaveCount(1);await expect(page.locator('.darling i,.darling em')).toHaveText('beta');await d.shelf();const saved=await persistedBook(page,'Parity '+test.info().testId);expect(saved.darlings).toHaveLength(1);expect(saved.darlings[0].text).toBe('beta');expect(saved.darlings[0].html).toMatch(/<(i|em)>beta<\/(i|em)>/);expect(Number.isFinite(Date.parse(saved.darlings[0].date))).toBe(true);expect(saved.darlings[0].chapterId).toBe(saved.chapters[0].id);expect(saved.darlings[0].chapterLabel).toBe('Chapter 1');
});
test('[NEO-133-A] Leafloom: collapsed Darling cut hints without changing text or creating an item',async({page})=>{
 const d=await writing(page);await markedStory(d);await d.select(0,0,5);await d.key(mod+'+Shift+d');await expect(page.locator('#hint')).toContainText('Select the passage first');await d.expectParagraphs([['Alpha beta.','Gamma.']]);await tab(d,'darlings');await expect(page.locator('.darling')).toHaveCount(0);
});
test('[NEO-136-A] Leafloom: unchanged styled Darling returns to its exact inline cut position and persists',async({page})=>{
 const d=await writing(page);await markedStory(d);await d.select(0,0,6,10);await d.key(mod+'+Shift+d');await d.expectParagraphs([['Alpha .','Gamma.']]);await tab(d,'darlings');await page.locator('.darling').getByRole('button',{name:'Restore',exact:true}).click();await expect(page.locator('.chapter-body').first()).toBeVisible();await d.expectParagraphs([['Alpha beta.','Gamma.']]);expect(await page.locator('.chapter-body p').first().locator('i,em').evaluateAll(nodes=>nodes.map(n=>n.textContent).join(''))).toBe('beta.');await tab(d,'darlings');await expect(page.locator('.darling')).toHaveCount(0);await tab(d,'manuscript');await d.reopen();await d.expectParagraphs([['Alpha beta.','Gamma.']]);expect(await page.locator('.chapter-body p').first().locator('i,em').evaluateAll(nodes=>nodes.map(n=>n.textContent).join(''))).toBe('beta.');
});
test('[NEO-140-A] Leafloom: Darling cut and restore share author Undo and Redo with coherent prose and list',async({page})=>{
 const d=await writing(page);await markedStory(d);await d.select(0,0,6,10);await d.key(mod+'+Shift+d');await d.expectParagraphs([['Alpha .','Gamma.']]);await d.undo();await d.expectParagraphs([['Alpha beta.','Gamma.']]);expect(await d.caret()).toMatchObject({chapter:0,paragraph:0,offset:6});await tab(d,'darlings');await expect(page.locator('.darling')).toHaveCount(0);await d.redo();await expect(page.locator('.darling')).toHaveCount(1);await page.locator('.darling').getByRole('button',{name:'Restore',exact:true}).click();await expect(page.locator('.chapter-body').first()).toBeVisible();await d.expectParagraphs([['Alpha beta.','Gamma.']]);await d.undo();await d.expectParagraphs([['Alpha .','Gamma.']]);await tab(d,'darlings');await expect(page.locator('.darling')).toHaveCount(1);await d.redo();await expect(page.locator('.darling')).toHaveCount(0);await tab(d,'manuscript');await d.expectParagraphs([['Alpha beta.','Gamma.']]);
});

test('[NEO-136-A] Leafloom: restoring an offscreen styled Darling reveals its original paragraph rather than chapter top',async({page})=>{const paragraphs=Array.from({length:90},(_,i)=>`<p>Line ${i}: Alpha <i>beta</i> ending.</p>`).join('');const c=await existingBook(page,{chapters:[paragraphs]});await c.driver.select(0,65,15,19);await c.driver.key(mod+'+Shift+d');await page.locator('.tab[data-tab="darlings"]').click();await expect(page.locator('.darling')).toHaveCount(1);await page.locator('.darling').getByRole('button',{name:'Restore',exact:true}).click();await expect(page.locator('#paper')).toBeVisible();await expect(page.locator('.chapter-body p').nth(65)).toHaveText('Line 65: Alpha beta ending.');await expect.poll(()=>page.locator('.chapter-body p').nth(65).evaluate(p=>{const r=p.getBoundingClientRect(),s=document.querySelector('#paper-scroll')!.getBoundingClientRect();return Math.abs((r.top+r.bottom)/2-(s.top+s.bottom)/2);})).toBeLessThan(40);await c.driver.shelf();expect((await persistedBook(page,c.title)).darlings).toHaveLength(0);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('<i>beta</i>');});
