import {poetryShortcut} from './editing-helpers';
import {test,expect} from './author-fixture';
import {writing,markedStory} from './editing-helpers';
import {clickReferenceMenu} from '../reference/harness';
async function poetry(d:Awaited<ReturnType<typeof writing>>){if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await clickReferenceMenu(d.page,['Format','Poetry Paragraph']);else{await d.page.locator('#format-menu').click();await d.page.getByRole('menuitemradio',{name:'Poetry',exact:true}).click();}}
test('[NEO-094-A] Leafloom: immediate double Enter Undo heals the paragraph seam with marks and author caret',async({page})=>{
 const d=await writing(page);await markedStory(d);await d.select(0,0,6);await d.key('Enter');await d.key('Enter');await d.expectParagraphs([['Alpha ','***','beta.','Gamma.']]);await d.undo();await d.expectParagraphs([['Alpha beta.','Gamma.']]);await expect(page.locator('.chapter-body p').first().locator('em,i')).toHaveText('beta.');expect(await d.caret()).toMatchObject({chapter:0,paragraph:0,offset:6});await d.reopen();await d.expectParagraphs([['Alpha beta.','Gamma.']]);
});
test('[NEO-095-A] Leafloom: successive Undo of triple Enter restores scene then original paragraph and caret',async({page})=>{
 const d=await writing(page);await markedStory(d);await d.select(0,0,6);await d.key('Enter');await d.key('Enter');await d.key('Enter');await d.expectParagraphs([['Alpha '],['beta.','Gamma.']]);await d.undo();await d.expectParagraphs([['Alpha ','***','beta.','Gamma.']]);await expect(page.locator('.chapter-body p.scene-break')).toHaveCount(1);await d.undo();await d.expectParagraphs([['Alpha beta.','Gamma.']]);expect(await d.caret()).toMatchObject({chapter:0,paragraph:0,offset:6});await expect(page.locator('.chapter-body p').first().locator('em,i')).toHaveText('beta.');
});
test('[NEO-088-A] Leafloom: chapter heading Shift Enter inserts native italic poetry before opening prose',async({page})=>{
 const d=await writing(page);await d.type('Alpha.');await page.locator('#nav-hotzone').hover();await page.locator('#nav-pin').click();await page.locator('#nav-add').click();await d.type('Beta.');await d.expectParagraphs([['Alpha.'],['Beta.']]);await page.locator('.ch-title').first().click();await d.key(poetryShortcut);await d.expectParagraphs([['','Alpha.'],['Beta.']]);await expect(page.locator('.chapter-body').first().locator('p').first()).toHaveClass(/poetry/);expect(await d.caret()).toMatchObject({chapter:0,paragraph:0,offset:0});await d.type('Verse');await expect(page.locator('.chapter-body').first().locator('p').first().locator('i,em')).toHaveText('Verse');await d.reopen();await d.expectParagraphs([['Verse','Alpha.'],['Beta.']]);
});
test('[NEO-089-A] Leafloom: Format Poetry toggles all touched paragraphs and mixed selection while preserving scene',async({page})=>{
 const d=await writing(page);await d.type('Alpha.');await d.key('Enter');await d.type('Beta.');await d.key('Enter');await d.key('Enter');await d.type('Gamma.');await d.expectParagraphs([['Alpha.','Beta.','***','Gamma.']]);await d.select(0,0,0,6,1);await poetry(d);expect(await page.locator('.chapter-body p').evaluateAll(ps=>ps.map(p=>p.classList.contains('poetry')))).toEqual([true,true,false,false]);expect(await d.caret()).toMatchObject({paragraph:0,offset:0});await d.select(0,0,0,6,1);await poetry(d);expect(await page.locator('.chapter-body p').evaluateAll(ps=>ps.map(p=>p.classList.contains('poetry')))).toEqual([false,false,false,false]);await d.select(0,0,0,6);await poetry(d);await d.select(0,0,0,6,3);await poetry(d);expect(await page.locator('.chapter-body p').evaluateAll(ps=>ps.map(p=>p.classList.contains('poetry')))).toEqual([true,true,false,true]);expect(await d.caret()).toMatchObject({paragraph:0,offset:0});await d.expectParagraphs([['Alpha.','Beta.','***','Gamma.']]);
});
