import {poetryShortcut} from './editing-helpers';
import {test,expect} from './author-fixture';
import type {Page} from '@playwright/test';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {existingBook} from './book-fixture';
import {persistedBook,persistedLibrary,privateStorageRoot} from './storage-probe';
import {focusHistoryChrome} from './history-chrome';
import {clickReferenceMenu} from '../reference/harness';
import {Reviews} from '../../../packages/reviews/review-contracts/src/index';
const source=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference',mod=process.platform==='darwin'?'Meta':'Control';
const tab=(p:Page,k:string)=>p.locator(`.tab[data-tab="${k}"]`).click();
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
async function durable(page:Page,title:string,id:string){
 const saved=await persistedBook(page,title,id),outline=await readFile(path.join(saved.directory,'outline.html'),'utf8');
 const ownedKeys=['title','subtitle','author','chapterKinds','chapterTitles','chapterNotes','sectionNotes','tabNames'];
 const metadata=Object.fromEntries(ownedKeys.map(k=>[k,saved.metadata[k]??null]));
 if(!source){const raw=await readFile(path.join(saved.directory,'manuscript.json'),'utf8'),book=JSON.parse(raw),reviews=Reviews.parse(JSON.parse(await readFile(path.join(saved.directory,'reviews.json'),'utf8')));expect(reviews.bookId).toBe(id);expect(reviews.version).toBe(book.version);const notes=await readFile(path.join(saved.directory,'notes.html'),'utf8');expect(notes).toBe(saved.notes);await test.info().attach('actual-four-file-receipt',{body:JSON.stringify({bookId:id,version:book.version,sha256:{manuscript:hash(raw),reviews:hash(await readFile(path.join(saved.directory,'reviews.json'),'utf8')),notes:hash(notes),outline:hash(outline)}}),contentType:'application/json'});}
 return{metadata,chapters:saved.chapters.map((c:{id:string;html:string})=>({id:c.id,html:c.html})),darlings:saved.darlings,stickies:saved.stickies,notes:saved.notes,outline};
}
async function nav(page:Page,index:number){if((await page.locator('#nav-pin').getAttribute('aria-pressed'))!=='true'){await page.locator('#nav-hotzone').hover();await page.locator('#nav-pin').click();}await page.locator('.nav-item .n-row').nth(index).click({button:'right'});}
async function choice(page:Page,label:string){await page.getByRole('menuitem',{name:label,exact:true}).click();}
for(const action of ['kind','delete','reorder','poetry','darling-cut','darling-restore','replace-all'] as const)test(`[NEO-096-A] Leafloom: ${action} Undo restores all owned chapter metadata rich prose and auxiliary files`,async({page})=>{
 const c=await existingBook(page,{chapters:['<p><b>Alpha</b> <span class="ph-mark" data-sid="flag" contenteditable="false">⚑</span> beta.</p><p class="scene-break" data-sec-brk="plan">***</p><p class="ghost" data-sec-id="plan">Planned scene</p>','<p><i>Gamma delta.</i></p>','<p>Later.</p>'],metadata:{subtitle:'Owned subtitle',chapterKinds:{'ch-2':'unnumbered'},chapterTitles:{'ch-1':'Opening','ch-2':'Middle','ch-3':'Ending'},chapterNotes:{'ch-1':'Owner note'},sectionNotes:{'ch-1':[{id:'plan',text:'Planned scene'}]}},notes:'<p><b>Research</b> and <i>records.</i></p>',stickies:[{id:'flag',chapterId:'ch-1',text:'Keep this note',resolved:false}],darlings:[{id:'kept',chapterId:'ch-1',chapterLabel:'Chapter 1',date:'2026-10-01T10:00:00Z',html:'<i>Saved line.</i>',text:'Saved line.',anchorPrefix:'Alpha',anchorSuffix:' ⚑ beta.'}]});
 // Establish a real complete save then reopen; initial disk preparation is not the durable receipt.
 await c.driver.select(0,0,0);await c.driver.type('X');await c.driver.undo();await c.driver.reopen();await c.driver.shelf();const before=await durable(page,c.title,c.id);await c.driver.selectBook(c.title);
 if(action==='kind'){await nav(page,0);await page.getByRole('menuitemradio',{name:'Part',exact:true}).click();}
 if(action==='delete'){await nav(page,0);await choice(page,'Delete');}
 if(action==='reorder'){await page.locator('#nav-hotzone').hover();if((await page.locator('#nav-pin').getAttribute('aria-pressed'))!=='true')await page.locator('#nav-pin').click();const rows=page.locator('.nav-item .n-row'),a=await rows.nth(2).boundingBox(),b=await page.locator('.nav-item').first().boundingBox();if(!a||!b)throw Error('Actual drag rows missing');await page.mouse.move(a.x+30,a.y+a.height/2);await page.mouse.down();await page.mouse.move(a.x+42,a.y+a.height/2+5,{steps:3});await page.mouse.move(b.x+30,b.y+b.height*.2,{steps:12});await page.mouse.move(b.x+31,b.y+b.height*.2);await expect(page.locator('.nav-drop-ind')).toBeVisible();await page.mouse.up();}
 if(action==='poetry'){await c.driver.select(1,0,5);await page.keyboard.press(poetryShortcut);}
 if(action==='darling-cut'){await c.driver.select(1,0,0,5);await c.driver.key(mod+'+Shift+d');}
 if(action==='darling-restore'){await tab(page,'darlings');await page.locator('.darling').getByRole('button',{name:'Restore',exact:true}).click();}
 if(action==='replace-all'){if(source)await clickReferenceMenu(page,['Edit','Find & Replace']);else await page.keyboard.press(mod+'+f');await page.locator('#search-input').fill('Alpha');await expect(page.locator('#search-count')).toHaveText('1 found');await page.locator('#replace-input').fill('Omega');await page.locator('#replace-all').click();}
 await expect.poll(()=>durable(page,c.title,c.id)).not.toEqual(before);
 await focusHistoryChrome(page);await c.driver.undo();await c.driver.shelf();expect(await durable(page,c.title,c.id)).toEqual(before);await c.driver.selectBook(c.title);await c.driver.shelf();expect(await durable(page,c.title,c.id)).toEqual(before);
});
async function coverGoal(page:Page,id:string,value:string,cancel=false){await page.locator(`.book[data-book-id="${id}"]`).click({button:'right'});if(source)await page.locator('.fr-choice').filter({hasText:'Set word goal…'}).click();else await choice(page,'Set word goal…');const input=page.locator('.modal-backdrop:visible input');await input.fill(value);if(cancel)await page.locator('.modal-backdrop:visible').getByRole('button',{name:'Cancel',exact:true}).click();else await input.press('Enter');await expect(input).toHaveCount(0);}
test('[NEO-188-B] Leafloom: cancelled lower cover goal preserves old progress then confirmed goal clamps and clearing persists',async({page})=>{
 const words=Array.from({length:20},(_,i)=>'word'+i).join(' '),c=await existingBook(page,{chapters:[`<p>${words}</p>`],metadata:{wordCount:20}});await c.driver.shelf();const tile=page.locator(`.book[data-book-id="${c.id}"]`);await coverGoal(page,c.id,'100');await expect.poll(async()=>(await persistedBook(page,c.title,c.id)).metadata.wordGoal).toBe(100);expect(await tile.locator('.b-progress > div').evaluate(e=>(e as HTMLElement).style.width)).toBe('20%');await coverGoal(page,c.id,'10',true);expect((await persistedBook(page,c.title,c.id)).metadata.wordGoal).toBe(100);expect(await tile.locator('.b-progress > div').evaluate(e=>(e as HTMLElement).style.width)).toBe('20%');await coverGoal(page,c.id,'10');await expect.poll(async()=>(await persistedBook(page,c.title,c.id)).metadata.wordGoal).toBe(10);await expect.poll(()=>tile.locator('.b-progress > div').evaluate(e=>(e as HTMLElement).style.width)).toBe('100%');await c.driver.selectBook(c.title);await page.locator('#goal-counter').click();await expect(page.locator('.stats-nums .big').nth(2)).toHaveText('100%');await page.getByRole('button',{name:'Done',exact:true}).click();await c.driver.shelf();await coverGoal(page,c.id,'');await expect(tile.locator('.b-progress')).toBeHidden();await page.reload();await expect(tile.locator('.b-progress')).toBeHidden();expect((await persistedBook(page,c.title,c.id)).metadata.wordGoal||0).toBe(0);
});
test('[NEO-191-B] Leafloom: negative writing days clamp bars at zero while missing days and cumulative history persist',async({page})=>{
 await page.clock.setFixedTime(new Date('2026-10-02T12:00:00+01:00'));const dailyCounts={'2026-09-03':{start:10,end:20},'2026-10-01':{start:20,end:15},'2026-10-02':{start:15,end:17}},c=await existingBook(page,{chapters:[`<p>${Array.from({length:17},(_,i)=>'word'+i).join(' ')}</p>`],metadata:{wordCount:17,dailyCounts,wordGoal:50},library:{dailyGoal:10}});await page.locator('#goal-counter').click();const chart=page.locator('#stats-chart');await expect(chart.locator('rect')).toHaveCount(30);expect(await chart.locator('rect').evaluateAll(nodes=>nodes.map(n=>Number(n.getAttribute('height'))))).toEqual([90,...Array(28).fill(0),18]);await expect(chart.locator('line')).toHaveCount(1);const coordinates=(await chart.locator('path').getAttribute('d'))!.split(/\s+/);expect(coordinates).toHaveLength(30);await page.getByRole('button',{name:'Done',exact:true}).click();await c.driver.shelf();expect((await persistedBook(page,c.title,c.id)).metadata.dailyCounts).toEqual(dailyCounts);expect((await persistedLibrary(page)).dailyGoal).toBe(10);await c.driver.selectBook(c.title);await page.locator('#goal-counter').click();expect(await chart.locator('path').getAttribute('d')).toBe(coordinates.join(' '));
});
test('[NEO-259-B] Leafloom: actual saved rich Markdown edition escapes title and retains one Part heading poetry and front body back order',async({page})=>{
 const title='A [Book] *Beyond*',c=await existingBook(page,{chapters:['<p>Copyright rights.</p>','<p>For our readers.</p>','<p>Movement One</p><p>Part opening.</p>','<p><b>Bold</b> and <i>italic</i>.</p><p class="poetry"><i>Verse line.</i></p><p class="ghost">SECRET_GHOST</p>','<p>Closing biography.</p>'],metadata:{author:'Élodie Writer',subtitle:'A [Small] *Edition*',chapterKinds:{'ch-1':'copyright','ch-2':'dedication','ch-3':'part','ch-5':'about'},chapterTitles:{'ch-3':'Movement One','ch-4':'Opening'}}});await c.driver.title(title);await c.driver.select(3,0,0);await c.driver.type('Edited ');await c.driver.shelf();const baseline=await persistedBook(page,title,c.id);await c.driver.selectBook(title);const live=await c.driver.paragraphs(),destination=path.join(source?path.resolve(privateStorageRoot(page),'../..'):privateStorageRoot(page),'edition-md-'+test.info().testId+'.md');
 if(source){await writeFile(path.join(path.dirname(destination),'.neo-parity-host.json'),JSON.stringify({savePath:destination}));await clickReferenceMenu(page,['File','Export','Markdown (.md)']);}
 else{const origin=new URL(page.url()).origin;const reply=await page.request.post(origin+'/__leafloom/host',{headers:{origin},data:{method:'exportBook',payload:{bookId:c.id,format:'md',destination}}});expect((await reply.json()).ok).toBe(true);test.info().annotations.push({type:'portable-host-artifact',description:'Actual fixed validated development host renderer after author UI save; does not exercise a native save picker.'});}
 await expect.poll(()=>readFile(destination,'utf8').then(s=>s.length,()=>0)).toBeGreaterThan(30);const md=await readFile(destination,'utf8');await test.info().attach('actual-edition.md',{body:Buffer.from(md),contentType:'text/markdown'});expect(md).toContain('A \\[Book\\] \\*Beyond\\*');expect(md).toContain('*A \\[Small\\] \\*Edition\\**');expect(md).toContain('**by Élodie Writer**');expect(md).not.toMatch(/^##\s*$/m);expect((md.match(/^#+.*Movement One/gm)||[])).toHaveLength(1);expect(md).toMatch(/^>.*Verse line\./m);expect(md).toContain('**Edited Bold**');expect(md).toContain('*italic*');expect(md).toContain('Edited ');expect(md).not.toContain('SECRET_GHOST');let at=-1;for(const text of ['Copyright rights.','For our readers.','Movement One','Edited','Verse line.','Closing biography.']){const next=md.indexOf(text);expect(next).toBeGreaterThan(at);at=next;}await c.driver.expectParagraphs(live);await c.driver.shelf();expect((await persistedBook(page,title,c.id)).chapters).toEqual(baseline.chapters);
});
