import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {clickReferenceMenu,referenceVersion} from '../reference/harness';
import type {Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const mod=process.platform==='darwin'?'Meta':'Control';
async function inside(page:Page,selector:string){await expect.poll(()=>page.locator(selector).evaluate(el=>el.contains(document.activeElement))).toBe(true);}
const fixture={chapters:['<p>Alpha.</p>','<p>Beta.</p>','<p>Gamma.</p>'],stickies:[{id:'sticky-one',chapterId:'ch-1',text:'Remember this',resolved:false}]};
test('[NEO-279-A] Leafloom: F6 and Ctrl Tab cycle actual page chapters stickies and bottom then restore native caret',async({page})=>{
 const c=await existingBook(page,fixture);await c.driver.select(0,0,5);for(const [key,region] of [['F6','#nav-pane'],['Control+Tab','#side-pane'],['F6','#bottombar'],['Control+Tab','#paper-scroll']]){await page.keyboard.press(key);await inside(page,region);}expect(await c.driver.caret()).toMatchObject({chapter:0,paragraph:0,offset:5});await c.driver.expectParagraphs([['Alpha.'],['Beta.'],['Gamma.']]);
});
test('[NEO-279-B] Leafloom: reverse region cycle restores manuscript caret and alternates shelf identity and cover',async({page})=>{
 const c=await existingBook(page,fixture);await c.driver.select(0,0,5);for(const [key,region] of [['Shift+F6','#bottombar'],['Control+Shift+Tab','#side-pane'],['Control+Shift+Tab','#nav-pane'],['Control+Shift+Tab','#paper-scroll']]){await page.keyboard.press(key);await inside(page,region);}expect(await c.driver.caret()).toMatchObject({chapter:0,paragraph:0,offset:5});await c.driver.shelf();await page.locator('.book:not(.new-book)').first().focus();await page.keyboard.press('Shift+F6');await expect(page.locator('#author-chip')).toBeFocused();await page.keyboard.press('Control+Shift+Tab');await inside(page,'#shelves');
});
test('[NEO-280-A] Leafloom: Escape from keyboard-open chapter pane restores author selection and closes the unpinned pane',async({page})=>{
 const c=await existingBook(page,fixture);await c.driver.select(0,0,5);await page.keyboard.press('F6');await inside(page,'#nav-pane');await page.mouse.move(550,30);await page.keyboard.press('Escape');await inside(page,'#paper-scroll');expect(await c.driver.caret()).toMatchObject({chapter:0,paragraph:0,offset:5});await expect.poll(()=>page.locator('#nav-pane').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThan(1);await expect(page.locator('#editor-view')).toBeVisible();
});
test('[NEO-281-A] Leafloom: tab arrows wrap focus without activation until actual Enter or Space',async({page})=>{
 const c=await existingBook(page,fixture);await c.driver.select(0,0,5);await page.keyboard.press('Shift+F6');const manuscript=page.locator('.tab[data-tab="manuscript"]'),notes=page.locator('.tab[data-tab="notes"]'),darlings=page.locator('.tab[data-tab="darlings"]');await expect(manuscript).toBeFocused();await page.keyboard.press('ArrowRight');await expect(notes).toBeFocused();await expect(manuscript).toHaveAttribute('aria-selected','true');await expect(notes).toHaveAttribute('aria-selected','false');await page.keyboard.press('Space');await expect(notes).toHaveAttribute('aria-selected','true');await inside(page,'#paper-scroll');await page.keyboard.press('Shift+F6');await expect(notes).toBeFocused();await page.keyboard.press('ArrowLeft');await expect(manuscript).toBeFocused();await expect(notes).toHaveAttribute('aria-selected','true');await page.keyboard.press('Enter');await expect(manuscript).toHaveAttribute('aria-selected','true');await inside(page,'#paper-scroll');await page.keyboard.press('Shift+F6');await expect(manuscript).toBeFocused();await page.keyboard.press('ArrowLeft');await expect(darlings).toBeFocused();await expect(manuscript).toHaveAttribute('aria-selected','true');await page.keyboard.press('Enter');await expect(darlings).toHaveAttribute('aria-selected','true');
});
test('[NEO-282-B] Leafloom: chapter arrows clamp and Enter moves the native author caret into the chosen story',async({page})=>{
 const c=await existingBook(page,fixture);await c.driver.select(0,0,5);await page.keyboard.press('F6');await inside(page,'#nav-pane');const row=()=>page.evaluate(()=>{const el=document.activeElement?.closest('.nav-item');return el?.getAttribute('data-id')??el?.getAttribute('data-chid');});await page.keyboard.press('ArrowUp');expect(await row()).toBe('ch-1');for(let i=0;i<4;i++)await page.keyboard.press('ArrowDown');expect(await row()).toBe('ch-3');await page.keyboard.press('Enter');await inside(page,'#paper-scroll');await expect.poll(()=>c.driver.caret()).toMatchObject({chapter:2,paragraph:0,offset:6});await page.keyboard.press('F6');await inside(page,'#nav-pane');await page.locator('.nav-item').last().locator('.n-row').click({button:'right'});const menu=page.getByRole('menu');await expect(menu).toBeVisible();await inside(page,'[role=menu]');const first=await page.evaluate(()=>document.activeElement?.textContent);await page.keyboard.press('ArrowDown');await inside(page,'[role=menu]');expect(await page.evaluate(()=>document.activeElement?.textContent)).not.toBe(first);await page.keyboard.press('Escape');await expect(menu).toBeHidden();await c.driver.expectParagraphs([['Alpha.'],['Beta.'],['Gamma.']]);
});
test('[NEO-216-A] Leafloom: shortcut reference opens from actual Cmd slash and owns focus, Tab cycle and Escape without losing native selection',async({page})=>{
 const c=await existingBook(page,fixture);await c.driver.select(0,0,5);await page.keyboard.press(mod+'+/');const dialog=page.getByRole('dialog',{name:/Keyboard shortcuts/i});await expect(dialog).toBeVisible();const reference=dialog.getByRole('region',{name:'Shortcut reference'});await expect(reference).toBeFocused();await expect(dialog.locator('kbd')).not.toHaveCount(0);await expect(dialog).toContainText('Darlings');await page.keyboard.press('Tab');const done=dialog.getByRole('button',{name:'Done',exact:true});await expect(done).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(reference).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toBeHidden();await inside(page,'#paper-scroll');expect(await c.driver.caret()).toMatchObject({chapter:0,paragraph:0,offset:5});await c.driver.expectParagraphs([['Alpha.'],['Beta.'],['Gamma.']]);
});
test('[NEO-216-B] Leafloom: logical question-mark shortcut opens one reference repeatedly and restores native author selection',async({page})=>{
 const c=await existingBook(page,fixture);await c.driver.select(0,0,5);await page.evaluate(()=>{const rows:unknown[]=[];Object.assign(window,{__questionKeyTrace:rows});for(const capture of [true,false])window.addEventListener('keydown',e=>{if(e.code==='Slash'||e.key==='?')rows.push({capture,key:e.key,code:e.code,keyCode:e.keyCode,meta:e.metaKey,ctrl:e.ctrlKey,defaultPrevented:e.defaultPrevented,isComposing:e.isComposing,target:(e.target as Element)?.outerHTML?.slice(0,180)});},{capture});});const input=await page.context().newCDPSession(page);try{for(let i=0;i<2;i++){await input.send('Input.dispatchKeyEvent',{type:'keyDown',key:'?',code:'Slash',windowsVirtualKeyCode:191,nativeVirtualKeyCode:191,modifiers:process.platform==='darwin'?4:2});await input.send('Input.dispatchKeyEvent',{type:'keyUp',key:'?',code:'Slash',windowsVirtualKeyCode:191,nativeVirtualKeyCode:191,modifiers:process.platform==='darwin'?4:2});}}finally{await input.detach();}await test.info().attach('question-key-delivery',{body:JSON.stringify(await page.evaluate(()=>Reflect.get(window,'__questionKeyTrace')),null,2),contentType:'application/json'});const dialog=page.getByRole('dialog',{name:/Keyboard shortcuts/i});await expect(dialog).toHaveCount(1);await expect(dialog).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).toBeHidden();expect(await c.driver.caret()).toMatchObject({chapter:0,paragraph:0,offset:5});await c.driver.expectParagraphs([['Alpha.'],['Beta.'],['Gamma.']]);
});
test('[NEO-270-A] Leafloom: About reports actual application version and author purpose then returns to exact writing',async({page})=>{
 const c=await existingBook(page,fixture);await c.driver.select(0,0,5);const reference=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference',version=reference?await referenceVersion(page):JSON.parse(await readFile(new URL('../../../package.json',import.meta.url),'utf8')).version;if(reference)await clickReferenceMenu(page,['Help','About NEO']);else{await page.locator('#view-menu').click();await page.getByRole('menuitem',{name:'About Leafloom',exact:true}).click();}const dialog=page.getByRole('dialog',{name:reference?'NEO':'Leafloom',exact:true});await expect(dialog).toBeVisible();await expect(dialog).toContainText('Version '+version);await expect(dialog).toContainText(/a word processor for authors/i);await expect(dialog.getByRole('button',{name:'Back to writing',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(dialog).toBeHidden();await c.driver.expectParagraphs([['Alpha.'],['Beta.'],['Gamma.']]);
});
test('[NEO-284-A] Leafloom: pointer counter activation releases quiet chrome focus while keyboard Space remains focus-visible',async({page})=>{
 const c=await existingBook(page,fixture);const counter=page.locator('#word-counter');await c.driver.select(0,0,5);await counter.click();await expect(counter).toHaveText(/^ch\. 1: 1 words?$/);await expect(counter).not.toBeFocused();const afterClick=await counter.textContent();await page.keyboard.press('Space');await expect(counter).toHaveText(afterClick!);await expect(page.getByRole('dialog')).toHaveCount(0);await c.driver.expectParagraphs([['Alpha.'],['Beta.'],['Gamma.']]);await c.driver.select(0,0,5);await page.keyboard.press('Shift+F6');for(let i=0;i<25&&!(await counter.evaluate(el=>document.activeElement===el));i++)await page.keyboard.press('Tab');await expect(counter).toBeFocused();expect(await counter.evaluate(el=>el.matches(':focus-visible'))).toBe(true);await page.keyboard.press('Space');await expect(counter).toHaveText('3 words');await expect(counter).toBeFocused();expect(await counter.evaluate(el=>el.matches(':focus-visible'))).toBe(true);await c.driver.expectParagraphs([['Alpha.'],['Beta.'],['Gamma.']]);
});
