import {test,expect} from './author-fixture';
import type {Page} from '@playwright/test';
import {existingBook} from './book-fixture';
import {persistedBook,persistedLibrary} from './storage-probe';
const reference=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference';
async function author(page:Page,operation:'add'|'rename'|'delete'|'switch',name=''){
 await page.locator('#author-chip').click();const label=reference?({add:'Add a pen name…',rename:'Rename '+name,delete:'Remove '+name,switch:'Write as '+name})[operation]:({add:'New author…',rename:'Rename author…',delete:'Delete author',switch:name})[operation];
 if(reference)await page.locator('.fr-choice').filter({hasText:label}).click();else await page.getByRole('menuitem',{name:label,exact:true}).click();
}
async function answer(page:Page,value:string){const dialog=page.getByRole('dialog');await dialog.getByRole('textbox').fill(value);await dialog.getByRole('textbox').press('Enter');await expect(dialog).toBeHidden();}
test('[NEO-015-A] Leafloom: adding a pen name owns new shelves and new books without losing the original book',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();await author(page,'add');await answer(page,'Penny Writer');await expect(page.locator('#author-chip')).toHaveText('Penny Writer');await expect(page.locator('.book:not(.new-book)')).toHaveCount(0);await expect(page.locator('.shelf')).toHaveCount(1);await c.driver.newBook();await expect(page.locator('#tp-author')).toHaveText('Penny Writer');await c.driver.title('Penny book '+test.info().testId.slice(-8));await c.driver.shelf();const library=await persistedLibrary(page);expect(library.authors.map((a:{name:string})=>a.name)).toEqual(['Fixture Writer','Penny Writer']);expect(library.shelves.filter((s:{authorId:string})=>s.authorId===library.currentAuthorId)).toHaveLength(1);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('Alpha beta.');
});
test('[NEO-013-A] Leafloom: switching identities shows only owned shelves and new title pages inherit that identity',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();await author(page,'add');await answer(page,'Penny Writer');await author(page,'switch','Fixture Writer');await expect(page.locator('#author-chip')).toHaveText('Fixture Writer');await expect(page.locator('.book:not(.new-book)')).toHaveCount(1);await expect(page.locator('.shelf-label')).toHaveText('Fixture books');await c.driver.newBook();await expect(page.locator('#tp-author')).toHaveText('Fixture Writer');await c.driver.shelf();await author(page,'switch','Penny Writer');await expect(page.locator('.book:not(.new-book)')).toHaveCount(0);await expect(page.locator('#author-chip')).toHaveText('Penny Writer');await page.reload();await expect(page.locator('#author-chip')).toHaveText('Penny Writer');await expect(page.locator('.book:not(.new-book)')).toHaveCount(0);
});
test('[NEO-014-A] Leafloom: author rename persists identity while existing prose and book directories remain intact',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();const before=await persistedLibrary(page);await author(page,'rename','Fixture Writer');await answer(page,'Renamed Writer');await expect(page.locator('#author-chip')).toHaveText('Renamed Writer');await expect.poll(async()=>(await persistedLibrary(page)).authors[0].name).toBe('Renamed Writer');const library=await persistedLibrary(page);expect(library.authors[0].id).toBe(before.authors[0].id);expect(library.authors[0].name).toBe('Renamed Writer');expect(library.shelves[0].bookIds).toEqual([c.id]);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('Alpha beta.');await page.reload();await expect(page.locator('#author-chip')).toHaveText('Renamed Writer');await c.driver.newBook();await expect(page.locator('#tp-author')).toHaveText('Renamed Writer');await c.driver.shelf();
});
test('[NEO-016-A] Leafloom: removing a pen identity rehomes its shelves and retains both authors actual book files',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();await author(page,'add');await answer(page,'Penny Writer');await c.driver.newBook();const title='Penny book '+test.info().testId.slice(-8);await c.driver.title(title);await c.driver.type('Penny prose.');await c.driver.shelf();await author(page,'delete','Penny Writer');await expect(page.locator('#author-chip')).toHaveText('Fixture Writer');await expect(page.locator('.book:not(.new-book)')).toHaveCount(2);await expect.poll(async()=>(await persistedLibrary(page)).authors.length).toBe(1);const library=await persistedLibrary(page);expect(library.authors).toHaveLength(1);expect(library.shelves.every((s:{authorId:string})=>s.authorId===library.authors[0].id)).toBe(true);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('Alpha beta.');expect((await persistedBook(page,title)).chapters[0].html).toContain('Penny prose.');await page.reload();await expect(page.locator('.book:not(.new-book)')).toHaveCount(2);
});
