import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedLibrary,persistedBook,privateStorageRoot} from './storage-probe';
import {clickReferenceMenu} from '../reference/harness';
import {readFile,writeFile,cp,readdir,access,rename,rm} from 'node:fs/promises';
import path from 'node:path';
import type {Page} from '@playwright/test';
const reference=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference';
async function pick(page:Page,label:string){if(reference)await page.locator('.modal-backdrop:visible .fr-choice').filter({hasText:label}).click();else if(await page.getByRole('menu').isVisible())await page.getByRole('menuitem',{name:label,exact:true}).click();else await page.getByRole('dialog').locator('.fr-choice').filter({hasText:label}).click();}
async function reshelve(page:Page){if(reference)await clickReferenceMenu(page,['File','Reshelve a Book…']);else{await page.locator('#file-menu').click();await page.getByRole('menuitem',{name:'Reshelve a Book…',exact:true}).click();}}
async function nativeResponse(page:Page,response:number){if(reference)await writeFile(path.resolve(privateStorageRoot(page),'../../.neo-parity-host.json'),JSON.stringify({messageResponses:[response]}));}
async function confirm(page:Page,yes:boolean){if(reference)return;await page.getByRole('dialog').getByRole('button',{name:yes?'Move to Trash':'Cancel',exact:true}).click();}
async function fileBytes(folder:string):Promise<Record<string,string>>{const out:Record<string,string>={};async function visit(current:string){for(const entry of await readdir(current,{withFileTypes:true})){const file=path.join(current,entry.name);if(entry.isDirectory())await visit(file);else if(entry.isFile())out[path.relative(folder,file)]=(await readFile(file)).toString('base64');}}await visit(folder);return out;}
async function closed(folder:string){await expect.poll(()=>access(path.join(folder,'.writer.lock')).then(()=>true,()=>false)).toBe(false);}
async function closeSheet(page:Page,title:string,kind:string,text:string){await page.locator('.ps-done').click();await expect(page.locator('.page-sheet')).toBeHidden();const id=await page.locator('.page-tile.kind-'+kind).getAttribute('data-book-id');if(!id)throw Error('Missing current page identity');await expect.poll(async()=>(await persistedBook(page,title,id)).chapters[0].html).toContain(text);const saved=await persistedBook(page,title,id);await closed(saved.directory);return saved;}

test('[NEO-017-A] Leafloom: Remove from bookshelf retains exact book files and reload omits only its placement',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();const before=await fileBytes(c.folder);await page.locator('.book[data-book-id="'+c.id+'"]').click({button:'right'});await pick(page,'Remove from bookshelf');await expect.poll(async()=>(await persistedLibrary(page)).shelves[0].bookIds).toEqual([]);expect(await fileBytes(c.folder)).toEqual(before);await page.reload();await expect(page.locator('.book[data-book-id="'+c.id+'"]')).toHaveCount(0);expect((await persistedBook(page,c.title,c.id)).chapters[0].html).toContain('Alpha beta.');await reshelve(page);await pick(page,c.title);await expect.poll(async()=>(await persistedLibrary(page)).shelves[0].bookIds).toEqual([c.id]);await page.locator('.book[data-book-id="'+c.id+'"]').click();await expect(page.locator('.chapter-body').first()).toContainText('Alpha beta.');
});
test('[NEO-019-A] Leafloom: Reshelve sorts loose manuscripts by modification and excludes parked and publication pages while restoring to current author first shelf',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();const root=privateStorageRoot(page);await closed(c.folder);if(!reference){if(await readFile(path.join(root,'.leafloom-parity-fixture'),'utf8')!=='isolated-leafloom-candidate-v1')throw Error('Unmarked fixture');for(const entry of await readdir(root,{withFileTypes:true}))if(entry.isDirectory()&&entry.name.startsWith('book-')&&entry.name!==c.id)await rm(path.join(root,entry.name),{recursive:true,force:true});}for(const [id,title,modified,kind] of [['book-loose-old','Older loose story','2026-01-01T00:00:00Z',''],['book-loose-new','Newest loose story','2026-10-02T20:00:00Z',''],['book-parked','Parked story','2026-10-02T22:00:00Z',''],['book-page','Loose dedication','2026-10-02T23:00:00Z','dedication']]){const folder=path.join(root,id);await cp(c.folder,folder,{recursive:true});const metaFile=path.join(folder,reference?'book.json':'manuscript.json'),data=JSON.parse(await readFile(metaFile,'utf8')),meta=reference?data:data.metadata;Object.assign(meta,{id,title,modified});if(kind)meta.kind=kind;await writeFile(metaFile,JSON.stringify(data));if(!reference){const reviewsFile=path.join(folder,'reviews.json'),reviews=JSON.parse(await readFile(reviewsFile,'utf8'));reviews.bookId=id;await writeFile(reviewsFile,JSON.stringify(reviews));}}
 const parkedBytes=await fileBytes(path.join(root,'book-parked'));const library=await persistedLibrary(page);library.authors.push({id:'penny',name:'Penny'});library.currentAuthorId='penny';library.shelves[0].binding={bound:false,numbering:'through',parked:[{id:'book-parked',kind:'part',before:null}]};library.shelves.push({id:'penny-first',authorId:'penny',name:'Penny first',bookIds:[]},{id:'penny-second',authorId:'penny',name:'Penny second',bookIds:[]});await writeFile(path.join(root,'library.json'),JSON.stringify(library));await page.reload();await reshelve(page);if(reference)await expect(page.locator('.modal-backdrop:visible .fr-choice strong')).toHaveText(['Newest loose story','Older loose story']);else await expect(page.getByRole('dialog').locator('.fr-choice')).toHaveText(['Newest loose story','Older loose story']);await page.keyboard.press('Escape');expect((await persistedLibrary(page)).shelves[1].bookIds).toEqual([]);await reshelve(page);await pick(page,'Newest loose story');await expect.poll(async()=>(await persistedLibrary(page)).shelves[1].bookIds).toEqual(['book-loose-new']);expect((await persistedLibrary(page)).shelves[2].bookIds).toEqual([]);expect((await persistedBook(page,'Newest loose story','book-loose-new')).metadata.author).toBe('Fixture Writer');expect(await fileBytes(path.join(root,'book-parked'))).toEqual(parkedBytes);await page.reload();await page.locator('.book[data-book-id="book-loose-new"]').click();await expect(page.locator('.chapter-body').first()).toContainText('Alpha beta.');
});
for(const yes of [false,true])test(`[NEO-043-A] Leafloom: publication page Remove ${yes?'confirmed':'cancelled'} preserves unrelated files and changes only the requested page`,async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();await page.locator('.shelf-label').first().click({button:'right'});await pick(page,reference?'Bind into one book':'Bind shelf');await page.locator('.shelf').hover();await page.locator('.ghost-page').filter({has:page.locator('.pt-label').filter({hasText:/^Dedication$/})}).click();await expect(page.locator('.ps-body')).toBeFocused();await page.keyboard.type('For the author.');const meta=await closeSheet(page,'Dedication — Fixture books','dedication','For the author.');await closed(c.folder);const unrelated=await fileBytes(c.folder);await page.locator('.shelf').hover();await page.locator('.ghost-page').filter({has:page.locator('.pt-label').filter({hasText:/^Epigraph$/})}).click();await expect(page.locator('.ps-body')).toBeFocused();await page.keyboard.type('Preserved quotation.');const otherPage=await closeSheet(page,'Epigraph — Fixture books','epigraph','Preserved quotation.'),otherBytes=await fileBytes(otherPage.directory);await page.locator('.page-tile.kind-dedication').click({button:'right'});if(reference)await expect(page.locator('.modal-backdrop:visible .fr-choice strong')).toHaveText(['Open','Remove page']);else await expect(page.getByRole('menuitem')).toHaveText(['Open','Remove page']);await pick(page,'Open');await expect(page.locator('.ps-body')).toHaveText('For the author.');await closeSheet(page,'Dedication — Fixture books','dedication','For the author.');await nativeResponse(page,yes?1:0);await page.locator('.page-tile.kind-dedication').click({button:'right'});await pick(page,'Remove page');await confirm(page,yes);await expect.poll(async()=>(await persistedLibrary(page)).shelves[0].bookIds.includes(meta.metadata.id)).toBe(!yes);expect(await fileBytes(c.folder)).toEqual(unrelated);expect(await fileBytes(otherPage.directory)).toEqual(otherBytes);if(yes){await expect.poll(async()=>access(meta.directory).then(()=>true,()=>false)).toBe(false);if(reference){const trash=path.resolve(privateStorageRoot(page),'../../Trash'),entries=await readdir(trash);expect(entries.some(name=>name.startsWith(meta.metadata.id+'-'))).toBe(true);}}else expect((await persistedBook(page,'Dedication — Fixture books',meta.metadata.id)).chapters[0].html).toContain('For the author.');await page.reload();await expect(page.locator('.page-tile.kind-dedication')).toHaveCount(yes?0:1);await expect(page.locator('.page-tile.kind-epigraph')).toHaveCount(1);await page.locator('.shelf').hover();await page.locator('.part-seam').first().click();await expect(page.locator('.ps-label')).toHaveText('Part I');await page.locator('.ps-done').click();await expect(page.locator('.page-tile.kind-part')).toHaveText('Part I');expect(await fileBytes(otherPage.directory)).toEqual(otherBytes);
});
for(const yes of [false,true])test(`[NEO-018-A] Leafloom: book Trash ${yes?'confirmed':'cancelled'} retains recoverable bytes and preserves the neighbouring manuscript`,async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();await c.driver.newBook();await c.driver.title('Neighbour kept');await c.driver.type('Neighbour words.');await c.driver.shelf();const neighbourId=await page.locator('.book:not(.new-book)').evaluateAll((elements,seed)=>elements.map(el=>el.getAttribute('data-book-id')).find(id=>id!==seed),c.id);if(!neighbourId)throw Error('Missing current neighbour cover identity');const neighbour=await persistedBook(page,'Neighbour kept',neighbourId);await closed(neighbour.directory);await closed(c.folder);const before=await fileBytes(c.folder),other=await fileBytes(neighbour.directory);await nativeResponse(page,yes?1:0);await page.locator('.book[data-book-id="'+c.id+'"]').click({button:'right'});await pick(page,reference?'Move to Trash':'Delete book…');await confirm(page,yes);await expect.poll(async()=>(await persistedLibrary(page)).shelves[0].bookIds.includes(c.id)).toBe(!yes);expect(await fileBytes(neighbour.directory)).toEqual(other);if(yes){await expect.poll(async()=>access(c.folder).then(()=>true,()=>false)).toBe(false);if(reference){const trash=path.resolve(privateStorageRoot(page),'../../Trash'),entry=(await readdir(trash)).find(name=>name.startsWith(c.id+'-'));if(!entry)throw Error('Missing actual recoverable fixture Trash folder');expect(await fileBytes(path.join(trash,entry))).toEqual(before);}}else expect(await fileBytes(c.folder)).toEqual(before);await page.reload();await expect(page.locator('.book[data-book-id="'+c.id+'"]')).toHaveCount(yes?0:1);await page.locator('.book[data-book-id="'+neighbour.metadata.id+'"]').click();await expect(page.locator('.chapter-body').first()).toHaveText('Neighbour words.');
});

test('[NEO-018-A] Leafloom: a real Trash filesystem failure preserves book placement and every manuscript byte',async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();const root=privateStorageRoot(page),trash=reference?path.resolve(root,'../../Trash'):path.join(root,'Trash'),backup=trash+'-preserved-'+test.info().testId;const existed=await access(trash).then(()=>true,()=>false);if(existed)await rename(trash,backup);await writeFile(trash,'Fixture regular file blocks the real Trash directory creation.');try{const before=await fileBytes(c.folder),ids=(await persistedLibrary(page)).shelves[0].bookIds;await nativeResponse(page,1);await page.locator('.book[data-book-id="'+c.id+'"]').click({button:'right'});await pick(page,reference?'Move to Trash':'Delete book…');await confirm(page,true);if(reference)await expect.poll(async()=>{const effects=JSON.parse(await readFile(path.resolve(root,'../../intercepted-effects.json'),'utf8'));return effects.some((e:{type:string;payload:string})=>e.type==='reveal-file'&&e.payload===c.folder);}).toBe(true);else await expect(page.locator('#hint')).toContainText(/EEXIST|file already exists|DISK_ERROR/);expect((await persistedLibrary(page)).shelves[0].bookIds).toEqual(ids);expect(await fileBytes(c.folder)).toEqual(before);await page.reload();await page.locator('.book[data-book-id="'+c.id+'"]').click();await expect(page.locator('.chapter-body').first()).toContainText('Alpha beta.');}finally{await rm(trash,{force:true});if(existed)await rename(backup,trash);}
});
