import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedLibrary,persistedBook} from './storage-probe';
import type {Page,Locator} from '@playwright/test';
const mod=process.platform==='darwin'?'Meta':'Control';
async function add(page:Page,name:string){await page.locator('#add-shelf-btn').click();const label=page.locator('.shelf-label').last();await expect(label).toBeFocused();await label.fill(name);await label.press('Enter');await expect.poll(async()=>(await persistedLibrary(page)).shelves.at(-1).name).toBe(name);}
async function start(page:Page,from:Locator){const a=await from.boundingBox();if(!a)throw Error('Missing actual pointer origin');await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(a.x+a.width/2+12,a.y+a.height/2+12,{steps:3});}
async function over(page:Page,to:Locator,after=false){const b=await to.boundingBox();if(!b)throw Error('Missing actual pointer destination');await page.mouse.move(b.x+(after?b.width-5:5),b.y+b.height/2,{steps:12});await page.mouse.move(b.x+(after?b.width-4:6),b.y+b.height/2+1);await expect(page.locator('.drop-indicator')).toBeVisible();}
async function books(page:Page){const c=await existingBook(page);await c.driver.shelf();await c.driver.newBook();await c.driver.title('Neighbour');await c.driver.type('Neighbour words.');await c.driver.shelf();return c;}
test('[NEO-008-B] Leafloom: shelf before-after insertion indicator follows actual grip pointer and durable order',async({page})=>{
 await page.setViewportSize({width:1100,height:1600});const c=await existingBook(page);await c.driver.shelf();await add(page,'Second shelf');await add(page,'Third shelf');const initial=(await persistedLibrary(page)).shelves.map((s:{id:string})=>s.id);
 await start(page,page.locator('.shelf-grip').last());const target=await page.locator('.shelf').first().boundingBox();if(!target)throw Error('Missing first shelf');await page.mouse.move(target.x+30,target.y+5,{steps:12});await page.mouse.move(target.x+31,target.y+6);await expect(page.locator('.shelf-drop-ind')).toBeVisible();expect(await page.locator('.shelf-drop-ind').evaluate(e=>e.nextElementSibling?.getAttribute('data-shelf-id'))).toBe(initial[0]);await page.mouse.up();await expect.poll(async()=>(await persistedLibrary(page)).shelves.map((s:{id:string})=>s.id)).toEqual([initial[2],initial[0],initial[1]]);
 await start(page,page.locator('.shelf-grip').first());const last=await page.locator('.shelf').last().boundingBox();if(!last)throw Error('Missing last shelf');await page.mouse.move(last.x+30,last.y+last.height-5,{steps:12});await page.mouse.move(last.x+31,last.y+last.height-6);await expect(page.locator('.shelf-drop-ind')).toBeVisible();expect(await page.locator('.shelf-drop-ind').evaluate(e=>e.previousElementSibling?.getAttribute('data-shelf-id'))).toBe(initial[1]);await page.mouse.up();await expect.poll(async()=>(await persistedLibrary(page)).shelves.map((s:{id:string})=>s.id)).toEqual(initial);await start(page,page.locator('.shelf-grip').first());const middle=await page.locator('.shelf').nth(1).boundingBox();if(!middle)throw Error('Missing middle shelf');await page.mouse.move(middle.x+30,middle.y+5,{steps:12});await page.mouse.move(middle.x+31,middle.y+6);await expect(page.locator('.shelf-drop-ind')).toBeVisible();expect(await page.locator('.shelf-drop-ind').evaluate(e=>e.nextElementSibling?.getAttribute('data-shelf-id'))).toBe(initial[1]);await page.mouse.up();expect((await persistedLibrary(page)).shelves.map((s:{id:string})=>s.id)).toEqual(initial);
 await start(page,page.locator('.shelf-grip').last());const first=await page.locator('.shelf').first().boundingBox();if(!first)throw Error('Missing first shelf');await page.mouse.move(first.x+30,first.y+first.height-5,{steps:12});await page.mouse.move(first.x+31,first.y+first.height-6);await expect(page.locator('.shelf-drop-ind')).toBeVisible();expect(await page.locator('.shelf-drop-ind').evaluate(e=>e.previousElementSibling?.getAttribute('data-shelf-id'))).toBe(initial[0]);await page.mouse.up();await expect.poll(async()=>(await persistedLibrary(page)).shelves.map((s:{id:string})=>s.id)).toEqual([initial[0],initial[2],initial[1]]);await page.reload();await expect(page.locator('.shelf-label')).toHaveText(['Fixture books','Third shelf','Second shelf']);
});
for(const cross of [false,true])for(const key of ['Escape',mod+'+z'])test(`[NEO-012-A] Leafloom: ordinary ${cross?'cross-shelf':'same-shelf'} pointer drag survives ${key} without cross-author Undo`,async({page})=>{
 const c=await books(page);if(cross)await add(page,'Destination');const before=await persistedLibrary(page),ids=before.shelves[0].bookIds;await start(page,page.locator(`.book[data-book-id="${c.id}"]`));await over(page,cross?page.locator('.shelf').last().locator('.new-book'):page.locator(`.book[data-book-id="${ids[1]}"]`),!cross);await page.mouse.up();const order=cross?[[ids[1]],[c.id]]:[[ids[1],c.id]];await expect.poll(async()=>(await persistedLibrary(page)).shelves.map((s:{bookIds:string[]})=>s.bookIds)).toEqual(order);await page.keyboard.press(key);expect((await persistedLibrary(page)).shelves.map((s:{bookIds:string[]})=>s.bookIds)).toEqual(order);expect((await persistedBook(page,c.title,c.id)).metadata.author).toBe('Fixture Writer');await page.reload();await expect.poll(async()=>(await persistedLibrary(page)).shelves.map((s:{bookIds:string[]})=>s.bookIds)).toEqual(order);await c.driver.selectBook(c.title);await c.driver.expectParagraphs([['Alpha beta.','Gamma delta.']]);
});
for(const key of ['Enter','Space'])test(`[NEO-022-A] Leafloom: ${key} keyboard header activation and empty-shelf New book retain active author placement`,async({page})=>{
 const c=await existingBook(page);await c.driver.shelf();await page.locator('#author-chip').focus();await expect(page.locator('#author-chip')).toBeFocused();for(let i=0;i<10&&!await page.locator('#add-shelf-btn').evaluate(e=>e===document.activeElement);i++)await page.keyboard.press('Tab');await expect(page.locator('#add-shelf-btn')).toBeFocused();await page.keyboard.press(key);const label=page.locator('.shelf-label').last();await expect(label).toBeFocused();await label.fill('Keyboard empty');await label.press('Enter');await expect.poll(async()=>(await persistedLibrary(page)).shelves.at(-1).name).toBe('Keyboard empty');await label.focus();for(let i=0;i<6&&!await page.locator('.shelf').last().locator('.new-book').evaluate(e=>e===document.activeElement);i++)await page.keyboard.press('Tab');const blank=page.locator('.shelf').last().locator('.new-book');await expect(blank).toBeFocused();await page.keyboard.press(key);await expect(page.locator('#tp-title')).toBeVisible();await expect(page.locator('#tp-author')).toHaveText('Fixture Writer');await c.driver.title('Keyboard '+key);await c.driver.type('Keyboard prose.');await c.driver.shelf();const library=await persistedLibrary(page);expect(library.shelves[0].bookIds).toEqual([c.id]);expect(library.shelves.at(-1).bookIds).toHaveLength(1);const id=library.shelves.at(-1).bookIds[0];expect((await persistedBook(page,'Keyboard '+key,id)).metadata.author).toBe('Fixture Writer');await page.reload();await expect(page.locator('.shelf').last().locator(`.book[data-book-id="${id}"]`)).toBeVisible();
});
test('[NEO-024-A] Leafloom: actual hover refresh icon persists fresh seeded cover art and identity through reload',async({page})=>{
 const c=await existingBook(page,{metadata:{coverSeed:'pointer-refresh-source-seed'}});await c.driver.shelf();const tile=page.locator(`.book[data-book-id="${c.id}"]`),art=()=>tile.evaluate(e=>getComputedStyle(e).backgroundImage);await expect.poll(art).toContain('data:image/png');const old=await art();await tile.hover();await tile.locator('.b-refresh').click();await expect.poll(async()=>(await persistedBook(page,c.title,c.id)).metadata.coverSeed).not.toBe('pointer-refresh-source-seed');await expect.poll(art).not.toBe(old);const changed=await art(),seed=(await persistedBook(page,c.title,c.id)).metadata.coverSeed;const dress=await tile.evaluate(e=>({class:e.className,color:getComputedStyle(e.querySelector('.b-title')!).color,font:getComputedStyle(e.querySelector('.b-title')!).fontFamily}));await expect(tile.locator('.b-author')).toHaveText('Fixture Writer');expect((await persistedBook(page,c.title,c.id)).metadata.title).toBe(c.title);await page.reload();await expect.poll(art).toBe(changed);expect((await persistedBook(page,c.title,c.id)).metadata.coverSeed).toBe(seed);expect(await tile.evaluate(e=>({class:e.className,color:getComputedStyle(e.querySelector('.b-title')!).color,font:getComputedStyle(e.querySelector('.b-title')!).fontFamily}))).toEqual(dress);await c.driver.selectBook(c.title);await c.driver.expectParagraphs([['Alpha beta.','Gamma delta.']]);
});
for(const origin of ['book','shelf'] as const)for(const edge of ['upper','lower'] as const)test(`[NEO-010-A] Leafloom: ${origin} drag ${edge} edge scrolls and real Escape cancellation stops without moving files`,async({page})=>{
 const id='book-'+test.info().testId,shelves=Array.from({length:13},(_,i)=>({id:'scroll-'+i,name:'Scroll shelf '+i,authorId:'fixture-author',bookIds:i===(edge==='upper'?12:0)?[id]:[]})),c=await existingBook(page,{library:{shelves}});await c.driver.shelf();const before=await persistedLibrary(page),prose=(await persistedBook(page,c.title,c.id)).chapters,view=page.locator('#bookshelf-view');await view.evaluate((e,upper)=>{e.scrollTop=upper?e.scrollHeight:0;},edge==='upper');const initial=await view.evaluate(e=>e.scrollTop);await start(page,origin==='book'?page.locator(`.book[data-book-id="${id}"]`):page.locator('.shelf-grip').nth(edge==='upper'?12:0));const height=await page.evaluate(()=>innerHeight);await page.mouse.move(500,edge==='upper'?8:height-8,{steps:20});if(edge==='upper')await expect.poll(()=>view.evaluate(e=>e.scrollTop)).toBeLessThan(initial-50);else await expect.poll(()=>view.evaluate(e=>e.scrollTop)).toBeGreaterThan(initial+50);
 await page.keyboard.press('Escape');await page.mouse.up();await test.info().attach('cancelled-drag-indicator-observation',{body:JSON.stringify({count:await page.locator('.drop-indicator,.shelf-drop-ind').count(),visible:await page.locator('.drop-indicator,.shelf-drop-ind').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBoundingClientRect(),style=getComputedStyle(e);return r.width>0&&r.height>0&&style.display!=='none'&&style.visibility!=='hidden';}))}),contentType:'application/json'});const stopped=await view.evaluate(e=>e.scrollTop);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));expect(await view.evaluate(e=>e.scrollTop)).toBe(stopped);expect((await persistedLibrary(page)).shelves).toEqual(before.shelves);expect((await persistedBook(page,c.title,c.id)).chapters).toEqual(prose);await page.reload();expect((await persistedLibrary(page)).shelves).toEqual(before.shelves);
});
