import {test,expect} from './author-fixture';
import {BrowserAuthorDriver} from './browser-driver';
import {existingBook} from './book-fixture';
import {persistedLibrary,persistedBook,privateStorageRoot} from './storage-probe';
import {clickReferenceMenu} from '../reference/harness';
import {readFile,writeFile,readdir,access} from 'node:fs/promises';
import path from 'node:path';
import type {Page} from '@playwright/test';
const reference=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference',mod=process.platform==='darwin'?'Meta':'Control';
const target135=!reference||process.env.LEAFLOOM_REFERENCE_VERSION==='1.3.5';
async function option(page:Page,label:string){if(reference)await page.locator('.modal-backdrop:visible .fr-choice').filter({hasText:label}).click();else await page.getByRole('menuitem',{name:label,exact:true}).click();}
async function author(page:Page,name:string,add=false){await page.locator('#author-chip').click();await option(page,add?(reference?'Add a pen name…':'New author…'):(reference?'Write as '+name:name));if(add){const field=page.getByRole('dialog').getByRole('textbox');await field.fill(name);await field.press('Enter');}await expect(page.locator('#author-chip')).toHaveText(name);}
async function byID(page:Page,id:string){const raw=JSON.parse(await readFile(path.join(privateStorageRoot(page),id,reference?'book.json':'manuscript.json'),'utf8'));return persistedBook(page,(reference?raw:raw.metadata).title,id);}
async function closed(page:Page,id:string){await expect.poll(()=>access(path.join(privateStorageRoot(page),id,'.writer.lock')).then(()=>true,()=>false)).toBe(false);}
async function bytes(folder:string){const out:Record<string,string>={};async function visit(dir:string){for(const e of await readdir(dir,{withFileTypes:true})){const file=path.join(dir,e.name);if(e.isDirectory())await visit(file);else if(e.isFile())out[path.relative(folder,file)]=(await readFile(file)).toString('base64');}}await visit(folder);return out;}
async function addShelf(page:Page,name:string){await page.locator('#add-shelf-btn').click();const field=page.locator('.shelf-label').last();await expect(field).toBeFocused();await field.fill(name);await field.press('Enter');await expect.poll(async()=>(await persistedLibrary(page)).shelves.at(-1).name).toBe(name);}
test('[NEO-001-B][NEO-002-B] Leafloom: onboarded real and pen identities retain separately attributed rich books and selected shelves through restart',async({page})=>{
 if(!reference)await writeFile(path.join(privateStorageRoot(page),'library.json'),'{}');const d=new BrowserAuthorDriver(page);await d.open();await d.onboard('Real Writer','Pen Writer');await d.newBook();await d.title('Real signed book');await d.type('Real manuscript.');await d.select(0,0,0,4);await d.key(mod+'+b');await d.shelf();const real=await persistedBook(page,'Real signed book');await closed(page,real.metadata.id);const original=await bytes(real.directory);
 // First-run pen text is a saved name; the source registers a distinct identity through Add a pen name.
 await author(page,'Pen Writer',true);await d.newBook();await expect(page.locator('#tp-author')).toHaveText('Pen Writer');await d.title('Pen signed book');await d.type('Pen manuscript.');await d.select(0,0,0,3);await d.key(mod+'+i');await d.shelf();const pen=await persistedBook(page,'Pen signed book');await closed(page,pen.metadata.id);const penBytes=await bytes(pen.directory),library=await persistedLibrary(page);expect(library.penNames).toEqual(['Pen Writer']);expect(library.authors.map((a:{name:string})=>a.name)).toEqual(['Real Writer','Pen Writer']);expect(library.shelves.find((s:{authorId:string})=>(s.authorId||library.authors[0].id)===library.authors[0].id).bookIds).toEqual([real.metadata.id]);expect(library.shelves.find((s:{authorId:string})=>s.authorId===library.authors[1].id).bookIds).toEqual([pen.metadata.id]);expect(real.metadata.author).toBe('Real Writer');expect(pen.metadata.author).toBe('Pen Writer');await page.reload();await expect(page.locator('#firstrun')).toBeHidden();await expect(page.locator('#author-chip')).toHaveText('Pen Writer');await expect(page.locator('.book:not(.new-book)')).toHaveCount(1);expect(await bytes(real.directory)).toEqual(original);expect(await bytes(pen.directory)).toEqual(penBytes);await author(page,'Real Writer');await expect(page.locator(`.book[data-book-id="${real.metadata.id}"]`)).toBeVisible();await expect(page.locator(`.book[data-book-id="${pen.metadata.id}"]`)).toHaveCount(0);await page.reload();expect((await persistedLibrary(page)).currentAuthorId).toBe(library.authors[0].id);await d.selectBook('Real signed book');await d.expectParagraphs([['Real manuscript.']]);await expect(page.locator('.chapter-body b,.chapter-body strong')).toHaveText('Real');await d.shelf();await author(page,'Pen Writer');await d.selectBook('Pen signed book');await expect(page.locator('.chapter-body i,.chapter-body em')).toHaveText('Pen');await d.shelf();
});
for(const style of ['pantser','plotter'] as const)test(`[NEO-003-A] Leafloom: later ${style} menu default affects only future books and persists while existing rich prose remains`,async({page})=>{
 const c=await existingBook(page,{chapters:['<p><b>Existing</b> manuscript.</p>'],library:{writingStyle:style==='pantser'?'plotter':'pantser'}});await c.driver.shelf();await closed(page,c.id);const before=(await persistedBook(page,c.title,c.id)).chapters;await c.driver.selectBook(c.title);
 if(reference)await clickReferenceMenu(page,['File','New Books Open To',style==='plotter'?'Outline First':'Blank Page']);else{await page.locator('#view-menu').click();await page.getByRole('menuitemradio',{name:new RegExp(style==='plotter'?'Plotter':'Pantser')}).click();}await expect.poll(async()=>(await persistedLibrary(page)).writingStyle).toBe(style);await c.driver.expectParagraphs([['Existing manuscript.']]);await c.driver.shelf();const previous=(await persistedLibrary(page)).shelves[0].bookIds;await c.driver.newBook();if(style==='plotter'){if(target135){await expect(page.locator('#outline-board')).toBeVisible();await page.locator('#outline-views button[data-view="list"]').click();test.info().annotations.push({type:'source-characterization',description:'NEO 1.3.5 new plotter books open the Outline cards view by default; select the real List view before the retained chapter-note workflow. The 1.2.4 source setup is unchanged.'});}await expect(page.locator('#outline-list')).toBeVisible();await expect(page.locator('#paper')).toBeHidden();await page.locator('.ol-text').first().fill('Future planned scene.');await page.locator('.tab[data-tab="notes"]').click();}else{await expect(page.locator('#tp-title')).toBeFocused();await c.driver.title('Future blank story');await c.driver.type('Future prose.');}await c.driver.shelf();const library=await persistedLibrary(page),id=library.shelves[0].bookIds.find((id:string)=>!previous.includes(id));expect(id).toBeTruthy();const future=await byID(page,id);expect(future.metadata.author).toBe('Fixture Writer');if(style==='plotter')expect(Object.values(future.metadata.chapterNotes??{})).toContain('Future planned scene.');else expect(future.chapters[0].html).toContain('Future prose.');expect((await persistedBook(page,c.title,c.id)).chapters).toEqual(before);await page.reload();expect((await persistedLibrary(page)).writingStyle).toBe(style);await c.driver.selectBook(c.title);await expect(page.locator('.chapter-body b,.chapter-body strong')).toHaveText('Existing');await c.driver.shelf();
});
test('[NEO-021-A][NEO-021-B] Leafloom: author title creation rename move and shelf rename regenerate the actual readable catalog',async({page})=>{
 const c=await existingBook(page);await c.driver.title('Mapped');await c.driver.shelf();const original=(await persistedBook(page,'Mapped',c.id)).chapters,map=()=>readFile(path.join(privateStorageRoot(page),'_catalog.txt'),'utf8');await expect.poll(map).toContain('Mapped  —  '+c.id+'  —  shelf: Fixture books');await c.driver.newBook();await c.driver.title('New catalog neighbour');await c.driver.type('Neighbour prose.');await c.driver.shelf();const neighbour=await persistedBook(page,'New catalog neighbour');await expect.poll(map).toContain('New catalog neighbour  —  '+neighbour.metadata.id+'  —  shelf: Fixture books');await addShelf(page,'Destination');const a=await page.locator(`.book[data-book-id="${c.id}"]`).boundingBox(),b=await page.locator('.shelf').last().locator('.new-book').boundingBox();if(!a||!b)throw Error('Missing real catalog drag endpoints');await page.mouse.move(a.x+25,a.y+40);await page.mouse.down();await page.mouse.move(a.x+37,a.y+52,{steps:3});await page.mouse.move(b.x+20,b.y+40,{steps:12});await page.mouse.move(b.x+21,b.y+41);await expect(page.locator('.drop-indicator')).toBeVisible();await page.mouse.up();await expect.poll(map).toContain('Mapped  —  '+c.id+'  —  shelf: Destination');const label=page.locator('.shelf-label').last();await label.fill('Renamed destination');await label.press('Enter');await expect.poll(map).toContain('Mapped  —  '+c.id+'  —  shelf: Renamed destination');await page.reload();expect((await persistedBook(page,'Mapped',c.id)).chapters).toEqual(original);expect((await persistedLibrary(page)).shelves.at(-1).bookIds).toEqual([c.id]);expect(await map()).toContain('New catalog neighbour  —  '+neighbour.metadata.id+'  —  shelf: Fixture books');await test.info().attach('actual-library-map',{body:await map(),contentType:'text/plain'});
});
test('[NEO-023-B] Leafloom: seven stored template seeds render real saved title and author overlays consistently through reload',async({page})=>{
 const entries=[['cinzel','stored-cover-closure-0'],['oswald','stored-cover-closure-1'],['stack','stored-cover-closure-2'],['fat','stored-cover-closure-5'],['black','stored-cover-closure-7'],['band','stored-cover-closure-14'],['bebas','stored-cover-closure-16']];const c=await existingBook(page,{metadata:{author:'Library Writer'},library:{authors:[{id:'fixture-author',name:'Library Writer'}],authorName:'Library Writer'}});await c.driver.title('Template proof');await c.driver.shelf();for(let i=1;i<entries.length;i++){await c.driver.newBook();await c.driver.title('Template proof');await c.driver.type('Template words '+i+'.');await c.driver.shelf();}const ids=(await persistedLibrary(page)).shelves[0].bookIds,prose=[];expect(ids).toHaveLength(entries.length);for(let i=0;i<ids.length;i++){await closed(page,ids[i]);const saved=await byID(page,ids[i]);prose.push(saved.chapters);const file=path.join(saved.directory,reference?'book.json':'manuscript.json'),raw=JSON.parse(await readFile(file,'utf8'));(reference?raw:raw.metadata).coverSeed=entries[i][1];await writeFile(file,JSON.stringify(raw));}await page.reload();const pixels=[];for(let i=0;i<ids.length;i++){const tile=page.locator(`.book[data-book-id="${ids[i]}"]`);await expect(tile).toHaveClass(new RegExp('cv-'+entries[i][0]+'(?: |$)'));await expect.poll(async()=>(await tile.locator('.b-line').allTextContents()).join(' ').toUpperCase()).toBe('TEMPLATE PROOF');await expect(tile.locator('.b-author')).toHaveText('Library Writer');await expect.poll(()=>tile.evaluate(e=>getComputedStyle(e).backgroundImage)).toContain('data:image/png');pixels.push(await tile.evaluate(e=>getComputedStyle(e).backgroundImage));expect((await byID(page,ids[i])).chapters).toEqual(prose[i]);}await page.reload();for(let i=0;i<ids.length;i++){const tile=page.locator(`.book[data-book-id="${ids[i]}"]`);await expect.poll(()=>tile.evaluate(e=>getComputedStyle(e).backgroundImage)).toBe(pixels[i]);expect((await byID(page,ids[i])).metadata.coverSeed).toBe(entries[i][1]);}test.info().annotations.push({type:'stored-template-fixture',description:'Author-created books, closed-file deterministic seed preparation, real overlay/reload proof. No all-seven art-style pixel or native picker claim.'});
});
async function binding(page:Page,bind:boolean){await page.locator('.shelf-label').first().click({button:'right'});await option(page,reference?(bind?'Bind into one book':'Unbind'):(bind?'Bind shelf':'Unbind shelf'));await expect.poll(async()=>(await persistedLibrary(page)).shelves[0].binding?.bound??false).toBe(bind);}
test('[NEO-036-B] Leafloom: unbind restart rebind restores parked Part before second story and final About with exact rich page files',async({page})=>{
 const c=await existingBook(page,{chapters:['<p><b>First</b> story.</p>']});await c.driver.shelf();await c.driver.newBook();await c.driver.title('Second story');await c.driver.type('Second prose.');await c.driver.shelf();const stories=(await persistedLibrary(page)).shelves[0].bookIds;await binding(page,true);await page.locator('.shelf').hover();await page.locator('.part-seam').nth(1).click();await expect(page.locator('.ps-label')).toHaveText('Part I');await expect(page.locator('.ps-body')).toBeFocused();await page.keyboard.type('Movement Two');await page.keyboard.press('Enter');await page.keyboard.type('Part verse.');await page.locator('.ps-done').click();await page.locator('.shelf').hover();await page.locator('.ghost-page').filter({has:page.locator('.pt-label').filter({hasText:/^About the Author$/})}).click();await expect(page.locator('.ps-body')).toBeFocused();await page.keyboard.type('Biography words.');await page.keyboard.press(mod+'+a');await page.keyboard.press(mod+'+i');await page.locator('.ps-done').click();const order=(await persistedLibrary(page)).shelves[0].bookIds,partId=await page.locator('.page-tile.kind-part').getAttribute('data-book-id'),aboutId=await page.locator('.page-tile.kind-about').getAttribute('data-book-id');if(!partId||!aboutId)throw Error('Missing owned Part/About IDs');expect(order).toEqual([order[0],stories[0],partId,stories[1],aboutId]);await closed(page,partId);await closed(page,aboutId);const part=await byID(page,partId),about=await byID(page,aboutId),partBytes=await bytes(part.directory),aboutBytes=await bytes(about.directory);expect(part.chapters[0].html).toContain('Movement Two');expect(about.chapters[0].html).toMatch(/<(?:i|em)>Biography words\./);await binding(page,false);expect((await persistedLibrary(page)).shelves[0].bookIds).toEqual(stories);expect(await bytes(part.directory)).toEqual(partBytes);expect(await bytes(about.directory)).toEqual(aboutBytes);await page.reload();await binding(page,true);expect((await persistedLibrary(page)).shelves[0].bookIds).toEqual(order);expect(await bytes(part.directory)).toEqual(partBytes);expect(await bytes(about.directory)).toEqual(aboutBytes);await page.locator('.page-tile.kind-part').click();await expect(page.locator('.ps-body')).toContainText('Movement Two');await expect(page.locator('.ps-body')).toContainText('Part verse.');await page.keyboard.press('Escape');await page.locator('.page-tile.kind-about').click();await expect(page.locator('.ps-body i,.ps-body em')).toHaveText('Biography words.');await page.keyboard.press('Escape');expect((await byID(page,partId)).chapters).toEqual(part.chapters);expect((await byID(page,aboutId)).chapters).toEqual(about.chapters);expect((await byID(page,stories[0])).chapters[0].html).toContain('<b>First</b>');
});
