import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedLibrary} from './storage-probe';
const closed=async(page:import('@playwright/test').Page)=>{const c=await existingBook(page);await c.driver.shelf();return c;};
async function add(page:import('@playwright/test').Page,name:string){await page.locator('#add-shelf-btn').click();const label=page.locator('.shelf-label').last();await expect(label).toBeFocused();await label.fill(name);await label.press('Enter');await expect(label).toHaveText(name);}
test('[NEO-006-A] Leafloom: one-click shelf creation selects its source default name and native Enter persists replacement',async({page})=>{
 await closed(page);await page.locator('#add-shelf-btn').click();const label=page.locator('.shelf-label').last();await expect(label).toHaveText('New Shelf');await expect(label).toBeFocused();expect((await page.evaluate(()=>getSelection()?.toString()))?.toLowerCase()).toBe('new shelf');await page.keyboard.type('Working drafts');await page.keyboard.press('Enter');await expect(label).not.toBeFocused();await expect.poll(async()=>(await persistedLibrary(page)).shelves.at(-1).name).toBe('Working drafts');await page.reload();await expect(page.locator('.shelf-label').last()).toHaveText('Working drafts');
});
test('[NEO-006-B] Leafloom: Escape retains focused shelf draft until author-chip blur commits and reload preserves it',async({page})=>{
 await closed(page);const label=page.locator('.shelf-label').first();await label.fill('Pending name');await label.press('Escape');await expect(label).toBeFocused();expect((await persistedLibrary(page)).shelves[0].name).toBe('Fixture books');await page.locator('#author-chip').click();await expect.poll(async()=>(await persistedLibrary(page)).shelves[0].name).toBe('Pending name');await page.reload();await expect(page.locator('.shelf-label').first()).toHaveText('Pending name');
});
test('[NEO-006-A] Leafloom: empty shelf Enter blur restores its previous name in UI and on disk',async({page})=>{
 await closed(page);const label=page.locator('.shelf-label').first();await label.fill('');await label.press('Enter');await expect(label).toHaveText('Fixture books');expect((await persistedLibrary(page)).shelves[0].name).toBe('Fixture books');await page.reload();await expect(page.locator('.shelf-label').first()).toHaveText('Fixture books');
});
async function nativeDrag(page:import('@playwright/test').Page,from:import('@playwright/test').Locator,to:import('@playwright/test').Locator,after:boolean){await from.hover();const a=await from.boundingBox(),b=await to.boundingBox();if(!a||!b)throw Error('Native drag target missing');await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(a.x+a.width/2+10,a.y+a.height/2+10,{steps:3});const x=b.x+30,y=b.y+(after?b.height-10:10);await page.mouse.move(x,y,{steps:10});await page.mouse.move(x+1,y+1);await page.mouse.up();}
test('[NEO-007-A] Leafloom: real shelf-grip drag moves before and after neighbours with matching disk order after reload',async({page})=>{
 await page.setViewportSize({width:1100,height:1800});await closed(page);await page.evaluate(()=>{const traces:unknown[]=[];(window as unknown as {shelfDragTrace:unknown[]}).shelfDragTrace=traces;for(const type of ['dragstart','dragover','drop','dragend'])document.addEventListener(type,e=>{const ev=e as DragEvent;if(type==='dragover'&&traces.filter(x=>(x as {type:string}).type==='dragover').length>5)return;traces.push({type,target:(ev.target as HTMLElement)?.outerHTML.slice(0,250),types:[...(ev.dataTransfer?.types||[])],shelf:ev.dataTransfer?.getData('application/x-neo-shelf'),book:ev.dataTransfer?.getData('application/x-neo-book')});},true);});await add(page,'Second shelf');await add(page,'Third shelf');const third=page.locator('.shelf').filter({has:page.locator('.shelf-label').filter({hasText:'Third shelf'})});await nativeDrag(page,third.locator('.shelf-grip'),page.locator('.shelf').first(),false);await test.info().attach('native-shelf-drag-events',{body:JSON.stringify(await page.evaluate(()=>(window as unknown as {shelfDragTrace:unknown[]}).shelfDragTrace),null,2),contentType:'application/json'});await expect(page.locator('.shelf-label')).toHaveText(['Third shelf','Fixture books','Second shelf']);await expect.poll(async()=>(await persistedLibrary(page)).shelves.map((s:{name:string})=>s.name)).toEqual(['Third shelf','Fixture books','Second shelf']);const last=page.locator('.shelf').last(),box=await last.boundingBox();if(!box)throw Error('Missing real drop target');await nativeDrag(page,page.locator('.shelf-grip').first(),last,true);await expect(page.locator('.shelf-label')).toHaveText(['Fixture books','Second shelf','Third shelf']);await page.reload();await expect(page.locator('.shelf-label')).toHaveText(['Fixture books','Second shelf','Third shelf']);
});
