import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedLibrary,persistedBook} from './storage-probe';
import type {Page,Locator} from '@playwright/test';
async function setup(page:Page){const c=await existingBook(page);await c.driver.shelf();for(const title of ['Middle story','Last story']){await c.driver.newBook();await c.driver.title(title);await c.driver.type(title+' words.');await c.driver.shelf();}return c;}
async function drag(page:Page,from:Locator,target:Locator,after=false){const a=await from.boundingBox(),b=await target.boundingBox();if(!a||!b)throw Error('Missing actual cover drag bounds');await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(a.x+a.width/2+12,a.y+a.height/2+12,{steps:3});await page.mouse.move(b.x+(after?b.width-5:5),b.y+b.height/2,{steps:10});await page.mouse.move(b.x+(after?b.width-4:6),b.y+b.height/2+1);await expect(page.locator('.drop-indicator')).toBeVisible();await page.mouse.up();}
const order=async(page:Page)=>page.locator('.shelf').first().locator('.book:not(.new-book)').evaluateAll(books=>books.map(book=>book.getAttribute('data-book-id')));
test('[NEO-008-A] Leafloom: actual cover insertion indicator supports before and after neighbours with exact durable order',async({page})=>{const c=await setup(page),initial=(await persistedLibrary(page)).shelves[0].bookIds;await drag(page,page.locator('.book[data-book-id="'+initial[2]+'"]'),page.locator('.book[data-book-id="'+initial[0]+'"]'));await expect.poll(()=>order(page)).toEqual([initial[2],initial[0],initial[1]]);await expect.poll(async()=>(await persistedLibrary(page)).shelves[0].bookIds).toEqual([initial[2],initial[0],initial[1]]);await drag(page,page.locator('.book[data-book-id="'+initial[0]+'"]'),page.locator('.book[data-book-id="'+initial[1]+'"]'),true);await expect.poll(()=>order(page)).toEqual([initial[2],initial[1],initial[0]]);await page.reload();await expect.poll(()=>order(page)).toEqual([initial[2],initial[1],initial[0]]);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('Alpha beta.');});
test('[NEO-009-A] Leafloom: real cover drop into empty then populated shelf retains unique placement and original prose',async({page})=>{const c=await setup(page),initial=(await persistedLibrary(page)).shelves[0].bookIds;await page.locator('#add-shelf-btn').click();await page.locator('.shelf-label').last().fill('Destination');await page.locator('.shelf-label').last().press('Enter');const destination=page.locator('.shelf').last();await drag(page,page.locator('.book[data-book-id="'+c.id+'"]'),destination.locator('.new-book'));await expect.poll(async()=>(await persistedLibrary(page)).shelves.map((s:{bookIds:string[]})=>s.bookIds)).toEqual([[initial[1],initial[2]],[c.id]]);await drag(page,page.locator('.book[data-book-id="'+initial[2]+'"]'),destination.locator('.book[data-book-id="'+c.id+'"]'));await expect.poll(async()=>(await persistedLibrary(page)).shelves.map((s:{bookIds:string[]})=>s.bookIds)).toEqual([[initial[1]],[initial[2],c.id]]);await page.reload();await expect(destination.locator('.book:not(.new-book)')).toHaveCount(2);const ids=(await persistedLibrary(page)).shelves.flatMap((s:{bookIds:string[]})=>s.bookIds);expect([...ids].sort()).toEqual([...initial].sort());expect(new Set(ids).size).toBe(3);expect((await persistedBook(page,c.title)).chapters[0].html).toContain('Alpha beta.');});
