import {test,expect} from './author-fixture';
import type {Page} from '@playwright/test';
import {writing} from './editing-helpers';
import {persistedBook} from './storage-probe';
import {writeReferenceClipboard} from '../reference/harness';
const mod=process.platform==='darwin'?'Meta':'Control';
async function notes(page:Page){await page.locator('.tab[data-tab="notes"]').click();await expect(page.locator('#aux-editor')).toBeVisible();const editable=page.locator(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'?'#aux-editor':'#aux-editor .ProseMirror');await expect(editable).toBeVisible();await editable.click();await expect(editable).toBeFocused();}
async function paste(page:Page,text:string,html?:string){if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await writeReferenceClipboard(page,text,html);else{await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.evaluate(async({text,html})=>{await navigator.clipboard.write([new ClipboardItem({'text/plain':new Blob([text],{type:'text/plain'}),...(html?{'text/html':new Blob([html],{type:'text/html'})}:{})})]);},{text,html});}await page.keyboard.press(mod+'+v');}
const content=(page:Page)=>page.locator('#aux-editor').evaluate(el=>[...el.querySelectorAll('p')].map(p=>{const copy=p.cloneNode(true) as HTMLElement;copy.querySelectorAll('.ProseMirror-trailingBreak,.ProseMirror-separator').forEach(n=>n.remove());copy.querySelectorAll('br').forEach(n=>n.replaceWith(document.createTextNode('\n')));return copy.textContent??'';}));
test('[NEO-145-A] Leafloom: Notes native typing formatting typography Markdown and multiline paste save and reopen',async({page})=>{
 const d=await writing(page);await d.type('Manuscript stays.');await notes(page);await d.key(mod+'+b');await d.type('Bold');await d.key(mod+'+b');await d.key('Enter');await d.type('"Hello" Wait...');await d.key('Enter');await d.type('*Italic*');await d.key('Enter');await paste(page,'First\nSecond');await expect.poll(()=>content(page)).toEqual(['Bold','“Hello” Wait…','Italic','First','Second']);await expect(page.locator('#aux-editor b,#aux-editor strong')).toHaveText('Bold');await expect(page.locator('#aux-editor i,#aux-editor em')).toHaveText('Italic');await page.locator('.tab[data-tab="manuscript"]').click();await d.expectParagraphs([['Manuscript stays.']]);await d.shelf();const saved=await persistedBook(page,'Parity '+test.info().testId);expect(saved.notes).toContain('“Hello” Wait…');expect(saved.notes).toMatch(/<(i|em)>Italic<\/(i|em)>/);await d.restart();await notes(page);await expect.poll(()=>content(page)).toEqual(['Bold','“Hello” Wait…','Italic','First','Second']);
});
test('[NEO-145-B] Leafloom: Notes rich paste soft break empty paragraph and atomic flag retain clean disk and reopen',async({page})=>{
 const d=await writing(page);await notes(page);await paste(page,'Alpha⚑','<p><i>Alpha</i><span class="ph-mark" data-sid="sticky-one" contenteditable="false">⚑</span></p>');await expect.poll(()=>content(page)).toEqual(['Alpha⚑']);await page.evaluate(()=>{const el=document.querySelector('#aux-editor [contenteditable="true"]')??document.querySelector('#aux-editor')!;(el as HTMLElement).focus();const r=document.createRange();r.selectNodeContents(el);r.collapse(false);const selection=getSelection()!;selection.removeAllRanges();selection.addRange(r);});await d.key('Enter');await d.type('Soft');await d.key('Shift+Enter');await d.type('line');await d.key('Enter');await expect.poll(()=>content(page)).toEqual(['Alpha⚑','Soft\nline','']);await d.shelf();const saved=await persistedBook(page,'Parity '+test.info().testId);expect(saved.notes).not.toMatch(/ProseMirror|data-pm-|neo-spell|neo-search|<img\b/);expect(saved.notes).toContain('data-sid="sticky-one"');expect(saved.notes).toMatch(/<(i|em)>Alpha<\/(i|em)>/);await d.restart();await notes(page);await expect.poll(()=>content(page)).toEqual(['Alpha⚑','Soft\nline','']);await expect(page.locator('#aux-editor .ph-mark')).toHaveAttribute('contenteditable','false');
});
