import {test,expect} from './author-fixture';
import type {Page} from '@playwright/test';
import {existingBook,type BookFixture} from './book-fixture';
import {BrowserAuthorDriver} from './browser-driver';
type Context=Awaited<ReturnType<typeof existingBook>>;
function scenario(id:string,title:string,fixture:BookFixture,run:(ctx:Context)=>Promise<void>){test(`[${id}] Leafloom: ${title}`,async({page})=>{const ctx=await existingBook(page,fixture);try{await run(ctx);}finally{if(await page.locator('#editor-view').isVisible())await ctx.driver.shelf();}});}
const tab=async(page:Page,name:string)=>page.locator(`.tab[data-tab="${name}"]`).click();
const outlined:BookFixture={chapters:['<p>Alpha.</p>','<p>Beta.</p>'],metadata:{chapterNotes:{'ch-1':'Beginning','ch-2':'End'},sectionNotes:{'ch-1':[{id:'sec-one',text:'First beat'},{id:'sec-two',text:'Second beat'}]}}};
async function point(page:Page,selector:string,offset:number){await page.locator(selector).evaluate((el,offset)=>{(el as HTMLElement).focus();const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n:Node|null,left=offset;const r=document.createRange();while((n=w.nextNode())){if(left<=(n.textContent??'').length){r.setStart(n,left);break;}left-=(n.textContent??'').length;}if(!n)r.setStart(el,0);r.collapse(true);const s=window.getSelection()!;s.removeAllRanges();s.addRange(r);},offset);await expect(page.locator(selector)).toBeFocused();}
async function reopen(ctx:Context){await ctx.driver.reopen();}
async function assertTexts(page:Page,text:string[][]){await new BrowserAuthorDriver(page).expectParagraphs(text);}
scenario('NEO-146-A','outline chapter note syncs navigation and metadata',outlined,async(ctx)=>{await tab(ctx.page,'outline');const line=ctx.page.locator('.ol-chapter[data-ch-id="ch-1"] .ol-text');await line.fill('New beginning');await tab(ctx.page,'manuscript');await expect(ctx.page.locator(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'?'.nav-item[data-id="ch-1"] .nav-note':'.nav-item[data-chid="ch-1"] .nav-note')).toHaveText('New beginning');await reopen(ctx);await tab(ctx.page,'outline');await expect(line).toHaveText('New beginning');});
scenario('NEO-147-A','section labels wrap Z back to A',{chapters:['<p>Alpha.</p>'],metadata:{sectionNotes:{'ch-1':Array.from({length:28},(_,i)=>({id:'sec-'+i,text:'beat '+i}))}}},async({page})=>{await tab(page,'outline');expect(await page.locator('.ol-section .ol-num').allTextContents()).toEqual(Array.from({length:28},(_,i)=>String.fromCharCode(65+i%26)));});
for(const offset of [0,5])scenario('NEO-148-A',`section Enter offset ${offset} creates ${offset===0?'above':'below'}`,outlined,async({page})=>{await tab(page,'outline');await point(page,'.ol-section[data-sec-id="sec-one"] .ol-text',offset);await page.keyboard.press('Enter');expect(await page.locator('.ol-section .ol-text').allTextContents()).toEqual(offset===0?['','First beat','Second beat']:['First beat','','Second beat']);await expect(page.locator('.ol-section .ol-text').nth(offset===0?0:1)).toBeFocused();});
scenario('NEO-149-A','outline arrows move line end and clamp',outlined,async({page})=>{await tab(page,'outline');await point(page,'.ol-chapter[data-ch-id="ch-1"] .ol-text',0);await page.keyboard.press('ArrowUp');await expect(page.locator('.ol-chapter .ol-text').first()).toBeFocused();await page.keyboard.press('ArrowDown');await expect(page.locator('.ol-section .ol-text').first()).toBeFocused();expect(await page.evaluate(()=>(()=>{const s=window.getSelection()!,r=s.getRangeAt(0),pre=document.createRange();pre.selectNodeContents(document.activeElement!);pre.setEnd(r.startContainer,r.startOffset);return pre.toString().length;})())).toBe(10);await page.keyboard.press('ArrowUp');await expect(page.locator('.ol-chapter .ol-text').first()).toBeFocused();expect(await page.evaluate(()=>(()=>{const s=window.getSelection()!,r=s.getRangeAt(0),pre=document.createRange();pre.selectNodeContents(document.activeElement!);pre.setEnd(r.startContainer,r.startOffset);return pre.toString().length;})())).toBe(9);});
scenario('NEO-150-A','Tab empty second chapter becomes prior section',{chapters:['<p>Alpha.</p>','<p><br></p>'],metadata:{chapterNotes:{'ch-2':'New beat'}}},async(ctx)=>{await tab(ctx.page,'outline');await ctx.page.locator('.ol-chapter[data-ch-id="ch-2"] .ol-text').click();await ctx.page.keyboard.press('Tab');await expect(ctx.page.locator('.ol-chapter')).toHaveCount(1);await expect(ctx.page.locator('.ol-section .ol-text')).toHaveText('New beat');await tab(ctx.page,'manuscript');await expect(ctx.page.locator('.chapter-body')).toHaveCount(1);await expect(ctx.page.locator('p.ghost')).toHaveText('New beat');});
scenario('NEO-151-A','Shift Tab section creates new chapter note',outlined,async({page})=>{await tab(page,'outline');await page.locator('.ol-section[data-sec-id="sec-one"] .ol-text').click();await page.keyboard.press('Shift+Tab');await expect(page.locator('.ol-chapter')).toHaveCount(3);expect(await page.locator('.ol-chapter .ol-text').allTextContents()).toEqual(['Beginning','First beat','End']);await expect(page.locator('.ol-section .ol-text')).toHaveText('Second beat');await tab(page,'manuscript');await expect(page.locator('.chapter-body')).toHaveCount(3);});
scenario('NEO-152-A','empty section Backspace removes only section',{metadata:{sectionNotes:{'ch-1':[{id:'sec-one',text:''},{id:'sec-two',text:'Keep beat'}]}}},async({page})=>{await tab(page,'outline');await page.locator('.ol-section[data-sec-id="sec-one"] .ol-text').click();await page.keyboard.press('Backspace');await expect(page.locator('.ol-section')).toHaveCount(1);await expect(page.locator('.ol-section .ol-text')).toHaveText('Keep beat');await expect(page.locator('.ol-chapter')).toHaveCount(1);});
scenario('NEO-154-A','section notes create ordered ghosts and owned scene breaks',outlined,async({page})=>{await tab(page,'outline');await page.locator('.ol-section .ol-text').first().click();await page.locator('.ol-chapter .ol-text').first().click();await tab(page,'manuscript');await expect(page.locator('p.ghost')).toHaveText(['First beat','Second beat']);await expect(page.locator('p.scene-break[data-sec-brk]')).toHaveCount(2);expect(await page.locator('p.ghost').evaluateAll(ps=>ps.map(p=>p.getAttribute('data-sec-id')))).toEqual(['sec-one','sec-two']);});
scenario('NEO-155-A','click ghost selects text and typing overwrites without losing section ID',outlined,async({page})=>{await tab(page,'outline');await page.locator('.ol-section .ol-text').first().click();await page.locator('.ol-chapter .ol-text').first().click();await tab(page,'manuscript');await page.locator('p.ghost[data-sec-id="sec-one"]').click();expect(await page.evaluate(()=>window.getSelection()?.toString())).toBe('First beat');await page.keyboard.type('Written prose.');await expect(page.locator('p[data-sec-id="sec-one"]')).toHaveText('Written prose.');await expect(page.locator('p[data-sec-id="sec-one"]')).not.toHaveClass(/ghost/);await expect(page.locator('p.ghost')).toHaveText('Second beat');});
scenario('NEO-156-A','renaming outline ghost leaves written section intact',{chapters:['<p data-sec-id="sec-one">Written prose.</p>'],metadata:{sectionNotes:{'ch-1':[{id:'sec-one',text:'Old outline'},{id:'sec-two',text:'Untouched'}]}}},async({page})=>{await tab(page,'outline');await page.locator('.ol-section[data-sec-id="sec-one"] .ol-text').fill('Changed outline');await page.locator('.ol-section[data-sec-id="sec-two"] .ol-text').fill('Renamed ghost');await tab(page,'manuscript');await expect(page.locator('p[data-sec-id="sec-one"]')).toHaveText('Written prose.');await expect(page.locator('p.ghost[data-sec-id="sec-two"]')).toHaveText('Renamed ghost');});
for(const kind of ['ghost','written'])scenario('NEO-153-A',`delete outline section removes ${kind==='ghost'?'untouched ghost':'note only, preserves written prose'}`,{chapters:[kind==='ghost'?'<p>Alpha.</p><p class="scene-break" data-sec-brk="sec-one">***</p><p class="ghost" data-sec-id="sec-one">First beat</p>':'<p>Alpha.</p><p class="scene-break" data-sec-brk="sec-one">***</p><p data-sec-id="sec-one">Written prose.</p>'],metadata:{sectionNotes:{'ch-1':[{id:'sec-one',text:'First beat'}]}}},async({page})=>{await tab(page,'outline');await page.locator('.ol-section').click({button:'right'});if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await page.locator('.fr-choice').filter({hasText:'Delete section'}).click();else await page.getByRole('menuitem',{name:'Delete section',exact:true}).click();await expect(page.locator('.ol-section')).toHaveCount(0);await tab(page,'manuscript');await assertTexts(page,kind==='ghost'?[['Alpha.']]:[['Alpha.','***','Written prose.']]);});
scenario('NEO-157-A','outline section edit immediately flushes and reopens with ghost',outlined,async(ctx)=>{await tab(ctx.page,'outline');await ctx.page.locator('.ol-section[data-sec-id="sec-one"] .ol-text').fill('Revised beat');await reopen(ctx);await tab(ctx.page,'outline');await expect(ctx.page.locator('.ol-section[data-sec-id="sec-one"] .ol-text')).toHaveText('Revised beat');await tab(ctx.page,'manuscript');await expect(ctx.page.locator('p.ghost[data-sec-id="sec-one"]')).toHaveText('Revised beat');});
for(const offset of [0,5])scenario('NEO-148-A',`chapter Enter offset ${offset} inserts ${offset===0?'above':'below'} without moving existing section ownership`,outlined,async({page})=>{await tab(page,'outline');await point(page,'.ol-chapter[data-ch-id="ch-1"] .ol-text',offset);await page.keyboard.press('Enter');await expect(page.locator('.ol-chapter .ol-text')).toHaveText(offset===0?['','Beginning','End']:['Beginning','','End']);await expect(page.locator('.ol-chapter .ol-text').nth(offset===0?0:1)).toBeFocused();await expect(page.locator('.ol-section[data-ch-id="ch-1"]')).toHaveCount(2);await tab(page,'manuscript');await expect(page.locator('.chapter-body')).toHaveCount(3);});
for(const kind of ['first','written'])scenario('NEO-150-A',`Tab ${kind} chapter is denied with a nonblocking hint and retained prose`,{chapters:['<p>Alpha.</p>','<p>Beta.</p>']},async({page})=>{await tab(page,'outline');await page.locator(`.ol-chapter[data-ch-id="${kind==='first'?'ch-1':'ch-2'}"] .ol-text`).click();await page.keyboard.press('Tab');await expect(page.locator('#hint')).toContainText(kind==='first'?'first line':'already has words');await expect(page.locator('.ol-chapter')).toHaveCount(2);await expect(page.locator('.ol-section')).toHaveCount(0);await tab(page,'manuscript');await assertTexts(page,[['Alpha.'],['Beta.']]);});
scenario('NEO-152-A','empty nonfirst section Backspace focuses the end of prior section',{metadata:{chapterNotes:{'ch-1':'Owner'},sectionNotes:{'ch-1':[{id:'sec-one',text:'Keep beat'},{id:'sec-two',text:''}]}}},async({page})=>{await tab(page,'outline');await page.locator('.ol-section[data-sec-id="sec-two"] .ol-text').click();await page.keyboard.press('Backspace');await expect(page.locator('.ol-section')).toHaveCount(1);await expect(page.locator('.ol-section[data-sec-id="sec-one"] .ol-text')).toBeFocused();expect(await page.evaluate(()=>{const s=getSelection()!,r=document.createRange();r.selectNodeContents(document.activeElement!);r.setEnd(s.anchorNode!,s.anchorOffset);return r.toString().length;})).toBe(9);});
scenario('NEO-152-A','empty chapter Backspace removes only when another story exists',{chapters:['<p>Alpha.</p>','<p></p>']},async({page})=>{await tab(page,'outline');await page.locator('.ol-chapter[data-ch-id="ch-2"] .ol-text').click();await page.keyboard.press('Backspace');await expect(page.locator('.ol-chapter')).toHaveCount(1);await expect(page.locator('.ol-chapter[data-ch-id="ch-1"] .ol-text')).toBeFocused();await tab(page,'manuscript');await assertTexts(page,[['Alpha.']]);});
scenario('NEO-152-A','last empty story Backspace retains the sole chapter',{chapters:['<p></p>']},async({page})=>{await tab(page,'outline');await page.locator('.ol-chapter .ol-text').click();await page.keyboard.press('Backspace');await expect(page.locator('.ol-chapter')).toHaveCount(1);await expect(page.locator('.ol-chapter .ol-text')).toBeFocused();await tab(page,'manuscript');await assertTexts(page,[['']]);});
scenario('NEO-146-A','outline displays story and part roles while published pages stay outside the outline',{chapters:['<p>Legal words.</p>','<p>Opening.</p>','<p>Journey</p><p><i>A quotation.</i></p>','<p>Chapter prose.</p>','<p>Named prose.</p>','<p>Closing.</p>','<p>Thanks.</p>'],metadata:{chapterKinds:{'ch-1':'copyright','ch-2':'prologue','ch-3':'part','ch-5':'unnumbered','ch-6':'epilogue','ch-7':'acknowledgments'},chapterTitles:{'ch-5':'Named story'},chapterNotes:{'ch-2':'Before','ch-4':'During','ch-5':'Named','ch-6':'After'}}},async({page})=>{await tab(page,'outline');await expect(page.locator('.ol-line')).toHaveCount(5);expect(await page.locator('.ol-line').evaluateAll(lines=>lines.map(line=>line.getAttribute('data-ch-id')))).toEqual(['ch-2','ch-3','ch-4','ch-5','ch-6']);await expect(page.locator('.ol-chapter .ol-num')).toHaveText(['❦','1','❦','❦']);await expect(page.locator('.ol-part .ol-num')).toHaveText('I');await expect(page.locator('.ol-part-name')).toHaveText('Part I: Journey');await expect(page.locator('.ol-chapter .ol-text')).toHaveText(['Before','During','Named','After']);});
scenario('NEO-154-A','loading section-note metadata alone creates no ghosts and existing persisted ghosts are excluded from words',{chapters:['<p>Alpha.</p><p class="ghost" data-sec-id="persisted">Existing thought.</p>'],metadata:{sectionNotes:{'ch-1':[{id:'fresh',text:'Metadata only'},{id:'persisted',text:'Existing thought.'}]}}},async({page})=>{await expect(page.locator('p.ghost')).toHaveCount(1);await expect(page.locator('p.ghost')).toHaveText('Existing thought.');await expect(page.locator('#word-counter')).toHaveText('1 word');await tab(page,'outline');await expect(page.locator('.ol-section .ol-text')).toHaveText(['Metadata only','Existing thought.']);await tab(page,'manuscript');await expect(page.locator('p.ghost')).toHaveCount(1);await expect(page.locator('#word-counter')).toHaveText('1 word');});
