import {randomUUID} from 'node:crypto';
import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {defineConfig} from '@playwright/test';
import {evidenceMetadata,root} from '../evidence.mjs';
const fixture=process.env.LEAFLOOM_TEST_ROOT??mkdtempSync(path.join(tmpdir(),'leafloom-candidate-'));
const marker=path.join(fixture,'.leafloom-parity-fixture');
if(process.env.LEAFLOOM_TEST_ROOT){if(readFileSync(marker,'utf8')!=='isolated-leafloom-candidate-v1')throw Error('Candidate fixture must be a marked private parity directory');}else writeFileSync(marker,'isolated-leafloom-candidate-v1');
process.env.LEAFLOOM_TEST_ROOT=fixture;
const artifactDirectory=process.env.LEAFLOOM_CANDIDATE_ARTIFACT_DIR??=path.join(root,'.leafloom/test-results',`candidate-${Date.now()}-${randomUUID()}`);
export default defineConfig({outputDir:artifactDirectory,metadata:await evidenceMetadata('browser'),testDir:'.',testMatch:'*.spec.ts',workers:1,retries:0,timeout:45_000,expect:{timeout:10_000},reporter:[['list'],['json',{outputFile:process.env.LEAFLOOM_CANDIDATE_REPORT?path.resolve(root,process.env.LEAFLOOM_CANDIDATE_REPORT):path.join(root,'tests/neo-compat/candidate-results.json')}]],use:{headless:true,viewport:{width:1100,height:760},trace:'retain-on-failure'},webServer:{cwd:root,command:'pnpm dev',env:{LEAFLOOM_TEST_ROOT:fixture},url:'http://localhost:5190',reuseExistingServer:false,timeout:60_000}});
