import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedLibrary,persistedBook} from './storage-probe';
import {clickReferenceMenu} from '../reference/harness';
import type {Page} from '@playwright/test';
const mod=process.platform==='darwin'?'Meta':'Control';
async function cycle(page:Page){if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await clickReferenceMenu(page,['View','Focus Mode','Cycle']);else await page.keyboard.press(mod+'+Shift+o');}
async function typewriter(page:Page){if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await clickReferenceMenu(page,['Format','Typewriter Scrolling']);else await page.keyboard.press(mod+'+Shift+t');}
async function size(page:Page,delta:number){if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'&&delta===0)await clickReferenceMenu(page,['Format','Reset Text Size']);else await page.keyboard.press(mod+'+'+(delta===0?'0':delta>0?'=':'-'));}
async function highlights(page:Page){return page.evaluate(()=>[...((CSS as typeof CSS & {highlights:Map<string,Set<Range>>}).highlights.get('neo-focus')??[])].map(range=>range.toString()));}
async function caretY(page:Page){return page.evaluate(()=>getSelection()!.getRangeAt(0).getBoundingClientRect().top);}
const story=Array.from({length:60},(_,i)=>`<p>Paragraph ${i} is a line of writing.</p>`).join('');
test('[NEO-210-A] Leafloom: paragraph focus follows actual caret and retains previous manuscript highlight in Notes',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>First sentence. Second thought.</p><p>Other paragraph.</p>']});await c.driver.select(0,0,3);await cycle(page);await expect(page.locator('body')).toHaveClass(/focus-mode/);await expect.poll(()=>highlights(page)).toEqual(['First sentence. Second thought.']);await expect(page.locator('.chapter-body')).toHaveClass(/focus-cap/);await c.driver.select(0,1,2);await expect.poll(()=>highlights(page)).toEqual(['Other paragraph.']);await expect(page.locator('.chapter-body')).not.toHaveClass(/focus-cap/);await page.locator('.tab[data-tab="notes"]').click();await page.locator('#aux-editor').click();await expect.poll(()=>highlights(page)).toEqual(['Other paragraph.']);await c.driver.shelf();const library=await persistedLibrary(page);expect(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'?library.focus:library.focusMode).toBe('paragraph');expect((await persistedBook(page,c.title)).chapters[0].html).not.toMatch(/focus-cap|neo-focus/);
});
test('[NEO-211-A] Leafloom: native Focus cycle selects punctuated sentence and Off clears highlight without changing prose',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>First sentence. Second thought. Last.</p>']});await c.driver.select(0,0,19);await cycle(page);await cycle(page);await expect.poll(()=>highlights(page)).toEqual(['Second thought.']);await page.locator('.tab[data-tab="notes"]').click();await page.locator('#aux-editor').click();await expect.poll(()=>highlights(page)).toEqual(['Second thought.']);await page.locator('.tab[data-tab="manuscript"]').click();await cycle(page);await expect(page.locator('body')).not.toHaveClass(/focus-mode/);await expect.poll(()=>highlights(page)).toEqual([]);await c.driver.expectParagraphs([['First sentence. Second thought. Last.']]);
});
test('[NEO-204-A] Leafloom: trusted text-size shortcuts clamp fourteen through twenty-two without entering prose and persist',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>']});await c.driver.select(0,0,6);for(let i=0;i<12;i++)await size(page,1);await expect.poll(()=>page.locator('.chapter-body p').evaluate(p=>parseFloat(getComputedStyle(p).fontSize))).toBe(22);for(let i=0;i<15;i++)await size(page,-1);await expect.poll(()=>page.locator('.chapter-body p').evaluate(p=>parseFloat(getComputedStyle(p).fontSize))).toBe(14);await c.driver.expectParagraphs([['Alpha.']]);expect(await c.driver.caret()).toMatchObject({offset:6});await c.driver.shelf();expect((await persistedLibrary(page)).editorFontSize).toBe(14);await page.reload();await c.driver.selectBook(c.title);await expect.poll(()=>page.locator('.chapter-body p').evaluate(p=>parseFloat(getComputedStyle(p).fontSize))).toBe(14);
});
test('[NEO-204-A] Leafloom: resizing text holds the visible native caret at its reading height',async({page})=>{
 const c=await existingBook(page,{chapters:[story]});await page.locator('#paper-scroll').hover();await page.mouse.wheel(0,550);await expect.poll(()=>page.locator('#paper-scroll').evaluate(el=>el.scrollTop)).toBe(550);await c.driver.select(0,10,4);const before=await caretY(page);expect(before).toBeGreaterThan(0);expect(before).toBeLessThan(700);await size(page,1);await expect.poll(()=>page.locator('.chapter-body p').first().evaluate(p=>parseFloat(getComputedStyle(p).fontSize))).toBe(18);await expect.poll(async()=>Math.abs(await caretY(page)-before)).toBeLessThan(2);expect(await c.driver.caret()).toMatchObject({paragraph:10,offset:4});
});
test('[NEO-205-A] Leafloom: typography reset restores seventeen and page zoom one while retaining body font and interface size',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>'],library:{editorFontSize:20,pageZoom:1.8,uiZoom:1.5,fonts:{body:'Palatino',dropcap:'literary'}}});await c.driver.select(0,0,3);await size(page,0);await expect.poll(()=>page.evaluate(()=>document.documentElement.style.getPropertyValue('--editor-size'))).toBe('17px');await expect(page.locator('#zoom-level')).toHaveText('100%');expect(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--body-font'))).toContain('Palatino');expect(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--ui-zoom'))).toBe('1.5');await page.setViewportSize({width:1800,height:1000});await page.locator('#zoom-in').click();await expect(page.locator('#zoom-level')).toHaveText('110%');await page.locator('#zoom-level').click();await expect(page.locator('#zoom-level')).toHaveText('100%');
 await page.locator('#paper-scroll').hover();await page.keyboard.down('Control');await page.mouse.wheel(0,50);await page.keyboard.up('Control');await expect.poll(()=>page.locator('#zoom-level').textContent()).toBe('78%');
 await page.locator('#zoom-control').hover();await page.mouse.wheel(0,-100);await expect.poll(()=>page.locator('#zoom-level').textContent()).toBe('95%');expect(await c.driver.caret()).toMatchObject({offset:3});await page.locator('#zoom-level').click();await expect(page.locator('#zoom-level')).toHaveText('100%');
 await c.driver.shelf();const library=await persistedLibrary(page);expect(library.editorFontSize).toBe(17);expect(library.pageZoom).toBe(1);expect(library.uiZoom).toBe(1.5);expect(library.fonts.body).toBe('Palatino');
});
for(const theme of ['night','paper','light'])test(`[NEO-200-A] Leafloom: ${theme} page theme changes paper and room then persists on the library and reopen`,async({page})=>{
 const c=await existingBook(page);if(theme==='paper'){await page.emulateMedia({contrast:'more'});await expect(page.locator('body')).toHaveClass(/bright/);await page.emulateMedia({contrast:'no-preference'});await expect(page.locator('body')).not.toHaveClass(/bright/);}if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await clickReferenceMenu(page,['View','Page',theme[0].toUpperCase()+theme.slice(1)]);else{await page.locator('#view-menu').click();await page.getByRole('menuitem',{name:'Theme: '+theme,exact:true}).click();}await expect.poll(()=>page.locator('body').evaluate(el=>({night:el.classList.contains('night'),light:el.classList.contains('light')}))).toEqual({night:theme==='night',light:theme==='light'});const palette=await page.evaluate(()=>({ink:getComputedStyle(document.documentElement).getPropertyValue('--ink').trim(),paper:getComputedStyle(document.documentElement).getPropertyValue('--paper').trim(),room:getComputedStyle(document.body).backgroundColor}));expect(palette.paper).not.toBe('');await c.driver.shelf();expect((await persistedLibrary(page)).pageTheme).toBe(theme);expect(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(palette.room);await page.reload();await c.driver.selectBook(c.title);expect(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--paper').trim())).toBe(palette.paper);
});
test('[NEO-209-A] Leafloom: typewriter centers keyboard caret, leaves visible mouse choice in place and removes extra room when disabled',async({page})=>{
 const c=await existingBook(page,{chapters:[story]});const normalMargin=await page.locator('#paper').evaluate(el=>getComputedStyle(el).marginBottom);await typewriter(page);await expect(page.locator('body')).toHaveClass(/typewriter/);await c.driver.select(0,25,3);await page.keyboard.press('ArrowRight');await expect.poll(async()=>Math.abs(await caretY(page)-342)).toBeLessThan(45);const room=await page.locator('#paper').evaluate(el=>parseFloat(getComputedStyle(el).getPropertyValue('--typewriter-room')));expect(room).toBeGreaterThanOrEqual(120);expect(room).toBeLessThan(760);expect(await page.locator('#paper').evaluate(el=>parseFloat(getComputedStyle(el).marginBottom))).toBeGreaterThan(parseFloat(normalMargin));const before=await page.locator('#paper-scroll').evaluate(el=>el.scrollTop);await page.locator('.chapter-body p').nth(28).click();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));expect(Math.abs(await page.locator('#paper-scroll').evaluate(el=>el.scrollTop)-before)).toBeLessThan(3);expect(await c.driver.caret()).toMatchObject({paragraph:28});await typewriter(page);await expect(page.locator('body')).not.toHaveClass(/typewriter/);await expect.poll(()=>page.locator('#paper').evaluate(el=>getComputedStyle(el).marginBottom)).toBe(normalMargin);await c.driver.shelf();expect((await persistedLibrary(page)).typewriter).toBe(false);
});
