import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {JSDOM} from 'jsdom';
import type {Page} from '@playwright/test';
import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook} from './storage-probe';
import {SourceBook} from '../../../packages/documents/document-contracts/src/index';
import {inspectHTML} from '../../../packages/editing/prosemirror-editor/src/fidelity';
import {entries,signature} from '../../../packages/editing/prosemirror-editor/src/identity';
const original=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference';
const dom=new JSDOM('').window.document;
async function position(folder:string,pos:Record<string,unknown>,subtitle:string){const file=path.join(folder,original?'book.json':'manuscript.json'),raw=JSON.parse(await readFile(file,'utf8'));if(original){raw.lastPosition=pos;raw.subtitle=subtitle;}else{raw.metadata.lastPosition=pos;raw.metadata.subtitle=subtitle;}await writeFile(file,JSON.stringify(raw));}
async function refresh(page:Page,marker:string){await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.locator('#tp-subtitle')).toHaveText(marker);}
async function setup(page:Page){const c=await existingBook(page,{metadata:{lastPosition:{chapterId:'ch-1',pIdx:0,off:1,scroll:0,at:Date.now()-600000}}});await expect.poll(()=>c.driver.caret()).toMatchObject({paragraph:0,offset:1});return c;}
async function arriving(folder:string){const html='<p>Alpha beta.</p><p>Gamma delta.</p><p>Waiting third.</p><p>Arrived paragraph.</p>';if(original)await writeFile(path.join(folder,'chapters/ch-1.html'),html);else{const file=path.join(folder,'manuscript.json'),book=SourceBook.parse(JSON.parse(await readFile(file,'utf8'))),parsed=inspectHTML(dom,html);if(!parsed.supported)throw Error('Unsupported arrival fixture');book.chapters=book.chapters.map(ch=>{if(ch.id!=='ch-1')return ch;if(!('passages'in ch))return{...ch,html};return{...ch,html,passages:entries(parsed.model).map(e=>{const s=signature(e.node),old=ch.passages.find(p=>p.signature===s&&JSON.stringify(p.path)===JSON.stringify(e.path));return{id:old?.id??crypto.randomUUID(),path:e.path,signature:s};})};});await writeFile(file,JSON.stringify(SourceBook.parse(book)));}}

test('[NEO-244-A] Leafloom: a newer remote idle reading place follows the exact paragraph letter and preserves author identity',async({page})=>{const c=await setup(page);await position(c.folder,{chapterId:'ch-1',pIdx:1,off:4,scroll:0,at:Date.now()},'Idle remote marker');await refresh(page,'Idle remote marker');await expect.poll(()=>c.driver.caret()).toMatchObject({chapter:0,paragraph:1,offset:4,collapsed:true});await c.driver.type('X');await c.driver.expectParagraphs([['Alpha beta.','GammXa delta.']]);await c.driver.shelf();const saved=await persistedBook(page,c.title,c.id);expect(saved.metadata.id).toBe(c.id);expect(saved.chapters[0].html).toContain('GammXa delta.');});

test('[NEO-244-A] Leafloom: real Shift activity blocks a newer persisted remote spot that predates that activity',async({page})=>{const c=await setup(page),at=Date.now();await position(c.folder,{chapterId:'ch-1',pIdx:1,off:4,at},'Activity remote marker');await expect.poll(()=>page.evaluate(()=>Date.now())).toBeGreaterThan(at);await page.keyboard.press('Shift');await refresh(page,'Activity remote marker');expect(await c.driver.caret()).toMatchObject({paragraph:0,offset:1});await c.driver.type('X');await c.driver.expectParagraphs([['AXlpha beta.','Gamma delta.']]);await c.driver.shelf();expect((await persistedBook(page,c.title,c.id)).chapters[0].html).toContain('AXlpha beta.');});

test('[NEO-244-A] Leafloom: an actual open Goals dialog blocks remote caret following despite a newer spot',async({page})=>{const c=await setup(page);await page.locator('#goal-counter').click();await expect(page.locator('#st-daily')).toBeVisible();await page.locator('#st-daily').click();await expect(page.locator('#st-daily')).toBeFocused();const opened=Date.now();await expect.poll(()=>page.evaluate(()=>Date.now())).toBeGreaterThan(opened);await position(c.folder,{chapterId:'ch-1',pIdx:1,off:4,at:Date.now()},'Modal remote marker');await refresh(page,'Modal remote marker');await expect(page.locator('#st-daily')).toBeVisible();await expect(page.locator('#st-daily')).toBeFocused();await page.locator('#st-daily').press('Escape');await expect(page.locator('#st-daily')).toHaveCount(0);if(original){expect(await c.driver.caret()).toBeNull();test.info().annotations.push({type:'source-characterization',description:'NEO app7106–7118 removes the Goals backdrop without restoring the prior body selection after input focus. Leafloom must preserve its master caret; original continuation explicitly selects the prior author location.'});await c.driver.select(0,0,1);}else{await expect.poll(()=>c.driver.caret()).toMatchObject({paragraph:0,offset:1});}await c.driver.type('X');await c.driver.expectParagraphs([['AXlpha beta.','Gamma delta.']]);await c.driver.shelf();expect((await persistedBook(page,c.title,c.id)).chapters[0].html).toContain('AXlpha beta.');});

test('[NEO-244-A] Leafloom: a recent missing remote paragraph waits and then follows when its real prose arrives',async({page})=>{const c=await setup(page),at=Date.now();await position(c.folder,{chapterId:'ch-1',pIdx:3,off:7,at},'Pending remote marker');await refresh(page,'Pending remote marker');expect(await c.driver.caret()).toMatchObject({paragraph:0,offset:1});await arriving(c.folder);await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await c.driver.expectParagraphs([['Alpha beta.','Gamma delta.','Waiting third.','Arrived paragraph.']]);await expect.poll(()=>c.driver.caret()).toMatchObject({paragraph:3,offset:7});await c.driver.type('X');await c.driver.expectParagraphs([['Alpha beta.','Gamma delta.','Waiting third.','ArrivedX paragraph.']]);await c.driver.shelf();expect((await persistedBook(page,c.title,c.id)).chapters[0].html).toContain('ArrivedX paragraph.');});

test('[NEO-244-A] Leafloom: an idle remote spot older than two minutes falls back from a missing paragraph to the final paragraph end',async({page})=>{const c=await setup(page);await position(c.folder,{chapterId:'ch-1',pIdx:999,off:999,at:Date.now()-121000},'Old remote marker');await refresh(page,'Old remote marker');await expect.poll(()=>c.driver.caret()).toMatchObject({paragraph:1,offset:12});await c.driver.type('X');await c.driver.expectParagraphs([['Alpha beta.','Gamma delta.X']]);await c.driver.shelf();expect((await persistedBook(page,c.title,c.id)).chapters[0].html).toContain('Gamma delta.X');});
