import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook} from './storage-probe';
import type {Page} from '@playwright/test';
import {clickReferenceMenu} from '../reference/harness';
const mod=process.platform==='darwin'?'Meta':'Control';
async function find(page:Page,query:string){if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await clickReferenceMenu(page,['Edit','Find & Replace']);else await page.keyboard.press(mod+'+f');await expect(page.locator('#search-input')).toBeFocused();await page.locator('#search-input').fill(query);}
const tab=(page:Page,name:string)=>page.locator(`.tab[data-tab="${name}"]`).click();
async function ranges(page:Page,name:string){return page.evaluate(name=>{const highlights=(CSS as typeof CSS & {highlights:Map<string,Set<Range>>}).highlights;return [...(highlights.get(name)??[])].map(range=>range.toString());},name);}
const rich={id:'darling-one',html:'<p>Al<b>pha</b> Alpha <i>[beta]</i></p>',text:'Alpha Alpha [beta]',chapterId:'ch-1',chapterLabel:'Alpha owner',date:'2026-10-02T10:00:00Z'};
test('[NEO-161-A] Leafloom: Find cannot cross formatted text-node boundaries in manuscript or Darling excerpts',async({page})=>{
 await existingBook(page,{chapters:['<p>Al<b>pha</b> Alpha.</p>'],darlings:[rich]});await find(page,'Alpha');await expect(page.locator('#search-count')).toHaveText('1 found');await tab(page,'darlings');await expect(page.locator('#search-count')).toHaveText('1 found');await expect(page.locator('.darling b')).toHaveText('pha');
});
test('[NEO-162-A] Leafloom: Find scopes Manuscript Notes Outline and Darlings while auxiliary Replace controls stay hidden',async({page})=>{
 await existingBook(page,{chapters:['<p>Alpha Alpha.</p>'],notes:'<p>Alpha Alpha Alpha.</p>',metadata:{chapterNotes:{'ch-1':'Alpha Alpha Alpha Alpha'}},darlings:[rich,{...rich,id:'darling-two',html:'<p>Alpha.</p>',text:'Alpha.'}]});await find(page,'Alpha');await expect(page.locator('#search-count')).toHaveText('2 found');await expect(page.locator('#replace-input')).toBeVisible();for(const [name,count] of [['notes','3 found'],['outline','4 found'],['darlings','2 found']]){await tab(page,name);await expect(page.locator('#search-count')).toHaveText(count);await expect(page.locator('#replace-input')).toBeHidden();await expect(page.locator('#replace-one')).toBeHidden();await expect(page.locator('#replace-all')).toBeHidden();}await tab(page,'manuscript');await expect(page.locator('#search-count')).toHaveText('2 found');await expect(page.locator('#replace-input')).toBeVisible();
});
test('[NEO-163-A] Leafloom: Darling Find excludes metadata and actions, highlights literal rich runs and saves no search markup',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Manuscript.</p>'],darlings:[rich]});await tab(page,'darlings');await find(page,'Alpha');await expect(page.locator('#search-count')).toHaveText('1 found');await expect.poll(()=>ranges(page,'neo-search')).toEqual(['Alpha']);await page.locator('#search-input').press('Enter');await expect(page.locator('#search-count')).toHaveText('1 of 1');await expect.poll(()=>ranges(page,'neo-search-current')).toEqual(['Alpha']);expect(await page.evaluate(()=>getSelection()?.toString())).toBe('');for(const query of ['owner','2026','Restore','Discard']){await page.locator('#search-input').fill(query);await expect(page.locator('#search-count')).toHaveText('none');await expect.poll(()=>ranges(page,'neo-search')).toEqual([]);}await page.locator('#search-input').fill('[beta]');await expect(page.locator('#search-count')).toHaveText('1 found');await expect.poll(()=>ranges(page,'neo-search')).toEqual(['[beta]']);await page.locator('#search-input').press('Escape');await expect(page.locator('#searchbar')).toBeHidden();await expect.poll(()=>ranges(page,'neo-search')).toEqual([]);await c.driver.shelf();const saved=await persistedBook(page,c.title);expect(saved.darlings[0].html).toBe(rich.html);expect(saved.chapters[0].html).not.toMatch(/search-hit|neo-search/);expect(saved.darlings[0].html).not.toMatch(/search-hit|neo-search/);
});
test('[NEO-168-A] Leafloom: closed Find retains its query and tab switches refresh matches for current auxiliary content',async({page})=>{
 await existingBook(page,{chapters:['<p>Alpha.</p>'],notes:'<p>Alpha Alpha.</p>',metadata:{chapterNotes:{'ch-1':'Alpha Alpha Alpha'}},darlings:[rich]});await find(page,'Alpha');await page.locator('#search-input').press('Escape');await expect(page.locator('#searchbar')).toBeHidden();if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await clickReferenceMenu(page,['Edit','Find & Replace']);else await page.keyboard.press(mod+'+f');await expect(page.locator('#search-input')).toHaveValue('Alpha');await expect(page.locator('#search-count')).toHaveText('1 found');await tab(page,'notes');await expect(page.locator('#search-count')).toHaveText('2 found');await tab(page,'outline');await expect(page.locator('#search-count')).toHaveText('3 found');await tab(page,'darlings');await expect(page.locator('#search-count')).toHaveText('1 found');await page.locator('#search-close').click();await expect(page.locator('#searchbar')).toBeHidden();if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await clickReferenceMenu(page,['Edit','Find & Replace']);else await page.keyboard.press(mod+'+f');await expect(page.locator('#search-input')).toHaveValue('Alpha');await expect(page.locator('#search-count')).toHaveText('1 found');
});
test('[NEO-163-A] Leafloom: Find debounces actual query input for 250 milliseconds and replaces the pending query',async({page})=>{await existingBook(page,{chapters:['<p>Alpha Beta Beta.</p>']});if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference')await clickReferenceMenu(page,['Edit','Find & Replace']);else await page.keyboard.press(mod+'+f');await expect(page.locator('#search-input')).toBeFocused();await page.clock.install({time:new Date('2026-10-02T12:00:00Z')});await page.clock.pauseAt(new Date('2026-10-02T12:00:01Z'));await page.locator('#search-input').fill('Alpha');await page.clock.runFor(100);await page.locator('#search-input').fill('Beta');await page.clock.runFor(249);expect(await page.locator('#search-count').textContent()).toBe('');await page.clock.runFor(1);await expect(page.locator('#search-count')).toHaveText('2 found');});
test('[NEO-164-A] Leafloom: Find next reveals an offscreen later match without selecting or rewriting prose',async({page})=>{const paragraphs=Array.from({length:90},(_,i)=>`<p>Line ${i}: ${i===70?'Needle':'ordinary prose'}.</p>`).join('');const c=await existingBook(page,{chapters:[paragraphs]});await c.driver.select(0,0,4);const before=await c.driver.caret();await find(page,'Needle');await expect(page.locator('#search-count')).toHaveText('1 found');await page.locator('#search-input').press('Enter');await expect(page.locator('#search-count')).toHaveText('1 of 1');await expect.poll(()=>page.locator('.chapter-body p').nth(70).evaluate(p=>{const r=p.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;})).toBe(true);expect(await page.evaluate(()=>getSelection()?.toString())).toBe('');await c.driver.shelf();const saved=await persistedBook(page,c.title);expect(saved.chapters[0].html).toContain('Line 70: Needle.');expect(saved.chapters[0].html).not.toMatch(/neo-search|search-hit/);expect(before).toMatchObject({paragraph:0,offset:4});});
