import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook} from './storage-probe';
import type {Page} from '@playwright/test';
const mod=process.platform==='darwin'?'Meta':'Control';
async function create(page:Page,selected=false){const c=await existingBook(page,{chapters:['<p>Alpha.</p>','<p>Beta.</p>']});await c.driver.select(0,0,selected?0:6,selected?5:undefined);await page.keyboard.press(mod+'+Shift+x');const note=page.locator('#sticky-list textarea').first();await expect(note).toBeFocused();await expect(note).toHaveValue('');return {...c,note};}
const noteList=async(page:Page,title:string)=>(await persistedBook(page,title)).stickies as {id:string,chapterId:string,text:string,resolved:boolean}[];
test('[NEO-122-A] Leafloom: actual Sticky shortcut inserts noneditable paired flag, empty focused note and owning chapter red dot',async({page})=>{
 const c=await create(page);const mark=page.locator('.chapter-body .ph-mark');await expect(mark).toHaveCount(1);await expect(mark).toHaveAttribute('contenteditable','false');await expect(mark).toHaveText('⚑');await expect(page.locator('#side-pane')).toHaveClass(/open/);await expect(page.locator('#nav-list .nav-item').first().locator('.n-flag')).toHaveCount(1);await c.driver.shelf();const saved=await persistedBook(page,c.title);expect(saved.stickies).toHaveLength(1);expect(saved.stickies[0]).toMatchObject({text:'',chapterId:saved.chapters[0].id,resolved:false});expect(saved.chapters[0].html).toContain('data-sid="'+saved.stickies[0].id+'"');
});
test('[NEO-123-A] Leafloom: selected words survive Sticky creation at selection end and subsequent page typing',async({page})=>{
 const c=await create(page,true);await expect(page.locator('.chapter-body p').first()).toHaveText('Alpha⚑ .');await c.note.press('Enter');await page.keyboard.type('Z');await expect(page.locator('.chapter-body p').first()).toHaveText('Alpha⚑ Z.');await c.driver.shelf();const saved=await persistedBook(page,c.title);expect(saved.chapters[0].html).toMatch(/Alpha<span[^>]*ph-mark[^>]*>⚑<\/span> Z\./);expect(saved.stickies).toHaveLength(1);
});
test('[NEO-124-A] Leafloom: multiline Sticky idle debounce writes actual note text and immediate shelf flush retains follow-up',async({page})=>{
 const c=await create(page);await c.note.fill('First line\nSecond line');await expect.poll(async()=> (await noteList(page,c.title))[0]?.text).toBe('First line\nSecond line');await c.note.press('End');await c.note.type(' immediate');await c.driver.shelf();expect((await noteList(page,c.title))[0].text).toBe('First line\nSecond line immediate');await c.driver.selectBook(c.title);if(!(await page.locator('#side-pane').evaluate(el=>el.classList.contains('open'))))await page.locator('#side-hotzone').hover();await expect(page.locator('#sticky-list textarea')).toHaveValue('First line\nSecond line immediate');
});
for(const pinned of [false,true])test(`[NEO-125-A] Leafloom: Sticky Shift Enter keeps newline and Enter returns past flag with ${pinned?'pinned':'auto-open unpinned'} pane`,async({page})=>{
 const c=await create(page);if(pinned){await page.locator('#side-pin').click();await c.note.focus();}await c.note.type('First');await c.note.press('Shift+Enter');await c.note.type('Second');await expect(c.note).toHaveValue('First\nSecond');await c.note.press('Enter');await page.mouse.move(550,30);await expect.poll(()=>page.locator('#paper-scroll').evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.keyboard.type('X');await expect(page.locator('.chapter-body p').first()).toHaveText('Alpha.⚑ X');await expect(page.locator('#side-pane')).toHaveClass(pinned?/open/:/^(?!.*\bopen\b)/);await c.driver.shelf();expect((await noteList(page,c.title))[0].text).toBe('First\nSecond');
});
test('[NEO-126-A] Leafloom: Sticky Go to returns from Notes to owning offscreen manuscript flag and exact insertion point',async({page})=>{
 const c=await existingBook(page,{chapters:[Array.from({length:28},(_,i)=>`<p>First line ${i}.</p>`).join(''),'<p>Beta<span class="ph-mark" data-sid="note-two" contenteditable="false">⚑</span> .</p>'],stickies:[{id:'note-two',chapterId:'ch-2',text:'Visit beta',resolved:false}]});await page.locator('.tab[data-tab="notes"]').click();if(!(await page.locator('#side-pane').evaluate(el=>el.classList.contains('open'))))await page.locator('#side-hotzone').hover();await page.locator('.sticky').getByRole('button',{name:/^Go to( passage)?$/,exact:true}).click();await expect(page.locator('.tab[data-tab="manuscript"]')).toHaveAttribute('aria-selected','true');await expect.poll(()=>page.locator('.chapter-body .ph-mark').evaluate(el=>{const r=el.getBoundingClientRect(),p=document.querySelector('#paper-scroll')!.getBoundingClientRect();return r.top>=p.top&&r.bottom<=p.bottom;})).toBe(true);await page.keyboard.type('Z');await expect(page.locator('.chapter-body').nth(1).locator('p')).toHaveText('Beta⚑ Z.');await c.driver.shelf();expect((await persistedBook(page,c.title)).chapters[1].html).toContain(' Z.');
});
test('[NEO-127-A] Leafloom: Resolve removes paired note and red dot while normalizing neighboring NBSP spaces on real disk',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha&nbsp;<span class="ph-mark" data-sid="old-note" contenteditable="false">⚑</span>&nbsp;beta.</p>'],stickies:[{id:'old-note',chapterId:'ch-1',text:'Resolve me',resolved:false}]});if(!(await page.locator('#side-pane').evaluate(el=>el.classList.contains('open'))))await page.locator('#side-hotzone').hover();await page.locator('.sticky').getByRole('button',{name:'Resolve',exact:true}).click();await expect(page.locator('.ph-mark')).toHaveCount(0);await expect(page.locator('.sticky')).toHaveCount(0);await expect(page.locator('.n-flag')).toHaveCount(0);await expect(page.locator('.chapter-body p')).toHaveText('Alpha beta.');await c.driver.shelf();const saved=await persistedBook(page,c.title);expect(saved.stickies).toHaveLength(0);expect(saved.chapters[0].html).not.toMatch(/ph-mark|data-sid|&nbsp;|\u00a0/);expect(saved.chapters[0].html).toContain('Alpha beta.');
});
test('[NEO-128-A] Leafloom: clicking an actual manuscript flag focuses its own note without replacing styled prose',async({page})=>{
 const c=await existingBook(page,{chapters:['<p><i>Alpha</i><span class="ph-mark" data-sid="flag-note" contenteditable="false">⚑</span> beta.</p>'],stickies:[{id:'flag-note',chapterId:'ch-1',text:'Keep this note',resolved:false}]});await page.locator('.ph-mark').click();await expect(page.locator('#sticky-list textarea')).toBeFocused();await expect(page.locator('#sticky-list textarea')).toHaveValue('Keep this note');await expect(page.locator('.chapter-body p')).toHaveText('Alpha⚑ beta.');await expect(page.locator('.chapter-body i,.chapter-body em')).toHaveText('Alpha');await c.driver.shelf();expect((await persistedBook(page,c.title)).chapters[0].html).toMatch(/<(i|em)>Alpha<\/(i|em)>/);
});
async function pasteSticky(page:Page,text:string,html:string){if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'){const {writeReferenceClipboard}=await import('../reference/harness');await writeReferenceClipboard(page,text,html);}else{await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.evaluate(async({text,html})=>navigator.clipboard.write([new ClipboardItem({'text/plain':new Blob([text],{type:'text/plain'}),'text/html':new Blob([html],{type:'text/html'})})]),{text,html});}await page.keyboard.press(mod+'+v');}
test('[NEO-129-A] Leafloom: rich native paste pairs an orphan flag with a new empty note retaining its unused identity',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>']});await c.driver.select(0,0,6);await pasteSticky(page,' Orphan⚑','<p> Orphan<span class="ph-mark" data-sid="external-note" contenteditable="false">⚑</span></p>');await expect(page.locator('.ph-mark')).toHaveCount(1);await expect(page.locator('.ph-mark')).toHaveAttribute('data-sid','external-note');if(!(await page.locator('#side-pane').evaluate(el=>el.classList.contains('open'))))await page.locator('#side-hotzone').hover();await expect(page.locator('.sticky textarea')).toHaveValue('');await c.driver.shelf();const saved=await persistedBook(page,c.title);expect(saved.stickies).toHaveLength(1);expect(saved.stickies[0]).toMatchObject({id:'external-note',chapterId:saved.chapters[0].id,text:'',resolved:false});
});
test('[NEO-129-A] Leafloom: duplicate pasted flag receives a fresh identity and copied note without overwriting its original pairing',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha<span class="ph-mark" data-sid="original-note" contenteditable="false">⚑</span> .</p>','<p>Beta.</p>'],stickies:[{id:'original-note',chapterId:'ch-1',text:'Keep rich note',resolved:false}]});await c.driver.select(1,0,5);await pasteSticky(page,' Copy⚑','<p> Copy<span class="ph-mark" data-sid="original-note" contenteditable="false">⚑</span></p>');await expect(page.locator('.ph-mark')).toHaveCount(2);const ids=await page.locator('.ph-mark').evaluateAll(m=>m.map(el=>el.getAttribute('data-sid')));expect(new Set(ids).size).toBe(2);expect(ids[0]).toBe('original-note');await c.driver.shelf();const saved=await persistedBook(page,c.title);expect(saved.stickies).toHaveLength(2);expect(saved.stickies.find((s:{id:string})=>s.id==='original-note')).toMatchObject({chapterId:'ch-1',text:'Keep rich note'});expect(saved.stickies.find((s:{id:string})=>s.id!== 'original-note')).toMatchObject({chapterId:'ch-2',text:'Keep rich note'});
});
test('[NEO-129-A] Leafloom: actual cross-chapter native cut and paste transfers the flag and its note ownership',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha<span class="ph-mark" data-sid="moving-note" contenteditable="false">⚑</span> .</p>','<p>Beta.</p>'],stickies:[{id:'moving-note',chapterId:'ch-1',text:'Travel with prose',resolved:false}]});if(process.env.LEAFLOOM_PARITY_DRIVER!=='neo-reference')await page.context().grantPermissions(['clipboard-read','clipboard-write']);await c.driver.select(0,0,0,8);await page.keyboard.press(mod+'+x');await c.driver.select(1,0,5);await page.keyboard.press(mod+'+v');await expect(page.locator('.chapter-body').first().locator('.ph-mark')).toHaveCount(0);await expect(page.locator('.chapter-body').nth(1).locator('.ph-mark')).toHaveAttribute('data-sid','moving-note');await c.driver.shelf();const saved=await persistedBook(page,c.title);expect(saved.stickies.find((s:{id:string})=>s.id==='moving-note')).toMatchObject({chapterId:'ch-2',text:'Travel with prose'});expect(saved.chapters[1].html).toContain('Alpha');
});
test('[NEO-130-A] Leafloom: adjacent flag deletion resolves its note and unified Undo restores the intact pairing where supported',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha<span class="ph-mark" data-sid="undo-note" contenteditable="false">⚑</span> beta.</p>'],stickies:[{id:'undo-note',chapterId:'ch-1',text:'Never lose note text',resolved:false}]});await page.evaluate(()=>{const mark=document.querySelector('.ph-mark')!,body=mark.closest('.chapter-body')!;((body.querySelector('[contenteditable="true"]')??body) as HTMLElement).focus();const r=document.createRange();r.setStartAfter(mark);r.collapse(true);const s=getSelection()!;s.removeAllRanges();s.addRange(r);});await page.keyboard.press('Backspace');await expect(page.locator('.ph-mark')).toHaveCount(0);await expect(page.locator('.sticky')).toHaveCount(0);await c.driver.undo();if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'){await expect(page.locator('.ph-mark')).toHaveCount(0);await expect(page.locator('.sticky')).toHaveCount(0);}else{await expect(page.locator('.ph-mark')).toHaveAttribute('data-sid','undo-note');if(!(await page.locator('#side-pane').evaluate(el=>el.classList.contains('open'))))await page.locator('#side-hotzone').hover();await expect(page.locator('.sticky textarea')).toHaveValue('Never lose note text');await c.driver.redo();await expect(page.locator('.ph-mark')).toHaveCount(0);await expect(page.locator('.sticky')).toHaveCount(0);}await c.driver.shelf();expect((await persistedBook(page,c.title)).stickies).toHaveLength(0);
});
test('[NEO-125-A] Leafloom: Enter keeps an already-open unpinned note pane while returning to its flag',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha.</p>']});if(!(await page.locator('#side-pane').evaluate(el=>el.classList.contains('open'))))await page.locator('#side-hotzone').hover();await expect(page.locator('#side-pane')).toHaveClass(/open/);await c.driver.select(0,0,6);await page.keyboard.press(mod+'+Shift+x');const note=page.locator('.sticky textarea');await expect(note).toBeFocused();await note.type('Already open');await note.press('Enter');await expect(page.locator('#side-pane')).toHaveClass(/open/);await page.keyboard.type('X');await expect(page.locator('.chapter-body p')).toHaveText('Alpha.⚑ X');await c.driver.shelf();expect((await persistedBook(page,c.title)).stickies[0].text).toBe('Already open');
});
test('[NEO-126-A] Leafloom: Go to an already-visible flag preserves manuscript scroll and typing lands past its space',async({page})=>{
 const c=await existingBook(page,{chapters:['<p>Alpha<span class="ph-mark" data-sid="visible-note" contenteditable="false">⚑</span> beta.</p>'],stickies:[{id:'visible-note',chapterId:'ch-1',text:'Visible',resolved:false}]});await page.locator('#paper-scroll').hover();await page.mouse.wheel(0,600);await expect.poll(()=>page.locator('.ph-mark').evaluate(el=>{const r=el.getBoundingClientRect(),p=document.querySelector('#paper-scroll')!.getBoundingClientRect();return r.top>=p.top+40&&r.bottom<=p.bottom-40;})).toBe(true);const before=await page.locator('#paper-scroll').evaluate(el=>el.scrollTop);if(!(await page.locator('#side-pane').evaluate(el=>el.classList.contains('open'))))await page.locator('#side-hotzone').hover();await page.locator('.sticky').getByRole('button',{name:/^Go to( passage)?$/,exact:true}).click();expect(await page.locator('#paper-scroll').evaluate(el=>el.scrollTop)).toBeCloseTo(before,0);await page.keyboard.type('Z');await expect(page.locator('.chapter-body p')).toHaveText('Alpha⚑ Zbeta.');await c.driver.shelf();expect((await persistedBook(page,c.title)).chapters[0].html).toContain(' Zbeta.');
});
