import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook,persistedLibrary} from './storage-probe';
async function wheelScroll(page:import('@playwright/test').Page,delta:number){const scroll=page.locator('#paper-scroll');await scroll.hover();const before=await scroll.evaluate(el=>el.scrollTop);await page.mouse.wheel(0,delta);await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeGreaterThan(before);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));return scroll.evaluate(el=>el.scrollTop);}
async function geometry(page:import('@playwright/test').Page,label:string){const value=await page.evaluate(()=>{const scroller=document.querySelector<HTMLElement>('#paper-scroll')!,rect=(el:Element|null)=>{if(!el)return null;const r=el.getBoundingClientRect();return{top:r.top,height:r.height,bottom:r.bottom};},selection=getSelection();return{scrollTop:scroller.scrollTop,scrollHeight:scroller.scrollHeight,clientHeight:scroller.clientHeight,paper:rect(document.querySelector('#paper')),aux:rect(document.querySelector('#aux-paper')),chapters:[...document.querySelectorAll('.chapter')].map(rect),activeElement:document.activeElement?.outerHTML.slice(0,200),selectionText:selection?.toString(),anchorOffset:selection?.anchorOffset,anchorText:selection?.anchorNode?.textContent?.slice(0,120)};});await test.info().attach(label,{body:JSON.stringify(value,null,2),contentType:'application/json'});return value;}
const tab=(page:import('@playwright/test').Page,name:string)=>page.locator(`.tab[data-tab="${name}"]`);
for(const kind of ['notes','outline'] as const)test(`[NEO-144-A] Leafloom: ${kind} tab double-click rename persists book identity and future-book default`,async({page})=>{
 const c=await existingBook(page),custom=kind==='notes'?'Research journal':'Story map';await tab(page,kind).dblclick();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();const input=dialog.locator('input');await expect(input).toHaveValue(kind==='notes'?'Notes':'Outline');await input.fill(custom);await input.press('Enter');await expect(dialog).toBeHidden();await expect(tab(page,kind)).toHaveText(custom);await expect(tab(page,kind)).toHaveAttribute('aria-selected','true');if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'){await expect(page.locator('#aux-title')).toHaveText(kind==='notes'?'Notes':'Outline');await tab(page,'manuscript').click();await tab(page,kind).click();}await expect(page.locator('#aux-title')).toHaveText(custom);await c.driver.shelf();expect((await persistedBook(page,c.title)).metadata.tabNames[kind]).toBe(custom);await expect.poll(async()=>(await persistedLibrary(page)).tabDefaults?.[kind]).toBe(custom);await page.reload();await c.driver.selectBook(c.title);await expect(tab(page,kind)).toHaveText(custom);await c.driver.shelf();await c.driver.newBook();await expect(tab(page,kind)).toHaveText(custom);
});
test('[NEO-144-A] Leafloom: blank or cancelled rename retains custom label while only Notes and Outline are renameable',async({page})=>{
 const c=await existingBook(page,{metadata:{tabNames:{notes:'Journal',outline:'Map'}}});await tab(page,'notes').dblclick();let dialog=page.getByRole('dialog');await expect(dialog.locator('input')).toHaveValue('Journal');await dialog.locator('input').fill('');await dialog.locator('input').press('Enter');await expect(dialog).toBeHidden();await expect(tab(page,'notes')).toHaveText('Journal');await tab(page,'outline').dblclick();dialog=page.getByRole('dialog');await dialog.locator('input').fill('Uncommitted');await dialog.locator('input').press('Escape');await expect(dialog).toBeHidden();if(process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference'){await expect(page.locator('#bookshelf-view')).toBeVisible();await c.driver.selectBook(c.title);}else await expect(page.locator('#editor-view')).toBeVisible();await expect(tab(page,'outline')).toHaveText('Map');for(const kind of ['manuscript','darlings']){await tab(page,kind).dblclick();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(tab(page,kind)).toHaveAttribute('aria-selected','true');}
});
test('[NEO-144-A] Leafloom: all four native tab buttons project exactly one active ARIA workspace',async({page})=>{
 const c=await existingBook(page);for(const kind of ['notes','outline','darlings','manuscript']){await tab(page,kind).click();await expect(page.locator('.tab[aria-selected="true"]')).toHaveCount(1);await expect(tab(page,kind)).toHaveAttribute('aria-selected','true');if(kind==='manuscript')await expect(page.locator('#paper')).toBeVisible();else{await expect(page.locator('#paper')).toBeHidden();await expect(page.locator(kind==='notes'?'#aux-editor':kind==='outline'?'#outline-list':'#darlings-list')).toBeVisible();}}await c.driver.select(0,0,6);await c.driver.type('X');await c.driver.expectParagraphs([['Alpha Xbeta.','Gamma delta.']]);
});
test('[NEO-158-A] Leafloom: manuscript caret and Notes scroll return independently after writing and switching workspaces',async({page})=>{
 const paragraphs=Array.from({length:80},(_,i)=>`<p>Manuscript line ${i} with text.</p>`).join(''),notes=Array.from({length:100},(_,i)=>`<p>Research line ${i}.</p>`).join('');const c=await existingBook(page,{chapters:[paragraphs],notes});const scroll=page.locator('#paper-scroll');await c.driver.select(0,30,10);await c.driver.type('X');const manuscriptScroll=await wheelScroll(page,800);expect(manuscriptScroll).toBeGreaterThan(100);const caret=await c.driver.caret();await geometry(page,'manuscript-before-tab');await tab(page,'notes').click();await expect(page.locator('#aux-editor')).toBeVisible();await expect(page.locator('#aux-editor')).toContainText('Research line 99.');const notesScroll=await wheelScroll(page,1400);await geometry(page,'notes-before-tab');await tab(page,'manuscript').click();await expect.poll(()=>c.driver.caret()).toEqual(caret);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await geometry(page,'manuscript-return');await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeCloseTo(manuscriptScroll,0);await c.driver.type('Y');await expect(page.locator('.chapter-body p').nth(30)).toHaveText('ManuscriptXY line 30 with text.');await tab(page,'notes').click();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await geometry(page,'notes-return');await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeCloseTo(notesScroll,0);
});
test('[NEO-144-A] Leafloom: Outline and Darlings remember their independent long-workspace scroll positions',async({page})=>{const chapters=Array.from({length:35},(_,i)=>`<p>Chapter ${i} prose.</p>`),chapterNotes=Object.fromEntries(chapters.map((_,i)=>['ch-'+(i+1),'Planning note for chapter '+i])),darlings=Array.from({length:70},(_,i)=>({id:'saved-'+i,html:`<p>Saved excerpt ${i}: the river keeps moving.</p>`,text:`Saved excerpt ${i}: the river keeps moving.`,chapterId:'ch-1',chapterLabel:'Chapter 1',date:'2026-10-02T10:00:00Z'}));await existingBook(page,{chapters,metadata:{chapterNotes},darlings});const scroll=page.locator('#paper-scroll');await tab(page,'outline').click();await expect(page.locator('#outline-list')).toBeVisible();const outlineScroll=await wheelScroll(page,650);expect(outlineScroll).toBeGreaterThan(200);await tab(page,'darlings').click();await expect(page.locator('.darling')).toHaveCount(70);const darlingScroll=await wheelScroll(page,1200);expect(darlingScroll).toBeGreaterThan(500);await tab(page,'notes').click();await tab(page,'outline').click();await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeCloseTo(outlineScroll,0);await tab(page,'darlings').click();await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeCloseTo(darlingScroll,0);await expect(page.locator('.darling')).toHaveCount(70);});
