import {test,expect} from './author-fixture';
import {existingBook} from './book-fixture';
import {persistedBook,persistedLibrary} from './storage-probe';
import {clickReferenceMenu} from '../reference/harness';
import type {Page} from '@playwright/test';
const reference=process.env.LEAFLOOM_PARITY_DRIVER==='neo-reference';
async function toggle(page:Page){if(reference)await clickReferenceMenu(page,['View','Vim Keys']);else{await page.locator('#format-menu').click();await page.getByRole('menuitem',{name:'Vim mode',exact:true}).click();}}
async function setup(page:Page,chapters=['<p>Alpha beta. Gamma.</p>']){const c=await existingBook(page,{chapters,library:{vimKeys:true}});await c.driver.select(0,0,0);await page.keyboard.press('Escape');await expect(page.locator('body')).toHaveClass(/vim-nav/);return c;}
test('[NEO-219-A] Leafloom: Vim Escape stays in navigation i inserts and disabling persists without changing prose',async({page})=>{
 const c=await setup(page);await page.keyboard.press('Escape');await expect(page.locator('#editor-view')).toBeVisible();await page.keyboard.press('i');await expect(page.locator('body')).not.toHaveClass(/vim-nav/);await page.keyboard.type('New ');await c.driver.expectParagraphs([['New Alpha beta. Gamma.']]);await page.keyboard.press('Escape');await page.keyboard.press('v');await page.keyboard.press('l');await toggle(page);await expect(page.locator('body')).not.toHaveClass(/vim-nav/);await expect.poll(async()=>(await persistedLibrary(page)).vimKeys).toBe(false);await c.driver.shelf();await page.reload();await c.driver.selectBook(c.title);await c.driver.expectParagraphs([['New Alpha beta. Gamma.']]);expect((await persistedLibrary(page)).vimKeys).toBe(false);
});
test('[NEO-220-B] Leafloom: Vim character aliases unknown commands and bounded counts preserve exact prose',async({page})=>{
 const text='word '.repeat(300),c=await setup(page,[`<p>${text}</p>`]);await page.keyboard.type('9999l');expect(await c.driver.caret()).toMatchObject({paragraph:0,offset:999});await c.driver.select(0,0,10);await page.keyboard.press('Backspace');expect(await c.driver.caret()).toMatchObject({offset:9});await page.keyboard.press('Space');expect(await c.driver.caret()).toMatchObject({offset:10});await page.keyboard.type('5z');await page.keyboard.press('l');expect(await c.driver.caret()).toMatchObject({offset:11});await page.keyboard.press('Escape');await c.driver.select(0,0,10);await page.keyboard.type('0');expect(await c.driver.caret()).toMatchObject({offset:0});await c.driver.expectParagraphs([[text]]);
});
for(const [word,key,at,expected] of [['punctuation w','w',0,5],['punctuation e','e',0,4],['punctuation b','b',7,5],['apostrophe w','w',8,14],['Unicode w','w',14,19]] as const)test(`[NEO-221-B] Leafloom: Vim ${word} reaches source word edge without modifying authored text`,async({page})=>{
 const c=await setup(page,['<p>alpha!! can’t café next.</p>']);await c.driver.select(0,0,at);await page.keyboard.press(key);expect(await c.driver.caret()).toMatchObject({offset:expected});await c.driver.shelf();expect((await persistedBook(page,c.title,c.id)).chapters[0].html).toContain('alpha!! can’t café next.');
});
test('[NEO-223-A] Leafloom: Vim bracket pairs move chapters and clamp at both manuscript ends',async({page})=>{
 const c=await setup(page,['<p>First.</p>','<p>Second.</p>','<p>Third.</p>']);await page.keyboard.type(']]');expect(await c.driver.caret()).toMatchObject({chapter:1,offset:0});await page.keyboard.type('9]]');expect(await c.driver.caret()).toMatchObject({chapter:2,offset:0});await page.keyboard.type(']]');expect(await c.driver.caret()).toMatchObject({chapter:2,offset:0});await page.keyboard.type('[[');expect(await c.driver.caret()).toMatchObject({chapter:1,offset:0});await page.keyboard.type('9[[');expect(await c.driver.caret()).toMatchObject({chapter:0,offset:0});await page.keyboard.type('[[');expect(await c.driver.caret()).toMatchObject({chapter:0,offset:0});await c.driver.expectParagraphs([['First.'],['Second.'],['Third.']]);
});
for(const [command,offset,paragraphs,paragraph,caret] of [['a',2,['AlpXha beta. Gamma.'],0,4],['I',8,['XAlpha beta. Gamma.'],0,1],['A',2,['Alpha beta. Gamma.X'],0,19],['o',2,['Alpha beta. Gamma.','X'],1,1],['O',2,['X','Alpha beta. Gamma.'],0,1]] as const)test(`[NEO-226-${command==='o'||command==='O'?'A':'B'}] Leafloom: Vim ${command} starts author input at the intended line or paragraph destination`,async({page})=>{
 const c=await setup(page);await c.driver.select(0,0,offset);await page.keyboard.press(command);await expect(page.locator('body')).not.toHaveClass(/vim-nav/);await page.keyboard.type('X');await c.driver.expectParagraphs([[...paragraphs]]);expect(await c.driver.caret()).toMatchObject({paragraph,offset:caret});await c.driver.shelf();expect((await persistedBook(page,c.title,c.id)).chapters[0].html).toContain('X');
});
test('[NEO-228-A] Leafloom: Vim plain d is harmless x deletes and Undo restores before slash opens Find in insertion mode',async({page})=>{
 const c=await setup(page);await page.keyboard.press('d');await c.driver.expectParagraphs([['Alpha beta. Gamma.']]);await page.keyboard.press('x');await c.driver.expectParagraphs([['lpha beta. Gamma.']]);await page.keyboard.press(process.platform==='darwin'?'Meta+z':'Control+z');await c.driver.expectParagraphs([['Alpha beta. Gamma.']]);await page.keyboard.press('/');await expect(page.locator('#search-input')).toBeFocused();await expect(page.locator('body')).not.toHaveClass(/vim-nav/);
});
