import { test,expect,type Page } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { writeFile,mkdir } from 'node:fs/promises';
import { ManuscriptSchema } from '../src/contracts';
const errors=new Map<Page,string[]>();
test.beforeEach(async({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});});
test.afterEach(async({page})=>{expect(errors.get(page)).toEqual([]);});
async function start(page:Page,size=5){await page.goto(`/?book=${randomUUID()}&size=${size}`);await expect(page.getByRole('textbox',{name:'Manuscript',exact:true})).toBeVisible();}
async function select(page:Page,id:string,from:number,to=from){await page.locator(`[data-block-id="${id}"]`).evaluate((element,selection)=>{
 const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];let node:Node|null;while((node=walker.nextNode()))nodes.push(node as Text);
 const at=(offset:number):[Node,number]=>{for(const node of nodes){if(offset<=node.length)return[node,offset];offset-=node.length;}return[element,0];};const range=document.createRange();range.setStart(...at(selection.from));range.setEnd(...at(selection.to));window.getSelection()?.removeAllRanges();window.getSelection()?.addRange(range);(element.closest('[contenteditable=true]') as HTMLElement).focus();
 },{from,to});}
const snapshot=(page:Page)=>page.evaluate(()=>window.uiSpike.core.snapshot());
test('format, Darling, unified undo/redo, notes/outline and real-file reopen',async({page})=>{
 await start(page);await expect(page).toHaveTitle('NEO · The Light Keeper');expect(await page.locator('.ProseMirror').getAttribute('spellcheck')).toBe('true');
 await select(page,'opening',26,36);await page.getByRole('button',{name:'Darlings',exact:true}).click();await page.getByRole('button',{name:'Keep selected passage'}).click();await expect(page.locator('.darling blockquote')).toHaveText('Too quiet.');expect((await snapshot(page)).chapters[0].blocks[0].runs).toEqual([{text:'The lighthouse was quiet. '}]);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.darling')).toHaveCount(0);await expect(page.locator('[data-block-id=opening] em')).toHaveText('Too quiet.');
 await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.locator('.darling')).toHaveCount(1);await page.getByRole('button',{name:'Restore passage'}).click();await expect(page.locator('[data-block-id=opening] em')).toHaveText('Too quiet.');
 await select(page,'opening',0,3);await page.getByRole('button',{name:'Bold',exact:true}).click();await expect(page.locator('[data-block-id=opening] strong')).toHaveText('The');
 await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('textbox',{name:'Book notes'}).fill('Mara fears the morning.');await page.getByRole('button',{name:'Outline',exact:true}).click();await page.getByRole('textbox',{name:'Book outline'}).fill('Arrival → promise → return.');
 await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Saved');const saved=await snapshot(page);ManuscriptSchema.parse(saved);
 await page.reload();await page.getByRole('button',{name:'Reopen',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Reopened');expect(await snapshot(page)).toEqual(saved);
 await page.getByRole('button',{name:'Notes',exact:true}).click();await expect(page.getByRole('textbox',{name:'Book notes'})).toHaveValue('Mara fears the morning.');await page.getByRole('button',{name:'Outline',exact:true}).click();await expect(page.getByRole('textbox',{name:'Book outline'})).toHaveValue('Arrival → promise → return.');
 const report=await page.evaluate(()=>window.uiSpike.diagnostics.report());expect(report.spans.some(s=>s.name==='reopen')).toBe(true);expect(JSON.stringify(report)).not.toContain('Mara fears');
});
test('NEO paragraph → scene → chapter, keyboard history and navigation',async({page})=>{
 await start(page);const initial=await snapshot(page);await select(page,'opening',36);await page.keyboard.press('Enter');await expect(page.locator('[data-id=chapter-one] p')).toHaveCount(4);await page.keyboard.press('Enter');await expect(page.locator('[data-id=chapter-one] .scene-break')).toHaveCount(1);await page.keyboard.press('Enter');await expect(page.locator('.chapter')).toHaveCount(3);ManuscriptSchema.parse(await snapshot(page));
 for(let i=0;i<3;i++)await page.keyboard.press('ControlOrMeta+z');expect((await snapshot(page)).chapters).toEqual(initial.chapters);await page.keyboard.press('ControlOrMeta+Shift+z');await expect(page.locator('[data-id=chapter-one] p')).toHaveCount(4);
 await page.getByRole('button',{name:'2 A promise'}).click();await expect(page.getByRole('button',{name:'2 A promise'})).toHaveClass(/current/);await page.keyboard.type('Now ');await expect(page.locator('[data-block-id=return]')).toContainText('Now At sunrise');
});
test('DOM paste creates unique stable blocks, sanitizes content and remains undoable',async({page})=>{
 await start(page);const initial=await snapshot(page);await select(page,'opening',0);
 await page.locator('.ProseMirror').evaluate(element=>{const data=new DataTransfer();data.setData('text/html','<p data-block-id="opening"><strong>Another voice</strong></p><p data-block-id="opening">A second paragraph<script>throw new Error("executed")</script></p>');element.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});
 const doc=await snapshot(page);ManuscriptSchema.parse(doc);expect(doc.chapters[0].blocks[0].runs[0]).toEqual({text:'Another voice',bold:true});expect(JSON.stringify(doc)).not.toContain('executed');
 await page.keyboard.press('ControlOrMeta+z');expect((await snapshot(page)).chapters).toEqual(initial.chapters);
});
test('reopen never overwrites writing that changed while reading disk',async({page})=>{
 await start(page);await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Saved');await page.route('**/__spike/book/*/manuscript',async route=>{if(route.request().method()==='GET'){const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,250));await route.fulfill({response});}else await route.continue();});
 await page.getByRole('button',{name:'Reopen',exact:true}).click();await select(page,'opening',0);await page.keyboard.type('New ');await expect(page.getByRole('status')).toContainText('Writing changed');await expect(page.locator('[data-block-id=opening]')).toContainText('New The lighthouse');
});
const percent=(values:number[],p:number)=>[...values].sort((a,b)=>a-b)[Math.ceil(values.length*p)-1];
for(const size of [5,500])test(`responsive typing and structural commands: ${size} paragraphs`,async({page},info)=>{
 await start(page,size);const id=size===5?'opening':'paragraph-0-0';await select(page,id,0);const before=await page.evaluate(()=>window.uiSpike.core.snapshots);await page.keyboard.type('The morning tide kept returning to the lighthouse. ',{delay:20});
 expect(await page.evaluate(()=>window.uiSpike.core.snapshots)).toBe(before);await page.waitForTimeout(50);const frames=await page.evaluate(()=>window.uiSpike.diagnostics.frames.filter(f=>f.kind==='input').map(f=>f.milliseconds));expect(frames.length).toBeGreaterThanOrEqual(45);expect(percent(frames,.95)).toBeLessThanOrEqual(50);expect(percent(frames,.99)).toBeLessThanOrEqual(100);await expect(page.locator(`[data-block-id="${id}"]`)).toContainText('The morning tide kept returning');
 await page.keyboard.press('End');for(let i=0;i<3;i++)await page.keyboard.press('Enter');await page.waitForTimeout(60);const commands=await page.evaluate(()=>window.uiSpike.diagnostics.frames.filter(f=>f.kind==='command').map(f=>f.milliseconds));expect(commands.length).toBeGreaterThanOrEqual(3);expect(Math.max(...commands)).toBeLessThanOrEqual(150);ManuscriptSchema.parse(await snapshot(page));
 const commits=await page.evaluate(()=>window.uiSpike.diagnostics.commits.filter(f=>f.kind==='input').map(f=>f.milliseconds));expect(commits.length).toBeGreaterThanOrEqual(45);expect(percent(commits,.95)).toBeLessThanOrEqual(10);const report={size,commitP50:percent(commits,.5),commitP95:percent(commits,.95),inputSamples:frames.length,p50:percent(frames,.5),p95:percent(frames,.95),p99:percent(frames,.99),commandMax:Math.max(...commands),snapshotOnTyping:0};await info.attach('responsiveness',{body:JSON.stringify(report),contentType:'application/json'});await mkdir('/tmp/neo-ui-spike',{recursive:true});await writeFile(`/tmp/neo-ui-spike/performance-${size}.json`,JSON.stringify(report,null,2));
});
for(const size of [5,500])test(`baseline session pipeline: ${size} paragraphs`,async({page},info)=>{
 await page.goto(`/baseline.html?size=${size}`);await expect(page.locator('.ProseMirror')).toBeVisible();await select(page,size===5?'opening':'paragraph-0-0',0);await page.keyboard.type('The morning tide kept returning to the lighthouse. ',{delay:20});await page.waitForTimeout(50);
 const frames=await page.evaluate(()=>(window as unknown as {baseline:{diagnostics:{frames:{kind:string;milliseconds:number}[]}}}).baseline.diagnostics.frames.map(f=>f.milliseconds));const commits=await page.evaluate(()=>(window as unknown as {baseline:{diagnostics:{commits:{milliseconds:number}[]}}}).baseline.diagnostics.commits.map(f=>f.milliseconds));const report={size,commitP50:percent(commits,.5),commitP95:percent(commits,.95),inputSamples:frames.length,p50:percent(frames,.5),p95:percent(frames,.95),p99:percent(frames,.99)};await info.attach('baseline',{body:JSON.stringify(report),contentType:'application/json'});await writeFile(`/tmp/neo-ui-spike/baseline-${size}.json`,JSON.stringify(report,null,2));
});
test('paper appearance and narrow viewport stay usable',async({page})=>{await start(page);await mkdir('/tmp/neo-ui-spike',{recursive:true});await page.screenshot({path:'/tmp/neo-ui-spike/desktop.png'});await page.getByRole('button',{name:'Toggle dark mode'}).click();await expect(page.locator('.workbench')).toHaveClass(/dark/);await page.screenshot({path:'/tmp/neo-ui-spike/dark.png'});await page.setViewportSize({width:390,height:844});await expect(page.getByRole('textbox',{name:'Manuscript',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'/tmp/neo-ui-spike/narrow.png'});});
